### ISSUE TITLE
Keine Funktion bei der Option "eigene Einstellungen (nur Pro)"

### ISSUE THREAD

**Issue by Snatch2001** [ioBroker/ioBroker.iot#1]
Wenn man auf eigene Einstellungen im Reiter "Erweiterte Einstellungen" klickt und danach auf abbrechen, bleibt das Häckchen gesetzt. Nach einer Bestätigung für eine Neustart, verschindet das Häcken wieder und der Adapter wird nicht neu gestartet.

**Comment by GermanBluefox** [comment]
Sollte mit 0.1.6 gefixt sein.
