### ISSUE TITLE
SSL handshake failure

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.iot#10]
Bekomme seitdem ich heute 2 ioT Instanzen mit dem selben PRO Account eingerichtet hatte, diese Fehler im Log. Deaktivieren der iot.1 Instanz und Neusetzen der Logindaten in der iot.0 hilft auch nicht.
Deaktiviere ich die 0 springt die 1 auf grün. Aber ich brauche eigentlich beide parallel mit dem selben Konto. Sonst müsste ich ja zwei Lizenzen kaufen.

> iot.0 | 2018-12-12 13:29:19.665 | error | 1996287904:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
> -- | -- | -- | --
> iot.0 | 2018-12-12 13:29:19.665 | error | write EPROTO 1996287904:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1498:SSL alert number 46
> iot.0 | 2018-12-12 13:29:19.664 | error | 1996287904:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
> iot.0 | 2018-12-12 13:29:19.664 | error | write EPROTO 1996287904:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1498:SSL alert number 46

Generell wäre hier also die Frage: 
Kann man überhaupt zwei ioT Instanzen mit dem selben Login verwenden um Smart Geräte getrennt für zwei Echo Dot festlegen zu können? Denn das ist das Ziel. Immerhin werden die Geräte im JSON ja pro Instanz gespeichert.

**Comment by Apollon77** [comment]
Nur eine iot verbindung mit dem gleichen Pro account ist meines Wissens nach möglich.

**Comment by Diginix** [comment]
Hm, das ist natürlich schlecht. Wozu werden die Smart Geräte dann pro Instanz gespeichert?
Wäre ja genau das was ich brauche um für unterschiedliche Amazon Echos die Geräte getrennt festlegen zu können. Zwei Lizenzen dafür zu kaufen ist keine Option. Darf gern als Denkanstoß gewertet werden.

Dann braucht es hier doch den feature request den ich im cloud adapter angelegt habe.

Wie bekomme ich nun mein iot.0 wieder lauffähig?

**Comment by Apollon77** [comment]
Aktuell sind smartdevices global und nicht pro instanz soweit ich weiss. Es gibt einen feature request dazu.

Zur Instanz: Lösch sie mal und leg sie neu an dann sollte er die zertifikate und so neu initialisieren

**Comment by Diginix** [comment]
Ne, also pro Instanz geht auf jeden Fall mit dem iot. Das habe ich heute schon erfolgreich testen können.
Man muss nur die automatische Anlage deaktivieren. Alle die man manuell zuordnet sind wie in dem Feature request von mir zu sehen schon pro Instanz im JSON. Ein manuell hinzugefügtes Gerät bei iot.0 ist nicht bei iot.1 zu sehen. Es muss sogar explizit dort ebenfalls angelegt werden.
Wenn also das Login für beide iot Instanzen erlaubt wäre, hätte ich alles was ich wollte ohne dass ein feature request nötig ist.
Es fehlt nur aktuell die Möglichkeit die Assistenz Lizenz zu kaufen. Ohne sind nur die 10 Test Anfragen für beide Instanzen möglich.

**Comment by Apollon77** [comment]
Aahhh cool . wieder was gelernt :-)

**Comment by Diginix** [comment]
Issue kann geschlossen werden. Löschen aller iot Instanzen und anlegen einer neuen hat geholfen.
