### ISSUE TITLE
"Letzter Wert" funktioniert nicht nach 2x "aus"

### ISSUE THREAD

**Issue by padrino-x** [ioBroker/ioBroker.iot#101]
Hat man "bei an" auf "letzter Wert" eingestellt und schaltet (aus Versehen ;-)) ein Gerät, das bereits aus (=0%) ist erneut aus und versucht es danach wieder anzuschalten wurde "letzter Wert" wohl gelöscht und das Gerät wird mit 100% eingeschaltet.

**Comment by padrino-x** [comment]
Hm, ist das Gerät an, _kann_ ein zweites mal "an" bedeuten, dass der Wert auf 100% geht, muss aber nicht. Oft bleibt die eingestellte Prozentzahl einfach unverändert. *grübel*

**Comment by padrino-x** [comment]
Can't this be reopened?
It's a valid bug/problem IMO. =)

**Comment by padrino-x** [comment]
@Apollon77
Thanks. 😍

**Comment by padrino-x** [comment]
Touching this so stale bot does not auto close...

**Comment by Apollon77** [comment]
Please add debug logs from iot adapter from such a case

**Comment by padrino-x** [comment]
Argh, immer dieser Bot, der mich ins Englische pusht... =))

Hier ist ein Log, hoffe, das ist richtig so.

Vorgang ist:
- fernsehlicht an (Wert = 90)
- fernsehlicht aus (Wert = 0)
- fernsehlicht aus (??)
- fernsehlicht an (Wert = 0)

[iobroker.2021-06-04.log.txt](https://github.com/ioBroker/ioBroker.iot/files/6597705/iobroker.2021-06-04.log.txt)

**Comment by padrino-x** [comment]
Just giving this a push, as eager stale bot wants to close it again. :D

**Comment by Apollon77** [comment]
try 1.9.6... coming now to npm, latest tomorrow

**Comment by padrino-x** [comment]
Seems to work, well kind of...

Is it possible that "device off" suddenly sends a string instead of number before?
Cause I get an error that state is expecting a number (which I did not see/have earlier)...

**Comment by Apollon77** [comment]
Can you please show debug log?

**Comment by padrino-x** [comment]
Ok, will send you an email right away, topic is

device off log

**Comment by padrino-x** [comment]
Hmm, das Licht war über Nacht aus und iob scheint den Status vergessen zu haben...
Ein "an" produziert auch den Fehler 

"0_userdata.0.Fernsehlicht_WZ.Helligkeit_Fernsehlicht_WZ" has to be type "number" but received type "string"

(was "normal" nur bei "aus" passiert und der Wert im Datenpunkt "100", statt "last saved")...

**Comment by padrino-x** [comment]
Ich frage mich gerade, ob das Problem "globaler Natur" ist, denn mir ist gerade das gleiche mit dem tr64 Adapter aufgefallen.
Und der Adapter selbst sollte ja eigentlich wissen welche Datenpunkttypen er angelegt hat und wie er sie beschreibt (ich habe daran auf jeden Fall nix geändert 😇)

tr-064.0 | 2022-03-04 12:38:33.276 | info | (19846) State value to set for "tr-064.0.callmonitor.lastCall.callee" has to be type "number" but received type "string"

tr-064.0 | 2022-03-04 12:38:33.266 | info | (19846) State value to set for "tr-064.0.callmonitor.inbound.callee" has to be type "number" but received type "string"

**Comment by Apollon77** [comment]
Bitte nicht adapter mixen!!

**Comment by padrino-x** [comment]
Ich vermute ein iot Problem, da das alles erst nach dem iot Update auftritt... 🤷🏻‍♂️

**Comment by Apollon77** [comment]
Naja ich denke das ich nicht damit gerechnet habe das byOn ein string mit ner zahl ist die eher ein % ist ...  muss ich schauen

**Comment by padrino-x** [comment]
Meinst Du jetzt Bug #102 😅

**Comment by Apollon77** [comment]
Naja, sehr auffällig und vllt schon des rätsels Lösung: Typ ist "number" ... aber min/max sind als String angegeben. Maxh mal die " weg bei min/max

**Comment by Apollon77** [comment]
Ok, bitte Github version installieren und laufen lassen. wenn es nochmal passiert dann log senden bitte nochmal ... aber mit log seit der aktion davor. An sich kann nur sein das irgendwo ein wert mit string herkam ... hhmmm
