### ISSUE TITLE
Einstellung in GUI für Prozent für "byon" erzeugt absolute Werte

### ISSUE THREAD

**Issue by padrino-x** [ioBroker/ioBroker.iot#102]
Bei einem Beispielgerät mit

"min": 0,
"max": 2400,

sind 50% ja 1200.
Das merkt man, wenn man sagt "Alexa, schalte Beispielgerät auf 50%" (die 50 Prozent werden dann von der Spanne 0-2400 berechnet).

Stelle ich aber im GUI "letzter Wert" auf 50%, werden "min" und "max" nicht berücksichtigt und es wird
"byON": "50",
statt
"byON": "1200"
in den Datenpunkt eingetragen.

**Comment by padrino-x** [comment]
Touching does, as I missed the bot closing it... =)

But should be a valid bug? :)

**Comment by padrino-x** [comment]
Könnte hier nochmal auf gemacht werden? =)

**Comment by Apollon77** [comment]
ich glaube es existiert keine Logik für byOn 50% ... ?!?! Warum schreibst Du da nicht den gewünschten Wert 1200 rein?

**Comment by padrino-x** [comment]
Hmm, sieht in den iot prefs aber so aus, oder? 🤔 

![prozent_wert](https://user-images.githubusercontent.com/40962599/156451470-b923e7bc-e12f-4691-aabd-e806fe92c822.PNG)

**Comment by Apollon77** [comment]
ok, was steht denn im objekt wenn du 50% wählst?

**Comment by padrino-x** [comment]
Wie oben geschrieben...

> Stelle ich aber im GUI "letzter Wert" auf 50%, werden "min" und "max" nicht berücksichtigt und es wird
> "byON": "50",
> statt
> ...

**Comment by Apollon77** [comment]
Der aktuelle coDe setzt den Wert aus byOn und ist damit daraus ausgelegt das das nurt bei "dimmer style "werten mit 0..100% geht ... muss ich mir ansehen

**Comment by Apollon77** [comment]
Bitte GitHub versuchen

**Comment by padrino-x** [comment]
Seems to work. Thanks.
ByOn in % takes the "max" value into account.
Closing here.
