### ISSUE TITLE
Geräte Liste leer 

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.iot#104]
Ich verwende Momenten die Version 1.1.8. Ich habe es nun bereits mehrmals gehabt, dass dir Geräte Liste plötzlich komplett leer war. Leider konnte ich im log jetzt nichts erkennen... Anscheinend haben dieses Problem auch andere

**Comment by n3roGit** [comment]
https://m.facebook.com/groups/440499112958264?view=permalink&id=1075365222804980&comment_id=1075973562744146&notif_t=group_comment&notif_id=1578712427238779&ref=m_notif

**Comment by TA2k** [comment]
Auch mit der aktuellen 1.2.0?

**Comment by n3roGit** [comment]
Kann ich gleich nochmal testen

**Comment by Apollon77** [comment]
Frage ist auch was das so für Geräte waren? Alle von einem Adapter? Von welchem?

**Comment by n3roGit** [comment]
Das waren verschiedene Geräte aus verschiedenen Adaptern
Max, deconz, milight, sonoff. Alle weg

**Comment by TA2k** [comment]
auch mit 1.2.0? Kommt ein Fehler in der Chrome developer console?

**Comment by n3roGit** [comment]
Ich hab den Adapter auf die Version 1.2 gebracht und die Geräte neu angelegt. Mal ein paar Tage abwarten wie es sich entwickelt. Ich gebe bescheid :)

**Comment by n3roGit** [comment]
Hallo,
heute ist die Liste der Geräte im IOT wieder komplett leer...! :(

Auch in den Objekten fehlt die Information dazu. Ich steh wirklich vor einem Rätsel. Im Log konnte ich auch nichts erkennen.

Könnt ihr vielleicht die Option implementieren die IOT Geräte zu exportieren? Dann hätte ich zumindest ein Backup was ich in so einem Fall einspielen kann. Darüber hinaus könnte man so eine Datei exportieren, Diese editieren um ggfs viele Änderungen vorzunehmen und dann dies einspielen :)

**Comment by Apollon77** [comment]
welcher js-controller?

**Comment by n3roGit** [comment]
2.2.9

**Comment by n3roGit** [comment]
Ich hab das Problem gerade erneut gehabt. Direkt nachdem ich ein ein paar Objekte die influxDB History aktiviert habe sind die IOT Geräte weg

**Comment by n3roGit** [comment]
Wenn ich in die stündlichen SHnapshots gucke ist die Datei auch vor ein paar Stunden plötzlich fast leer gewesen mit folgenden Inhalt.

{
  "system": {
    "memoryLimitMB": 0,
    "hostname": "iobroker",
    "statisticsInterval": 15000,
    "statisticsIntervalComment": "Interval how often the counters for input/output in adapters and controller will be updated",
    "checkDiskInterval": 300000,
    "checkDiskIntervalComment": "Interval how often the disk size will be checked",
    "noChmod": false,
    "noChmodComment": "Flag to test new feature with no chmod call. Must be deleted later and noChmod must be mainline (2018.06.04)"
  },
  "multihostService": {
    "enabled": false,
    "secure": true
  },
  "network": {
    "IPv4": true,
    "IPv6": true,
    "bindAddress": null
  },
  "objects": {
    "type": "file",
    "typeComment": "Possible values: 'file' - [port 9001], redis - [port 6379], couch - [port 5984].",
    "host": "127.0.0.1",
    "port": 9001,
    "user": "",
    "pass": "",
    "noFileCache": false,
    "connectTimeout": 2000,
    "backup": {
      "disabled": false,
      "files": 24,
      "filesComment": "Minimal number of backup files, after the deletion will be executed according to backupTime settings",
      "hours": 48,
      "hoursComment": "All backups older than 48 hours will be deleted. But only if the number of files is greater than of backupNumber",
      "period": 120,
      "periodComment": "by default backup every 2 hours. Time is in minutes. To disable backup set the value to 0",
      "path": "",
      "pathComment": "Absolute path to backup directory or empty to backup in data directory"
    },
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    },
    "dataDir": "../../iobroker-data/"
  },
  "states": {
    "type": "redis",
    "typeComment": "Possible values: 'file' - [port 9000], 'redis' - [port 6379].",
    "host": "127.0.0.1",
    "port": 36379,
    "maxQueue": 1000,
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    },
    "backup": {
      "disabled": false,
      "files": 24,
      "filesComment": "Minimal number of backup files, after the deletion will be executed according to backupTime settings",
      "hours": 48,
      "hoursComment": "All backups older than 48 hours will be deleted. But only if the number of files is greater than of backupNumber",
      "period": 120,
      "periodComment": "by default backup every 2 hours. Time is in minutes. To disable backup set the value to 0",
      "path": "",
      "pathComment": "Absolute path to backup directory or empty to backup in data directory"
    }
  },
  "log": {
    "level": "info",
    "maxDays": 7,
    "noStdout": true,
    "transport": {
      "file1": {
        "type": "file",
        "enabled": true,
        "filename": "log/iobroker",
        "fileext": ".log",
        "maxsize": null,
        "maxFiles": null
      },
      "syslog1": {
        "type": "syslog",
        "enabled": false,
        "host": "localhost",
        "host_comment": "The host running syslogd, defaults to localhost.",
        "port": 514,
        "port_comment": "The port on the host that syslog is running on, defaults to syslogd's default port(514/UDP).",
        "protocol": "udp4",
        "protocol_comment": "The network protocol to log over (e.g. udp,udp4,udp6,tcp,tcp4,tcp6).",
        "path_comment": "The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).",
        "facility_comment": "Syslog facility to use (Default: local0).",
        "localhost": "iobroker",
        "localhost_comment": "Host to indicate that log messages are coming from (Default: localhost).",
        "sysLogType_comment": "The type of the syslog protocol to use (Default: BSD).",
        "app_name_comment": "The name of the application (Default: process.title).",
        "eol_comment": "The end of line character to be added to the end of the message (Default: Message without modifications)."
      }
    }
  },
  "dataDirComment": "Always relative to iobroker.js-controller/",
  "dataDir": "../../iobroker-data/"
}

**Comment by Apollon77** [comment]
Welche Admin Version ist installiert?
