### ISSUE TITLE
Work through a reverse proxy.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.iot#105]
I connect to iobroker via a reverse proxy. When you try to enter the adapter settings, the iobroker icon is constantly spinning. The page log contains the following:
![image](https://user-images.githubusercontent.com/37106885/72415632-e3c8ff00-3785-11ea-9288-c4879437f16a.png)
8081 is the admin.0 port, but I threw admin.1 into the reverse proxy it has port 9081, I think this is the problem.

**Comment by Apollon77** [comment]
Bitte 1.3.1 testen. Braucht aber Web 3.0

**Comment by Anzic23** [comment]
this should be solved by 1.3.2
