### ISSUE TITLE
iot.0 instanz bleibt rot

### ISSUE THREAD

**Issue by Hoeps** [ioBroker/ioBroker.iot#106]
Hallo zusammen,
bin im iobroker.pro angemeldet, und habe den IoT Assistents in der Version 1.2.1 installiert.
die IoT.0 instanz bleibt (trotz korrekter Anmeldung) jedoch auf rot !!! Für die Instanz wird auch keine RAM-Nutzung angezeigt ?!
Ich benötige KEINEN Fernzugriff !
Ich hoffe, das LOG-File kann helfen :

host.raspi | 2020-01-18 12:57:45.404 | info | Restart adapter system.adapter.iot.0 because enabled
-- | -- | -- | --
host.raspi | 2020-01-18 12:57:45.404 | error | instance system.adapter.iot.0 terminated with code 1 ()
Caught | 2020-01-18 12:57:45.404 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.iot/main.js:11:22)
Caught | 2020-01-18 12:57:45.404 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2020-01-18 12:57:45.404 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2020-01-18 12:57:45.404 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2020-01-18 12:57:45.403 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2020-01-18 12:57:45.403 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2020-01-18 12:57:45.403 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2020-01-18 12:57:45.403 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2020-01-18 12:57:45.402 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2020-01-18 12:57:45.402 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2020-01-18 12:57:45.402 | error | by controller[0]: SyntaxError: Unexpected identifier
Caught | 2020-01-18 12:57:45.402 | error | by controller[0]: ^^^^^^^^^^^^
Caught | 2020-01-18 12:57:45.402 | error | by controller[0]: async processState(ids, objects, id, roomName, funcName, result, smartEnum, parentId) {
Caught | 2020-01-18 12:57:45.401 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1361
host.raspi | 2020-01-18 12:57:44.132 | info | instance system.adapter.iot.0 started with pid 5205
host.raspi | 2020-01-18 12:57:14.100 | info | Restart adapter system.adapter.iot.0 because enabled
host.raspi | 2020-01-18 12:57:14.100 | error | instance system.adapter.iot.0 terminated with code 1 ()
Caught | 2020-01-18 12:57:14.100 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.iot/main.js:11:22)
Caught | 2020-01-18 12:57:14.100 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2020-01-18 12:57:14.100 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2020-01-18 12:57:14.100 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2020-01-18 12:57:14.100 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: SyntaxError: Unexpected identifier
Caught | 2020-01-18 12:57:14.099 | error | by controller[0]: ^^^^^^^^^^^^
Caught | 2020-01-18 12:57:14.098 | error | by controller[0]: async processState(ids, objects, id, roomName, funcName, result, smartEnum, parentId) {
Caught | 2020-01-18 12:57:14.098 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1361
host.raspi | 2020-01-18 12:57:12.816 | info | instance system.adapter.iot.0 started with pid 5162
host.raspi | 2020-01-18 12:56:42.789 | info | Restart adapter system.adapter.iot.0 because enabled
host.raspi | 2020-01-18 12:56:42.788 | error | instance system.adapter.iot.0 terminated with code 1 ()
Caught | 2020-01-18 12:56:42.788 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.iot/main.js:11:22)
Caught | 2020-01-18 12:56:42.788 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at Function.Module._load (module.js:445:3)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at Module._compile (module.js:549:28)
Caught | 2020-01-18 12:56:42.786 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2020-01-18 12:56:42.785 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2020-01-18 12:56:42.785 | error | by controller[0]: SyntaxError: Unexpected identifier
Caught | 2020-01-18 12:56:42.785 | error | by controller[0]: ^^^^^^^^^^^^
Caught | 2020-01-18 12:56:42.785 | error | by controller[0]: async processState(ids, objects, id, roomName, funcName, result, smartEnum, parentId) {
Caught | 2020-01-18 12:56:42.784 | error | by controller[0]: /opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1361
host.raspi | 2020-01-18 12:56:41.513 | info | instance system.adapter.iot.0 started with pid 5155
host.raspi | 2020-01-18 12:56:11.488 | info | Restart adapter system.adapter.iot.0 because enabled
host.raspi | 2020-01-18 12:56:11.488 | error | instance system.adapter.iot.0 terminated with code 1 ()
Caught | 2020-01-18 12:56:11.488 | error | by controller[0]: at Object.<anonymous> 

Ich hoffe auf Hilfe

**Comment by Apollon77** [comment]
Which nodejs Version do you use? Nodejs 8 is Minimum for iot Adapter!

**Comment by Hoeps** [comment]
That was the mistake! Nodejs was in version 6.x.
Thank you very much, and have a nice weekend!
