### ISSUE TITLE
Status einer Lampe wird nicht angezeigt (sonoff/mqtt)

### ISSUE THREAD

**Issue by IcynatorHD** [ioBroker/ioBroker.iot#107]
Hallo zusammen,

ich versuche nun seit geraumer Zeit eine Lampe die über Sonoff/MQTT angebunden ist in den iot Adapter zu bringen. Das ganze sieht dann so aus:

<img width="1078" alt="Bildschirmfoto 2020-01-19 um 22 14 12" src="https://user-images.githubusercontent.com/29740976/72688666-ba073380-3b09-11ea-8f0b-eba464c0b7c6.png">

Das Gerät wird auch im iot erkannt.

<img width="1078" alt="Bildschirmfoto 2020-01-19 um 22 15 12" src="https://user-images.githubusercontent.com/29740976/72688670-c3909b80-3b09-11ea-8b81-af1e7c4c4dc9.png">

wird allerdings anschließend nur als Switch angezeigt.

![IMG_9FB14B593A7A-1](https://user-images.githubusercontent.com/29740976/72688640-93e19380-3b09-11ea-9113-6beff48ea0ff.jpeg)

Bei dem alten Alexa Adapter hat man immer gesehen ob das Gerät nun an ist oder nicht. Hab ich hier einen Fehler oder kann der iot Adapter das aktuell noch nicht besser?

**Comment by IcynatorHD** [comment]
Keine Antwort? :(

**Comment by Apollon77** [comment]
Mir wäre neu das der Cloud-Adapter den Status anzeigen konnte, weil das mit dem aktuell genutzten Protokoll nicht tut

**Comment by Sacred-Shadow** [comment]
Wäre aber schon cool, wenn das endlich mal gehen würde. :) 
Betrifft aber ja auch andere Adapter, da wird der Status nicht gespeichert, damit Alexa den aktuellen Status anzeigen kann.

**Comment by Sacred-Shadow** [comment]
Auch wenn das Ticket schon was älter ist ... das "Problem" ist ja weiterhin da.
