### ISSUE TITLE
gelöst: kein Reiter "Smart Geräte"

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.iot#108]
Hallo,
installiert ist iot 1.2.1 und an iobroker.pro angemeldet.
Ich möchte eine neue Scene über  Alexa steuern, aber im Adapter iot.0 fehlt offensichtlich
der Tab "Smarte Geräte", der öfters erwähnt wird ???
Unter "Intelligente Aufzählungen" ist "Räume" leer und bei "Funktionen" gibt es "Color"
Unter dem Tab "Alexa Geräte" werden bereits vorhandene Scenen angezeigt:
z.B. ID: scene.Küche_saugen, jedoch keine neuen Scenen.

**Comment by Apollon77** [comment]
Gibt es Fehler im Browser Log?

**Comment by Hans-Zwiesel** [comment]
kein Fehler.
Der Adapter funktioniert offensichtlich inzwischen anders:
Ich kann unter Alexa-Geräte einen neuen Eintrag anlegen und dabei ein Objekt auswählen,
das ist wahrscheinlich das "Smarte Gerät" und dann einen Namen vergeben, den dann Alexa 
auch versteht.
Vielen Dank.
