### ISSUE TITLE
Cannot read keys

### ISSUE THREAD

**Issue by knobi4711** [ioBroker/ioBroker.iot#110]
I get the message:
Cannot read keys: "[object Object]" / Error: [object Object]
Cannot fetch keys: {"message": "Internal server error"}

Neither the renewed requesting of the certificates, nor a new creation of the certificates from iobroker.pro, nor recrystallization of the entire system was successful.

**Comment by Apollon77** [comment]
Please contact us in forum. Please also make sure the credentials of your pro account are correct and your password do not contain special characters (# and % are known to be problematic curently).
