### ISSUE TITLE
Nicht aufrufbar wenn admin port ungleich 8081

### ISSUE THREAD

**Issue by lug-gh** [ioBroker/ioBroker.iot#111]
Hi, in der Version 1.2.1 soll das ja gefixt sein, leider wird laut chrome console trotzdem versucht 8081 aufzurufen.. mein port ist aber 443 :)

![image](https://user-images.githubusercontent.com/24546639/73296932-ece8b000-420a-11ea-90fd-80821efd87f8.png)

Mein workaround ist jetzt ein reverse proxy vors iobroker hängen und den auf 443 und 8081 lauschen lassen, admin wieder auf 8081 und alle anfragen dahin..

**Comment by Anzic23** [comment]
#105

**Comment by Apollon77** [comment]
Bitte 1.3.1 testen. Braucht aber Web 3.0

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/74131566-a8d7b100-4bf5-11ea-8ba8-8d3958e3faa8.png)
Still not working. web 3.0 iot 1.3.1

**Comment by Apollon77** [comment]
Can you please try to explizitely write :443 in the URL. Does it work then? I want to verify something.

**Comment by Apollon77** [comment]
PS: Why: The code reads the port out of the location ... I could imaging theh for 80/443 when not written as explicit port number this info is simply empty and so it falls back to default

**Comment by Anzic23** [comment]
> Can you please try to explizitely write :443 in the URL. Does it work then? I want to verify something.

if I put https://iob.huako.ru:443/#tab-instances/config/system.adapter.iot.0 in the line, then Google Chrome removes 443 and does https://iob.huako.ru/#tab-instances/config/system.adapter.iot.0

**Comment by Apollon77** [comment]
grmpf ... I try to find this out ...

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/74132690-1edd1780-4bf8-11ea-80fd-592129e6b57b.png)
can it help? these are reverse proxy settings.

**Comment by Anzic23** [comment]
console log
![image](https://user-images.githubusercontent.com/37106885/74132904-81ceae80-4bf8-11ea-95f2-c759aeadc2cb.png)

**Comment by Apollon77** [comment]
I have no idea if reverse proxy will ever work with current concept because the javascript uses the port out of the location in the browser! It will only work if also the websocket connections are correctly proxied through. No idea if this works.

And this issue ist just about a custom port! (reverse proxy is an other topic and needs to be solve somehow different).

Please check 1.3.2 from GitHub how it works with non-iobroker-standard-ports 433/80, ideally first without a reverse proxy

**Comment by lug-gh** [comment]
@Anzic23 Reverse Proxy is not the problem, as it also occurs when you have your port set to 443 and connect without Reverse Proxy.
That's why I also proxy the websocket connectins (yes that works @Apollon77 )

**Comment by Apollon77** [comment]
ANd exactly this should be solved by 1.3.2 on GitHub

**Comment by Anzic23** [comment]
> I have no idea if reverse proxy will ever work with current concept because the javascript uses the port out of the location in the browser! It will only work if also the websocket connections are correctly proxied through. No idea if this works.
> 
> And this issue ist just about a custom port! (reverse proxy is an other topic and needs to be solve somehow different).
> 
> Please check 1.3.2 from GitHub how it works with non-iobroker-standard-ports 433/80, ideally first without a reverse proxy

after updating from github. works fine. even through reverse proxy

**Comment by Zefau** [comment]
Following error comes up when the port of the web adapter (for socket) is changed from `8081`to something else:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://192.168.178.29:8081/socket.io/?ws=true&EIO=3&transport=polling&t=N6sBaBt. (Reason: CORS request did not succeed).
Connect error: Error: xhr poll error
```

**Comment by Zefau** [comment]
@Apollon77 please re-open, thanks

**Comment by Apollon77** [comment]
No please create a new issue. Ist 1.4.9 working?

**Comment by Apollon77** [comment]
And BTW what has Web Adapter to do with iot? Admin is the relevant dep here that provides the socketio lib.

**Comment by Zefau** [comment]
How do I know? ;-) Are you sure though? If I change the port of the Web Adapter from 8082 back to 8081 it works with iot (at least I don't get the Cross-Origin block, but iot is infinitely loading..)

**Comment by Apollon77** [comment]
yes because it seems (why ever) that iot is no longer getting the real port and thans whx falling back to 8081 which normally is the Admin port
