### ISSUE TITLE
TypeError: this._getObjectName(...).replace is not a function

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.iot#113]
I can’t understand what the mistake is. previously complained about 2 objects in linkeddevices.0.server-room.1 and linkeddevices.0.server-room.2. I deleted them, but the error remained. How to fix it?
(14852) [ALISA] Cannot process "linkeddevices.0.server-room": TypeError: this._getObjectName(...).replace is not a function
Found differences in the code, maybe this is the case?
![image](https://user-images.githubusercontent.com/37106885/74213491-80f65500-4caa-11ea-8a10-0f6f18f5b19f.png)

**Comment by Apollon77** [comment]
No in fact you need to search with _getObjectName :-)

Can you please show the object json definition of those two objects?

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/74310350-11ea3080-4d7e-11ea-9435-c937f36b7388.png)
```
{
  "from": "system.adapter.iot.0",
  "user": "system.user.admin",
  "ts": 1581342162052,
  "common": {
    "name": "svet v zale",
    "role": "level.dimmer",
    "type": "number",
    "desc": "Created by linkeddevices",
    "unit": "%",
    "min": 0,
    "max": 100,
    "def": 0,
    "read": true,
    "write": true,
    "smartName": true,
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "parentId": "mqtt.0.homebridge.Tests.Свет_зал",
        "parentType": "number",
        "isLinked": true
      },
      "material": {
        "admin": {
          "useDefaultIcon": false,
          "name": "Свет в зале",
          "colorOn": "",
          "doubleSize": "",
          "colorOff": "",
          "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAPaSURBVGhD7ZpbqFVVFIZ3VFZqRnmFDNIQ85IoaYgIRnSBrJdUUJTeQrz2oKA+iGhJoJZJIOqDgWBR+JIPPmgpYV5AydQQEwIvlGKBaQaapn7fPGfCYnP2Pvvss+Zyb/OHD8+Ynr3GHHvNNeaYY51SAXqg9d+m1hPwG2wMVhPrBbgNe4PVxLofSKPpngmkB/wMHwSrAbQZ9sBTwSpGb8Gv8GawctL34BL5EToaTFd4sOXHmvU2XAd9znAgL/WG49BeMN1gEmyBE3AZ/MxN+B0Owgp4ESptlNkgkizJbDC7HMioOyyFv8H/z+JYnFgWv5DXIauhkDSIKIP5Ab4OVoteA79tnd+C72A+DAGXVVRfeBk+hjMQA9oOT4IaBGfBL6VQzYMb4IRMBqOhFnWB2XAR/OwpeB7uigzCSfwHixyoQ96lfeB1DOoZKFSvgg+w+HB3Ro+Ay8tgfoLsckwqH+wLoON670S5zHbHwGt+4kARWgY6LM9cnZXJweftGjzrQEo9DlfA7ORekLc2gF/SpmAl1BTQ0c5g5a/nwOv/AR2tBjqkraCjOcFKo6OgjwnBSiTzvU7cuFJpNehjYbDq1NPg2s9iloq6CjoxZaaSVYE+stnL0iU7p+FQcen1AzOGF8liTaRMkdp/Biud3Jf081WwSqV3ITufyHJoU4+CG9PhMj4EZcbyApeClU4xoXwRrFJpJOyH7JysoidC3foX3M0fDlYazQQD+SxYieSxVSfDgpVGn4I+3g9WIn0OOulURmlHv4A+xgUrkSaDTg4FK3+NAq9vJZx0Q/Qc4a6rs5ccyFmxRPHwlVwLQGcHIM8G9QgwkfwDhZxL3AzjDj/LgRzknY4HLKvrwvQGWAHbKMhjia0FgzgJhR2somzr6Pwc9HegTk0Hr+OSssVamAZATzCrfANOwtOd70I6qlfAu+rdneYAMnNZDiWVbUwd2xJSLgNrMYOxDeRar1V++3+Bn13sALIc0a6no1mzYhBZx8pl5fJyvNa06d2Lva31DrTKSruWjmbdskCr1gE0dVo5mz5r6U/FM8e3UL7xlbdnY/MuF8VNsFobcyX4O1+CFWw13LkNeiC0JYOJdd1HDuSl98CqtJrGgo5r5QhUUy9wqdpdKVTx7ZQPsL3hSuwGf69h32LFQEzF1TQemiKQ0+DZX7lPlD8fdtobOhCbAk5QfMM1JmO3RcMGMhicoJ3Id+Ax8Lha/ozE13i+hmhIPQS+nTKt2twuX1IyFXaAgayDhtVcsG6Ky6cS5yE+Rw0rX6+tgW2QDcrJ+8c1S6APNJXs364Cl5oNwPv6n6hUugN0+S7EQlyozwAAAABJRU5ErkJggg==",
          "iconOff": "",
          "background": "",
          "enabled": true
        }
      }
    },
    "icon": "linkeddevices_small.png"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "linkeddevices.0.zal.dimmer",
  "type": "state"
}
```
```
{
  "type": "state",
  "common": {
    "name": "dimmer zal on-off",
    "role": "switch.light",
    "type": "boolean",
    "desc": "Created by linkeddevices",
    "read": true,
    "write": true,
    "def": false,
    "smartName": true,
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "parentId": "mqtt.2.devices.dimmer4.controls.ON-OFF-zal",
        "parentType": "boolean",
        "isLinked": true
      },
      "material": {
        "admin": {
          "enabled": false,
          "name": "zal",
          "icon": "linkeddevices_small.png"
        }
      }
    },
    "icon": "linkeddevices_small.png"
  },
  "native": {},
  "from": "system.adapter.iot.0",
  "user": "system.user.admin",
  "ts": 1581399405598,
  "_id": "linkeddevices.0.zal.state",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  }
}
```
```
{
  "_id": "linkeddevices.0.server-room",
  "type": "channel",
  "common": {
    "name": {
      "ru": "server-room"
    },
    "desc": "Created by linkeddevices",
    "smartName": {
      "ru": "",
      "ghTraits": [
        "action.devices.traits.OnOff"
      ],
      "ghType": "action.devices.types.SWITCH",
      "ghAttributes": "{\n        \"commandOnlyOnOff\": false\n      }"
    },
    "role": "thermostat"
  },
  "native": {},
  "from": "system.adapter.iot.0",
  "user": "system.user.admin",
  "ts": 1581490593985,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by Apollon77** [comment]
The reason is the "smartname: true" ... there should be more data then just "true" ... We can add a check

**Comment by Apollon77** [comment]
Please try iot 1.3.3 from GitHub

**Comment by Anzic23** [comment]
> Please try iot 1.3.3 from GitHub

yes, it's work, but now Google devices not open
![image](https://user-images.githubusercontent.com/37106885/74314918-65ad4780-4d87-11ea-8a2b-af262684c370.png)

**Comment by Apollon77** [comment]
Were they opening before?

**Comment by Anzic23** [comment]
> Were they opening before?

yes

**Comment by Apollon77** [comment]
which version of iot you had before? Now you need Admin 4.0.1 too ... have that installed?

**Comment by Anzic23** [comment]
> which version of iot you had before? Now you need Admin 4.0.1 too ... have that installed?

1.3.2 Admin 4.0.1

**Comment by Apollon77** [comment]
Hm ... now I'm out ... someone with FE experience ened to check that

**Comment by Anzic23** [comment]
> Hm ... now I'm out ... someone with FE experience ened to check that

strange, returned to version 1.3.2 and still can not get into the google devices tab. There were errors in the installation during installation (if I understood correctly), maybe because of this?
[iot-install 1.3.2.log](https://github.com/ioBroker/ioBroker.iot/files/4191588/iot-install.1.3.2.log)

**Comment by Apollon77** [comment]
Ok, if also after downgrade it is still not ok then it should not be from this version.

**Comment by Anzic23** [comment]
any news?

**Comment by TA2k** [comment]
Can you paste a error log with the 1.3.4 version?

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/77110470-ae1aed80-6a36-11ea-833f-f775e51a8b01.png)
[iobroker.2020-03-19.log](https://github.com/ioBroker/ioBroker.iot/files/4356723/iobroker.2020-03-19.log)

**Comment by Apollon77** [comment]
Try disable you anti virus if you have something. Especially Kaspersky ... else I have no idea which chrome extension makes problems here. Should have nothing to do with the adapter!!

**Comment by Anzic23** [comment]
tried on MacBook with Safari, same problem.

**Comment by Anzic23** [comment]
adapter v 1.4.6, js-controller 2.2.9 still not working. Console says `DevTools failed to parse SourceMap: https://iob.huako.ru/adapter/iot/vendor/socket.io.js.map`
![image](https://user-images.githubusercontent.com/37106885/79696740-3800e500-8287-11ea-8007-82f0f8b264f4.png)

**Comment by TA2k** [comment]
Can you please remove the rooms from the linkeddevices ? and then step by step add rooms to device to see when the tab is stop working

**Comment by Anzic23** [comment]
> Can you please remove the rooms from the linkeddevices ? and then step by step add rooms to device to see when the tab is stop working

after deleting all the rooms in the linkeddevices, it still didn't work. After completely clearing all devices and rooms, the adapter finally opened on the Google devices tab. And there were loaded some devices that have linked rooms and functions in the admin, but in the categories everything is empty. very strange, I will try to completely clear all the rooms and functions everywhere, and start gradually adding checking whether the tab will stop working. Thanks for the tip.
