### ISSUE TITLE
Button lässt sich nicht anlegen

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.iot#114]
Ich kann manuell keinen Button mehr unter den Smartgeräten anlegen - ich möchte ungern in der RAW Datei rumkritzeln. 

Was mache ich falsch?

![Bildschirmfoto 2020-02-17 um 10 09 01](https://user-images.githubusercontent.com/8560588/74640455-dbdaf100-516f-11ea-8335-3b0be9d9b55d.png)

**Comment by Diginix** [comment]
Kann den Fehler bestätigen. Weder aus javascript.0 noch 0_userdata.0 lassen sich Buttons in der iot Instanz hinzufügen. role=switch funktioniert. Button hat in älteren iot Versionen auch funktioniert.
Bereits im iot hinzugefügte lassen sich auch dort bearbeiten. Es funktioniert also nur das initiale Hinzufügen nicht.
