### ISSUE TITLE
Typ des Alexa-Gerätes setzt sich immer wieder zurück

### ISSUE THREAD

**Issue by BillyRay83** [ioBroker/ioBroker.iot#115]
Mehrere Steckdosen mit angeschlossenen Lampen, die ich über FHEM steuere und manuell im IoT-Adater eingefügt habe, werden anfangs als 'kein Typ' gekennzeichnet. Daran ändert sich auch nichts, egal wie oft der FHEM-Adapter neu gestartet wird.
Damit man sie mittels Alexa-Komando 'Alexa, schalte Licht an' steuern kann, wurde der Typ als Light definiert. Das bleibt aber nur solange bestehen, bis der FHEM-Adapter neu gestartet wird, dann werden all diese Steckdosen auf einmal auf Switch gestellt, womit das Alexa-Kommando natürlich nicht mehr geht.
Wieso wird die manuelle Typen-Einstellung manuell eingefügter Geräte überhaupt überschrieben? Kann man das irgendwie verhindern?

**Comment by Apollon77** [comment]
Dann scheint der fhem Adapter Objekte zu überschreiben. Bitte dort ein issue anlegen. 

Is: welcher js-Controller?

**Comment by BillyRay83** [comment]
js-controller 2.2.9

Erstaunlich ist halt, dass 'kein Typ' **nicht** überschrieben wird.

Wenn der fhem Adapter der Ausgangspunkt der Problematik ist, dann müsste er aber doch von entsprechenden Einträgen in anderen Adaptern wie dem iot Adapter _Kenntnis_ haben, um sie aktiv zu ändern. Umgekehrt kennt der iot Adapter aber die _Herkunft_ seiner Geräte und könnte auf Aktualisierungen reagieren.
Deshalb war ich davon ausgegangen, dass das Problem vom iot Adapter ausgeht.

**Comment by BillyRay83** [comment]
Das Problem lag an einer Einstellung im fhem Adapter. Allerdings wird dieser nicht in der Instanz - wo ich es vermutet hätte - sondern im Objekt selbst eingestellt. Wenn der Eintrag unter _fhem.0.info.Configurations.autoSmartName_ auf **false** geändert wird, wird der Typ im iot Adapter nicht mehr überschrieben.
