### ISSUE TITLE
Eigene Enums in intelligenten Aufzählungen darstellen

### ISSUE THREAD

**Issue by cataklysm** [ioBroker/ioBroker.iot#116]
Wäre es möglich eigene Aufzählungen anzubieten. Ich denke die meisten unterteilen nicht nur strikt nach räumen, sondern definieren auch bereiche. Die man gern separat steuern möchte. Wenn ich in meinem Büro das Licht einschalten möchte betrifft dies zumeist die Deckenleuchte, darüber hinaus befinden sich aber noch eine Stehlampe, sowie 6 Hue play lightbars und ein hue led stripe in meinem büro, die aus bleiben sollen.

**Comment by Apollon77** [comment]
Es sollten alle Enums angezeigt werden die existieren im System. Leg doch deine einfach unter Enums im ioBroker an.

**Comment by saschadietl** [comment]
Nein laut code werden ausschließlich functions und rooms verwendet

**Comment by Apollon77** [comment]
Ahhh ok, so war es gemeint. Das Problem ist das Amazo und Google maximal mit diesen beiden typen arbeiten ...

Die Bereiche als Räume anlegen ist keine Option?

**Comment by saschadietl** [comment]
Doch eine Option wäre es schon, aber nicht so toll. Für Amazon und Google werden devices exposed, also würde es lediglich weitere Benennungen für devices mit einem Smartname geben bspw. "Essbereich Licht". Das sollte mMn schon funktionieren.

Ist natürlich nicht Kriegsentscheidend, aber eine weitere Unterteilung in Bereiche würde mir im ioBroker insgesamt entgegenkommen.
