### ISSUE TITLE
IOT-adapter stop receiving posts from IFTTT 

### ISSUE THREAD

**Issue by naesle** [ioBroker/ioBroker.iot#118]
Since last week I face problems with IOT adapter. It stops receiving the commands fom IFTTT.
Next day it works again without doing anything but stops after some commands / time
I installed cloud adapter again and this works without any problems.
Yesterday I switched to IOT again and it was working for half an hour after it stopped again. Today in the morning it worked when I did a test. Is there a known  problem with iobroker cloud or thith the adapter. In logfile is no hint for issues

**Comment by Apollon77** [comment]
How many messages you do per day? Do you have a pro license? anything in the logs?

**Comment by naesle** [comment]
Would say 10 - 20 messages
Have no pro licence
Was changing 2 months ago feom cloud adapter to IOT
Always worked without problems since end of last week
Attached logfile from IOT adapter restart
[IOT Log.txt](https://github.com/ioBroker/ioBroker.iot/files/4249668/IOT.Log.txt)

**Comment by Apollon77** [comment]
Without a payed pro license you can process 20 iot requests per day for free ... Here alexa/google interactions cound and also service calls like ifttt ... and this would perfectly describe your behaviour that it stops working (probably after 20 calls) and then restarts working the next day.

**Comment by Apollon77** [comment]
PS: Could it be that you in the past was always below the 20 and now are having more then these?

**Comment by naesle** [comment]
It could be for one day when I was testing something
Is this limitation also in cloud adapter?
Yesterday and on sunday it stopped in IOT but I could proceed in cloud adapter then
