### ISSUE TITLE
multiple adapter, different accounts, different smart devices

### ISSUE THREAD

**Issue by micfire** [ioBroker/ioBroker.iot#12]
hey... is it possible to have this adapter installed multiple times with different iobroker.xxx accounts and have separated smart device list for e.g. alexa. The goal for this feature is, to have different location handled by iobroker and alexa.
thx

**Comment by Apollon77** [comment]
Yes this is possible. Use the "Eigene Einstellungen" option and the smart devices will be edited per inatance of iot
