### ISSUE TITLE
Add link to Documentation to Konfigurationsdialog

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.iot#124]
https://www.iobroker.net/#de/documentation/cloud/iot.md
For every language

**Comment by Apollon77** [comment]
Maybe also update? Forum points to a newer version in the meantime https://forum.iobroker.net/topic/18517/anleitung-iot-pro-cloud-assistenten-service-iobroker-iot-reloaded-alexa-und-services

**Comment by GermanBluefox** [comment]
Both ist done.
