### ISSUE TITLE
Vorschlag: Exportieren & Importieren der Geräte

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.iot#125]
Es wäre toll, wenn man die Möglichkeit hätte direkt im Adapter die Konfiguration z.B. als Json zu exportieren und zu importieren.

So wäre das anlegen von vielen Geräten deutlich schneller, da man einfach anhand eines Gerätes mehrere im Editor "bauen" kann.

Zudem hätte ich eine Lösung für das Problem mit dem Verlust der Geräte: 
https://github.com/ioBroker/ioBroker.iot/issues/104

**Comment by Apollon77** [comment]
Rein Faktisch ist ein backup vom ioBroker - vor allem der Objects-Datenbank das einfachste, weil die iot Einstellungen auf alle Objektr verteilt sind.

**Comment by n3roGit** [comment]
Klar das stimmt wohl. Allerdings wäre es viel schneller, wenn man viele Geräte eben im Editor hinfummeln kann.

**Comment by n3roGit** [comment]
Update
