### ISSUE TITLE
IoT Adapter 1.4.0 Cannot initialize getImage: ReferenceError: BigInt is not defined

### ISSUE THREAD

**Issue by m0rph2k** [ioBroker/ioBroker.iot#126]
Hi

Seit dem Update auf 1.4.0 bekomme ich beim starten des Adapters diese Warnung  
Cannot initialize getImage: ReferenceError: BigInt is not defined

ioBroker 4.0.5
JS 2.2.9

LG

**Comment by GermanBluefox** [comment]
Mit 1.5.1 Keine Warnung mehr
