### ISSUE TITLE
ioT Adapter 1.4.1

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.iot#127]
After the installation comes the error
Cannot initialize getImage: Error: Cannot find module 'canvas'
JS Menu no longer works.

**Comment by LJSven** [comment]
I`m getting the following error message while updating via console

`Update iot from @1.3.4 to @1.4.1
host.tinkerboardmaster Adapter "system.adapter.iot.0" is stopped.
NPM version: 6.13.4
npm install iobroker.iot@1.4.1 --loglevel error --prefix "/opt/iobroker" (System call)
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.69-rockchip
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /opt/iobroker/node_modules/canvas
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.69-rockchip
node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvas
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.0/libvips-8.9.0-linux-armv7.tar.gz
Update "system.adapter.iot.0"
upload [20] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/runtime-main.28893cca.js.map static/js/runtime-main.28893cca.js.map application/json
upload [19] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/runtime-main.28893cca.js static/js/runtime-main.28893cca.js application/javascript
upload [18] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/main.51e5dfdb.chunk.js.map static/js/main.51e5dfdb.chunk.js.map application/json
upload [17] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/main.51e5dfdb.chunk.js static/js/main.51e5dfdb.chunk.js application/javascript
upload [16] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/2.f4263b8d.chunk.js.map static/js/2.f4263b8d.chunk.js.map application/json
upload [15] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/2.f4263b8d.chunk.js.LICENSE.txt static/js/2.f4263b8d.chunk.js.LICENSE.txt text/plain
upload [14] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/js/2.f4263b8d.chunk.js static/js/2.f4263b8d.chunk.js application/javascript
upload [13] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/main.d4bed9c6.chunk.css.map static/css/main.d4bed9c6.chunk.css.map application/json
upload [12] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/main.d4bed9c6.chunk.css static/css/main.d4bed9c6.chunk.css text/css
upload [11] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/2.b1b16afe.chunk.css.map static/css/2.b1b16afe.chunk.css.map application/json
upload [10] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/css/2.b1b16afe.chunk.css static/css/2.b1b16afe.chunk.css text/css
upload [9] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/service-worker.js service-worker.js application/javascript
upload [8] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/precache-manifest.4e40cda158381693460d8f57769a04b4.js precache-manifest.4e40cda158381693460d8f57769a04b4.js application/javascript
upload [7] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/manifest.json manifest.json application/json
upload [6] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/iot.png iot.png image/png
upload [5] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/index_m.html index_m.html text/html
upload [4] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [3] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/blockly.js blockly.js application/javascript
upload [2] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/asset-manifest.json asset-manifest.json application/json
upload [1] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/alexalogo.png alexalogo.png image/png
upload [0] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/actions.js actions.js application/javascript
Adapter "iot" updated
host.tinkerboardmaster Adapter "system.adapter.iot.0" is started`

**Comment by bergjet** [comment]
I can't find a module "Canvas".

**Comment by Apollon77** [comment]
it is ok because it is optional

**Comment by GermanBluefox** [comment]
Mit 1.5.1 Keine Warnung mehr
