### ISSUE TITLE
Creating groups within the smart device section fails

### ISSUE THREAD

**Issue by ak1de** [ioBroker/ioBroker.iot#13]
You are supposed to create groups of smart devices, by adding an addl. smart device and give it a name of an already existing smart device. A group should be created with all devices with the same smart device name.

This approach fails. When you try to use a smart device which is already used, you'll receive an error message stating exactly that. The creation of the new smart device will be aborted, no group created.

**Comment by Apollon77** [comment]
@GermanBluefox should be fixed at least in iot :-)) (leave cloud out)

**Comment by Apollon77** [comment]
Current workaround: Add a space to the name and it will be added
