### ISSUE TITLE
Anzahl der im Adapter hinterlegten Geräte bei Anfrage des Alexa-Skills ist begrenzt 

### ISSUE THREAD

**Issue by ska77** [ioBroker/ioBroker.iot#131]
Wenn zu viele Geräte im Adapter iot angelegt sind, bricht der Skill für Alexa die Anfrage einseitig ab. Bei 452 Geräten getestet. Keine Synchronisation zu Alexa möglich. Das Limit sollte geklärt werden.

**Comment by Apollon77** [comment]
BTW: Alexa Limit sind 300 :-)

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.iot#limits
