### ISSUE TITLE
Cannot initialize getImage: Error: Cannot find module 'canvas'

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.iot#135]
Hello Developer,

so far my pro account of the adapter worked without any error messages. Recently the following message appears constantly:
`iot.0 | 2020-04-28 17:22:16.409 | warn | (1994) Cannot initialize getImage: Error: Cannot find module 'canvas'
-- | -- | -- | --`

Why is this module 'canvas' necessary and if necessary, how do I install it?

Thank you

**Comment by Apollon77** [comment]
This is ok because optional

**Comment by realwax** [comment]
I get this, too plus additional warning after upgrading nodejs and npm.  I did a npm rebuild successfully before. After the warning I did a npm install again not changing anything.
Node.js v12.16.3 NPM 6.14.4


ot.0 | 2020-04-30 18:40:55.706 | warn | the module (for instance, using `npm rebuild` or `npm install`).
-- | -- | -- | --
iot.0 | 2020-04-30 18:40:55.706 | warn | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
iot.0 | 2020-04-30 18:40:55.706 | warn | NODE_MODULE_VERSION 64. This version of Node.js requires
iot.0 | 2020-04-30 18:40:55.706 | warn | was compiled against a different Node.js version using

**Comment by Apollon77** [comment]
After updating nodejs you need to do rebuild ... see forum thread on how to correctly update nodejs

**Comment by FabianHM** [comment]
@Apollon77 
Okay, ich habe nun gemäß der Anleitung Node.js auf 12 angehoben:
[https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten](url)
Und danach brav den Fixer laufen lassen.
Im Ergebnis zeigen sich nun im Log noch mehr Warnings beim IOT Adapter:
`
iot.0 | 2020-05-02 11:53:50.599 | warn | - /opt/iobroker/node_modules/iobroker.iot/main.js
-- | -- | -- | --
iot.0 | 2020-05-02 11:53:50.599 | warn | - /opt/iobroker/node_modules/iobroker.iot/lib/alexaCustomBlood.js
iot.0 | 2020-05-02 11:53:50.599 | warn | - /opt/iobroker/node_modules/iobroker.iot/lib/getImage.js
iot.0 | 2020-05-02 11:53:50.599 | warn | Require stack:
iot.0 | 2020-05-02 11:53:50.599 | warn | (1822) Cannot initialize getImage: Error: Cannot find module 'canvas' `

Was läuft hier falsch?
Danke vorab für Deine Expertise,
Grüße
Fabian

**Comment by FabianHM** [comment]
Warnung lautet nun:

iot.0 | 2020-05-02 16:45:14.839 | warn | (1882) Cannot initialize getImage: Error: Cannot find module 'canvas' Require stack: - /opt/iobroker/node_modules/iobroker.iot/lib/getImage.js - /opt/iobroker/node_modules/iobroker.iot/lib/alexaCustom
-- | -- | -- | --

**Comment by realwax** [comment]
> After updating nodejs you need to do rebuild ... see forum thread on how to correctly update nodejs

Fallls du einen npm rebuild meinst, der ist gelaufen.

**Comment by TA2k** [comment]
cd /opt/iobroker
npm install canvas --unsafe-perm --production --save --prefix

**Comment by realwax** [comment]
@TA2k Danke, das wars :)

**Comment by FabianHM** [comment]
Thanks for Help!
