### ISSUE TITLE
Anzeigefehler der DP-Auswahlliste - v. 1.4.14

### ISSUE THREAD

**Issue by Mauflo** [ioBroker/ioBroker.iot#138]
Seit dem letzten Update auf 1.4.14 bleibt die Liste für die Auswahl der DP für die Alexageräte weiß. Somit ist die Suche etwas schwierig, weil man nichts mehr lesen kann!

Siehe: https://forum.iobroker.net/assets/uploads/files/1588639361676-899ea5ae-2a67-4821-9b0b-b5ab6af6ff50-image.png

**Comment by tobasium** [comment]
kann ich bestätigen gibt's hier schon eine Lösung?

**Comment by mrbungle64** [comment]
Bei mir betrifft es die Anzeige unter "Google devices", so dass man die Einträge nicht mehr lesen kann. Die Schrift wird aber in allen Tabs überwiegend weiß dargestellt.

* Google Chrome, Version 83.0.4103.61 (Linux)
* Admin 4.1.1
* Web server 3.0.8

**Comment by tobasium** [comment]
Ich habe jetzt noch einmal den cache geleert und browser gecleant sieht jetzt wieder gut aus bei mir

**Comment by mrbungle64** [comment]
> Ich habe jetzt noch einmal den cache geleert und browser gecleant sieht jetzt wieder gut aus bei mir

Bei mir hatte das leider nicht geholfen. Ich habe es gerade noch mal probiert - war aber das gleiche Ergebnis wie bisher.

**Comment by TA2k** [comment]
Hast du besondere devices.. linkeddevices oder alias? Ging es schon mal? Was sagt der Browser Log. Schon mal probiert ein paar smart room oder function zu deaktiviern

**Comment by mrbungle64** [comment]
> Hast du besondere devices.. linkeddevices oder alias? Ging es schon mal? Was sagt der Browser Log. Schon mal probiert ein paar smart room oder function zu deaktiviern

Ja bis vor kurzem war alles korrekt bzw. lesbar.

Ich habe nun mal alle Einträge unter "Google devices" entfernt - bis auf einen einzigen (selbst angelegter Datenpunkt). Vorher waren u.a. Einträge über linkeddevices dabei.

In der Browser Konsole sind 2 Einträge die evtl. zu erwähnen wären:
* DevTools failed to load SourceMap: Could not load content for http://raspberrypi:8081/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
* [Violation] 'message' handler took 297ms
Die Violation Warnung kommt mehrmals ...

Die Smart rooms und functions haben ich inzwischen alle deaktiviert.

Das Problem besteht leider immer noch.

**Comment by TA2k** [comment]
das ist verdammt eigenartig kannst du den iot adapter in den instanzen übersicht in den log modue debug setzen. dazu musst du unter instanzen erst auf experten wechseln

**Comment by mrbungle64** [comment]
> das ist verdammt eigenartig kannst du den iot adapter in den instanzen übersicht in den log modue debug setzen. dazu musst du unter instanzen erst auf experten wechseln

Ich sehe da nichts auffälliges.
Nur Ausgaben, welche auf die ausgeschalteten Smart rooms und functions zurückzuführen sind.
Beispiel:

```
...
iot.0 | 2020-05-26 21:44:20.617 | warn | (3647) linkeddevices.0.Beleuchtung.Herd is ignored because the property smartName is false or ignore. To use this state again, remove the property smartName in Object explorer or add it manually unde
iot.0 | 2020-05-26 21:44:20.617 | debug | (3647) Process: linkeddevices.0.Beleuchtung.Herd Küche Nicht definiert
...
```

Ansonsten nur Ausgaben die nach normalem Verhalten aussehen:
```
iot.0 | 2020-05-26 21:44:20.775 | debug | (3647) sendTo "browseGH" to system.adapter.admin.0 from system.adapter.iot.0
iot.0 | 2020-05-26 21:44:20.774 | debug | (3647) [GHOME] Subscribe done
iot.0 | 2020-05-26 21:44:20.675 | debug | (3647) [GHOME] Subscribe 1 states for google home
iot.0 | 2020-05-26 21:44:20.674 | debug | (3647) [GHOME] Global.CloudSwitches.Nachtschalter => action.devices.types.SWITCH
```

@Mauflo 
Hat sich das Problem bei Dir erledigt?

**Comment by mrbungle64** [comment]
@TA2k 

Mit der Version 1.6.0 ist das Problem bei mir nun behoben. Die Schrift ist nun überall wieder lesbar :+1:

**Comment by mrbungle64** [comment]
Ich würde den Issue ja schließen, aber ich weiß nicht, ob das Probem auch für den Ersteller ( @Mauflo ) gelöst ist.
Evtl. hatte das ja nicht die gleiche Ursache.

**Comment by Mauflo** [comment]
> Ich würde den Issue ja schließen, aber ich weiß nicht, ob das Probem auch für den Ersteller ( @Mauflo ) gelöst ist.
> Evtl. hatte das ja nicht die gleiche Ursache.

Ja hat sich nunmehr in Wohlgefallen aufgelöst! Sorry für die späte Antwort. War auf Urlaub! ;-)

**Comment by mrbungle64** [comment]
> > Ich würde den Issue ja schließen, aber ich weiß nicht, ob das Probem auch für den Ersteller ( @Mauflo ) gelöst ist.
> > Evtl. hatte das ja nicht die gleiche Ursache.
> 
> Ja hat sich nunmehr in Wohlgefallen aufgelöst! Sorry für die späte Antwort. War auf Urlaub! ;-)

@Mauflo 
Kannst Du das Ticket bitte noch schließen? Ich darf es leider nicht...
