### ISSUE TITLE
Also allow to select objects with "write=false"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.iot#14]
Currently they are not added as object without any notice or message. To query temperature sensors this shuld be allowed

**Comment by aPlagge** [comment]
Hi guys, any news on this? I just switched from the cloud adapter to iot (including the paid Remote license) and it is really a problem that I lost the functionality for my door/window and temperature sensor devices.
Thanks ahead for an update.

**Comment by aPlagge** [comment]
If you need any help I could also try to look into the issue. Just let me know. (In German is fine as well)
