### ISSUE TITLE
new password check is not working correct

### ISSUE THREAD

**Issue by mk176** [ioBroker/ioBroker.iot#140]
After updating to 1.5 the adapter is not starting, with error "The password must be at least 8 ..." error.
My password has a length of 10 characters with upper/lower letters, number and special chars.

2020-05-20 16:50:18.897  - info: host.Server instance system.adapter.iot.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
--
2020-05-20 16:50:21.383  - info: host.Server instance system.adapter.iot.0 started with pid 24804
2020-05-20 16:50:23.901  - info:  iot.0 (24804) starting. Version 1.5.0 in C:/Program  Files/iobroker/node_modules/iobroker.iot, node: v12.16.3, js-controller:  3.1.4
2020-05-20 16:50:23.914  - error:  iot.0 (24804) The password must be at least 8 characters long and have  numbers, upper and lower case letters. Please change the password in the  profile https://iobroker.pro/accountProfile.

**Comment by Schimi1983** [comment]
have the same problem!!

**Comment by MasterYod4** [comment]
I have the same thing with me

**Comment by ihavenonick** [comment]
Ebenfalls das Passwort jetzt schon 5 mal geändert, Zahlen Buchstaben groß und klein, trotzdem immer die selbe Meldung im Log.

  | (12530) The password must be at least 8 characters long and have  numbers, upper and lower case letters. Please change the password in the  profile https://iobroker.pro/accountProfil
-- | --

**Comment by schotte11** [comment]
Habe das selbe problem.

**Comment by skvarel** [comment]
me too!

**Comment by JF62** [comment]
same here

**Comment by Speedbreaker12** [comment]
ich auch!

**Comment by ooooli** [comment]
Dito, gleiche Meldung. Ist auch mit 1.5.1 noch so

**Comment by Diginix** [comment]
Bei mir kommt auch die Fehlermeldung, aber nur bei der iot.1 Instanz ohne Assistenz Lizenz.
Bei der iot.0 nutze ich ein Konto mit bezahlter Assistenz Lizenz. Beide Passwörter haben das gleiche Schema.

**Comment by m0rph2k** [comment]
Hallo

 (5065) The password must be at least 8 characters long and have numbers, upper and lower case letters. Please change the password in the profile https://iobroker.pro/accountProfile.

Es betrifft bei mir aber nur den Pro acc der Free funktioniert

Meins Passwort schaut ca so aus
A1W3BRtUuedAx26eaztrwnwFSV

Sollte also passen

**Comment by Garfonso** [comment]
Kann es auch bestätigen, habe ebenfalls Pro-Abo.

**Comment by Michaelnorge** [comment]
Jepp, hier das gleiche!

**Comment by GermanBluefox** [comment]
The code, that checks the Password is this one: https://github.com/ioBroker/ioBroker.iot/blob/master/main.js#L927

What could be wrong?? **Umlaute are not the letters.**

**Comment by eric2905** [comment]
Don‘t know what is wrong (code looks ok).

My password contains capital letters, letters, numbers and a special character.... but no Umlaut.
Changed password at ioBroker.pro ... same message and adapter stays yellow.

Downgrade to v1.4.x and everything works fine.

**Comment by JohGrei** [comment]
Mein Passwort enthält ein "!", "?", Zahlen und Groß- und Kleinbuchstaben. Version 1.5 funktioniert aber nicht

**Comment by DerDom2010** [comment]
Hier auch dasselbe Problem. Mein Passwort beinhaltet ein "_" 
Selbst nach dem ändern des Passwortes nach den Vorgaben, funktioniert es nicht.

**Comment by GermanBluefox** [comment]
Fixed. Please use 1.5.2

**Comment by eric2905** [comment]
Works fine. No errors in log.

**Comment by ihavenonick** [comment]
Der Adapter wird grün, allerdings schaltet Alexa keine Geräte die über IoT angebunden sind.
