### ISSUE TITLE
Nach Update kein einloggen mehr möglich

### ISSUE THREAD

**Issue by PommesTC** [ioBroker/ioBroker.iot#141]
Hallo

Gerade den Adapter ein Upgrade verpasst. Und obwohl mein Passwort den Anforderungen entspricht und ich dies auch testweise mehrfach geändert habe, ist kein einloggen möglich. Im Log steht immer das das Passwort nicht den Anforderungen entspricht.

MFG

Thomas

---

**System data:**

Model: Common KVM processor
RAM: 2.94 GB
Node.js: v12.16.3
NPM: 6.14.4
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
JS-Controller (1): 3.1.4
Admin: 4.1.1
IoT Assistants: 1.5.0

> *created by ioBroker.info*

**Comment by EduardSarjadjuk** [comment]
Hallo, 
ich habe das Selbe Problem.
Mit freundlichen Grüßen
Eduard

**Comment by Annonymus1988** [comment]
Meldung im Log nach Update: 
error | (14685) The password must be at least 8 characters long and have  numbers, upper and lower case letters. Please change the password in the  profile https://iobroker.pro/accountProfile.
-- | --
Passwort entspricht den Vorgaben, wurde geändert, aber Meldung bleibt

**Comment by Annonymus1988** [comment]
Das Problem besteht bei mir auch

**Comment by detafun** [comment]
Kann ich bestätigen, habe gerade sogar die 1.5.1 vom Git probiert, das selbe Problem.
Wieder downgrade gemacht erst mal.

**Comment by detafun** [comment]
gibt schon 1.5.2 gerade beim testen

**Comment by detafun** [comment]
1.5.2 geht wieder!

**Comment by eric2905** [comment]
Wurde doch bereits als #140 gemeldet und gelöst.
Nicht gesehen/gelesen?
