### ISSUE TITLE
Alexa-Signaltöne

### ISSUE THREAD

**Issue by ELK169** [ioBroker/ioBroker.iot#142]
Bisher gab es da wohl keine Möglichkeit, doch seit ein paar Wochen kann man in einer Routine auch „Töne“ auswählen. Da gibt es nun ein paar Töne und Geräusche, die abgespielt werden können. Leider sehr wenige und gar nicht mal so tolle... Schade. Aber zumindest über eine Routine auch aus einem eigenen Skript aufrufbar.
Ist jetzt evtl. eine neue Möglichkeit da, den Alexa-Adapter entsprechend zu erweitern?

**Comment by Apollon77** [comment]
ALex2 adaper hat mit iot nichts zu tun. Bitte Issue dort anlegen bzw ich glaube das gibts da schon
