### ISSUE TITLE
[Node.js v12.17.0] Smartnames werden ignoriert

### ISSUE THREAD

**Issue by volkerverkamp** [ioBroker/ioBroker.iot#143]
Nach dem Update auf v12.17.0 ist ist mit dem IOT-Adapter (v1.5.2) keine Alexa-Steuerung für mauell im Adapter angelegte Geräte mehr möglich. 

Die Geräte tauchen in der Geräteliste des Adapters gar nicht mehr auf. Die entsprechenden SmartName-Einträge bei den Datenpunkten sind aber noch da. Die automatisch vom Adapter angelegten Geräte (z.B. Homematic) sind noch vorhanden.

**Comment by Apollon77** [comment]
Ein nodejs update sollte keinerlei Auswirkungen auf die Objekte haben. Zeig bitte mal so ein objekt

**Comment by volkerverkamp** [comment]
Ich kann nur sagen, dass das Problem seit dem Node.js Update und einem darauffolgenden Neustart von iobroker auftritt. 

Hier ein Beispiel für ein Objekt, welches vorher noch problemlos mit Alexa bedient werden konnte und nun (wie einige andere) nicht mehr in der iot-Geräteliste auftaucht:

{
  "_id": "0_userdata.0.automower.automowerActivityCommand",
  "type": "state",
  "common": {
    "name": "automowerActivityCommand",
    "role": "state",
    "type": "boolean",
    "read": true,
    "write": true,
    "desc": "Manually created",
    "def": false,
    "smartName": {
      "de": "Rasenmäher"
    }
  },
  "native": {},
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1589403803165,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by volkerverkamp** [comment]
Hat offenbar doch nichts mit der node.js Version zu tun. Ich hatte zeitgleich noch die Systemsprache geändert und mir war nicht bewusst, dass das (in der Standardeinstellung) dazu führt, dass alle "de" SmartNames ignoriert werden. 

Wieder was gelernt... und Sorry!
