### ISSUE TITLE
Ein Gerät und ZWei Funktion

### ISSUE THREAD

**Issue by zakuma666** [ioBroker/ioBroker.iot#145]
Guten Morgen,

und zwar folgendes, hab ich via Zigbee eine Tradfri E27 eingebunden, welche Dimmbar ist, diese kann mit der Funktion breightness zwar den Befehl "Aus" aber geht dann in der Helligkeit auf 0% der State bleibt aber bei "True", besteht die Möglichkeit bei der Funktion Aus den State zu ändern?

Vielen dank schon mal

**Comment by marc2016** [comment]
Moin, wenn ich Deine Frage richtig verstehe, willst Du von der Ikea Lampe einmal die Helligkeit und einmal den An/Aus-Zustand steuern. Damit diese beiden States als ein Gerät in Google Home auftauchen, musst Du sie in dem IOT Konfig Menü gleich benennen (Smartnames in der Tabelle). Danach kannst Du die Helligkeit steuern und sie an und aus schalten.
Hier nochmal beschrieben: https://github.com/ioBroker/ioBroker.iot/issues/90

**Comment by zakuma666** [comment]
Danke, das werde ich mal probieren.
