### ISSUE TITLE
Alexa-Geräte Farbfehler

### ISSUE THREAD

**Issue by tobasium** [ioBroker/ioBroker.iot#146]
Hallo,

irgendwie habe ich einen komischen Ansichtsfehler sodass ich kaum etwas erkenne:
![iot160](https://user-images.githubusercontent.com/23247891/87251379-8deebe80-c46b-11ea-9982-ac9907c7a522.jpg)

Ich habe in meiner VIS kein CSS stehen. SIeht bei mir in chrome und Edge so aus. Woran liegt das den?

**Comment by Apollon77** [comment]
Welche iot Version? Dark Mode im Browser?

**Comment by tobasium** [comment]
IoT 1.6.0, chrome ganz normal,

**Comment by tobasium** [comment]
Ich habe jetzt mal design in chrome geändert auf ein sehr helles aber Darstellung bleibt gleich.

**Comment by Diginix** [comment]
Gleiches Problem bei mir auch. Ist auch beim neuen text2command Adapter. Bluefox nutzt da ggf. irgendwelche Standard Skins (hell oder dunkel), die sich nach Systemeinstellungen richten. Im Chrome ist dann alles dunkel bei mir. Aber z.T. unlesbar.
Im Edge ist alles hell. Wenn man schon keinen Einfluss darauf hat, wäre es schön wenn wenigsten der Lesekontrast gegeben bliebe.

**Comment by tobasium** [comment]
wobei ich beim text2command noch alles lesen kann da es dunkler hintergrund und weiße schrift ist.

**Comment by Diginix** [comment]
Ja, da ist bei mir auch alles lesbar. Aber da ist mir zum 1. mal der dark mode durch irgendwelche vererbten Standards aufgefallen.
Grundsätzlich fände ich ein komplett dunkles iot Interface super, aber bei bisher nur 1-2 Instanzeinstellungen wirkt das sehr inkonsistent und ich fände eine vorerst konsequente helle Darstellung besser. Wenn dann in weiter Ferne mal alle Adapter und Admin sauber in dunkel funktionieren, könnte man dann darauf wechseln.

**Comment by ak1de** [comment]
Gleiches Problem hier seit v1.6.0 auf Mac OS Catalina im Dark Mode mit Chrome.

**Comment by ak1de** [comment]
Ergänzung: Problem besteht bei mir auch (auf dem iPad) unter iOS 13.5. Ebenfalls im Dark Mode. Browser: Safari, Chrome, iCabMobile.
Deaktiviere ich den Dark Mode unter iOS, dann ist der Dialog wieder lesbar.

Das Gleiche gilt auch für Mac OS (siehe vorhergehender Post von mir). Sobald ich den Dark Mode im Betriebssystem deaktiviere, ist der Dialog wieder lesbar.

**Comment by ihavenonick** [comment]
Das ganze ist auch im Firefox kaum lesbar.
IoT 1.6.1 und Dark Mode
Im Edge sieht es gut aus, liegt somit am Browser, wobei das vorher auch im Firefox lesbar war.

Firefox:
![grafik](https://user-images.githubusercontent.com/36501310/87513184-9831d800-c678-11ea-8497-2cd981f22103.png)
 Edge:
![grafik](https://user-images.githubusercontent.com/36501310/87513264-bd264b00-c678-11ea-8cd4-e18cad0c7561.png)
Sieht so aus, als ob der Edge da den Dark Mode nicht nutzt.
