### ISSUE TITLE
ioBroker.iot skill for more Amazon Countries

### ISSUE THREAD

**Issue by tyson0941** [ioBroker/ioBroker.iot#150]
Hi to all,
     After changing from Cloud adapter to Iot adapter, the iobroker skill for Alexa isn't available anymore on Amazon.com store, it is only available on Amazon.de store. It will be nice to be available also on Amazon.com or Anazon.co.uk .

Regards

**Comment by GermanBluefox** [comment]
ioBroker.iot must be available in .com too.
Supported languages: 
![image](https://user-images.githubusercontent.com/4582016/99077963-deaf2900-25bd-11eb-926a-f86d905bea20.png)

**Comment by GermanBluefox** [comment]
@tyson0941 Can you check it?
https://forum.iobroker.net/topic/30569/no-iobroker-skill-in-alexa-us-account/8
