### ISSUE TITLE
V1.7 - how to add blinds and cameras?

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.iot#156]
How do we add blinds ? The "blind" is not avaible, only light, switch, smartlock, smartplug, camera..
Can you provide a short example, please?

How do we add cameras? Camera is avaible, but how it would work?
Can you provide a short example, please?

:-)

**Comment by Apollon77** [comment]
It is only added to Alisa ... you saw that ... it is not Alexa!!!!

**Comment by Ilovegym66** [comment]
seufz, ja habs gesehen.. Alisa, Alexa, ich verwechsel die Weiber halt.. sorry.. :-)

**Comment by Pocky2507** [comment]
Wer zum Teufel ist Alisa schon wieder...?

**Comment by Ilovegym66** [comment]
Alisa ist doch die, die die Zombies killt, oder😁

Nee, schau hier https://www.google.com/url?sa=t&source=web&rct=j&url=https://en.m.wikipedia.org/wiki/Alice_(virtual_assistant)&ved=2ahUKEwjno_HM6JrrAhXFGewKHfhLArQQFjABegQIARAB&usg=AOvVaw359jX5KbzIDGUS0iM625w5
