### ISSUE TITLE
Thermostat sendet den Durchschnittswert von Soll und Ist Tempeartur

### ISSUE THREAD

**Issue by mk176** [ioBroker/ioBroker.iot#157]
**Describe the bug**  
I habe für jedes HMIP Thermostat eine Gruppe unter Alexa Geräte angelegt.
Somit kann ich die aktuelle Temperatur abfragen und die Soll-Temperatur erhöhen.
![grafik](https://user-images.githubusercontent.com/60314176/90784558-b2a74300-e301-11ea-9967-6dda8a993c94.png)

Der Toltip über dem grünen Thermometer zeigt auch bei Actual "aktuelle Temperatur abrufen" und bei SET_POINT "Solltemperatur abrufen".
Frage ich über Alexa die Temperatur ab, erhalte ich als Ergebnis den Durchschnittswert der Soll und Ist Temperatur.

**To Reproduce**  
1. Alexa-Geräte
2. Füge ein Thermostat wie im Screenshot hinzu
3. Frage Alexa

**Expected behavior**  
Nur die aktuelle Temperatur soll bei der Berchnung herangezogen werden. Der Adapter kann scheinbar schon Soll und Ist unterscheiden

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.7.3
 - JS-Controller version: 3.1.6
 - Node version: 12.18.3
 - Operating system: Windows 10 x64

**Comment by Morluktom** [comment]
Ich habe das gleiche Problem. Was mir noch aufgefallen ist wenn per Alexa die Temperatur verstellt wird, wird auch auf den Ist-Temperatur Datenpunkt geschrieben.

**Comment by mk176** [comment]
works with 1.7.15
