### ISSUE TITLE
IoBroker Custom Skill sendet nicht das gesprochene

### ISSUE THREAD

**Issue by ma-gu-16** [ioBroker/ioBroker.iot#161]
Nach Aktivierung und Verknüpfung des Skills. Schreibt der IOT oder ALEXA nicht die gesprochenen Wörter in die Datenpunkte.

iot v 1.5.3
text2command Version 1.3.0
node: v12.18.2
js-controller: 3.1.6

In den Datenpunkten steht bei der Frage: Alexa, frage i.o. broker welche Fenster auf sind, folgendes:
`
lastCommand = askDevice

lastCommandObj = {"words":[],"intent":"askDevice","deviceId":"amzn1.ask.device.AHF7Z2xxxxx","sessionId":"amzn1.echo-api.session.48fdxxx45xxxxc","userId":"amzn1.ask.account.AFBKTW3xxxxx"}
`
Mir scheint das der Skill nicht vollständig übermittelt. Ich habe den Alexa PRO Account bei iobroker.pro

**Comment by ma-gu-16** [comment]
[url=https://ibb.co/KL5ndX6][img]https://i.ibb.co/4YFkz7W/Screenshot-2020-09-14-154407.png[/img][/url]

**Comment by Apollon77** [comment]
Interessant ... bei mir tuts ... gerade getestet. Hat er dich korrekt verstanden?

beispiel bei mir "... STatus Rasenmäher" war die Anfrage
* lastCommand: askDevice status rasenmäher
* lastCommandObj: {"words":["status","rasenmäher"],"intent":"askDevice","deviceId":"xxxxxxx","sessionId":"xxxx","userId":"xxxx"}

**Comment by ma-gu-16** [comment]
> Interessant ... bei mir tuts ... gerade getestet. Hat er dich korrekt verstanden?
> 
> beispiel bei mir "... STatus Rasenmäher" war die Anfrage
> 
> * lastCommand: askDevice status rasenmäher
> * lastCommandObj: {"words":["status","rasenmäher"],"intent":"askDevice","deviceId":"xxxxxxx","sessionId":"xxxx","userId":"xxxx"}

Ja genau so sind auch die ganzen youtube tutorials oder docus beschrieben.
Ich frag mich warum er das bei mir nicht macht. Auch die normalen Geräte im IOT Adapter , wenn ich sage: Alexa, Büro an.

Dann steht bei lastCommand = true, bei lastcommandObj, sind die Wörter wieder leer und bei lastResponse steht es korrekt 'Büro ist eingeschaltet'. 

Der Befehl wurde korrekt ausgeführt und das Büro-Licht ist an.

**Comment by Apollon77** [comment]
verwechselst Du gerade den Smart Home Skill mit dem Custom Skill?
Der Custom SKill triggert nur mittels "Alexa, sage ioBroker Bla Fasel Huhu" ... Das was Du oben schreibst ist der Smart Home Skill wo nur angelernte Geräte geschaltet werden -  da kommt dort nichts an beim Custom SKill

**Comment by ma-gu-16** [comment]
Ja ich habe beide aktiv. ist das der Fehler ?

**Comment by ma-gu-16** [comment]
> verwechselst Du gerade den Smart Home Skill mit dem Custom Skill?
> Der Custom SKill triggert nur mittels "Alexa, sage ioBroker Bla Fasel Huhu" ... Das was Du oben schreibst ist der Smart Home Skill wo nur angelernte Geräte geschaltet werden - da kommt dort nichts an beim Custom SKill

Update, auch wenn ich alles neu einrichte und NUR den Custom Skill verbinde, bleibt es bei dem gleichen Problem.

**Comment by Apollon77** [comment]
Und du sagst auch wirklich "Alexa, sage ioBroker Was auch immer er tun soll" ? Was ist die Antwort?

**Comment by Apollon77** [comment]
Bitte iot Adapter auf Debug stellen und Log zeigen

**Comment by ma-gu-16** [comment]
Adapter IOt , habe ich Ausgabe debuggen aktiv. Aber keinerlei LOG einträge. 

Ich starte den Skill direkt via:  Alexa, starte i.o. broker: 

Alexa sagt: Hallo, was möchtest du wissen oder steuern: 

Ich sage: welche Fenster sind auf 

Alexa: die Verarbeitung von "" ist nicht möglich.   (Die "" ist wie eine kleine Pause also ein Leerschlag)

**Comment by ma-gu-16** [comment]
kann ich sonst irgendwie helfen zu debuggen ?

**Comment by ma-gu-16** [comment]
> kann ich sonst irgendwie helfen zu debuggen ?

wie gesagt im log ist nichts, wo genau im code müsste ich debuggen ?

**Comment by Apollon77** [comment]
Hast du iot mal im debug log modus gestartet? Da muss was kommen ...
Instanzen -> expertenmodus -> Spalte Log-Stufe

**Comment by ma-gu-16** [comment]
> Hast du iot mal im debug log modus gestartet? Da muss was kommen ...
> Instanzen -> expertenmodus -> Spalte Log-Stufe

aaaahhhh ;-) Dachte es ist die Options Ausgabe Debuggen in der Instanz selbst. 

Ok here we go: gleicher Fenster satz: 

`

iot.0 | 2020-09-20 23:26:05.944 | debug | (10029) askDevice: questionStart = sind, adjective = undefined, articletwo = undefined, questionDetails = undefined, state = auf, place = undefined, device = fenster, article = die, status = undefined
-- | -- | -- | --
iot.0 | 2020-09-20 23:26:05.944 | debug | (10029) 1600637165944 ALEXA: {"version":"1.0","session":{"new":false,"sessionId":"amzn1.echo-api.session.xxxxx","application":{"applicationId":"amzn1.ask.skill.x-
iot.0 | 2020-09-20 23:26:05.943 | debug | (10029) Data: "{\"version\":\"1.0\",\"session\":{\"new\":false,\"sessionId\":\"amzn1.echo-api.session.xxxxx\",\"application\":{\"applicationId\":\"amzn1.ask.skill.6cee68
iot.0 | 2020-09-20 23:26:05.943 | debug | (10029) Request command/xxxxx/alexa
iot.0 | 2020-09-20 23:25:58.650 | debug | (10029) LaunchRequest

`

**Comment by ma-gu-16** [comment]
Ok Feedback, aus irgendwelchen Gründen auch immer aber jetzt funktioniert es. Ich habe bis auf den Debug (vor paar Minuten) nix geändert. auch text2command geht . Sehr merkwürdig. 

Somit hat sich das wohl erledigt. Danke für deine Hilfe.

**Comment by Apollon77** [comment]
Super, aber ja sehr merkwürdig ... wir haben nichts geändert ... hm ...Naja: Viel Spass :-)
