### ISSUE TITLE
GHOME: Beim Editieren hängt sich der Browser auf

### ISSUE THREAD

**Issue by MiJo112** [ioBroker/ioBroker.iot#162]
Beim Klicken auf Edit und mit OK übernehmen bei irgendeinem state oder channel im Tab Google-Geräte hangt sich der Browser auf.
Google Chrome in der letzten Version.

Fehler kann reproduziert werden.
Welche Logs sind Hilfreich?
JS Controller: 3.1.4
Node.js: v10.20.1 
IoT: 1.7.9

**Comment by MiJo112** [comment]
Nach Downgrade auf 1.7.7 geht es wieder. Bug wurde also mit 1.7.9 eingebaut

**Comment by Mimamau** [comment]
Tritt bei mir auch mit 1.7.7 auf.

**Comment by smoki3** [comment]
Habe auch das Problem. Aktuell mit 1.7.11

**Comment by JackDaniel007** [comment]
Hier auch das gleiche

Node.js v12.19.0
NPM 6.14.8
JS Controller latest

**Comment by thorsten26** [comment]
[https://github.com/ioBroker/ioBroker.iot/issues/176](related to this?)

**Comment by smoki3** [comment]
Hat schon jemand die 1.7.13 versucht?

**Comment by thorsten26** [comment]
@smoki3 siehe mein Beitrag hier mit Verweis auf 176.

**Comment by smoki3** [comment]
@thorsten26 das mit dem Dialogfeld ist ein anderes Problem gewesen (ist glaube ich mit 1.7.15 nun gefixed) Aber der Browser friert immer noch ein

**Comment by GermanBluefox** [comment]
Please test v1.8.0
