### ISSUE TITLE
Fehlende Namen bei Channels und Devices im Auswahlmenü

### ISSUE THREAD

**Issue by Speedbreaker12** [ioBroker/ioBroker.iot#164]
Hi Bluefox,

wie schon beim Javascript Adapter, fehlen im neuen Auswahldialog, die Namen bei channels und devices.
Es wäre super, wenn das hier auch gefixed werden könnte.

**Comment by DocGame69** [comment]
du sprichst mir aus dem Herzen....
Würde auch gerne von meiner V1.5.3 auf den neusten Stand gehen da ich jede Menge Jalosien, Saugroboter usw. sauber einbinden will. Ab einführung der neuen GUI in V1.6.1 ist der Adapter aufgrund der Fehlenden Namen Quasi nicht mehr zu bedienen(Wie auch andere Adapter mit der neuen Oberfläche----Scenen, text2command usw). Wenigstens wurde es inzwischen im JS-Adapter gerichtet. Ist beim IOP und den anderen auch damit zu rechnen?
![iot1 7 9](https://user-images.githubusercontent.com/43096454/94043083-a57fe700-fdcc-11ea-8a98-35adeeab9067.JPG)
Ab hier gings beim IOT los:
![IOTVersionen](https://user-images.githubusercontent.com/43096454/94043122-b92b4d80-fdcc-11ea-8e6b-36d159f0c76f.JPG)

**Comment by Negalein** [comment]
Mit IOT: 1.7.11 auch das Problem

![instances - ioBroker](https://user-images.githubusercontent.com/45309436/95136579-a9b1ea00-0766-11eb-88c1-4736a46ccdbf.png)

Node.js: 12.18.3 
NPM: 6.14.6
Admin: 4.8.1

**Comment by thorsten26** [comment]
[https://github.com/ioBroker/ioBroker.iot/issues/177](Related to here, 1.5 Monthes old!!!)
