### ISSUE TITLE
"Intelligente Aufzählungen" funktioniert nicht richtig mit "Eigene Einstellungen (nur pro)"

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.iot#168]
kurz zum Hintergrund: ich will eine IoT Instanz mit der ich mein SmartHome steuere/abfrage. Zusätzlich will ich eine iot Instanz für einen Kumpel der meine WetterDaten über text2kommand abfragen kann. diese zweite iot Instanz soll keine Alexa-Geräte kennen.
**Fehler**
Wenn man eine Zweite Iot Instanz erstellt und bei dieser "Eigene Einstellungen (nur pro)" aktiviert kann man die Intelligente Aufzählungen nicht abschalten. 

**To Reproduce**  
Installiert sind zwei Instanzen von Iot (Iot.0 und Iot.1)
Iot.0 nutzt die default SmartNamen (nicht "Eigene Einstellungen (nur pro)"). Hier sind Alle Intelligenten Aufzählungen aktiviert.
Iot.1 soll "Eigene Einstellungen (nur pro)" verwenden.
Wenn ich nun die Haken bei Iot.1,  "Intelligente Aufzählungen" rausmachen, werden weiterhin die Alexa-Geräte gefunden. Der Datenpunkt von z.B. "enum.functions.blinds" sieht nun so aus: 

> {
  "_id": "enum.functions.blinds",
  "common": {
    "name": {
      "en": "Blinds",
      "de": "Rollladen"
    },
    "members": [],
    **"custom": {
      "iot.0": {
        "smartName": false
      }**
    }
  },
  "type": "enum",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1588276123532,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
Hier muss man beachten dass er ein custom für iot.0 erzeugt hat, nicht für iot.1. Auch ein manuelles Ändern auf iot.1 brachte keine veränderung.

Ein weiterer Fehler der damit zusammenhängt: Wenn ich nun in iot.1 ein Alexa-Geräte lösche, sieht das Object danach so aus:
> {
  "_id": "0_userdata.0.testheizung.Termostat2.Temp",
  "type": "state",
  "common": {
    "name": "Temp",
    "role": "",
    "type": "number",
    "desc": "Manually created",
    "read": true,
    "write": true,
    "def": false,
    **"smartName": false**
  },
  "native": {},
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1588276254063,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  }
}

dadurch wird das Gerät für alle Iot Instanzen ignoriert.

**Expected behavior**  
jede Iot instanz soll seine Alexa-Gräte frei einstellen können

**Versions:**  
 - Adapter version: 1.7.11
 - JS-Controller version: 3.1.6
 - Node version: v10.20.1
 - Operating system: linux / Container

**Comment by DreamScout** [comment]
Gleiches Problem

**Comment by Airwave1981** [comment]
Hallo,

auch ich habe das Problem.


LG
