### ISSUE TITLE
Blockly Sendto iot.0 not working

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.iot#17]
the blockly sendto iot is not working - if I look at the javascript it is using cloud.0 instead of iot.0

**Comment by Plasmachef** [comment]
das kann ich bei IFTTT bestätigen!
hab alles korrekt eingestellt in der instanz "iot.0".
ich arbeite (wenn es geht) nur über blockly.
der empfang von daten über diese instanz klappt hervorragend.
jedoch, wenn ich versuche etwas zu versenden (IFTTT Key ist eingetragen und identisch mit dem der "cloud.0" instanz) dann kommt nichts an ... sobald ich aber die "cloud.0" instanz aktiviere. dann geht es sofort durch (sobald sie sich verbunden hat) obwohl ich an der aufforderung über "iot.0" zu senden nichts geändert habe und keinen aktiven befehl für das senden über "cloud.0" gegeben habe.
stehe für nachfagen gerne zur verfügung!

**Comment by liv-in-sky** [comment]
wenn man das "übersetzte" blockly  in ein jscript kopiert und - von hand - cloud.0 auf iot.0 ändert, funktioniert auch ifttt ohne cloud adapter

**Comment by GermanBluefox** [comment]
Fixed

вс, 30 дек. 2018 г., 18:48 liv-in-sky notifications@github.com:

**Comment by liv-in-sky** [comment]
hallo - sorry für die frage:
muss ich etwas installieren oder kommt der fix mit einem update -  momentan steht noch cloud.0 beim übersetzen blockly - ist blockly ein teil vom js-adapter?

**Comment by elzershark** [comment]
isues als Video:

https://drive.google.com/file/d/1LzhJsdh4yDu2tfrOmq6sVwQTQfY-Qj74/view

**Comment by Plasmachef** [comment]
Leider ist der Fehler mit der version 0.3.1 nicht behoben worden!
Es steht jetzt zwar im blockly die richtige instanz-zugehörigkeit drinnen (iot.0 ... auch im bei blockly-->skript umwandlung zu sehen), aber im hintergrund bezieht er sich immer noch auf "cloud.0".
Kann man ganz einfach testen in dem man die instanz "cloud.0" pausieren lässte ---> dann geht nichts mehr an IFTTT raus, trotz des selben "IFTTT-Keys" in beiden instanzen.
Bitte issue wieder auf "open" setzen.
Danke :-)

**Comment by Apollon77** [comment]
Ifttt blocklies sind im Cloud Adapter enthalten und nicht im ifttt Adapter. Bitte Cloud aktualisierten. Ggf vom GitHub.

**Comment by elzershark** [comment]
in der "normalen" Cloud wird ifttt verarbeitet. Beispiel: Blockly sendTo: ifttt iot.0 
Da steht zwar iot... Aber der iot sendet quasy an die "normale" Cloud das "er" doch bitte die Daten zu IFTTT schicken soll. Bedeutet.. ist die "normale" Cloud deinstalliert oder "rot", ist es normal, das ifttt nicht funzt... b.z.w. keine/einige Befehle funzen von Blockly SendTo

**Comment by Plasmachef** [comment]
Okay, das wusste ich nicht.
Dann ist es normal und gewollt. 
... sorry für die Aufregung!
Somit sollte das issue auch closed bleiben.

**Comment by Apollon77** [comment]
Ist nicht transparent ... mal überlegen
