### ISSUE TITLE
GHOME Geräte löschen und hinzufügen qualvoll

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.iot#171]
Ich würde gerne meine Geräte manuell zur Liste hinzufügen aber der Prozess ist qualvoll.

Löschen hat mich bei jedem Gerät zu der Browsermeldung "Eine Webesite verlangsamt ihren Browser .. Anhalten/Warten?" geführt .. irgendwie hab ich mich da durchgehangelt. Nun versuche ich Geräte hinzuzufügen und es ist genau das gleiche .. nur dass ich die Instanz nicht überlisten - und Geräte trotzdem hinzufügen - kann.

Probiert mit FireFox und Chrome.

Was mag da los sein?

**Comment by Johan219** [comment]
Bei mir genau das gleiche Problem! Gibt es da schon eine Lösung?

**Comment by daniel-lo** [comment]
@Johan219
Ich hab's letzlich so gemacht: Downgrade auf 1.7.1 .. alles hübsch gemacht .. dann wieder Upgrade auf 1.7.11

**Comment by Johan219** [comment]
@daniel-lo 
Danke für den Hinweis. Jetzt hat es bei mir auch geklappt! Natürlich schon schade, dass es umständlich muss

**Comment by daniel-lo** [comment]
Ihr Druckauftrag per Email wurde empfangen aber die Email-Adresse des Druckers ist nicht bekannt. Bitte prüfen Sie die Email-Adresse und versuchen Sie es erneut.

**Comment by thorsten26** [comment]
[https://github.com/ioBroker/ioBroker.iot/issues/176] (may be related)

**Comment by smoki3** [comment]
Das Problem wurde hier schon adressiert. Leider noch keine Reaktion

https://github.com/ioBroker/ioBroker.iot/issues/162

**Comment by GermanBluefox** [comment]
Please test v1.8.0

**Comment by smoki3** [comment]
@GermanBluefox Browser freezed nicht mehr. Allerdings lassen sich Geräte nicht mehr löschen. Der Haken ist ausgegraut.

**Comment by GermanBluefox** [comment]
Ich kann schalten nicht reproduzieren. Kannst du mi logs beim Start (mit DEBUG) hier oder privat (dogafox@gmail.com) posten?

**Comment by GermanBluefox** [comment]
Löschen von Geräten ist in 1.8.1 gefixt

**Comment by daniel-lo** [comment]
@GermanBluefox 

Ist auch gefixed, dass in GH gelöschte Geräte nicht auch gleich aus der Alexa-Geräteliste verschwinden? VG

**Comment by GermanBluefox** [comment]
> @GermanBluefox
> 
> Ist auch gefixed, dass in GH gelöschte Geräte nicht auch gleich aus der Alexa-Geräteliste verschwinden? VG

Alexa und Google haben wenig mit einander zu tun und das war gar nicht angestrebt.

**Comment by daniel-lo** [comment]
@GermanBluefox 

Ja .. aber es gab da beim Löschen irgendeine Verbindung/Abhängigkeit .. ich musste bei Alexa Geräte neu einrichten .. nachem ich sie im GH Reiter gelöscht hatte .. kann leider jetzt kein Beispiel mehr liefern .. läuft auch grad alles so schön :-)

**Comment by smoki3** [comment]
@GermanBluefox Ich habe noch ein Bug in der neuen Liste gefunden. Und zwar kann ich nicht alle Geräte sehen, außer ich zoome im Browser auf 10%
