### ISSUE TITLE
Getter Service für custom_ Objekte

### ISSUE THREAD

**Issue by msussek** [ioBroker/ioBroker.iot#172]
Hallo,

kann man eigentlich über die API von service.iobroker.in den Wert eines custom_ Objekts auch auslesen (also gibt es eine Getter-Funktion)?

Bisher ist mir nämlich nur die Setter-Funktion bekannt, also mit

https://service.iobroker.in/v1/iotService?service=custom_<NAME>&key=<XXX>&user=<USER_EMAIL>&data=myString

kann man über die Cloud den lokalen Datenpunkt iot.0.services.custom_<NAME> auf den Wert myString setzen.

Siehe hierzu auch https://github.com/ioBroker/ioBroker.iot

Das ist ein sehr nettes Feature, denn ich muss keinen Port dafür in der Firewall öffnen, sondern das Update erfolgt über die bestehende Verbindung zwischen lokalem Iobroker.iot Adapter und externem Cloud Server, der diese API bereit stellt. 

Ich nutze das beispielsweise schon für die Anwesenheitserkennung und es funktioniert gut.

Nun hat mich aber dieses Video https://youtu.be/A5PpgocM3Tc dazu inspiriert, mal in das Thema "eigene Alexa-Skills schreiben" einzusteigen.

Was ich aber vermeiden möchte ist, wie in diesem Video gezeigt einen Port öffnen zu müssen, damit der SimpleAPI-Adapter von außen durch die Amazon-Server angesprochen werden kann.

Daher meine Idee, dies über die custom_ Datenpunkte zu machen, die ja ohnehin schon über die externen Iobroker IoT-Cloud-Services gesetzt werden können.

So würde ich mir das potentiell gefährliche Öffnen eines Ports sparen und könnte diese Funktion trotzdem nutzen.

Allerdings fehlt mir dafür bisher wie gesagt leider die Möglichkeit, die aktuellen Werte der custom_ Datenpunkte per API auszulesen.

Gibt es diese Möglichkeit schon als versteckte / undokumentierte Funktion? Wenn nicht, wäre es möglich, eine solche Funktion in einem zukünftigen Release zu implementieren?

Dankeschön und viele Grüße, 
Marco

**Comment by GermanBluefox** [comment]
So ein Funktionalität steht in iobroker.cloud zur Verfügung:
https://github.com/ioBroker/ioBroker.cloud#simpleapi
