### ISSUE TITLE
Dialogfeld "ID auswählen" ist nicht mehr da

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.iot#176]
Grade ein Update iot von 1.7.11 auf 1.7.13 gamacht, Das Dialogfeld wird nicht eingeblendet.

Node.js 12.19.0
NPM 6.14.8
Host 3.1.6

**Comment by cocoon77** [comment]
Hab das selbe Problem 

Node.js 12.19.0
NPM 6.14.8
Host 3.1.6

Downgrade auf 1.7.7 funktioniert es wieder.

**Comment by vaaarg** [comment]
same here

**Comment by guergen1** [comment]
Downgrade auf 1.7.11 war bei mir ausreichend!

**Comment by FabianHM** [comment]
Problem auch bei mir vorhanden. 
Bei Aufruf des Buttons "+" wird die Oberfläche leer.
Downgrade auf 1.7.12 hilft auch nicht

**Comment by thorsten26** [comment]
Mich verwundert es ein wenig, dass seit 2 Tagen hier ein erheblicher Fehler vorliegt aber anscheinend bisher noch nicht die richtige Priorität vergeben wurde?

**ACHTUNG! DOWN FROM IOT ADAPTER!**

Warum Down? Nun, wenn ich diesen sehr wichtigen Adapter zu einem bezahlten Service nicht konfigurieren kann bleiben bei mir in der Zeit zum Beispiel die Lichter einfach aus! (Ich benutze ausschließlich Alex zur Steuerung meiner Lampen.

Deshalb hier eine ausführliche Fehlerbeschreibung:

Unter Instanzen/iot.0/Edit/Alexa-Geräte möchte ich über den Button + ein neues Gerät hinzufügen.
Nach Klicken auf das + erscheint allerdings keine Auswahlliste der Geräte! (Die Seite ist leer!!)

Dies betrifft die IOT Version 1.7.13. Nach Downgrade auf die Version 1.7.7 funktioniert wieder alles wie gewohnt.
Node.js 12.19.0
NPM 6.13.7

**Comment by FabianHM** [comment]
> 
> 
> Mich verwundert es ein wenig, dass seit 2 Tagen hier ein erheblicher Fehler vorliegt aber anscheinend bisher noch nicht die richtige Priorität vergeben wurde?
> 
> **ACHTUNG! DOWN FROM IOT ADAPTER!**
> 
> Warum Down? Nun, wenn ich diesen sehr wichtigen Adapter zu einem bezahlten Service nicht konfigurieren kann bleiben bei mir in der Zeit zum Beispiel die Lichter einfach aus! (Ich benutze ausschließlich Alex zur Steuerung meiner Lampen.
> 
> Deshalb hier eine ausführliche Fehlerbeschreibung:
> 
> Unter Instanzen/iot.0/Edit/Alexa-Geräte möchte ich über den Button + ein neues Gerät hinzufügen.
> Nach Klicken auf das + erscheint allerdings keine Auswahlliste der Geräte! (Die Seite ist leer!!)
> 
> Dies betrifft die IOT Version 1.7.13. Nach Downgrade auf die Version 1.7.7 funktioniert wieder alles wie gewohnt.
> Node.js 12.19.0
> NPM 6.13.7

Exakt mein Problem. Schade mit den ständig neuen Fehlern der letzten Woche 👎

**Comment by thorsten26** [comment]
@FabianHM ich bin gerade dabei quasi aufzugeben. Das System ist super, d.h. die Engin. Aber sobald man etwas visuell darstellen möchte - ein Fehler nach dem Anderen und das seit Jahren.

Ich denke man sollte die Weiterentwicklung des Backends mal ein paar Monate einfrieren und sich um die ganzen visuellen Fehler kümmern?

**Comment by Grothesk242** [comment]
> @FabianHM ich bin gerade dabei quasi aufzugeben. Das System ist super, d.h. die Engin. Aber sobald man etwas visuell darstellen möchte - ein Fehler nach dem Anderen und das seit Jahren.
> 
> Ich denke man sollte die Weiterentwicklung des Backends mal ein paar Monate einfrieren und sich um die ganzen visuellen Fehler kümmern?

Dir ist aber schon bewusst, dass es sich bei Version 1.7 des Adapters um eine BETA handelt und es da in der Natur der Sache liegt, dass dort Fehler drin sind und die dann über Issues adressiert werden? Wenn du damit nicht leben kannst, installier die stabile Version des Adapters.

**Comment by thorsten26** [comment]
@Grothesk242 das heißt dann mit den Fehlern der 1.5.3 bis 1.7.13 zu leben? Hört sich nach "Vom Regen in die Traufe an"?
[https://github.com/ioBroker/ioBroker.iot/issues/170](zur Info)

**Comment by Grothesk242** [comment]
> @Grothesk242 das heißt dann mit den Fehlern der 1.5.3 bis 1.7.13 zu leben? Hört sich nach "Vom Regen in die Traufe an"?
> [https://github.com/[/issues/170](https://github.com/ioBroker/ioBroker.iot/issues/170)](zur Info)
> 
> Bezüglich Versioning habe ich mich an anderer Stelle geäußert

Du musst dich halt entscheiden. Bleeding Edge mit neuen Fehlern, die natürlich drin sind oder eine stable, die eigentlich keine 'dicken Dinger' drin haben dürfte. Issue 170 ist doch nur ein Vorschlag. Stable ist der 1.5-Tree.

**Comment by Ilovegym66** [comment]
@thorsten26 trink mal n Bier und komm mal runter.. 
Auf dem produktiven System setzt man halt besser nur das ein, das auch getestet ist und stabil läuft. 
Eine komplett Fehlerfreie Software gibt es auf der ganzen Welt nicht, mit irgendwas muss man immer leben.
Wenn dir diese Version nicht produktiv genug ist, dann geh halt eins oder zwei Versionen zurück oder spiel das letzte für dich funktionierende Snapshot ein.

Die Programmierer hier haben alle auch einen Vollzeitjob, Familie ( und die trifft dieses Jahr Corona auch, egal wie und wo) und wenn du für die Programmierung bezahlen müsstest, wärst du nicht mit den paar Groschen für die Cloud/IOT Anbindung im Jahr dabei.. 

Ich hab mich auch schon geärgert, weil ich Gedankenlos eine Beta auf dem produktiv eingespielt hatte und dann kein Backup hatte also.. herzlich Willkommen bei den Beta-Testern, aber dann bitte mit sachgemässer Kritik und Logfiles aus iobroker und browserconsole, oder herzlich Willkommen auf dem stable.
Mann kann nicht alles gleichzeitig haben...

**Comment by thorsten26** [comment]
Ich bin mittlerweile Alkoholiker haha

Nein, ich sehe das ein wenig anders.
Ich versuche seit 2 Wochen eine blöde Osram Farblampe anzusteuern und 2 Philips Hue Lampen mit einem Color-Picker in VIS zu integrieren. Einfach geht anders!

Und dabei habe ich die Dummheit begangen das System auf den neusten Stand zu bringen mit dem Erfolg, dass sich die komplette Struktur unter Dekonz geändert hat - es läuft gar nichts mehr.

Ich bin ja nicht ganz unbedarft und habe sogar den Weg zu Git-Hub gefunden, aber was machen die normalen Benutzer?
Ist es zuviel verlangt wenn ich über den IOT Adapter meine Farbe der Lampen einstellen möchte?
Mal abgesehen davon das der Wunsch in der Alexa App die Farbe einstellen zu können anscheinend nicht nachvollzogen werden kann, immerhin eine Alternative zu Vis.

Hierbei handelt es sich aber nicht um einen Bug der Engin sondern um einen Bug der Benutzeroberfläche und dieser ist sei ca. mitte September "plötzlich" vorhanden.

Mir geht es im wesentlichen darum die Entwickler darauf hinzuweisen das man sich eventuell mal um die Basis eines IOT kümmern sollte, schlichtweg Lampen die seit Jahren existieren kontrollieren zu können oder wieder kontrollieren zu können ohne auf Linux-Ebene html dateien anpassen zu müssen.

Gerade auch im Hinblick auf den iobroker Shop.

**Comment by Apollon77** [comment]
@thorsten26 "die Entwickler darauf hinzuweisen" ist ja ok und das geht mit einem "thumbs up" im ersten Beitrag des Issues. DAS ist der Weg das User den Entwicklern zeigen können wir relevant ein Bug ist! Überdenke auch bitte mal Deine Art und Weise hier zu kommunizieren.

Oben wurde es genannt und ein grund warum die 1.7 nicht Stable ist, ist dieses Issue. Also: die Stable Version tut. Kannst gern downgraden.

Zu Deiner Lampe: siehe https://github.com/ioBroker/ioBroker.iot/issues/178#issuecomment-721414653

**Comment by GermanBluefox** [comment]
> Mich verwundert es ein wenig, dass seit 2 Tagen hier ein erheblicher Fehler vorliegt aber anscheinend bisher noch nicht die richtige Priorität vergeben wurde?
> 
> **ACHTUNG! DOWN FROM IOT ADAPTER!**
> 
> Warum Down? Nun, wenn ich diesen sehr wichtigen Adapter zu einem bezahlten Service nicht konfigurieren kann bleiben bei mir in der Zeit zum Beispiel die Lichter einfach aus! (Ich benutze ausschließlich Alex zur Steuerung meiner Lampen.
> 
> Deshalb hier eine ausführliche Fehlerbeschreibung:
> 
> Unter Instanzen/iot.0/Edit/Alexa-Geräte möchte ich über den Button + ein neues Gerät hinzufügen.
> Nach Klicken auf das + erscheint allerdings keine Auswahlliste der Geräte! (Die Seite ist leer!!)
> 
> Dies betrifft die IOT Version 1.7.13. Nach Downgrade auf die Version 1.7.7 funktioniert wieder alles wie gewohnt.
> Node.js 12.19.0
> NPM 6.13.7

**Benutze bitte nie die latest Versionen.** Bei Stable passiert so was quasi nie.

**Comment by guergen1** [comment]
Läuft wieder....
