### ISSUE TITLE
iot Adapter select Object-ID

### ISSUE THREAD

**Issue by thorsten26** [ioBroker/ioBroker.iot#177]
Um ein Gerät zum IOT-Adapter hinzuzufügen wird, nachdem man auf das + geklickt hat in einem Fenster eine Objektliste auf Ordnerebene angezeigt.

Beispiel deconz

durch Öffnen der Unterordner 0/lights erscheinen die Ordner für Lampen. Allerdings wird in dieser Liste lediglich die hexadezimale ID angezeigt und nicht zusätzlich der Name der Lampe oder das Zimmer der Lampe!
Bei 30 Lampen ist man quasi gezwungen jeden Ordner zu öffnen um dann irgend wann die richtige Lampe zu finden.
Dies gilt ebenfalls für alle anderen Ordner.

IOT Adapter 1.7.7

**Comment by GermanBluefox** [comment]
Sollte mit 1.7.15 gehen

**Comment by Ilovegym66** [comment]
yes, fixed! dankeschön!
