### ISSUE TITLE
deconz/phoscon/Iobroker hinzufügen einer Philips Hue Color Lampe

### ISSUE THREAD

**Issue by thorsten26** [ioBroker/ioBroker.iot#178]
Alle Adapter etc. auf neustem Stand!

**SCHOCK!!!!!**

Nachdem Anlernen einer Standard Philips Hue Color Lampe Typ LCA001 erscheint diese in IOBroker Admin unter Objekte.

Um diese Lampe mit Alexa ansteuern zu können werden  unter Instanzen/iot.0/EDIT/Alexa/ die Attribute:
Hue Color, Color temperature, Brightness, Saturation benötigt.

Allerdings tritt beim Hinzufügen der Attribute Hue und Saturation ein Fehler auf "Dieses Gerät kann nicht hinzugefügt werden"! Somit ist eine Ansteuerung mit Alexa nicht möglich.

**_Nach stundenlangem Suchen habe ich dann eine mögliche Lösung die Monate alt ist gefunden! (Betonung auf Monate!!!! bei einer Standard Lampe eines deutsche Marktführers!!!!!_**

In den Raw Werten für die Attribute Sat und Hue den leeren Wert "native": {}

durch
`  "native": {
    "read_only": true,
    "write_only": false
  }`
ersetzen.

Hierbei kann es sich ja wohl nur um einen Bug handeln und diese Änderung kann nur ein Workarround zur Umgehung des Bugs sein?

Hier die kompletten RAW Daten mit Hinweis auf die Attribute "read" und "write"

`{
  "type": "state",
  "common": {
    "name": "Hue color",
    "type": "number",
    "role": "level.color.hue",
    "read": true,
    "write": true,
    "unit": "°",
    "min": 0,
    "max": 360,
    "def": 360,
    "custom": {
      "iot.0": {
        "smartName": {
          "de": "WD3",
          "smartType": "LIGHT",
          "byON": "stored"
        }
      }
    }
  },
  "from": "system.adapter.deconz.0",
  "user": "system.user.admin",
  "ts": 1603118461322,
  "_id": "deconz.0.lights.001788010837f140.hue",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {
    "read_only": true,
    "write_only": false
  }
}`

**Comment by Apollon77** [comment]
Du sagst also das das Objekt was der deconz Adapter erzeugt hat falsch ist.Das ist ein Super Finding - Das Issue gehört also in das GitHub des deconz Adapters, oder ? Vor allem auch weil native Adapterspezifisch ist. Das kann also nichts mit iot zu tun haben.

Ich blicks gerade nicht?

PS: Schau mal bitte bei deiner Tastatur nach der hängenden Ausrufezeichen-Taste ;-)

**Comment by Apollon77** [comment]
Zu Deiner Lampe (und hier ist dem Adapter egal wie lange es die Lampe gibt - einzige die existierenden Objekte und States sind relevant! Wenn also ein Adapter Lampen so anlegt das Sie nicht genutzt werden können, so ist das leider im entsprechenden Adapter zu fixen!

Lampen in der aktuellen iot Implementierung gehen wenn ein Objekt mit der "role" level.color.hue existiert MIT einem level.color.saturation und optional noch einem level.dimmer. Alterativ geht es auch mit einem level.color.rgb objekt.

Was genau hast Du also für Objekte? Wenn falsch dfann bitte im deconz Adapter ein Issue anlegen

**Comment by GermanBluefox** [comment]
Bitte Bug bei deconz aufmachen.
