### ISSUE TITLE
IoBroker Admin Farbe der Ordnernamen unter Objekten

### ISSUE THREAD

**Issue by thorsten26** [ioBroker/ioBroker.iot#179]
Auch dieses Problem wird seit Monaten berichtet!

Die Farbgebung der Ordnernamen ist mehr als Missglückt!!! Grau auf Grau.

Warum nicht einfach ein hübsches Schwarz auf hellgrauem Grund?

Letztendlich gibt es ja das Ordnersymbol, mal abgesehen vom Pfeil um den Ordner zu erweitern....

![image](https://user-images.githubusercontent.com/56251890/97867812-d67a0280-1d0e-11eb-8096-f9a0ace6f13d.png)

**Comment by Apollon77** [comment]
Bitte issue im Admin Adapter prüfen und ggf dort anlegen. Hat nichts mit dem iot Adapter zu tun
