### ISSUE TITLE
2. iot instance startet nicht

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.iot#18]
habe 2 Alexas mit eigenen Amazon Accounts. 
Meine Annahme ist, das ich für jede Alexa mit eigenem Account jeweils eine eigene Alexa2 und iot  instance benötige.

habe dementsprechend einen Alexa2.0 und einen Alexa2.1 auf dem Raspberry laufen (beide grün)
habe dementsprechend einen iot.0 und einen iot.1 installliert, aber leider läuft nur der iot.0, der iot.1 bleibt bei Gelb, im Log steht

>iot.1 | 2018-12-27 21:22:36.912 | error | {}-- | -- | -- | --
iot.1 | 2018-12-27 21:22:36.909 | error | Cannot fetch keys: "Internal server error"
iot.1 | 2018-12-27 21:22:34.242 | error | Cannot read URL key: Not exists
iot.1 | 2018-12-27 21:22:34.186 | info | Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
iot.1 | 2018-12-27 21:22:34.110 | info | starting. Version 0.2.2 in /opt/iobroker/node_modules/iobroker.iot, node: v8.12.0

**Comment by Apollon77** [comment]
Aktuell ist nur eine iot Verbindung pro iot account möglich. Bei zwei iot Instanzen bräuchtest du aktuell auch zwei iot Accounts.

**Comment by Farmer-cb** [comment]
Jede alexa2 instance hat seine eigene Mailadresse
Jede iot instance hat auch seine eigene Mailadresse

**Comment by Apollon77** [comment]
Verbindungszertifikate neu erstellen funktioniert vllt?

**Comment by knobi4711** [comment]
I also get the message:
Cannot read keys: "[object Object]" / Error: [object Object]
Cannot fetch keys: {"message": "Internal server error"}

Neither the renewed requesting of the certificates, nor a new creation of the certificates from iobroker.pro, nor recrystallization of the entire system was successful.
