### ISSUE TITLE
Versioning von Adaptern

### ISSUE THREAD

**Issue by thorsten26** [ioBroker/ioBroker.iot#180]
In der Konfiguration von IOBroker mit der Admin Oberfläche gibt es die Möglichkeit einen aktiven Verwahrungsort einzustellen.

Dieser ist: Stabel (default) und Beta (latest).

Ich habe das Gefühl, dass die Version Stabel einfach zu weit hinter der Beta her ist und wahrscheinlich gar nicht mehr funktionsfähig ist insofern man seine Software auf dem neusten Stand hält.

Ein Beispiel:

IoT Assistants: Stabel 1.5.3
Beta: 1.7.13!!!!!!

Nach meinen Vorstellungen sollte eine Beta mit der irgendwann das Stadium verlassen, zum Beispiel mit 1.6 oder 1.7

Weitere Beispiele:

BackItUp, 1.6.7 und 1.7.0 (Was auf eine stabile Version schließen lässt.
deConz ZigBee 1.3.10 und 2.0.5!!!!
Script Engine 4.8.4 und 4.9.7

**Comment by Grothesk242** [comment]
Nach Gefühl geht das aber nicht. Auch nicht nach deinem. 

Am zigbee-Adapter kann man das z. B. ganz gut festmachen. Da hat der Developer selber schon gesagt, dass die V2 komplett überarbeitet werden muss. Ist auch okay, da BETA. Stable daher V1.

**Comment by Apollon77** [comment]
Am Ende liegt das beim jeweiligen Adapter Entwickler und dem Feedback der User. Ja hier ist der Diff etwas grösser und auch gerade ein Thema, daher duplicate

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.iot/issues/170 ... and yes postponed till we have test feedback from latest version
