### ISSUE TITLE
es können keine Geräte bei Alexa-Geräte manuell erfasst werden

### ISSUE THREAD

**Issue by CKMartens** [ioBroker/ioBroker.iot#182]
Unter Alexa-Geräte können keine Geräte manuell erfasst werden. Es erscheint eine leere weiße Fläche
![image](https://user-images.githubusercontent.com/19702758/98106682-d35f4d80-1e99-11eb-853e-c5785fc7afb9.png)

In der Entwicklerkonsole erscheint dieser Fehler:
`Autofocus processing was blocked because a document's URL has a fragment '#tab-instances/config/system.adapter.iot.0'.
index.js:17 iobroker.iot@1.7.13 using theme "colored"
instrument.ts:129 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

instrument.ts:129 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
instrument.ts:129 Help us to create open source project with reactJS!
instrument.ts:129 See you :)
admin.js:153 Cannot compare "" and "0.0.1"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.1.2"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.2.15"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.2.11"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "1.0.0"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.0.5"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.2.0"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.0.6"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.5.13"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.4.8-alpha.2"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.2.2"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.1.3"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.3.19"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.0.5"
upToDate @ admin.js:153
admin.js:153 Cannot compare "" and "0.2.0"
upToDate @ admin.js:153
instrument.ts:129 Send BROWSE!
instrument.ts:129 Update iot.0.smart.updates false/true
instrument.ts:129 BROWSE received.
instrument.ts:129 Update iot.0.smart.updates false/true
adminInstances.js:1065 195
DevTools failed to load SourceMap: Could not load content for https://iob1.martensnetz.de:8081/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
instrument.ts:129 ReferenceError: React is not defined
    at o.value (SelectID.js:121)
    at Fi (react-dom.production.min.js:182)
    at Mi (react-dom.production.min.js:181)
    at gs (react-dom.production.min.js:263)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Va (react-dom.production.min.js:122)
    at R (react-dom.production.min.js:287)
    at Kt (react-dom.production.min.js:68)
    at HTMLDocument.r (helpers.ts:87)
(anonymous) @ instrument.ts:129
es @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
fo @ react-dom.production.min.js:131
os @ react-dom.production.min.js:212
pl @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
fl @ react-dom.production.min.js:248
Zs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Va @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
r @ helpers.ts:87
SelectID.js:121 Uncaught ReferenceError: React is not defined
    at o.value (SelectID.js:121)
    at Fi (react-dom.production.min.js:182)
    at Mi (react-dom.production.min.js:181)
    at gs (react-dom.production.min.js:263)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Ha (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Va (react-dom.production.min.js:122)
    at R (react-dom.production.min.js:287)
    at Kt (react-dom.production.min.js:68)
    at HTMLDocument.r (helpers.ts:87)
value @ SelectID.js:121
Fi @ react-dom.production.min.js:182
Mi @ react-dom.production.min.js:181
gs @ react-dom.production.min.js:263
cl @ react-dom.production.min.js:246
sl @ react-dom.production.min.js:246
Zs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Va @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
r @ helpers.ts:87`

iot-Version 1.7.13
js-Controller 3.1.6
Node.js v12.19.0
NPM 6.14.8

**Comment by FH3D** [comment]
Ich habe dasselbe Problem. Mit 1.4.18 funktioniert es wieder (interim-Lösung, bis gefixed)

**Comment by CKMartens** [comment]
Danke für den Tipp @FH3D

**Comment by techducks** [comment]
@FH3D @CKMartens 

Version 1.4.18 von was?





![Unbenannt1](https://user-images.githubusercontent.com/63047974/98150564-23a4d280-1ecf-11eb-8bd4-2e3eecb33839.PNG)

![Unbenannt2](https://user-images.githubusercontent.com/63047974/98150566-243d6900-1ecf-11eb-9eb9-eafce0bcdf15.PNG)

**Comment by FH3D** [comment]
@techducks 
<img width="244" alt="adapters - ioBroker" src="https://user-images.githubusercontent.com/63076683/98150837-8b5b1d80-1ecf-11eb-813b-171b93d09df4.png">

**Comment by GermanBluefox** [comment]
Please test 1.7.15

**Comment by CKMartens** [comment]
@GermanBluefox  thanks you, it works fine for me.
