### ISSUE TITLE
Alle Geräte (ausser Switches) verschwunden

### ISSUE THREAD

**Issue by mediaDS** [ioBroker/ioBroker.iot#184]
**Describe the bug**  
Okay, zuerst habe ich die kostenlose Version verwendet, das Echo Gerät eingerichtet bzw. verknüpft und dann meine Geräte hinzugefügt. Habs dann getestet - funktionierte wunderbar. Dann für Pro meine Kohle bezahlt. Alle Geräte in der Liste danach weg. Toll. Keine Fehlermeldungen im Log. Okay, dann nochmal Geräte eingegeben - etwa 9 Rolläden und verschieden Switches. Danach wieder alles ok, Funktionierte prächtig. Bis zum Update auf 1.7.14. Danach waren wieder alle Geräte weg bis auf die Switches (siehe Screenshots - das ist der traurige Rest, der geblieben ist. Das heutige Update auf 1.7.15 hat nichts verändert. Da ich keine Lust verspüre, den ganzen Mist jedesmal wieder neu einzugeben, bitte ich inständig darum, mal nachzuschauen, was da schief läuft.

![Bildschirmfoto vom 2020-11-05 18-52-44](https://user-images.githubusercontent.com/48488629/98306823-e15dbd00-1fc4-11eb-88a2-4cfab3eeb8e1.jpg)

**Expected behavior**  
Ich habe erwartet, das die eingegebenen Geräte unangetastet bleiben.

**Screenshots & Logfiles**  

Das ist das einzige, was im Log stand

```
iot.0	2020-11-05 18:53:25.063	info	(25341) Request devices
iot.0	2020-11-05 18:52:38.670	info	(25341) Request devices
iot.0	2020-11-05 18:52:23.787	info	(25341) Request devices
iot.0	2020-11-05 18:51:35.869	info	(25341) Request devices
iot.0	2020-11-05 18:51:24.443	info	(25341) Request devices
iot.0	2020-11-05 18:50:20.296	info	(25341) Request devices
iot.0	2020-11-05 18:50:16.094	info	(25341) Request devices

```

**Versions:**  
 - Adapter version: 1.7.15
 - JS-Controller version: 3.1.6
 - Node version:  12.19.0
 - Operating system: Linux Arm64

**Comment by mediaDS** [comment]
Hallo? Da ich nicht vorhabe, bei jedem Update um die 20-30 Geräte neu einzugeben, wäre eine Möglichkeit, die Geräteliste separat zu sichern eine willkommene Funktion.

**Comment by AFPass** [comment]
Ich habe genau das gleiche Problem.
Alleine am IOT Adapter kann es aber nicht liegen. Habe es mit Version 1.5.3, 1.7.11 probiert.
Nach einem ioBroker Neustart sind die Geräte weg.

**Comment by Apollon77** [comment]
Die Daten werden bei den geräteobjekten gespeichert. Das das weg ist kann an sich nicht sein.

Was passiert nur bei einem Adapter Restart? Da noch alles da?

Irgendwelche Fehler im Logfile?

**Comment by AFPass** [comment]
Wenn ich den IOT Adapter neustarte sind die Geräte noch da.
Im Logfile sehe ich nichts

**Comment by mediaDS** [comment]
Hallo

> Die Daten werden bei den geräteobjekten gespeichert. Das das weg ist kann an sich nicht sein.

Doch. Ist so. Schon zweimal.

> Was passiert nur bei einem Adapter Restart? Da noch alles da?

Wenn ich nur den Adapter neustarte ist alles ok. Nach der Aktualisierung waren bisher zweimal (fast) alle Geräte weg. Siehe oben.

> Irgendwelche Fehler im Logfile?

Nein. Nur die von mir bereits aufgeführte Meldung.

**Comment by AFPass** [comment]
> > Die Daten werden bei den geräteobjekten gespeichert. Das das weg ist kann an sich nicht sein.
> 
> Doch. Ist so. Schon zweimal.

Passiert bei mir bei jedem ioBroker Neustart

**Comment by mediaDS** [comment]
Beim **Adapter Neustart** ist bei mir alles ok. ioBroker starte ich höchst selten neu, habe es aber gestern nochmal machen dürfen - danach waren alle Geräte noch da. Sehr seltsam. Ich habe einen Screenshot angehängt - mit insgesamt 10 Geräten. Mehr will ich erstmal nicht eingeben, ich nehme es mal als Referenz, falls es wieder gelöscht wird. Blöderweise ist der Fehler kaum zu reproduzieren, von daher muss ich auf das nächste Update warten.

![Bildschirmfoto vom 2020-11-09 13-31-02](https://user-images.githubusercontent.com/48488629/98541714-279a7100-2290-11eb-9a04-12c74d3dbb20.jpg)

**Comment by Apollon77** [comment]
@AFPass und keinerlei Fehler im Log? Der iot Adapter hat tausende Nutzer und ich höre das aktuell zum ersten mal.

Bitte stellt sicher das Admin, js-controller und so aktuell sind bitte!!

**Comment by AFPass** [comment]
Hallo,

Admin: 4.1.10
Javascript Adapter: 4.10.4
js-controller: 3.1.6
IOT: 1.7.15
node.js: 12.19

Gerade noch einmal ein Gerät angelegt.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/13101074/98602137-49bbdf80-22e0-11eb-9fbd-c480ff004f2d.png">

Keine Fehler im Logfile.

Gerät ist nach Neustart weg.

**Comment by mediaDS** [comment]
Alle Adapter sind aktuell auf ihrem heutigen Stand. Alle. Wie schon gesagt - dies passiert bei mir ausschließlich bei einer Aktualisierung des iot Adapters. Unter alexa.amazon.de sind alle Geräte danach vorhanden gewesen. Nur eben nicht unter Geräte im iot Adpater.

Ich werde es bei weiteren Aktualisierungen weiter beobachten und enstpr. hier weiter posten. An irgendwas muss es ja liegen.

**Comment by AFPass** [comment]
Ich habe noch etwas rum probiert.
Es scheint mit dem Adapter linkeddevices zu tun zu haben.

Ich habe 3 Alexa Geräte im iot Adapter. Die bleiben bei jedem Neustart stehen. Darunter sind 2 Geräte aus linkeddevices.
Ich habe nun ein neues linkeddevices Gerät im iot für Alexa angelegt.
Neustart iot. Alle Geräte sind noch da.
Neustart linkeddevices. Nur das neue Gerät ist weg. Die 3 anderen sind noch da.

**Comment by AFPass** [comment]
Ich werde morgen mal folgendes probieren:
https://forum.iobroker.net/topic/34420/gelöst-troubleshooting-iot-smart-devices-linkeddevices/10

**Comment by AFPass** [comment]
Die ersten Tests sehen gut aus. Scheinbar liegt es (in meinem Fall) an Linkeddevice.

**Comment by Apollon77** [comment]
Dann am besten issue dort öffnen. Es sollte zwar nicht passieren das custom Teile gelöscht werden aber wenn Objekte falsch "erweitert" werden kann es zu Problemen kommen

**Comment by mediaDS** [comment]
Ich verwende keine linkeddevices bei mir. Ich habe sowohl direkt Hardware-Datenpunkte als auch virtuelle Datenpunkte als Ziel für die Geräte. Aber sowohl die einen als auch die anderen werden gelöscht. Ein System darin kann ich nicht erkennen. Wie schon gesagt - ich werde es weiter beobachten.
