### ISSUE TITLE
temperature change with Alexa on own datapoint not working since 1.7.15

### ISSUE THREAD

**Issue by JF62** [ioBroker/ioBroker.iot#185]
As said in topic, since 1.7.15 a change of a own datapoint of a heatingsystem to new value via Alexa works fine until 1.7.14. in 1.7.15 I get feedback from Alexa: "Temerature changed to 0 degrees" instead of the new value and datapoint doesn't change to new value.

**Comment by mk176** [comment]
Got the same issue. 
"Temperatur is changed to 0"

**Comment by mk176** [comment]
No it works for me. If you put on silly logging it said:
"Cannot control hm-rpc.1.XXXXX.1.SET_POINT_TEMPERATURE. Role is not level.temperature."
The role was not set in may case. If i set it to level.temperature it works.

**Comment by JF62** [comment]
That was my mistake also...Close
