### ISSUE TITLE
Alexa ask for temperature not working with 1.7.15

### ISSUE THREAD

**Issue by saschaabraham** [ioBroker/ioBroker.iot#186]
After the upgrade to 1.7.15 alexa responds only with Device is not responding, no actual temperature. After downgrade to 1.7.14 it works again.

The temperature devices are some BME280 over mqtt and some xiaomi ble devices via the BLE-Adapter.

Nahc dem Upgrade auf 1.7.15 funktionieren keine Temperaturabfragen mehr. ALexa antwortet mit "Gerät antwortet nicht". Nach einem Downgrade zu 1.7.14 ist wieder alles normal.
Es handelt sich um  ein paar BME280 Sensoren über mqtt und um Xiaomi Bluetooth Sensoren über den BLE Adapter.

**Comment by Apollon77** [comment]
Steht irgendetwas im Log? Es wurde ein Check eingabaut das nur die Objekte berücksichtigt werden die auch die korrekte Rolle haben , da es sonst andere Probleme gab.
Welche Rolle haben die Objekte?

**Comment by saschaabraham** [comment]
Danke für den Tipp mit der Rolle. Die Objekte haben die Defaults gehabt beim BLE Adapter war das value, bei den MQTT war das variable. Die Werte werden so von den Adaptern angelegt, zumindest beim BLE bin ich mir sicher, hat gestern erst ein XIAMO so angelegt.
Im Source habe ich gefunden, dass es value.temperature sein muss.

**Comment by Apollon77** [comment]
>  Im Source habe ich gefunden, dass es value.temperature sein muss.

SOrry hätt ich irekt dazuschreiben sollen ...
