### ISSUE TITLE
Keine Bearbeiten der Google Geräte mehr möglich

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.iot#189]
**Describe the bug**  
Die Version 1.7.7 ist die letzte Version bei der ich Geräte in den Google Tab hinzufügen, entfernen oder bearbeiten kann. In den neueren Versionen hängt sich der Adapter jedes mal auf. 
![Screenshot 2020-10-26 at 11 37 35](https://user-images.githubusercontent.com/59663011/98861169-20788c00-2465-11eb-9cf6-f4b072a4fb8a.png)

**Comment by GermanBluefox** [comment]
Please test v1.8.0

**Comment by Dragon0501** [comment]
my broker still suggests 1.7.15. How do I get the 1.8.0?

**Comment by Dragon0501** [comment]
über die Katze geupdated. Alles gut. Funktioniert super!
