### ISSUE TITLE
Add the possibility to read humidity values and add them to Alexa/Google

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.iot#191]
Currenty it´s possible to add read only temperature sensors to iot and ask Alexa for the temperature in a room. This works fine. Many sensors come with humidity and I would like to get a reading on that as well.
If I try to add the humidity value I get an error msg like:State "jeelink.0.LaCrosse_6.humid" cannot be written and will be ignored

If I change the state to writeable and add it as thermostat for example it works, but it´s not read only.

Thanks 
Martin

**Comment by Apollon77** [comment]
requires skill v3 update https://github.com/ioBroker/ioBroker.iot/issues/29

**Comment by realwax** [comment]
@Apollon77 Gibt es dazu eigentlich news? Das v3 update  ist noch immer offen? Danke Ingo.

**Comment by Apollon77** [comment]
News dahingehend das ich langsam alle Themen die davor auf meiner Prioliste kommen abarbeite und bald an der Stelle angelangt bin ...

**Comment by realwax** [comment]
Danke!

**Comment by Pa1nstar** [comment]
Hallo @Apollon77,

habt Ihr einen konkreten Zeitplan für die Entwicklung des Alexa v3 Skills? Die letzten Einträge die ich gefunden habe, sind von 07/2022. Dort sagtest du dass von der Prio Liste her bald Zeit wäre. #29 ist die letzte Aktualisierung von 07/2020.

Wäre wirklich super wenn da noch etwas kommen würde, das würde Alexa deutlich leistungsfähiger machen. Derzeit finde ich keine Möglichkeit z.B. Luftfeuchtigkeit über Alexa auszugeben.

Ein kurzes Update wäre super. :-) gerne hier oder in #29.

DANKE!

Viele Grüße
#Bl4ckst4r
