### ISSUE TITLE
Update 1.8.2

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.iot#192]
Seit dem Update auf 1.8.2 werden alle Geräte bei google als nicht erreichbar angezeigt, kurz darauf wird der gesamte Account bei google rausgeschmissen. Downgrade auf 1.8.0 löst das Problem. Bei 1.8.1 ist das gleiche Problem.

**Comment by Dragon0501** [comment]
auch 1.8.3 löst das Problem leider nicht.

**Comment by GermanBluefox** [comment]
>  wird der gesamte Account bei google rausgeschmissen

Was bedeutet das? Das in Google home app ioBroker nicht mehr verbunden ist?

**Comment by Dragon0501** [comment]
Ja genau. Ich musste den ioBroker dann in der Home App neu hinzufügen. Übrigens gibt es doch eine Verbesserung bei der 1.8.3. Man kann wieder auf die 1.8.0 zurück und die Geräte funktionieren wieder ohne sie komplett in der Home App neu einzurichten.

**Comment by GermanBluefox** [comment]
Dann sollte was im ioBroker log drin sein. Kann man da was sehen?

**Comment by Dragon0501** [comment]
Was sollte man da sehen können?
Habe natürlich sofort die 1.8.0 zurückgespielt, damit es nutzbar ist ...

**Comment by GermanBluefox** [comment]
Fehler, Absturz

**Comment by Dragon0501** [comment]
1.8.5 works perfect! Danke für die Arbeit. Update versucht und bisher kein Problem gefunden. Vielen Dank für die Energie die du hier rein investierst.
