### ISSUE TITLE
in "intelligente Aufzählungen' its not possible to switch

### ISSUE THREAD

**Issue by intruder7777** [ioBroker/ioBroker.iot#195]
i updated from 1.4.2 to1.8.4 with somthing of the "intelligente Aufzählungen" switched to "ON".

After switch one of the functions to off its not possible to switch it back to on again.
![image](https://user-images.githubusercontent.com/45670139/99719703-f8180f80-2aac-11eb-923a-e0e7d461b6f8.png)
also it´s not possible to switch function to on which were off.the same to rooms

**Comment by nevermind2001** [comment]
same here

**Comment by intruder7777** [comment]
for me its working now with 1.8.5
