### ISSUE TITLE
UNMET dependencies for node version smaller than V15 for iot 1.8.5

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.iot#199]
Describe the bug
Broken dependencies with node 12.2.0, running node 15.3.0 works.

To Reproduce

node v12:

```
pi@raspberrypi:/opt/iobroker $ npm list moment
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.backitup@1.7.0
│ └─┬ node-schedule@1.3.2
│   └─┬ cron-parser@2.16.3
│     └─┬ moment-timezone@0.5.31
│       └── moment@2.27.0  deduped
├─┬ UNMET DEPENDENCY iobroker.iot@1.8.5
│ └── UNMET DEPENDENCY moment@2.29.1
└─┬ iobroker.js-controller@3.1.6
  └─┬ winston-daily-rotate-file@4.5.0
    └─┬ file-stream-rotator@0.5.7
      └── moment@2.27.0

npm ERR! missing: iobroker.iot@1.8.5, required by iobroker.inst@2.0.3
npm ERR! missing: moment@2.29.1, required by iobroker.iot@1.8.5
```
node v14:

```
pi@raspberrypi:/opt/iobroker $ npm list moment
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.backitup@1.7.0
│ └─┬ node-schedule@1.3.2
│   └─┬ cron-parser@2.16.3
│     └─┬ moment-timezone@0.5.31
│       └── moment@2.27.0  deduped
├─┬ UNMET DEPENDENCY iobroker.iot@1.8.5
│ └── UNMET DEPENDENCY moment@2.29.1
└─┬ iobroker.js-controller@3.1.6
  └─┬ winston-daily-rotate-file@4.5.0
    └─┬ file-stream-rotator@0.5.7
      └── moment@2.27.0

npm ERR! missing: iobroker.iot@1.8.5, required by iobroker.inst@2.0.3
npm ERR! missing: moment@2.29.1, required by iobroker.iot@1.8.5
```
node v15:

```
pi@raspberrypi:/opt/iobroker $ npm list moment
iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.backitup@1.7.0
│ └─┬ node-schedule@1.3.2
│   └─┬ cron-parser@2.16.3
│     └─┬ moment-timezone@0.5.31
│       └── moment@2.27.0 deduped
├─┬ iobroker.iot@1.8.5
│ └── moment@2.29.1
└─┬ iobroker.js-controller@3.1.6
  └─┬ winston-daily-rotate-file@4.5.0
    └─┬ file-stream-rotator@0.5.7
      └── moment@2.27.0
```

Expected behavior
Dependencies should met the stable and recommended node12.

Versions:

Adapter version: iot - v1.8.5
JS-Controller version: 3.1.6
Node version: See above
Operating system: Raspberry OS 'Buster'
Additional context
See forum threads:
https://forum.iobroker.net/topic/39024/info-0-fehler-instanz-steht-auf-rot
https://forum.iobroker.net/topic/39013/iobroker-l%C3%A4uft-nicht-mehr-richtig-nur-noch-logfehler

**Comment by Apollon77** [comment]
honestly ... what the adapter can do here? it seems that npm did strange stuff ... moment 2.29.1 is dep for iot 1.8.5 according to package.json ... so what should we change?

**Comment by Apollon77** [comment]
PS: more intersting is which npm version you use BTW

**Comment by Grothesk242** [comment]
Here are three different runtimes (node 15, node14 and node12), nothing else changed. 
To me it looks as if moment@2.29.1 is required by iobroker.iot@1.8.5 but is only provided by node v15: 

npm ERR! missing: moment@2.29.1, required by iobroker.iot@1.8.5

node-Packages are retrieved from the nodesource repository. 

```
pi@raspberrypi:/opt/iobroker $ node -v
v15.3.0
pi@raspberrypi:/opt/iobroker $ npm -v
7.0.14
pi@raspberrypi:/opt/iobroker $ npm list moment
iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.backitup@1.7.0
│ └─┬ node-schedule@1.3.2
│   └─┬ cron-parser@2.16.3
│     └─┬ moment-timezone@0.5.31
│       └── moment@2.27.0 deduped
├─┬ iobroker.iot@1.8.5
│ └── moment@2.29.1
└─┬ iobroker.js-controller@3.1.6
  └─┬ winston-daily-rotate-file@4.5.0
    └─┬ file-stream-rotator@0.5.7
      └── moment@2.27.0

pi@raspberrypi:/opt/iobroker $ node -v
v14.15.1
pi@raspberrypi:/opt/iobroker $ npm -v
6.14.8
pi@raspberrypi:/opt/iobroker $ npm list moment
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.backitup@1.7.0
│ └─┬ node-schedule@1.3.2
│   └─┬ cron-parser@2.16.3
│     └─┬ moment-timezone@0.5.31
│       └── moment@2.27.0  deduped
├─┬ UNMET DEPENDENCY iobroker.iot@1.8.5
│ └── UNMET DEPENDENCY moment@2.29.1
└─┬ iobroker.js-controller@3.1.6
  └─┬ winston-daily-rotate-file@4.5.0
    └─┬ file-stream-rotator@0.5.7
      └── moment@2.27.0

npm ERR! missing: iobroker.iot@1.8.5, required by iobroker.inst@2.0.3
npm ERR! missing: moment@2.29.1, required by iobroker.iot@1.8.5
pi@raspberrypi:/opt/iobroker $ node -v
v12.20.0
pi@raspberrypi:/opt/iobroker $ npm -v
6.14.8
pi@raspberrypi:/opt/iobroker $ npm list moment
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
iobroker.inst@2.0.3 /opt/iobroker
├─┬ iobroker.backitup@1.7.0
│ └─┬ node-schedule@1.3.2
│   └─┬ cron-parser@2.16.3
│     └─┬ moment-timezone@0.5.31
│       └── moment@2.27.0  deduped
├─┬ UNMET DEPENDENCY iobroker.iot@1.8.5
│ └── UNMET DEPENDENCY moment@2.29.1
└─┬ iobroker.js-controller@3.1.6
  └─┬ winston-daily-rotate-file@4.5.0
    └─┬ file-stream-rotator@0.5.7
      └── moment@2.27.0

npm ERR! missing: iobroker.iot@1.8.5, required by iobroker.inst@2.0.3
npm ERR! missing: moment@2.29.1, required by iobroker.iot@1.8.5
```

**Comment by Apollon77** [comment]
or npm 7 behaves somehow strange? I still do not get what the adapter can do. for me it more seems like an npm issue

**Comment by Grothesk242** [comment]
Excerpt from iobroker.iot/package.json shows a requirement for 
"moment": "^2.29.1",
but this version of "moment" is not provided by node-Versions 12 or 14. 

```
  "dependencies": {
    "echarts": "^4.9.0",
    "jsdom": "^16.4.0",
    "moment": "^2.29.1",
    "aws-iot-device-sdk": "^2.2.6",
    "iobroker.type-detector": "^1.0.7",
    "request": "^2.88.2",
    "@iobroker/adapter-core": "^2.4.0",
    "uuid": "^8.3.1"
```

**Comment by Apollon77** [comment]
Hinestly ... the most important question is: is iot adapter working?

**Comment by Grothesk242** [comment]
Check the forum threads linked in the first post.
My iot is running, fresh installs seem to have an issue with the unmet dependencies.

**Comment by Apollon77** [comment]
did you tried to install it again? (cd /opt/iobroker and then "npm i iobroker.iot")?

**Comment by Grothesk242** [comment]
No, I'm running node15at the moment.

**Comment by Apollon77** [comment]
BTW: nodejs 15 is a dev version of nodejs and so not officially supported by us ... can work,but if you experience problems or non working adapters then we can not support that

**Comment by Grothesk242** [comment]
I'm completely aware of this status regarding uneven versions of nodeJS.

**Comment by GermanBluefox** [comment]
> Excerpt from iobroker.iot/package.json shows a requirement for
> "moment": "^2.29.1",
> but this version of "moment" is not provided by node-Versions 12 or 14.
> 
> ```
>   "dependencies": {
>     "echarts": "^4.9.0",
>     "jsdom": "^16.4.0",
>     "moment": "^2.29.1",
>     "aws-iot-device-sdk": "^2.2.6",
>     "iobroker.type-detector": "^1.0.7",
>     "request": "^2.88.2",
>     "@iobroker/adapter-core": "^2.4.0",
>     "uuid": "^8.3.1"
> ```

According to moment they do not have any limitations: 
https://github.com/moment/moment/blob/develop/package.json#L36

![image](https://user-images.githubusercontent.com/4582016/102017373-ee5d9100-3d66-11eb-9a39-8f83889524ef.png)

So iot uses valid version of moment. I do not understand the problem.
