### ISSUE TITLE
Gelöschte Geräte bleiben bis Seiten-Reload in der Liste stehen

### ISSUE THREAD

**Issue by Snatch2001** [ioBroker/ioBroker.iot#2]
Nach dem Löschen eines Gerätes, bleibt die Zeite rot markiert stehen. Es ist ein neuladen der Seite erforderlich.

**Comment by Apollon77** [comment]
Duplicate of #3?

**Comment by Snatch2001** [comment]
Yes, similar problem, but a different approach.

**Comment by Snatch2001** [comment]
The bug seems resolved with version 0.1.5
