### ISSUE TITLE
Änderung in iot.0 wird in iot.1 übernommen

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.iot#200]
hab gerade 2 neue Funktionen angelegt.
Waren sofort in beider IOT-Instanzen aktiv.
Dann in iot.1 eine Funktion der 2 wieder ausgeschaltet. In iot.0 nachgeschaut. Jetzt ist die ausgeschaltene in iot.0 ebenfalls ausgeschaltet.
Es verhält sich wie bei Alexa-Geräte.
Eine Änderung in iot.0 wird in iot.1 übernommen. Somit ist es  nicht möglich, iot.1 nur bestimmte Räume/Funktionen/Geräte zu übergeben.

**Versions:**  
 - IOT 1.8.5

 - JS-Controller version: 3.1.6
 - Node version: Node.js 12.18.3, NPM 6.14.6
 - Operating system: Synology Docker

![log](https://user-images.githubusercontent.com/45309436/100379255-de2e7d80-3014-11eb-9b5d-47d1e47973f3.gif)

**Comment by Apollon77** [comment]
Korrekt. Um das anders zu haben musst du einen Pro Account haben und kannst in den iot Settings wählen "eigene einstellungen". Dann ist quasi alles weg was vorher "global" da war und du kannst es getrennt eintrichten.
