### ISSUE TITLE
(9151) [GHOME] Cannot updateState: Request contains an invalid argument.

### ISSUE THREAD

**Issue by gmoerth** [ioBroker/ioBroker.iot#201]
**Describe the bug**  
(9151) [GHOME] Cannot updateState: Request contains an invalid argument.
Kommt so alle paar Minuten ... nicht regelmäßig

**To Reproduce**  
nur automatisch hinzugefügte Geräte

**Expected behavior**  
Erst seit der Version 1.8.5

**Screenshots & Logfiles**  
keine

**Versions:**  
 - Adapter version: <adapter-version> 1.8.5
 - JS-Controller version: <js-controller-version> 3.1.6 
 - Node version: <node-version> v12.20.0 
 - Operating system: <os-name> raspberrypi4 4gb ram Raspbian lite Buster

**Additional context**

**Comment by GermanBluefox** [comment]
> **Screenshots & Logfiles**
> keine

Schade. Kannst du auf "debug" umstellen und logs hier posten?

**Comment by gmoerth** [comment]
![image](https://user-images.githubusercontent.com/34843746/102024045-c6365800-3d8f-11eb-965b-1d8b25ee8022.png)

**Comment by gmoerth** [comment]
![image](https://user-images.githubusercontent.com/34843746/102028111-c131d280-3da8-11eb-88af-5af3ca9bdbc3.png)

**Comment by gmoerth** [comment]
![image](https://user-images.githubusercontent.com/34843746/102703727-ede75d80-4272-11eb-9d86-275eedefb1c5.png)

**Comment by christofkac** [comment]
Ich kann etwas beitragen.
Mit dem aktuellen Adapter 1.8.5 bekomme ich den Fehler immer, wenn ich versuche, die Farbtemperatur zu ändern.
Ich habe dazu einen State erstellt (Typ Number) und den im iot Adapter als "Light" + "ColorSetting_Temperature" konfiguriert.
Der Wert der Farbtemperatur wird auch in meinen State geschrieben, ich bekomme aber bei jedem Schreiben den Fehler.
Der Javascript Wert wird durch einen Event bei einer Stateänderung der Farbtemperatur ausgegeben, also funktioniert das Schreiben.

`iot.0	2020-12-24 13:42:17.181	error	(20116) [GHOME] Cannot updateState: Request contains an invalid argument.`
`javascript.0	2020-12-24 13:42:16.864	info	(18541) script.js.common.Zigbee: Farbtemperatur: 2700`

Wenn ich die Instanz auf "Debug" umstelle, bekomme ich die Fehlermeldung nicht, auch wird der State nicht gesetzt. Sieht aus. Ich bekomme aber mehr Details:
`iot.0	2020-12-24 13:41:28.431	debug	(20072) system.adapter.admin.0: logging false`
`iot.0	2020-12-24 13:41:25.790	debug	(20072) [GHOME] Response on action.devices.EXECUTE: {"requestId":"8997498703325853564","payload":{"commands":[]}}`
`iot.0	2020-12-24 13:41:25.789	debug	(20072) [GHOME] execute action.devices.commands.ColorAbsolute => {"color":{"name":"warm white","temperature":3000}}`
`iot.0	2020-12-24 13:41:25.789	debug	(20072) [GHOME] Received action.devices.EXECUTE`
`iot.0	2020-12-24 13:41:25.789	debug	(20072) Data: "{\"inputs\":[{\"context\":{\"locale_country\":\"US\",\"locale_language\":\"en\"},\"intent\":\"action.devices.EXECUTE\",\"payload\":{\"commands\":[{\"devices\":[{\"customData\":{\"get_c`
`iot.0	2020-12-24 13:41:25.788	debug	(20072) Request command/christof_k_gmx_de/ghome`
`iot.0	2020-12-24 13:41:23.761	debug	(20072) [GHOME] Response on action.devices.EXECUTE: {"requestId":"9955372870125535235","payload":{"commands":[]}}`
`iot.0	2020-12-24 13:41:23.760	debug	(20072) [GHOME] execute action.devices.commands.ColorAbsolute => {"color":{"name":"incandescent","temperature":2700}}`
`iot.0	2020-12-24 13:41:23.760	debug	(20072) [GHOME] Received action.devices.EXECUTE`
`iot.0	2020-12-24 13:41:23.759	debug	(20072) Data: "{\"inputs\":[{\"context\":{\"locale_country\":\"US\",\"locale_language\":\"en\"},\"intent\":\"action.devices.EXECUTE\",\"payload\":{\"commands\":[{\"devices\":[{\"customData\":{\"get_c`
`iot.0	2020-12-24 13:41:23.759	debug	(20072) Request command/christof_k_gmx_de/ghome`
`iot.0	2020-12-24 13:41:22.442	debug	(20072) [GHOME] Response on action.devices.EXECUTE: {"requestId":"12828265075588736702","payload":{"commands":[]}}`
`iot.0	2020-12-24 13:41:22.442	debug	(20072) [GHOME] execute action.devices.commands.ColorAbsolute => {"color":{"name":"daylight","temperature":5000}}`
`iot.0	2020-12-24 13:41:22.441	debug	(20072) [GHOME] Received action.devices.EXECUTE`

Kann es sein, dass der Adapter den Farbnamen + Farbtemperatur schreiben will, ich aber nur einen State habe? 
Was kann ich tun?
Außerdem vermisse ich beim Adapterupdate die Möglichkeit, die Werte von Google Home umzurechnen (gab es noch bei 1.5.3) da meine Zigbee Leuchte die Farbtemperatur in Werten bis ca. 300 einstellt. Übersehe ich etwas?

Sagt Bescheid, wenn mehr Infos benötigt werden.

Christof

**Comment by christofkac** [comment]
Ach ja, so ist der State definiert:
![image](https://user-images.githubusercontent.com/33951830/103090004-1e6f2480-45f0-11eb-8794-0437ab75c4a5.png)

**Comment by gmoerth** [comment]
A**dapter Version 1.8.9**

![image](https://user-images.githubusercontent.com/34843746/103308470-cfbbf300-4a12-11eb-9dec-86865111d4e5.png)

**Comment by Apollon77** [comment]
Scheinbar fehlt hier eine "color_saturation" ANgabe ... hilft das vllt?

**Comment by flotux2** [comment]
@Apollon77:
Ich stehe vor dem gleichen Problem und komme da nicht weiter. Hast du eine funktionierende Konfiguration, mit der du über den IoT Adapter bei einer Lampe die Farbtemperatur über Google Home ändern kannst? Ich bekomme das einfach nicht ans Laufen. Ich habe schon mit den custom States color_temperature color_saturation experimentiert. Es funktioniert leider alles nicht. :-(

![grafik](https://user-images.githubusercontent.com/23209679/108496935-11e31180-72ab-11eb-87cd-1a6349eba684.png)

![grafik](https://user-images.githubusercontent.com/23209679/108496981-21625a80-72ab-11eb-83ff-35df7bbcea81.png)

**Comment by Apollon77** [comment]
@tombox any idea?
