### ISSUE TITLE
Räume und Funktionen lassen sich nicht deaktivieren

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.iot#202]
Räume und Funktionen lassen sich nicht deaktivieren

**Versions:**  
- IOT 1.8.5
- JS-Controller version: 3.1.6
- Node version: Node.js 12.18.3, NPM 6.14.6
- Operating system: Synology Docker

**Additional context**  
![log](https://user-images.githubusercontent.com/45309436/100541092-d99adc80-3241-11eb-983b-a4552ec2c3c3.gif)
![Screenshot_2020-11-29 instances - ioBroker](https://user-images.githubusercontent.com/45309436/100541096-de5f9080-3241-11eb-853a-73e94d5d7ee0.png)

**Comment by sigi2345** [comment]
Bei mir das selbe verhalten.

`Platform: Windows
RAM: 16 GB 
Node.js: v12.19.0
NPM: 6.14.8
JS Controler: 3.1.6
Admin: 4.1.11
Web: 3.1.0
Socket.io: 3.0.13
Script Engine: 4.10.7
IOT: 1.8.5`

Sigi

**Comment by SkeeveKlah** [comment]
Hier auch: PI 4
Platform linux
Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 1500 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 3.74 GB
Node.js v12.20.0
NPM 6.14.8
IoT 1.8.5

**Comment by Negalein** [comment]
muss noch ergänzen, dass ich 2 Instanzen laufen habe.
Bei iot.0 funktionierts, bei iot.1 nicht.

Bei iot.1 ist "eigene Einstellungen" aktiviert, bei iot.0 nicht

**Comment by DreamScout** [comment]
Same Problem here

**Comment by marcbroe** [comment]
Ebenfalls das gleiche Problem... Ich hoffe das dies bald gefixt wird. :-) Danke schon einmal.

**Comment by Coalado** [comment]
Workaround (if somebody cannot wait for a fix) object.common.smartName :false|true stores the setting for each enum
Examples:
List rooms and their "State"

```
getEnums('rooms').forEach(obj => {
var details = getObject(obj.id);
log(obj.id + "\t" + !(details.common.smartName === false));
})
```

Disable all rooms:

```
getEnums('rooms').forEach(obj => {
extendObject(obj.id, { common: { smartName: false } })
})
```

Enable for bath-room.

```
extendObject("enum.rooms.batch", { common: { smartName: true} })
```

**Comment by Negalein** [comment]
> Workaround

ist das ein Script?

**Comment by quorle** [comment]
Selbes Problem hier

**Comment by Wwarrior69** [comment]
Hi zusammen,
gleiche Problem hier. Tritt nur auf, wenn mindestens eine (aber auch wenn alle!) der iot-Instanzen, das Flag "Eigene Einstellungen" gesetzt hat.
Gibt es dazu bereits eine Lösung?

**Comment by Wwarrior69** [comment]
Gerade manuell auf 1.8.9 aktualisiert und leider immer noch dasselbe Verhalten. Wenn auf einem iot-Adapter das Flag "Eigene Einstellungen" gesetzt ist, dann lassen sich keine Räume/Geräte deaktivieren.

**Comment by Wwarrior69** [comment]
Gibt es News dazu?

**Comment by ThorstenDtk** [comment]
> 
> 
> Workaround (if somebody cannot wait for a fix) object.common.smartName :false|true stores the setting for each enum
> Examples:
> List rooms and their "State"
> 
> ```
> getEnums('rooms').forEach(obj => {
> var details = getObject(obj.id);
> log(obj.id + "\t" + !(details.common.smartName === false));
> })
> ```
> 
> Disable all rooms:
> 
> ```
> getEnums('rooms').forEach(obj => {
> extendObject(obj.id, { common: { smartName: false } })
> })
> ```
> 
> Enable for bath-room.
> 
> ```
> extendObject("enum.rooms.batch", { common: { smartName: true} })
> ```

Funktioniert bei mir nicht. Für keine der Enum existiert bei mir details.common.smartName. Wenn ich unter Common bei Smartname die Checkbox setze, auf save klicke, die checkbox entferne und noch einmal auf save klicke ist details.common.smartName zwar auf false gesetzt, aber im iot-Adapter läßt sich der Raum trotzdem nicht deaktivieren. Trotz Neustart vom Adapter. Oder mache ich etwas falsch?

![grafik](https://user-images.githubusercontent.com/35042154/111039884-bd0d6380-8430-11eb-85a9-c5dfe7ed0db1.png)
![grafik](https://user-images.githubusercontent.com/35042154/111039898-dadac880-8430-11eb-9126-c63cf00c3268.png)

**Comment by Wwarrior69** [comment]
@GermanBluefox : wäre echt ne feine Sache, wenn sich ein Entwickler mal des Themas annehmen könnte. Ich habe extra zwei iot-Adapter mit zwei Accounts laufen, damit z.b. meine Tochter mit ihrer Alexa nicht die Rolläden im Schlafzimmer hochmacht und umgekehrt. Dies lässt sich aber genau auf Grund des Bugs nicht einstellen. Beide Accounts können alles bedienen!

Bin auch für jegliche Alternativen in Form von Workarounds offen und Vorschläge sind diesbezüglich higly welcome! ;-)

Vielen Dank im Vorfeld.

**Comment by Negalein** [comment]
mit 1.8.22 funktionierts auch noch nicht!
vielleicht kann sich @Apollon77 kurz melden! Wäre echt sehr wünschenswert, wenn dieser Bug bald behoben wird!

**Comment by Apollon77** [comment]
Ja bin hier? Das mus sich aber ein UI/Frontend Dev ansehen. da bin ich leider raus

**Comment by Negalein** [comment]
gibt es mittlerweile was neues?

**Comment by GermanBluefox** [comment]
Das Problem ist, dass ich es nicht reproduzieren kann.

**Comment by Negalein** [comment]
> Das Problem ist, dass ich es nicht reproduzieren kann.

Ich hab heute eine Testumgebung aufgesetzt um es zu reproduzieren.
Selber Verhalten wie bei der Hauptinstallation.

Wie können wir dir mit Infos helfen?

**Comment by Apollon77** [comment]
Wenn testumgebung ggf relevante Objekte exportieren?

**Comment by Negalein** [comment]
> Wenn testumgebung ggf relevante Objekte exportieren?

Testumgebung war unglücklich formuliert.
Ist eine 2. identische Installation.

Soll ich dir alle IOT-Objekte exportieren?
Oder können gerne mal mit Anydesk schaun.

**Comment by quorle** [comment]
V 1.8.24 selbiges Problem

**Comment by DerT94** [comment]
Ich habe das Problem auch und konnte es mit der Einstellung "Eigene Einstellungen (nur pro)" in Verbindung brinden.
 
![image](https://user-images.githubusercontent.com/58786605/150574166-ff69aa80-a581-41e8-85b4-1e8bcd6e1efc.png)

Sobald der Haken gesetzt ist kann ich zwar noch Räume und Funktionen aktivieren aber nicht wieder deaktivieren.

**Comment by GermanBluefox** [comment]
Muss mittlerweile gefixt werden. Lag an 
![image](https://user-images.githubusercontent.com/4582016/153055741-fea3bb47-1761-4e4e-ac87-4df5f704d004.png)
