### ISSUE TITLE
[GHOME] Device is not visible at a resolution of 2560 x 1600, Retina

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.iot#207]
**Describe the bug**  
The information part occupies the entire part of the screen.

**Expected behavior**  
Make the part with the description "collapsible".

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/100748093-f545e480-33f3-11eb-9b80-56a532c0710a.png)

**Versions:**  
 - Adapter version: 1.8.5
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: docker 5.0.0

**Comment by GermanBluefox** [comment]
Please click here:
![image](https://user-images.githubusercontent.com/4582016/102017271-35975200-3d66-11eb-8cbe-3175619a2b61.png)
