### ISSUE TITLE
Iot Clout Adapter öffnet Konfigurations Tab nicht mehr...

### ISSUE THREAD

**Issue by mrs14** [ioBroker/ioBroker.iot#209]
Hallo zusammen. 
Mein Iot Clout Adapter öffnet den Konfigurations tab nicht mehr.
Der Adapter läuft, also alles grün und verbunden.
Gibt es da eine Lösung?
![image](https://user-images.githubusercontent.com/75576590/101285755-31f45000-37e7-11eb-8ac0-f269b955b9a7.png)
Danke im Voraus...

**Comment by Apollon77** [comment]
Bitte Browser Konsole screenshot zeigen, da sollte ein Fehler sein

**Comment by mrs14** [comment]
SORRY, screen vom log?

**Comment by Apollon77** [comment]
im Browser unter "Tools" gibt meist ein "Entwicklertools" oder "Konsole" ...

**Comment by mrs14** [comment]
![image](https://user-images.githubusercontent.com/75576590/101286047-b72c3480-37e8-11eb-844a-3fd108376e0e.png)

**Comment by mrs14** [comment]
bin ich da richtig?

**Comment by mrs14** [comment]
Jetzt aber...
![image](https://user-images.githubusercontent.com/75576590/101286192-6ec14680-37e9-11eb-8349-135fc6bba687.png)

**Comment by mrs14** [comment]
Kann mit dem Fehler leider nichts anfangen. So fit bin ich nicht.
Hat jemand eine Idee? 
Danke schon einmal...

**Comment by Apollon77** [comment]
Du sollst auch damit nichts anzufangen wissen, ein Dev schon :-) Irgendein Objekt in deinem System ist "komisch"

**Comment by mrs14** [comment]
Danke, und wie finde ich das?

**Comment by Apollon77** [comment]
Das ist die gute Frage ...

**Comment by mrs14** [comment]
Hat jemand vielleicht noch eine Ideen?

**Comment by mrs14** [comment]
Das ist meine Fehlermeldung im Browser...
![image](https://user-images.githubusercontent.com/75576590/101366701-8d851300-38a5-11eb-8d32-f5a681021b9a.png)

**Comment by mrs14** [comment]
Was ist dieses für ein Fehler?

Uncaught TypeError: t.indexOf is not a function

kan ndas der Grund sein?

**Comment by mrs14** [comment]
Wie sollte ich bei der Fehlersuche vorgehen?

**Comment by DreamScout** [comment]
Ich glaub ich hatte das gleich Problem. Ich hab den Adapter dann gestartet und bin nochmal auf die Konfig Seite. Dann ging es.

**Comment by mrs14** [comment]
Danke für die Info. Richtig, wenn man mehrmals zwischen den Adapter hin und her swiched funktioniert es eventuell  mal wieder. Aber nur 1x. Das kann ja nicht die Lösung sein.
Gruß Michael.

**Comment by GermanBluefox** [comment]
Was für eine ioBroker.iot Version?

**Comment by DreamScout** [comment]
> 
> 
> Was für eine ioBroker.iot Version?

1.4

**Comment by GermanBluefox** [comment]
Hm... 1.8.5 hat so eine Datei nicht:
![image](https://user-images.githubusercontent.com/4582016/102020470-bf044f80-3d79-11eb-82d7-8ea8f51cad3e.png)

**Comment by mrs14** [comment]
>
![Screenshot_2020-12-13-20-50-12-469_com android chrome](https://user-images.githubusercontent.com/75576590/102022148-3390bb80-3d85-11eb-9d06-4e0cffcece67.jpg)

**Comment by mrs14** [comment]
Iobroker Version 4.1.10

**Comment by GermanBluefox** [comment]
> Iobroker Version 4.1.10

Ich denke, dass es um admin geht. 

Ich bitte dich auf die neueste Version den Adapter upzudaten (aktuell 1.8.8)
danach upload starten und dann hier berichten ob in der Browser-Konsole was zu finden ist.
![image](https://user-images.githubusercontent.com/4582016/102354408-cd857d80-3faa-11eb-853b-63c3d00202f8.png)
