### ISSUE TITLE
Keine Sprachsteuerung mehr möglich

### ISSUE THREAD

**Issue by m0rph2k** [ioBroker/ioBroker.iot#210]
Hi

Seit gestern Abend lassen sich bei mir mit dem Pro Account keine Geräte mehr steuern, alexa sagt "Etwas ist schief gegangen um Gerät XY zu Steuern Skill deaktiviere und wieder Aktievieren etc", die zweite Alexa anderes Konto lässt sich normal Steuern

Irgendwer das gleiche Problem ??

LG

**Comment by Apollon77** [comment]
Bitte nochmal detaillieren? Ein Amazon Account mit mehreren Alexa.-Geräten. Eins kann steuern und ein anderes nicht? Und was genau sagt sie? Mal neu gestartet das Alexa Gerät?

**Comment by m0rph2k** [comment]
> 
> 
> Bitte nochmal detaillieren? Ein Amazon Account mit mehreren Alexa.-Geräten. Eins kann steuern und ein anderes nicht? Und was genau sagt sie? Mal neu gestartet das Alexa Gerät?

2 Amazon Accounts mit jeweils einer Alexa  --> Iobroker Free Account funktioniert, Iobroker Pro funktioniert nicht.
Der Apdapter ist Grün über das Handy bekomme ich die Meldung das der Server nicht Reagiert.

Die Nachricht von Alexa ist "Tut mir leid etwas ist schiefgelaufen um XY zu Steuern versuche den Skill zu deaktiviere und dann erneut in der Alexa App zu aktivieren

Ich bilde mir ein ich hatte das schon mal und habe einfach dann Skill deaktiviert und wieder aktiviert, bevor ich das mache wollte ich aber nachfragen ob es allgemein ein Problem gibt.

LG

**Comment by Apollon77** [comment]
Es sind keine Probleme bekannt. Kann es sei das du den iot Adapter aktualisiert hast? Damit hat sich das zu nutzende Passwort für den Skill geändert. Daher verbinde mal neu und direkt das .pro Passwort nutzen!

**Comment by m0rph2k** [comment]
> 
> 
> Es sind keine Probleme bekannt. Kann es sei das du den iot Adapter aktualisiert hast? Damit hat sich das zu nutzende Passwort für den Skill geändert. Daher verbinde mal neu und direkt das .pro Passwort nutzen!

Hab den Skill jetzt mal Deaktiviert und wollte ihn wieder aktivieren, der Login der dann kommt da funktioniren die Login daten von https://iobroker.pro nicht, direkt auf der Seite funtkioniert der Login, normalerweise habe ich immer den Pro Login verwändet

**Comment by m0rph2k** [comment]
> 
> 
> Es sind keine Probleme bekannt. Kann es sei das du den iot Adapter aktualisiert hast? Damit hat sich das zu nutzende Passwort für den Skill geändert. Daher verbinde mal neu und direkt das .pro Passwort nutzen!

Ich habe jetzt den Skill neu verbunden bzw das Passwort zurückgesetzt, ich dachte eig. immer das der User und das Passwort beim verknüpfen des Skills das gleiche ist wie bei https://iobroker.pro, sollte das der fall sein das funktioniert es nicht.

Auf jedenfall funktioniert es jetzt wieder ich musste den Skill Deaktivieren/Aktivieren bzw vorher Kennwort Reseten.

LG
