### ISSUE TITLE
Thermostate werden nicht richtig erkannt

### ISSUE THREAD

**Issue by MeisterHoppel** [ioBroker/ioBroker.iot#212]
Node.js
    v12.20.0
NPM
    6.14.8

iot Adapter 1.8.5

Hallo Team,
bin von der HA Bridge jetzt auf iot umgestiegen. Lampen und Dimmer gehen wunderbar. Leider habe ich Probleme mit den Thermostaten von Homematic. Alexa findet zwar diese, aber ein Klick auf zum Badezimmer bekomme ich in der App gleich die Einstellungsseite (Nam bearbeiten, Verbunden über usw.) angezeigt, anstatt die Seite zum Einstellen der Temp. Datenpunkt ist Set.Temperatur / level.temperatur. Sollte eigentlich richtig sein. Auf zuruf wird diese auf korrekt verändert. Ich weiß jetzt nicht ob es an der App liegt oder am Adapter. Hat sonst noch jemand das Problem?

**Comment by Apollon77** [comment]
Screenshot bitte ... und hast du auch den korrekten Datenpunkt gewählt? Müssten ja zwei sein SET und ACTUAL

**Comment by MeisterHoppel** [comment]
Danke für die schnelle Antwort
![grafik](https://user-images.githubusercontent.com/14821979/101685268-d71d5b80-3a67-11eb-826a-12db3aba8666.png)
Sollte also passen. Hatte den Thermostat auch mal gelöscht und neu eingelesen. Selbe Ergebniss.
![grafik](https://user-images.githubusercontent.com/14821979/101685738-69256400-3a68-11eb-9625-7066d5fa7942.png)
![grafik](https://user-images.githubusercontent.com/14821979/101685796-7a6e7080-3a68-11eb-804f-9c90ea213a57.png)

**Comment by derherrgraf** [comment]
Ich supporte das mal, weil ich hab dieses Problem schon seit ein paar Monaten. Wie bereits erwähnt, funktionier das setzten super. Allerdings ist keine Abfragen möglich.
Ich nutzte die BLE eq3 Thermostate aber das macht ja für die Datenpunkte erstmal kein großen Unterschied senke ich. Anbei mal meine Screenshots.

![IMG_9746](https://user-images.githubusercontent.com/16402094/103218097-6c4e9a00-491a-11eb-99ff-4aed939e764a.PNG)
![Bildschirmfoto 2020-12-28 um 14 34 35](https://user-images.githubusercontent.com/16402094/103218107-71abe480-491a-11eb-849d-375b8f2564dd.png)
![Bildschirmfoto 2020-12-28 um 14 35 44](https://user-images.githubusercontent.com/16402094/103218123-7bcde300-491a-11eb-8471-a2ea6d06484b.png)

**Comment by Apollon77** [comment]
Die Rollen der States sind ESSENTIELL!! Bitte mal zeigen welche roles die states haben

**Comment by derherrgraf** [comment]
Wie im 2. Screenshot zu sehen ist, ist hat der eine die Rolle `level.temperature` und der andere `value.temperature`

**Comment by Messiahs** [comment]
wobei "PARTY_SET_POINT_TEMPERATURE" auch "level.temperature" als Rolle hat... keine Ahnung, ob dies Auswirkung hat.
P.S.: Habe hier das gleiche Problem.

**Comment by Apollon77** [comment]
@Morluktom any idea?

**Comment by Morluktom** [comment]
I think the App shows the Thermostate only at Payload V3 correct.
At Payload V2 is only Alexa working correct. 
Over Alexa i can ask for the set temperature, set the temperature and ask for the actual temperature. Everything is working correct.

**Comment by Morluktom** [comment]
My settings:
![image](https://user-images.githubusercontent.com/34573701/103405526-c0928d80-4b57-11eb-85c6-432c0c9eb296.png)

Actual temperature: (Important: only a read variable)
![image](https://user-images.githubusercontent.com/34573701/103405754-778f0900-4b58-11eb-8ff1-e55fc2c1f35a.png)

Set temperature:
![image](https://user-images.githubusercontent.com/34573701/103405870-04d25d80-4b59-11eb-8e65-f30ea7cc8db1.png)

**Comment by Morluktom** [comment]
@Apollon77  is somebody working on Payload V3? The complete App is only working on Payload V3 correct. I think it's time to switch to V3.

**Comment by Apollon77** [comment]
Ok then It is as feared :-(

In fact nobody is "actively working right now" on it ... it is a huge task and we need to find time and/or contributors for it ...

**Comment by Messiahs** [comment]
Der Smarttype "TEMPERATURE_SENSOR" sollte auch mit V2 funktionieren. Einfach mal "TEMPERATURE_SENSOR" im raw statt 'THERMOSTAT' angeben.
Der Screen in der AlexaApp sieht auch alle Fälle schon mal besser aus.

**Comment by MeisterHoppel** [comment]
Ich bekomme leider das gleiche Ergebniss:
![grafik](https://user-images.githubusercontent.com/14821979/103474824-ef9f3e00-4da7-11eb-960c-1797a8dd36d8.png)

**Comment by Messiahs** [comment]
Gerät gelöscht und neu angelernt ?

**Comment by Morluktom** [comment]
Temperatur Sensoren sind unter V2 unterstützt, sind aber in ioBroker nicht integriert.
Ein Temperatur Sensor ist kein Thermostat.
Ein typischer Temperatursensor ist z.B der Außen Fühler der Heizung, der kann nur angesehen/bzw. abgefragt werden und nichts verstellt.
Ein Thermostat kann die aktuelle Raumtemperatur zurückgeben und den Sollwert der Raumtemperatur anzeigen + verstellen.
Ich habe noch kein Thermostat richtig mit Payload V2 richtig gesehen.
Alle anderen Systeme wo ich mir angesehen haben arbeiten mit V3 (OpenHab, Fhem)

Die Ansicht eines Temperatursensors in der App ist folgende:
![image](https://user-images.githubusercontent.com/34573701/103476085-f5e6e780-4db2-11eb-9ed7-c161ecd418e6.png)


Die Ansicht eines Thermostat ist folgende(kann noch um den Modus kühlen erweitert werden):
![image](https://user-images.githubusercontent.com/34573701/103476004-62adb200-4db2-11eb-977a-b7878bbb8190.png)

**Comment by MeisterHoppel** [comment]
Danke Morluktom
ja habe ich gelöscht und neu angelernt. Komme aber zu dem gleichen Screen wie oben beschrieben, also direkt in die Einstellungen. Alexa kann allerdings in beiden Fällen die Temperatur per Zuruf Einstellen und abfragen.

**Comment by Messiahs** [comment]
> ja habe ich gelöscht und neu angelernt. 
IOT-Adapter musst Du m.M. auch restarten, sonst bekommt er die Änderung nicht mit.

**Comment by MeisterHoppel** [comment]
Ja hatte ich. :-( 
Was mich allerdings wundert, dass nur wenige das Problem zu haben scheinen.

Grüße
Jens

**Comment by Morluktom** [comment]
Ich denke das Problem hat jeder. Ich denke nur das das Augenmerk bei den meisten bei der Steuerung über Alexa liegt, und nicht bei der App. Wenn Anzeige und Steuerung per App gewollt ist werden hier die meisten auf die Visualisierung von ioBroker nutzen.

**Comment by Messiahs** [comment]
Zumindest wäre die Unterstützung für "Temperatur Sensoren" wünschenswert...

**Comment by Phil-Rei** [comment]
Ich schließe mich hier mal an, da ich das selbe Problem habe.
Homematik IP Thermostate in ioBroker über iot Adapter.
Temperatur setzen und abfragen via Alexa geht. 
In der Alexa App wird die Heizung jedoch lediglich als Gruppe dargestellt. Dort ist weder eine Anzeige der Raumtemperatur noch ein setzen der Temperatur möglich.

Hatte zuvor die Thermostate über Cloudmatic in Alexa eingebunden. Dort hat es funktioniert.

Vielleicht wird das ja in Zukunft mal angegangen. Wäre schön. Vielen Dank

**Comment by vaaarg** [comment]
müsste auch gerne ob es jetzt eine Lösung gibt ich habe z.b ein Objekt Klimaanlage angelegt und ein objekttemperatur das alles über den IOT Adapter dann als einzelnes Gerät Klimaanlage an Alexa eingebunden. wenn ich nun auf das Gerät Klimaanlage tippe in der App zeigt es mir im Endeffekt nur den an- und Ausschalter an der datenpunkt Temperatur hat value temperature. was muss ich denn jetzt genau noch verändern damit die Alexa App theoretisch einen Einstellen der Temperatur über die App ermöglicht ?

**Comment by accessburn** [comment]
Lange her, aber das Half mir bei dem selben Problem.
Andere Tatsache ist, ich befehle: "Alexa, Heizung Wohnzimmer 20 Grad". Sie Antwortet: "Automatischer Modus ist auf 20 Grad gestellt".

Die Funktion ist da, aber was quatscht die alte da? :-D

![image](https://github.com/user-attachments/assets/836f0030-af99-45f4-8657-188918e967de)

![image](https://github.com/user-attachments/assets/556297dc-d4e2-4258-8e1c-0252c52836ef)
