### ISSUE TITLE
Dialog "Objekt ID auswählen" unlesbar

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.iot#213]
Vielleicht stelle ich mich ja irgendwie doof an, aber wie ist das mit dem Auswahlfenster mit weißer Schrift auf weißem Grund gedacht?

![Image1](https://user-images.githubusercontent.com/35402108/101672422-235fa000-3a56-11eb-99ec-7ce35ac1e3bf.jpg)

Grüße
-jayvee

**Comment by Apollon77** [comment]
Welche Adapter version? STable? NImm mal katest ... bzw update kommt jetzt

**Comment by JayVee2** [comment]
Habe gerade die neue 1.8.5 installiert. Das Problem ist dasselbe und besteht immer noch.

Kann man die Schriftfarbe denn irgendwo setzen?
