### ISSUE TITLE
Nach Update auf v1.8.5 ist keine Verbindung zwischen Google Home App und ioBroker mehr möglich; Geräte nicht mehr steuerbar

### ISSUE THREAD

**Issue by MojitoJoe1813** [ioBroker/ioBroker.iot#215]
Mit Update auf iot-Adapter v1.8.5 sind meine Geräte (z.B. Rolladen) nicht mehr über Google steuerbar. Die Rückmeldung von Google lautet sinngemäß "Es tut mir leid, IOBroker ist momentan nicht erreichbar". Geräte synchronisieren oder eine Neu-Verbindung zum ioBroker-Service in der Home-App scheitert ganz ohne Rückmeldung und ohne dass der Dienst hinzugefügt wird und alle ioBroker-Geräte sind seit diesem Neu-Verbindungsversuch auch aus der Home-App verschwunden.

Dieses Problem scheint es bei mehreren Personen zu geben, siehe https://forum.iobroker.net/topic/38999/google-home-iobroker-nach-update-probleme/2

Ein Downgrade auf v1.7.15 schafft Abhilfe: Sofort ist eine Verbindung wieder möglich und alle Geräte erscheinen in der App und sind wieder steuerbar.

Node.js: v12.19.1
NPM: 6.14.8
js-controller: 3.1.6

**Comment by meistermopper** [comment]
Gleiches Verhalten bei mir. Nach einem Update auf 1.8.5 läuft zunächst alles gut. Sobald Veränderungen bei den Geräten vorgenommen werden, sind diese in google assistant inaktiv. Nach Adapter-Neustart und einer neuen Synchronisierung verliert GH die Verbindung zum iobroker-Dienst.

Anbei die entsprechende log-Datei:
[iot_log.txt](https://github.com/ioBroker/ioBroker.iot/files/5689994/iot_log.txt)

**Comment by GermanBluefox** [comment]
Fixed in 1.8.8
