### ISSUE TITLE
Device/Group name "Tannenbaum"

### ISSUE THREAD

**Issue by sgc-fireball** [ioBroker/ioBroker.iot#216]
**Describe the bug**  
I can't create a device named "Tannenbaum".
The device received automatically the device Namen "Weihnachtsbaum".

**To Reproduce**  
1. Go to ioBroker iot
2. Alexa Devices
3. add it Update a device to name "Tannenbaum".
4. Reload list

**Expected behavior**  
A device with name Tannenbaum, not Weihnachtsbaum.

**Comment by Apollon77** [comment]
Whhhaaatt??? There is nothing that changes on the tech side any names you enter. Are you really sure?
