### ISSUE TITLE
1.8.7 unhandled promise rejection

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.iot#217]
`iot.0	2020-12-14 19:12:41.180	info	(575003) Terminated (NO_ERROR): Without reason`
`iot.0	2020-12-14 19:12:41.177	info	(575003) terminating`
`iot.0	2020-12-14 19:12:40.330	error	(575003) unhandled promise rejection: undefined`
`iot.0	2020-12-14 19:12:40.328	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
`iot.0	2020-12-14 19:12:39.287	info	(575003) Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com`
`iot.0	2020-12-14 19:12:39.206	info	(575003) starting. Version 1.8.7 in /opt/iobroker/node_modules/iobroker.iot, node: v12.20.0, js-controller: 3.1.6`

JS-Controller: 3.1.6
NodeJS: 12.20.0
npm: 6.14.9

**Comment by GermanBluefox** [comment]
1.8.7 is not on npm, but thank you :)
