### ISSUE TITLE
Nach Update 1.8.8

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.iot#218]
Nach Update auf 1.8.8 hängt sich der Adapter/die Configseite auf wenn man versucht ein Gerät manuell bei Google Home hinzuzufügen. Bei 1.8.5 ohne Probleme möglich.

**Comment by Dragon0501** [comment]
Beschränkt sich auf den mobilen Zugriff habe ich festgestellt. Im Lan funktioniert es...

**Comment by GermanBluefox** [comment]
> mobilen Zugriff

Heisst es über iobroker.pro/net cloud?

**Comment by Dragon0501** [comment]
.pro cloud
