### ISSUE TITLE
Lautstärke von Sonos ändern

### ISSUE THREAD

**Issue by Kusi-Schweiz** [ioBroker/ioBroker.iot#224]
Ich habe einem Sonos Lautsprecher (Ikea Symfonisk) in den Objekten den Raum "Badezimmer" und die Funktion "Sonos" zugeordnet.
Nun lässt sich über die Sprachsteuerung Google Assistant der Sonos ein- und ausschalten.

Die Volume-ID zeigt im iot-Adapter jedoch die Funktion "Brightness" an, womit ich die Lautstärke ändern kann.
Gerne hätte ich aber nicht "Brightness" sondern "Volume"/"Lautstärke". Wenn ich die Funktion auf "Volume" ändere, 
ändert sich diese automatisch innert wenigen Sekunden wieder auf "Brightness" zurück.

Ist dies ein Fehler im iot-Adapter, so gewollt oder mache ich etwas falsch?

![image](https://user-images.githubusercontent.com/71840093/103480047-39048300-4dd2-11eb-9d0c-423daf93f0ca.png)

![image](https://user-images.githubusercontent.com/71840093/103479979-b380d300-4dd1-11eb-8cf4-103353f115dd.png)

**Comment by Apollon77** [comment]
This needs the v3 update for Amazon skill to support more control tyoes. v2 SKills only have brightness. indirect duplicate of #29
