### ISSUE TITLE
Dimmen der Lampen ändert immer Farbtemperatur

### ISSUE THREAD

**Issue by b3ster** [ioBroker/ioBroker.iot#225]
Bei der Nutzung von Lampen über Alexa und wenn die folgenden Werte verwendet werden:
- bri oder level
- ct
- on

Funktioniert das Anpassen der Farbtemperatur (weiß / warmweiß...) wie gewünscht.
Sobald man aber die Helligkeit mit "Alexa Helligkeit von xyz auf 80%" nutzt wird
immer auch die Farbtemperatur Prozentual auf einen Wert von 80% gesetzt.
Dies scheint mir ein Fehler zu sein, Ich nutze die PRO Version und hoffe das dies angepasst werden 
kann.

Vielen Dank vorab und mit freundlichem Gruß

**Comment by Apollon77** [comment]
Bitte Screenshot der Konfiguration des betroffenen Devices zeigen und Debug Log von einer solchen Schaltaktion.

**Comment by b3ster** [comment]
Vielen Dank für die schnelle Rückmeldung und bitte verzeihen Sie die fehlenden Informationen.

Folgende Punkte wurden geprüft
- utf8 - andere Namen als "Küchenzeile" 
- Anderer Adapter als Ziel (geprüft mit deconz und knx) um hier Probleme auszuschließen

Das Problem besteht unabhängig von den oben getesteten Einstellungen

- Dimmen funktioniert bei Verwendung der Elemente:
- bri (Helligkeit in Prozent)
- on (Schalter)

wird dann ct hinzugefügt kann man die Farbtemperatur ohne Probleme mit Alexa anpassen.
Ändert man nun aber die Helligkeit wird der Prozentwert auch an die Farbtemperatur angewendet
und diese jedes mal verstellt.

Änderung Farbtemperatur per Alexa
`iot.0	2021-01-05 12:25:17.517	debug	(8361) [ALEXA] DONE: deconz.0.Lights.1.ct
iot.0	2021-01-05 12:25:17.475	debug	(8361) [ALEXA] Won't control deconz.0.Lights.1.on as not a color temperature.
iot.0	2021-01-05 12:25:17.474	debug	(8361) [ALEXA] Controlling: deconz.0.Lights.1.ct setting to 370
iot.0	2021-01-05 12:25:17.474	debug	(8361) [ALEXA] Won't control deconz.0.Lights.1.bri as not a color temperature.
iot.0	2021-01-05 12:25:17.472	debug	(8361) [ALEXA] Controlling temperature kelvin: deconz.0.Lights.1.on
iot.0	2021-01-05 12:25:17.471	debug	(8361) [ALEXA] Controlling temperature kelvin: deconz.0.Lights.1.ct
iot.0	2021-01-05 12:25:17.471	debug	(8361) [ALEXA] Controlling temperature kelvin: deconz.0.Lights.1.bri
iot.0	2021-01-05 12:25:17.470	debug	(8361) [ALEXA] New Request: SetColorTemperatureRequest
iot.0	2021-01-05 12:25:17.469	debug	(8361) {"group":true,"channels":{"deconz.0.Lights.1":[{"id":"deconz.0.Lights.1.bri","role":"level.brightness","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff"]
iot.0	2021-01-05 12:25:17.468	debug	(8361) 1609845917468 ALEXA: {"header":{"namespace":"Alexa.ConnectedHome.Control","name":"SetColorTemperatureRequest","payloadVersion":"2","messageId":"9cf24ec6-eadf-43c5-b422-5139824d910b"},"payload":
iot.0	2021-01-05 12:25:17.468	debug	(8361) Data: "{\"header\":{\"namespace\":\"Alexa.ConnectedHome.Control\",\"name\":\"SetColorTemperatureRequest\",\"payloadVersion\":\"2\",\"messageId\":\"9cf24ec6-eadf-43c5-b422-5139824d910b\"},\"payl
iot.0	2021-01-05 12:25:17.468	debug	(8361) Request command/NOMAILHERE/alexa`

Änderung Helligkeit per Alexa
`iot.0	2021-01-05 12:27:09.901	debug	(8361) [ALEXA] Controlling deconz.0.Lights.1.on .
iot.0	2021-01-05 12:27:09.900	debug	(8361) [ALEXA] Remember ON value for "deconz.0.Lights.1.ct": 326.5
iot.0	2021-01-05 12:27:09.900	debug	(8361) [ALEXA] Controlling deconz.0.Lights.1.ct .
iot.0	2021-01-05 12:27:09.899	debug	(8361) [ALEXA] Remember ON value for "deconz.0.Lights.1.bri": 127
iot.0	2021-01-05 12:27:09.899	debug	(8361) [ALEXA] Controlling deconz.0.Lights.1.bri .
iot.0	2021-01-05 12:27:09.897	debug	(8361) [ALEXA] Controlling percentage: deconz.0.Lights.1.on
iot.0	2021-01-05 12:27:09.897	debug	(8361) [ALEXA] Controlling percentage: deconz.0.Lights.1.ct
iot.0	2021-01-05 12:27:09.897	debug	(8361) [ALEXA] Controlling percentage: deconz.0.Lights.1.bri
iot.0	2021-01-05 12:27:09.895	debug	(8361) null
iot.0	2021-01-05 12:27:09.895	debug	(8361) [ALEXA] DATA: [{"id":"deconz.0.Lights.1.bri","role":"level.brightness","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff"]},{"id":"deconz.0.Lights.1.ct","
iot.0	2021-01-05 12:27:09.895	debug	(8361) [ALEXA] ALEXA Percent: K_chenzeile 50%
iot.0	2021-01-05 12:27:09.895	debug	(8361) [ALEXA] New Request: SetPercentageRequest
iot.0	2021-01-05 12:27:09.894	debug	(8361) {"group":true,"channels":{"deconz.0.Lights.1":[{"id":"deconz.0.Lights.1.bri","role":"level.brightness","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff"]
iot.0	2021-01-05 12:27:09.894	debug	(8361) 1609846029894 ALEXA: {"header":{"namespace":"Alexa.ConnectedHome.Control","name":"SetPercentageRequest","payloadVersion":"2","messageId":"dbb86aa0-4a21-4ab9-9b31-58f103c13858"},"payload":{"acce
iot.0	2021-01-05 12:27:09.894	debug	(8361) Data: "{\"header\":{\"namespace\":\"Alexa.ConnectedHome.Control\",\"name\":\"SetPercentageRequest\",\"payloadVersion\":\"2\",\"messageId\":\"dbb86aa0-4a21-4ab9-9b31-58f103c13858\"},\"payload\":
iot.0	2021-01-05 12:27:09.894	debug	(8361) Request command/NOMAILHERE/alexa`

Konfigurationen

![Dimmen+CT](https://user-images.githubusercontent.com/28812766/103644154-36329b00-4f56-11eb-9df8-8ab76b8559ca.PNG)
![genutzte_werte](https://user-images.githubusercontent.com/28812766/103644157-36cb3180-4f56-11eb-8824-4642233e6568.PNG)

**Comment by Morluktom** [comment]
@Apollon77  das scheint das gleiche Problem zu sein wie beim Thermostat. 
Ich kann es nur leider nicht testen da ich keine HUE Lampen habe.

**Comment by b3ster** [comment]
@Morluktom @Apollon77 Das Problem tritt auch beim knx adapter auf. Ich gehe davon aus es wird sich auch nachstellen lassen wenn man sich einfach Datenpunkte anlegt für den iot adapter.
Problem scheint ja zu sein das ein return von Alexa auf alles angewendet wird und kein unterschied zwischen Helligkeit und/oder anderen Werten gemacht wird, auch wenn der Farbwert eigentlich nicht als "Prozent" geflaggt ist.

**Comment by Morluktom** [comment]
Ich kann Dir anbieten das ich heute Abend eine Version vorbereite wo ich denke das der Fehler behoben ist.
Du testest diese Version und falls der Fehler behoben ist erstelle ich einen Pullrequest.

**Comment by b3ster** [comment]
@Morluktom Sehr gern, Ich stehe gerne zur Verfügung zum testen

**Comment by Morluktom** [comment]
Ich kann das Problem nachstellen.
Versuche bitte mal folgende Version:
https://github.com/Morluktom/ioBroker.iot
Das ist die 1.8.9 + eine Anpassung

**Comment by b3ster** [comment]
@Morluktom Vielen Dank für die Anpassungen funktionieren mit dem Deconz-Adapter und den Spots die Ich gerade zum testen habe perfekt 💯 🥇 
Ich würde morgen noch andere Adapter und Leuchtmittel testen und dann nochmal Rückmeldung geben.
Vielen Dank schonmal an dieser Stelle

**Comment by Morluktom** [comment]
Danke für die Rückmeldung. Dann warte ich noch bis morgen.
Sollte eine positive Rückmeldung kommen erstelle ich den Request

**Comment by b3ster** [comment]
Funktioniert auch mit andern Leuchtmitteln wie auch dem KNX Adapter ohne Probleme 👍

**Comment by Morluktom** [comment]
Ich habe aber nochmals ein Problem gefunden.
Sage mal Alexa Lampe.. heller, bzw. dunkler. Dann ändert sich auch die Farbtemperatur. Das würde ich jetzt auch noch schnell fixen.

**Comment by b3ster** [comment]
Stimmt, gerade getestet, "wärmer" und "kälter" funktioniert, aber beim "heller" und "dunkler" wird die Farbetemperatur mit angepasst. Ich teste gern nochmal eine neue Version

**Comment by Morluktom** [comment]
Habe es bereits angepasst.
https://github.com/Morluktom/ioBroker.iot

**Comment by b3ster** [comment]
Eben getestet, funktioniert traumhaft 🥇

**Comment by Morluktom** [comment]
Ich habe den Pull Request gestellt. Sobald dieser übernommen wird können wir diesen Punkt schließen.
Danke fürs testen.

**Comment by Morluktom** [comment]
Guten Morgen,
Teste bitte die Offizielle Version nochmal und schliesse dann diese Punkt.
Gruß 
Tom

**Comment by Troox73** [comment]
Also bei wärmer/kälter/heller/dunkler bekomme ich immer "ich weiss nicht was schief gelaufen ist" als Antwort :) Wenn ich Weiß als Grund(Startfarbe) nehme, läßt sich keine Farbe per Sprachbefehl einstellen. Bri, ct, hue & on sind verknüpft. v1.8.11 via Deconz. Es ist eine GU10 Hue Richer Colors Spot Gruppe (3stk). Warum nutzt eigentlich kein Widget/Adapter den xy Datenpunkt der Hue's?

**Comment by Morluktom** [comment]
Hallo, kannst Du bitte auch mal die Konfiguration aus dem Iot Adapter und die Datenpunkte posten?

**Comment by Troox73** [comment]
Na klar :) Screenshot der Datenpunkte wurde direkt nach dem Befehl "Alexa, Licht weiß" / "Alexa, Licht Blau" aufgenommen. Es kommt eine Akustische Bestätigung (Düdüm ^^) und das Licht bleibt weiss. Komischerweise funktioniert heute morgen "Kälter/Wärmer/Dunkler/Heller" nachdem uns eine Sicherung um die Ohren geflogen ist und der Pi4 neu startete :-)

![Zwischenablage01](https://user-images.githubusercontent.com/45439011/106354484-6b7e9e80-62f2-11eb-8e9a-b30fad38e328.jpg)
![Zwischenablage02](https://user-images.githubusercontent.com/45439011/106354488-733e4300-62f2-11eb-95a5-21fff48c1c69.jpg)
![Zwischenablage03](https://user-images.githubusercontent.com/45439011/106354489-776a6080-62f2-11eb-857e-34c8dd749592.jpg)

**Comment by Troox73** [comment]
Auch erreichbar über Gitter unter dem selben Namen. Falls was ist :-)

**Comment by Morluktom** [comment]
Lösche mal den "colormode" raus, und füge den "sat" ein. Lerne dann das Gerät neu bei Alexa an, sieht es dann besser aus? Ich habe keine hue, daher kann ich es leider nicht probieren. Ich habe gerade nur Datenpunkte angelegt bei mir reagiert der hue Datenpunkt. Kann halt nicht sagen ob die Farbe richtig ist

**Comment by Troox73** [comment]
Habe cm durch sat ersetzt. cm war gestern noch vom testen aktiv :-) Brachte aber keinen Erfolg.
Was mir eben noch auffiel ist das bei änderungen von 100 auf x% sat und bri verändert werden.

`

iot.0 | 2021-01-30 15:19:16.297 | silly | (8860)  States user redis pmessage  iot.0.smart.*/iot.0.smart.lastObjectID:{"val":"deconz.0.Groups.20.sat","ack":true,"ts":1612016356291,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","l
-- | -- | -- | --
iot.0 | 2021-01-30 15:19:16.292 | silly | (8860)  States user redis pmessage  iot.0.smart.*/iot.0.smart.lastObjectID:{"val":"deconz.0.Groups.20.bri","ack":true,"ts":1612016356288,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","l
iot.0 | 2021-01-30 15:19:16.287 | silly | (8860)  States user redis pmessage  iot.0.smart.*/iot.0.smart.lastCommand:{"val":10,"ack":true,"ts":1612016356258,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1612016356258}
iot.0 | 2021-01-30 15:19:16.286 | silly | (8860)  States user redis pmessage  iot.0.smart.*/iot.0.smart.lastRoom:{"val":null,"ack":true,"ts":1612016356258,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1610396287709}
iot.0 | 2021-01-30 15:19:16.282 | silly | (8860)  States user redis pmessage  iot.0.smart.*/iot.0.smart.lastFunction:{"val":null,"ack":true,"ts":1612016356257,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1610396287709}
iot.0 | 2021-01-30 15:19:16.279 | silly | (8860)  States user redis pmessage  iot.0.smart.*/iot.0.smart.lastResponse:{"val":"Arbeitszimmer wird auf 10  Prozent  <emphasis>gesetzt</emphasis>","ack":true,"ts":1612016356257,"q":0,"from":"system.adap
iot.0 | 2021-01-30 15:19:16.256 | debug | (8860) [ALEXA] Controlling deconz.0.Groups.20.sat .
iot.0 | 2021-01-30 15:19:16.256 | debug | (8860) [ALEXA] deconz.0.Groups.20.on is no valid datapoint to set the percentage.
iot.0 | 2021-01-30 15:19:16.256 | debug | (8860) [ALEXA] deconz.0.Groups.20.hue is no valid datapoint to set the percentage.
iot.0 | 2021-01-30 15:19:16.255 | debug | (8860) [ALEXA] deconz.0.Groups.20.ct is no valid datapoint to set the percentage.
iot.0 | 2021-01-30 15:19:16.254 | debug | (8860) [ALEXA] Controlling deconz.0.Groups.20.bri .
iot.0 | 2021-01-30 15:19:16.251 | debug | (8860) [ALEXA] Controlling percentage: deconz.0.Groups.20.sat
iot.0 | 2021-01-30 15:19:16.250 | debug | (8860) [ALEXA] Controlling percentage: deconz.0.Groups.20.on
iot.0 | 2021-01-30 15:19:16.249 | debug | (8860) [ALEXA] Controlling percentage: deconz.0.Groups.20.hue
iot.0 | 2021-01-30 15:19:16.249 | debug | (8860) [ALEXA] Controlling percentage: deconz.0.Groups.20.ct
iot.0 | 2021-01-30 15:19:16.248 | debug | (8860) [ALEXA] Controlling percentage: deconz.0.Groups.20.bri
iot.0 | 2021-01-30 15:19:16.248 | debug | (8860) null
iot.0 | 2021-01-30 15:19:16.247 | debug | (8860)  [ALEXA] DATA:  [{"id":"deconz.0.Groups.20.bri","role":"level.brightness","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff"]},{"id":"deconz.0.Groups.20.ct"
iot.0 | 2021-01-30 15:19:16.247 | debug | (8860) [ALEXA] ALEXA Percent: Arbeitszimmer 10%
iot.0 | 2021-01-30 15:19:16.246 | debug | (8860) [ALEXA] New Request: SetPercentageRequest
iot.0 | 2021-01-30 15:19:16.246 | debug | (8860)   {"group":true,"channels":{"deconz.0.Groups.20":[{"id":"deconz.0.Groups.20.bri","role":"level.brightness","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff
iot.0 | 2021-01-30 15:19:16.246 | debug | (8860)  1612016356246 ALEXA:  {"header":{"namespace":"Alexa.ConnectedHome.Control","name":"SetPercentageRequest","payloadVersion":"2","messageId":"8edc49a7-a9b5-4100-9bad-52f980341d44"},"payload":{"acce
iot.0 | 2021-01-30 15:19:16.245 | debug | (8860)  Data:  "{\"header\":{\"namespace\":\"Alexa.ConnectedHome.Control\",\"name\":\"SetPercentageRequest\",\"payloadVersion\":\"2\",\"messageId\":\"8edc49a7-a9b5-4100-9bad-52f980341d44\"},\"payload\":

`
