### ISSUE TITLE
Dimmer in yandex

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.iot#228]
**Describe the bug**  
The dimmer created via devices does not work correctly in yandex. Does not read the ON_SET and SET states. If the values in Yandex change, only the ACTUAL and ON_ACTUAL values in iobroker change. At the same time, everything works correctly in google home, if the values come from Google, then the values of ON_SET and SET change in IoBroker. And, when viewing the device in Google Home, it displays the values from ACTUAL and ON_ACTUAL (everything is as it should work).

**To Reproduce**  
1. Go to 'Devices'
2. Сreate a dimmer
3. Go to Yandex app
4. change the dimmer state and look at the objects in the iobroker.

**Expected behavior**  
Need the same behavior as in google home. If the values change in Yandex, the ON_SET and SET objects should change in iobroker. The ACTUAL and ON_ACTUAL values should be used for the current device status and read by Yandex as the current state.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/104107288-155aa480-52cc-11eb-9e2c-fab09561d997.png)

**Versions:**  
 - Adapter version: 1.8.9
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: docker 5.1.0

**Comment by GermanBluefox** [comment]
Fixed in iobroker.iot@1.8.12
