### ISSUE TITLE
`State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions`

### ISSUE THREAD

**Issue by Pocky2507** [ioBroker/ioBroker.iot#229]
Nach Update aufjs-controller 3.2.4 diese Fehlermeldung

`State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions`

**Comment by vaaarg** [comment]
schliesse mich an

js-controller 3.2.7

`

iot.0 | 2021-01-17 10:29:46.348 | warn | (1999) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
iot.0 | 2021-01-17 10:29:46.213 | warn | (1999) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-17 10:29:46.109 | warn | (1999) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-17 10:29:46.101 | warn | (1999) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions

`

**Comment by sir0drake** [comment]
Hallo,
ich will einen Thermostat in alexa einbinden und komme zum gleichen neg. Ergebnis.
interessanterweise geht es aber bei anderen DPs.
Trifft also nicht auf alle DP zu.
vg
iot 1.8.9
js 4.10.9

iot.0 | 2021-01-20 14:11:15.684 | warn | (24340) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions

**Comment by Diginix** [comment]
Same log entry here with 
JS-Controller 3.2.8
iot 1.8.11
nodejs 12.20.1

**Comment by vaaarg** [comment]
just wanted to add that every voice command throws these warnings

`

iot.0 | 2021-01-23 08:59:42.973 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
iot.0 | 2021-01-23 08:59:42.852 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:42.779 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:42.770 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:36.263 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:36.140 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:36.015 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:36.005 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:29.141 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:29.000 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:28.916 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:28.892 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions
iot.0 | 2021-01-23 08:59:28.889 | warn | (1261) State "iot.0.smart.lastObjectID" has no existing object, this might lead to an error in future versions

`

**Comment by m0rph2k** [comment]
auch bei mir

Node.js v12.20.1
NPM 6.14.10
js-c 3.2.8
iot 1.8.11

**Comment by patrickbs96** [comment]
Ich kenne mich so technisch nicht mit dem Adapter aus, aber mit einer kurzen Suche im Code habe ich festgestellt, dass nur übersehen wurde den State zu erstellen. Ich habe den State dann einfach bei mir manuell angelegt und die Fehlermeldung kommt dann natürlich nicht mehr, da der State jetzt beschrieben werden kann.

![image](https://user-images.githubusercontent.com/49351462/105614763-b026a900-5dcb-11eb-8a88-0c35a21443d0.png)

@Apollon77  Ich vermute hier fehlt nur der Eintrag in der `io-package.json`.

**Comment by Mercator18** [comment]
Bei mir verschwanden ebenfalls die Log-Einträge , nachdem ich manuell den DP lastObjectID erzeugt hatte. Auch Latenzen bei Script-Überwachung/ausführung mittels on({id: ...)) waren danach genauso schnell weg, wie sie kamen.

**Comment by Apollon77** [comment]
will be fixedin 1.8.13
