### ISSUE TITLE
[gelöst] Alexa findet keine IoT Geräte

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.iot#235]
Plötzlich sagt Alexa, mit dem IoT Gerät stimmt etwas nicht - oder so ähnlich.

Was ich bisher gemacht habe:
IoT Adapter gelöscht und neu installiert. Version 1.8.9
Im https://iobroker.pro - Diagnose überprüft  -   Free Version, kein Abo
Log ohne Fehler

- debug: host.raspi4 object change system.adapter.iot.0 (from: system.adapter.admin.0)
- info: host.raspi4 "system.adapter.iot.0" enabled
- debug: host.raspi4 startInstance iot.0 loglevel=info, compact=false
- info: host.raspi4 instance system.adapter.iot.0 started with pid 20844
- debug: host.raspi4 Incoming Host message getLogs
- info: iot.0 (20844) starting. Version 1.8.9 in /opt/iobroker/node_modules/iobroker.iot, 
        node: v10.19.0, js-controller: 3.1.6
- info: iot.0 (20844) Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
- info: iot.0 (20844) Connection changed: connect
- debug: host.raspi4 Incoming Host message getLogs
- info: iot.0 (20844) Request devices

Alexa Gerät im IoT Adapter gelöscht und neu angelegt

Leider findet weder Alexa Skill noch Alexa App die neuen IoT Geräte.

Hoffentlich kennt jemand eine Abhilfe.

**Comment by Apollon77** [comment]
In Alexa sind die Geräte gelöscht? Adaote rist grün?

**Comment by Hans-Zwiesel** [comment]
@Apollon77 
- Adaote rist grün         Ich vermute mal, das soll heißen Adapter ist grün:
IoT Adapter gelöscht und neu installiert. Version 1.8.9, Adapter ist grün, mehrfach neu gestartet
auch nachdem ein Alexa Gerät im IoT Adapter gelöscht und neu angelegt wurde.

In Alexa ist auch noch ein IoT Alexa Gerät aus früheren Tagen vorhanden, welches mit Alexa noch angesprochen werden kann,
aber in ioBroker keine Reaktion mehr auslöst.

**Comment by Hans-Zwiesel** [comment]
Ich habe den ioBroker.iot Skill in Alexa deaktiviert und wieder aktiviert.
Jetzt findet Alexa meine IoT Geräte wieder.

**Comment by OberstVonGatow** [comment]
> 
> 
> Ich habe den ioBroker.iot Skill in Alexa deaktiviert und wieder aktiviert.
> Jetzt findet Alexa meine IoT Geräte wieder.

Das hat bei mir auch geholfen 👍
Vielleicht lag es bei mir daran, dass das iobroker.pro Abo abgelaufen war. 
Erneuern des Abos hat aber erstmal nicht geholfen und auch der Neustart der Instanz (immer grün) hatte nichts gebracht.
