### ISSUE TITLE
Sporadisch: "Gerät antwortet nicht. Überprüfe Stromversorgung..."

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.iot#243]
Ich habe immer mal wieder das Problem, dass beim Schalten einzelner Alexa-Geräte aus dem iot-Adapter via Alexa die Fehlermeldung von Alexa kommt: "Gerät antwortet gerade nicht. Überprüfe Stromversorgung...". Manchmal schaltet er dann mit etws Verzögerung nach dieser Fehlermeldung trotzdem, manchmal auch nicht.

Die Fehlermeldung kommt sporadisch, meist funktioniert es. Ich habe ein ioBroker Pro Abo. Sind da serverseitig sporadisch Überlastungen?

-jayvee

**Comment by vaaarg** [comment]
würde mich auch mal interessieren. habe dasselbe phenomenon
