### ISSUE TITLE
Objects created in the alias-manager do not appear on Yandex devices.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.iot#263]
**Describe the bug**  
I tried to create an object by copying it in the alias manager, but it doesn't appear in Yandex devices.

**To Reproduce**  
1. Go to 'alias-manager'
2. Click on 'copy alias'
3. Go to 'iot adapter, yandex tab'

**Expected behavior**  
the created devices must be added to Yandex devices. just like in Google home, since they are added there correctly

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/113412101-17f70280-93c0-11eb-8749-7dfbd494acc5.png)
![image](https://user-images.githubusercontent.com/37106885/113412442-f4808780-93c0-11eb-99ba-83a3c73469aa.png)
![image](https://user-images.githubusercontent.com/37106885/113412455-006c4980-93c1-11eb-9aae-b22c8c7bea07.png)
![image](https://user-images.githubusercontent.com/37106885/113412487-137f1980-93c1-11eb-85b8-bf78f2cd6221.png)

**Versions:**  
 - Adapter version: 1.8.16 (alias-manager 1.0.0)
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system: debian

**Comment by Apollon77** [comment]
Why you create thet iaaus ehere and not in alias-manager?
Can you please show the raw object definition? (english: click on pencil of the relevant alias object and select "raw experts only" and copy json)
