### ISSUE TITLE
No devices in Alise devices

### ISSUE THREAD

**Issue by 333brain333** [ioBroker/ioBroker.iot#265]
Hello, I have Mqtt switch state with room and function attached to it. All was done accordingly to your instructions in readme.md in the part "How names will be generated". But no name appeared in Alise devices (empty list). It seems to me that I'm not very first person faced with such issue. 
Even if I manually add device by pressing "+" button in Alise devices after pressing the update button it returns "Device mqtt.0.inTopic wasn't added". 
If then take a look at logs - "(795) Request Yandex Alice devices" only occurs. 
In the settings of the adapter I have checked 
- Place function in names first
- Persinal settings (only pro)
- Debug info
I have 1.8.16 version of the IOT adapter installed.

**Comment by Anzic23** [comment]
try to use Device adapter. Great device in this adapter (Device adapter) and connect to real objects.
