### ISSUE TITLE
Adding new smart device from the ioBroker Zigbee Adapter fails (after selecting the ID in the popup the list of devices is not updated).

### ISSUE THREAD

**Issue by joergzdarsky** [ioBroker/ioBroker.iot#27]
With the ioBroker.iot Adapter it is not possible to add a new smart device in the smart device tab.
After pressing plus on the top left a popup occurs to select the appropriate ID / datapoint,
but after selecting one and pressing save, the list of smart devices is not updated.

Tested with the current ioBroker.iot Adapter version and by adding an ID (Xiaomi Aqara temperature sensor - temperature ID) of within the ioBroker.Zigbee adapter.

**Comment by joergzdarsky** [comment]
The issue seems related to the corresponding datapoint and eventually the Zigbee Adapter in particular, because adding a different ID (e.g. sonoff or a custom javascript.0 one) works.

**Comment by Apollon77** [comment]
Can you show the object definition ? Is the state allowed to be written?

**Comment by joergzdarsky** [comment]
Due to your hint I checked the read/write checkboxes, indeed the object was not allowed to be written, after changing that it worked. Thank you.
In that case I think the issue can be closed / rejected, or maybe better it should be changed to an enhancement and the content should be a warning message while adding such an endpoint as smart device if it is not allowed to be written instead of showing nothing to the user.

**Comment by derFricklerDE** [comment]
same problem.

get an erorr in the console: Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by Apollon77** [comment]
More details to console? File? Line? Something?

**Comment by Mathiasb007** [comment]
Same Problemm:
https://youtu.be/tx4M1PVP6ZU

**Comment by chrram85** [comment]
I have the same problem as in the video. But only with devices that I add about zigbeeadapter. someone a solution?

**Comment by Gwenselah** [comment]
Hello,
I have the same problem and attached here the debug log of the iot adapter.

[iobroker.2019-05-02.log.html.zip](https://github.com/ioBroker/ioBroker.iot/files/3139736/iobroker.2019-05-02.log.html.zip)

**Comment by BigDi** [comment]
Have the same problem with an Osram Smart Plug. What do you mean with add whitespace anywhere? Can you post a screenshot?

**Comment by BigDi** [comment]
Okay. I managed it with adding a node into the raw data like:
![grafik](https://user-images.githubusercontent.com/11903065/61544345-873e8e80-aa45-11e9-8222-84f6db740ec7.png)

**Comment by Gwenselah** [comment]
With whitespace I meant to Type a blank anywhere. You don't have to add a complet node

**Comment by BigDi** [comment]
To the name and the value of the nodes?

**Comment by Gwenselah** [comment]
anywhere e.g. behind a comma. the trick is to force a save action. In think that saving corrects something in the data structure, but it is beyond my skills to analyze this

**Comment by zakuma666** [comment]
How Do I edit the raw Data?

**Comment by TBobsin** [comment]
Hello,
i could add an sonoff device to alexa without an problem. 
when i edit the raw data of an zigbee device i could add the zigbee device to alexa. 
so there is a bug within the dialogue with zigbee

**Comment by Schimi1983** [comment]
í´ve the same issue.... a fix would be great!! :-)
