### ISSUE TITLE
ioBroker Custom Skill / Javascript Problem

### ISSUE THREAD

**Issue by roe19xx** [ioBroker/ioBroker.iot#28]
Hallo,

Laut Github Beschreibung kann man ja auf die Fragen im ioBroker Custom Skill mit dem text2command Adapter reagieren, oder auch mit Javascript (Beispiel ist auch in Github zu finden).

Ich habe hierfür nun ein wenig mit Javascript experimentiert, da ich mir auf Dauer hier mehr Flexibilität und ggf. etwas weniger Pflegeaufwand als bei text2command verspreche.

Ich verwende den iot Adapter, und habe dort "Benutze text2command Instanz" deaktiviert.

Habe dann das Beispiel Script für einen kleinen Test etwas angepasst, das schaut dann so aus: 

`// important, that ack=true
on({id: 'iot.0.smart.lastCommand', ack: true, change: 'any'}, obj => {
    // you have 200ms to prepare the answer and to write it into iot.X.smart.lastResponse
    log("### Last Command: " +obj.state.val);
    if(obj.state.val.match(/büro/) && obj.state.val.match(/luftfeuchtigkeit/))
    {
        var humVal = getState("hm-rpc.0.MEQxxxxxxx.1.HUMIDITY").val;
        setState("iot.0.smart.lastResponse", "Die Luftfeuchtigkeit im Büro liegt aktuell bei " +humVal+ " Prozent"); // important, that ack=false (default)
        //setState('iot.0.smart.lastResponse', 'Received phrase is: ' + obj.state.val); // important, that ack=false (default)
    }
});`

Dann teste ich mit dem Satz "Alexa, Frag ioBroker nach der Luftfeuchtigkeit im Büro".
Bekomme auch sofort die Antwort "Die Luftfeuchtigkeit im Büro liegt aktuell bei <Wert> Prozent".

Theoretisch alles wunderbar.

Allerdings wartet Alexa nach der Antwort auf eine weitere Eingabe. D.h. sie bleibt aktiv und hört weiter zu. Wenn ich noch etwas sage, dann wird das auch als Eingabe vom ioBroker Skill verarbeitet und steht in iot.0.smart.lastCommand zur Verfügung.

Wenn ich nichts sage sprich nicht weiter reagiere, dann wartet sie ein paar Sekunden. Dann kommt der Quittierungston gefolgt von der Meldung "Ich habe im Moment Schwierigkeiten auf Deinen Custom ioBroker Skill zuzugreifen".

Der Skill ist aber korrekt verbunden bzw. verknüpft (wurde auch schon getrennt und wieder verbunden).

Gibt es da noch einen Fehler im ioBroker Custom Skill in Kombination mit Javascript?

Hier noch die Versionen der Adapter die meiner Meinung nach hier relevant sein könnten:
JS Script Engine >>> 4.0.11
IoT Adapter >>> 0.3.1

Ich verwende zwei JS Sript Engine Instanzen. Instanz 0 für Tests und Instanz 1 produktiv.
Getestet habe ich das Ganze bei mir in der javascript.0 Instanz.

Gibt es da ggf. noch einen Fehler beim IoT Adapter oder mache ich etwas falsch?

Habe die Anfrage ursprünglich auch im ioBroker Forum gestellt.
Zu finden hier: https://forum.iobroker.net/viewtopic.php?f=37&t=21105

Gruß
Roland

**Comment by Apollon77** [comment]
Ja, der Fakt das die Session offen bleibt im Default war so.

Bitte mal 0.4.0 vom Github testen. Dort bleibt die Session jetzt nur offen wenn vorher ein "öffne ioBroker" gesagt wurde, sonst geht die Session zu. Es sei denn man nutzt die neuen Möglichkeiten um es zu Kontrollieren :-))
Siehe https://github.com/ioBroker/ioBroker.iot#custom-skill
