### ISSUE TITLE
HTTP request is not working

### ISSUE THREAD

**Issue by JVF2** [ioBroker/ioBroker.iot#282]
Hello,

I would like to transfer data to the ioBroker via an Arduino.

Via browser the following hyperlink works perfectly:
https://service.iobroker.in/v1/iotService?service=custom_Webhook&key=KEY&user=USER&data=Test

But in the source code of the Arduino I don't get a positive result:

#include <MKRNB.h>

NBClient client;
GPRS gprs;
NB nbAccess;

char server[] = "iobroker.net";
char path[] = "/service/custom_Webhook/<key>/set/stateID?value=Test";
int port = 443; // port 80 is the default for HTTP

void setup() {
  Serial.begin(9600);
  while (!Serial) {
    ;
  }

  Serial.println("Connecting...");
  boolean connected = false;

  while (!connected) {
    if ((nbAccess.begin("","iot.1nce.net") == NB_READY) && (gprs.attachGPRS("iot.1nce.net") == GPRS_READY)) {
      connected = true;
      Serial.println("Connected.");
    } else {
      Serial.println("Not connected.");
      delay(1000);
    }
  }

  Serial.println("Connecting...");

  if (client.connect(server, port)) {
    Serial.println("Connected.");
    client.print("POST ");
    client.print(path);
    client.println(" HTTP/1.1");
    client.print("Host: ");
    client.println(server);
    client.println("Connection: close");
    client.println();
  } else {
    Serial.println("Connection failed.");
  }
}

void loop() {
  if (client.available()) {
    Serial.print((char)client.read());
  }

  if (!client.available() && !client.connected()) {
    Serial.println();
    Serial.println("Disconnecting.");
    client.stop();

    for (;;)
      ;
  }
}

What is wrong with the configuration of the HTTP request on the Arduino?

Thanks in advance.

**Comment by Apollon77** [comment]
(or is the used library capable to do https communication?

**Comment by JVF2** [comment]
The library is capable of HTTPS.

Unfortunately I am not an expert, but I seem to make a mistake in the following configutarion:
char server[] = "iobroker.net";
char path[] = "/service/custom_Webhook/[KEY]/set/stateID?value=Test";

**Comment by Apollon77** [comment]
Hm ... your URL where you say "works perfect" is a differen t one ... different server and different path ...

**Comment by JVF2** [comment]
Yes, I have tried different things.
The following configuration does not work either:
char server[] = "service.iobroker.in";
char path[] = "/v1/iotService?service=custom_Webhook&key=[KEY]&user=[User]&data=Test";

Could have been that the problem is solved quickly with one look.

**Comment by Apollon77** [comment]
I think we are all no Arduino devs ... :-( Cna you get any logs from that library?

**Comment by JVF2** [comment]
It really seems to be a problem with the Arduino.
I'll try my luck in the Arduino forum.

Thanks for your help.
