### ISSUE TITLE
Keine Verbindung mit v 1.8.19

### ISSUE THREAD

**Issue by Azathoth88** [ioBroker/ioBroker.iot#284]
Seit Update auf Version 1.8.19 erhalte ich keine Verbindung mehr. Stattdessen erhalte ich folgende Warnungen:
iot.0 2021-05-16 15:48:23.505	error	Cannot read keys: User not exist or invalid password.
iot.0 2021-05-16 15:48:23.504	error	Cannot fetch keys: "User not exist or invalid password."

Credentials haben sich nicht geändert. Ich habe diese aber obligatorisch neu eingegeben. Zertifikat neu heruntergeladen etc. pp.
Laut Forum sind weitere User betroffen, siehe auch:
https://forum.iobroker.net/topic/19241/iot-iot-adapter-verbindet-sich-nicht-bzw-verbindung-ist-gelb/326?_=1621172648145

Node.js v12.22.1
NPM 6.14.12

**Comment by GermanBluefox** [comment]
In 1.8.18-1.8.20 war das Password falsch verschlüsselt. 
Bitte auf 1.8.21 updaten und das Passwort im Konfigurations-Dialog von iot im Admin neu eingeben.

**Comment by Azathoth88** [comment]
Merci!

**Comment by Sven2Samrt** [comment]
Guten Morgen, ich ein Update von Version 1.8.19 auf Version 1.8.22 durchgeführt und erhalte immer keine Verbindung(immer gelb). Stattdessen erhalte ich folgende Warnungen:

iot.0 | 2021-05-19 07:29:53.329 | error | (2237) Cannot read keys: Error: write EPROTO 1

Die Credentials haben sich nicht geändert (Testweise einen neuen Iot.pro Account angelegt, leider das gleiche Ergebnis). Ich habe diese aber obligatorisch neu eingegeben und das Zertifikat neu heruntergeladen etc. pp.

Mein System:
Node.js v12.22.1
NPM 6.14.12

Macht  die Version 1.8.22 auch Probleme? Ich weiß jetzt nicht mehr weiter :-(

**Comment by Apollon77** [comment]
EPROTO means an SSL protocol error ... so somethiong with your connection. Can you please try again?
