### ISSUE TITLE
Cannot add data point to alexa devices

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.iot#287]
I made a new boolean data point but I cannot add it to iot adapter's alexa devices.

"Gerät 0_userdata.0.lg_chromecast wurde nicht hinzugefügt"

I did have this a while ago .. but I would have thought it was fixed (don't remember the workaround).

Logfile:

iot.0 | 2021-05-18 13:32:25.763 | error | "0_userdata.0.lg_chromecast" not exists or no native part.
-- | -- | -- | --

**Comment by daniel-lo** [comment]
Hab den alten Thread gefunden:
https://github.com/ioBroker/ioBroker.cloud/issues/103

Aber leider keine Lösung.

**Comment by Apollon77** [comment]
Please show the objects raw definition

**Comment by daniel-lo** [comment]
I had switched from logik to string .. but still didn't work:


{
  "common": {
    "name": "lg_firetv",
    "desc": "Manuell erzeugt",
    "role": "",
    "type": "string",
    "read": true,
    "write": true,
    "def": false
  },
  "type": "state",
  "_id": "0_userdata.0.lg_firetv",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1621350857723
}

**Comment by Apollon77** [comment]
As the error message said there is not a "native" ... try to add native: {} on top level, and also there is no "role" defined ... both required at least for iot to be able to do something with it

**Comment by daniel-lo** [comment]
sorry .. I don't understand where to add the native .. and no role is requested when I make a new data point

**Comment by Apollon77** [comment]
Start trying to set a sensefull role

**Comment by Apollon77** [comment]
If no role is request please open an issue in admin! Please use Admin5 and react ui ...

**Comment by daniel-lo** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/901

**Comment by daniel-lo** [comment]
5.0.31 .. no change .. (hab den datenpunkt auch neu gemacht .. boolean). IOT nimmt den Datenpunkt nicht als Alexa-Gerät an.

{
  "common": {
    "name": "lg_chromecast",
    "desc": "Manuell erzeugt",
    "role": "state",
    "type": "boolean",
    "read": true,
    "write": true,
    "def": false,
    "smartName": {
      "de": "lg chromecast"
    }
  },
  "type": "state",
  "_id": "0_userdata.0.lg_chromecast",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1621697521237
}

**Comment by daniel-lo** [comment]
Geht es denn bei euch? Ggf. mit meinen Raw-Daten?

**Comment by daniel-lo** [comment]
Nach einfügen der folgenden Zeile in "common":

    "states": "false:no;true:yes",

funktioniert es

**Comment by n3roGit** [comment]
Ich habe exakt die selbe Meldung, wenn ich einen einen DP hinzufügen möchte. Ich habe allerdings einige DPs aus früheren Zeiten die wunderbar funktionieren.



`{
  "common": {
    "name": "shutter-01",
    "desc": "Rolloposition",
    "role": "state",
    "type": "number",
    "unit": "%",
    "min": 0,
    "max": 100,
    "read": true,
    "write": true,
    "def": false,
    "custom": {
      "iot.0": {
        "smartName": {
          "de": "shutter 01"
        }
      }
    }
  },
  "type": "state",
  "_id": "0_userdata.0.Rooms.Wohnzimmer.shutter-01",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.user"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1643747433608
}`

**Comment by Apollon77** [comment]
Das Objekt hat keinen "native" Teil

**Comment by daniel-lo** [comment]
@Apollon77  bitte wieder öffnen

Admin 6.5.9

Ich versuche gerade einen Shelly State in IOT einzubinden (war auch schonmal drin - scheint rausgeflogen zu sein) .. aber bekomme wieder o.g. Meldung (siehe OP).
Habe auch schon alle Objekte neu generieren lassen. Die (vermeintliche) Lösung von oben:
Nach einfügen der folgenden Zeile in "common": "states": "false:no;true:yes",
tut nun auch nicht mehr.

{
  "type": "state",
  "common": {
    "name": "Open",
    "type": "boolean",
    "role": "button",
    "read": false,
    "write": true
  },
  "native": {},
  "_id": "shelly.0.SHSW-21#CC50E313572A#1.Shutter.Open",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1688553151430
}
