### ISSUE TITLE
iot Adaper immer gelb - Keine Verbindung - Version 1.8.22

### ISSUE THREAD

**Issue by Sven2Samrt** [ioBroker/ioBroker.iot#288]
Guten Morgen, ich habe ein Update von Version 1.8.19 auf Version 1.8.22 durchgeführt und erhalte immer keine Verbindung(immer gelb). Stattdessen erhalte ich folgende Warnungen:

iot.0 | 2021-05-19 07:29:53.329 | error | (2237) Cannot read keys: Error: write EPROTO 1
error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Die Credentials haben sich nicht geändert (Testweise einen neuen Iot.pro Account angelegt, leider das gleiche Ergebnis). Ich habe diese aber obligatorisch neu eingegeben und das Zertifikat neu heruntergeladen etc. pp.

Mein System:
Node.js v12.22.1
NPM 6.14.12

Macht  die Version 1.8.22 auch Probleme? Ich weiß jetzt nicht mehr weiter :-(

**Comment by Apollon77** [comment]
EPROTO means an SSL protocol error ... so somethiong with your connection. Can you please try again?

**Comment by Sven2Samrt** [comment]
Ja, gerade getestet, gleiche Meldung im Log:


iot.0 | 2021-05-19 12:51:35.726 | error | (2661) Cannot read keys: Error: write EPROTO

**Comment by Sven2Samrt** [comment]
Ich habe ioBroker mal testweise auf meinen Synology Nas per Docker Images installiert, dort ist genau das gleiche Problem (alle Daten sind identisch).

**Comment by Apollon77** [comment]
Ist irgendeine Firewall, Proxy oder sonstwas in der Verbindung was hier ggf den Netzwerkverkehr betreffen kann?

**Comment by Sven2Samrt** [comment]
Nein, ich habe nur eine AVM Fritz Box 7590. IoBroker ist in Proxmox auf einer Debian VM installiert. Auf der Synology NAS ist ja das gleiche Problem. Alles andere funktioniert, sonst habe ich keine Probleme. Kann man noch irgendwie etwas testen, damit den Fehler besser einkreisen kann?

Vielen Dank!

**Comment by GermanBluefox** [comment]
Gibt es neue Erkenntnisse? Vielleicht Zeit ist falsch auf ioBroker Rechner?
