### ISSUE TITLE
Do not set states to values outside of the min/max range

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.iot#289]
As reported in https://github.com/AlCalzone/ioBroker.zwave2/issues/629, it seems that the iot (and potentially cloud?) adapter sets states outside the defined min/max range. The `targetValue` states in zwave2 have a max of 99, but apparently iot tries to set 100 here.

**Comment by GermanBluefox** [comment]
Please test 1.8.24

**Comment by AlCalzone** [comment]
@rogerroger-coder as you've opened https://github.com/AlCalzone/ioBroker.zwave2/issues/629 originally, can you test this please?
