### ISSUE TITLE
iobroker iot adapter alexa RGB

### ISSUE THREAD

**Issue by faschmali** [ioBroker/ioBroker.iot#298]
Hi, I am using iobroker on a raspberry Pi 4, my Zigbee Gateway is a Conbee II. I connected my lamps via Zigbee adapter (I tried using deconz first but I could not Connect with lamps). 
I am currently trying to add those Lamps (partly with RGB/RGBW/WW) via the IOT Cloud Adapter to my alexa. I made groups of the device with the needed values (e.g. switch, brightness, color temperature and color for a spot with w/ww and RGB Lamps, more parameters are not available at that lamp). 
Alexa finds the lamps without any issues and I can control all the parameters using my voice or routines. But I am not able to change the values by hand in the App. If I go to the lamp I can only control On/Off of Brightness 100-75-50 etc. If I go to the settings of the Lamp there is the point color settings where it shows Color and Color temperature.

Is there a way to control the colors as before with Hue Gateway? A (good) solution using Scripts oder Nodered is also appreciated. 

By the way I am from Germany, in the git readme of this adapter it is mentioned that RGB Color control is only available in English. Does that cause my issue or is it another problem

**Comment by Apollon77** [comment]
I never saw a read "color circle control" in Alexaapp or such ... so, sorry but not possible

**Comment by faschmali** [comment]
> I never saw a read "color circle control" in Alexaapp or such ... so, sorry but not possible

What do you mean with "color circle control"? I have never seen something like that in Alexa too.
I was hoping to be able to use a slider for brightness and predefined Colors as before.

**Comment by Apollon77** [comment]
The color name list is still there for me, a slider on brightness never was ... maybe all gets better if we find time to implement Alexa v3
