### ISSUE TITLE
Neu erstellte Geräte werden erst nach einem Seiten-Reload angezeigt

### ISSUE THREAD

**Issue by Snatch2001** [ioBroker/ioBroker.iot#3]
Nach dem hinzufügen eines Gerätes, wird dieses auch erst angezeigt, wenn man die Seite neu lädt. Der Name kann dementsprechend auch erst dann angepasst werden.

**Comment by Apollon77** [comment]
Try if changing the tab in iot config also works please?!

**Comment by Snatch2001** [comment]
Yes, if you change the tap, the device is gone. Nevertheless, it is a mistake.

**Comment by Apollon77** [comment]
Sure

**Comment by Snatch2001** [comment]
The bug seems resolved with version 0.1.5

**Comment by Snatch2001** [comment]
The bug seems resolved with version 0.1.5
