### ISSUE TITLE
Alexa - Ich weiß nicht was schief gelaufen ist 

### ISSUE THREAD

**Issue by Menne01** [ioBroker/ioBroker.iot#324]
Hello all, 
wie der Titel schon aussagt, habe ich und einige User im Forum das obrige Problem, wenn man Alexa auffordert, einen Heizkörper auf eine gewisse Temperatur zu stellen.
Beispiel: "Alexa, stelle Büro Heizung auf 21 Grad" sollte die Antwort kommmen "Ist auf 21 Grad gestellt."
Es kommt aber "Ich weiß nicht, was schief gelaufen ist"

Die Debug Log`s von Alexa und Iot sende ich an info@iobroker.net

Iot Adapter: 1.8.33
Alexa2 Adapter: 3.9.3

**Comment by Morluktom** [comment]
Poste mal eine Konfiguration eines Thermostats und die verbundenen Datenpunkte.
Gruß 
Tom

**Comment by Menne01** [comment]
Bitteschön...
![grafik](https://user-images.githubusercontent.com/89869516/131747735-57323fa4-ff9c-4bb5-a4da-818f5b8c8f30.png)

**Comment by Morluktom** [comment]
Guten morgen,
mir ist gerade aufgefallen das es bei mir auch nicht mehr funktioniert.
Werde es die Tage mal ansehen.
Gruß
Tom

**Comment by Bernhard71** [comment]
Hallo,
habe leider das selbe Problem, nur mit dem S7 Adapter. Objekte funktionieren mit allen anderen Verknüpfungen oder scripten, seit gestern aber nicht mehr über Alexa. 
Gruß
Bernhard

**Comment by Apollon77** [comment]
@Bernhard71 Also hier hat sich das Thema Auf Thermostat-Temperatur Datenunkte herauskristalisiert ... bei Dir auch?

**Comment by Bernhard71** [comment]
Hatte ohne Änderungen im iOBroker die selben Meldungen, habe aber keine Thermostate angebunden sondern hauptsächlich den S7 Adapter. Die Melung " Ist was schiefgelaufen.." war aber die selbe. Habe es nach mehrmaligen installieren und deinstallieren sowie Alexa-Skill aktivieren deaktivieren wieder zum Laufen gebracht. Ich weiss leider nicht was der Fehler war, hat mich in Summe zwei Tage gekostet.

**Comment by Menne01** [comment]
Schön das es bei dir wieder läuft.
Bei mir ist seit Donnerstag alles tot....bekomme nicht einmal eine Verknüpfung zum ProAccount zustande. Der Account meldet jedesmal ein internal error.
Nun bin ich erst einmal für die wichtigsten Funktionen auf Siri umgestiegen.

Aber auf Dauer keine Lösung.

**Comment by Leo445566** [comment]
Moin,
habe gerade dieses Thema gefunden und kann auch bei mir das Problem bestätigen.
Alexa gibt die Meldung zurück "Ich weiß nicht was schie gelaufen ist", sobald man einen Heizkörper über Alexa anpricht. Dabei wird jedoch die gewünschte Temperatur trotzdem richtig gesetzt. Damals (vor dem Sommer) kam immer die Meldung zurück ".... ist auf 22 Grad gestellt".

admin: 5.1.23
iot: 1.8.22
Node.js: 10.21.0
hm-rega: 3.0.31
hm-rpc: 1.15.45

Sollte ich irgendwie unterstützen können, gebt mir bitte Bescheid.

**Comment by Menne01** [comment]
Sei aber vorsichtig, mache am besten alle deine Daten unkenntlich. Sonst könnte es dir so ergehen wie bei mir.
Vertrauen habe ich hier nicht mehr....
Seit Donnerstag geht nichts mehr.

**Comment by Menne01** [comment]
Bei mir hat sich was getan...mein Account läuft wieder.

**Comment by mabe1983** [comment]
Moin zusammen,

selbes Problem mit den Thermostaten bei mir - die Temperatur lässt sich einstellen aber Alexa gibt die Meldung dass etwas schiefgelaufen ist.
@Apollon77 Weißt du ob an dem Problem schon aktiv gearbeitet wird?

**Comment by Phil-Rei** [comment]
Auch bei mir tritt das Problem auf

**Comment by GermanBluefox** [comment]
Please test 1.8.23

**Comment by dslraser** [comment]
Funktioniert wieder, wobei ich jetzt immer die Antwort bekomme: "automatischer Modus ist auf xyz Grad gestellt" (die Heizung läuft bei mir aber im manuellen Modus)

**Comment by GermanBluefox** [comment]
> Funktioniert wieder, wobei ich jetzt immer die Antwort bekomme: "automatischer Modus ist auf xyz Grad gestellt" (die Heizung läuft bei mir aber im manuellen Modus)

Das hat Amazon geändert und OHNE Auto modus wird die Antwort als ungültig abgelehnt...
