### ISSUE TITLE
Fehlermeldung Admin-Adapter

### ISSUE THREAD

**Issue by karebs** [ioBroker/ioBroker.iot#327]
In den Logs kommt nach einer Neuinstallation(Wechsel von Raspi 3B+ auf 4) und Einspielung der alten Sicherung über Backitup die Fehlermeldung: 

**State "admin.0.info.connection" has no existing object, this might lead to an error in future versions**

Es laufen alle Adapter. Der Zugriff auf meinen PC ist über Ethernet wieder getrennt. Darum auch eine Fehlermeldung der nicht mehr erreichbaren IP-Adresse. Der Raspi läuft mit WIFI.

Admin-Adapter: 5.1.25
Backitup: 2.1.17
JS-Controller: V14.17.6
NPM: 6.14.15
RaspiOs: Buster

Woran liegt es?

**Comment by Apollon77** [comment]
Is that not an Admin issue? I would expect that admin logs that and not iot??
