### ISSUE TITLE
Sprache und unbekannte Smart Geräte 

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.iot#33]
Hallo,

die Namen von Smart Geräten sind in verschiedenen Sprachen?
Auch sind da welche die ich nicht habe?

![screenshot 1762](https://user-images.githubusercontent.com/41079106/52441726-be695500-2b21-11e9-9a09-7cc2957c2315.png)

**Comment by Apollon77** [comment]
Bitte prüfe bei Die Enums. Es ist schonmal bericjhtet worden das die Nutzung des OpenHab Adapters hier einige DInge anlegt wie dann diese Effekte haben ...
