### ISSUE TITLE
Und wieder sind alle Geräte gelöscht ...

### ISSUE THREAD

**Issue by DerEmder** [ioBroker/ioBroker.iot#333]
Hallo,

zum wiederholten Mal ist meine Geräteliste gelöscht worden. Heute morgen funktionierte alles wunderbar, heute nachmittag war alles weg. Keine besonderen Vorkommnisse im Haus, ich war nicht mal anwesend. Beim letzten Mal dachte ich das ich selber es irgendwie (Fehlbedienung oder so) gelöscht hätte, aber diesmal stellt sich heraus, das es wohl ein fieser Bug im Adapter ist.

Im Log stand nichts erhellendes (siehe Log unten). Wie kann ich ein Backup der Einstellungen erzeugen und lokal speichern? Falls es diese Funktion nicht gibt - warum nicht?

Nun, ich werde jetzt alle Geräte wieder von Hand anlegen müssen. Bitte fixt diesen Bug.

Und ja - ich bezahle für den Zugang über iobroker.pro - es wäre daher sehr wünschenswert, wenn dieser Bug verschwinden würde und/oder wenigstens eine Backup/Restore Funktion für die Einstellungen eingebaut werden könnte.

So sah die Liste heute morgen aus - und um kurz vor drei Uhr war sie komplett leer:

![ioT](https://user-images.githubusercontent.com/91392202/135757075-fdc382d5-df4e-43a0-b8da-cdcbaf8644f3.jpg)

Log mit relevanten Einträgen:

```
2021-10-03 12:56:44.787 - info: mqtt.0 (805) Starting MQTT server on 0.0.0.0:1883
2021-10-03 12:56:44.427 - info: zigbee.0 (794) Starting Zigbee npm ...
2021-10-03 12:56:44.919 - error: iot.0 (812) iot.0 already running
2021-10-03 12:56:44.923 - warn: iot.0 (812) Terminated (ADAPTER_ALREADY_RUNNING): Without reason
2021-10-03 12:56:45.162 - info: zigbee.0 (794) Installed Version: iobroker.zigbee@1.6.3

2021-10-03 12:57:18.161 - info: iot.0 (1023) starting. Version 1.8.24 in /opt/iobroker/node_modules/iobroker.iot, node: v12.22.6, js-controller: 3.3.18
2021-10-03 12:57:18.261 - info: iot.0 (1023) Connecting with ********.iot.eu-west-1.amazonaws.com

2021-10-03 12:57:29.844 - error: iot.0 (1023) Error by device connection: "getaddrinfo ENOTFOUND ********.iot.eu-west-1.amazonaws.com"
2021-10-03 12:57:29.846 - error: iot.0 (1023) Error by device connection: "getaddrinfo ENOTFOUND ********.iot.eu-west-1.amazonaws.com"
2021-10-03 12:57:29.849 - info: iot.0 (1023) Connection changed: disconnect

2021-10-03 13:18:37.093 - info: iot.0 (1023) Connection changed: connect

2021-10-03 14:52:26.882 - warn: iot.0 (1023) [ALEXA] Unknown applianceId: Anlage
2021-10-03 14:52:48.913 - warn: iot.0 (1023) [ALEXA] Unknown applianceId: Anlage
2021-10-03 14:53:05.818 - warn: iot.0 (1023) [ALEXA] Unknown applianceId: Anlage

```
Mein System:

**System**: ioBroker 5.1.25
**Hostname**: Casper
**Platform**: Linux arm64 @  Raspberry Pi 4
**Memory**: 4 GB
**Node.js**: 12.22.6
**NPM**: 7.24.1
**Admin Adapter**: 5.1.25
**JS Script Engine**: 5.2.13
**Z-Wave Adapter**: 2.2.0
**Zigbee Adapter**: 1.6.3
**MQTT Adapter**: 2.4.0 (Broker)
**Z-Wave Controller**: USB ZME-UZB1
**Zigbee Controller**: CC2652P v3.x

**Comment by Apollon77** [comment]
Ok, Das kann so nicht wirklich sein.

Wenn die "Geräte in IOT" weg sind heisst das das die zugrundliegenden Objekte gelöscht wurden.

Daher: Über welchen Adapter reden wir der die States anbietet die Du hier hast?

**Comment by DerEmder** [comment]
> Ok, Das kann so nicht wirklich sein.

Es ist genau so, wie ich es beschrieben habe.

> Wenn die "Geräte in IOT" weg sind heisst das das die zugrundliegenden Objekte gelöscht wurden.

Die Objekte sind alle da. Alle Geräte (Z-Wave und Zigbee) sind vorhanden und haben sich nicht geändert. Warum sollte irgendwas die Objekte gelöscht haben? Die normale Automatisierung funktioniert ja uneingeschränkt weiter. Absolut keine Probleme. Lediglich die Sprachsteuerung über den ioT-Adapter funktioniert nicht mehr, weil ja eben die Liste der Geräte weg ist.

> Daher: Über welchen Adapter reden wir der die States anbietet die Du hier hast?

Das sind einmal der Z-Wave Adapter (Rolladen), der Zigbee Adpater fürs gemütliche Licht sowie einige selbstdefinierte Variablen, die dann in einem Script diverse Aktionen auslösen.

Beispiel:

Ich habe eine Variable unter var.0.Alexa.Abwaschlicht, die per ioT/Alexa geschaltet wird (true/false). Ein Script wird getriggered und schaltet dann eine Philips Zigbee Lampe ein bzw. setzt die Helligkeit.

Sämtliche Datenpunkte bzw. Objekte sind zu jedem Zeitpunkt vorhanden gewesen und haben auch keine wie auch immer geartete Fehlermeldung im Log erzeugt. 

Fakt ist auch, das ich über alexa.amazon.de momentan Probleme habe. Wenn ich ein Gerät entfernen möchte, erscheint eine nichtssagende Fehlermeldung "Es ist ein Fehler aufgetreten. Das Gerät wurde nicht entfernt.". Wenn ich es nochmal versuche, funktioniert es manchmal und das Gerät wird entfernt. Aber eben nicht immer.

Und vorweg - ja, ich habe bereits neu gestartet und doppelt überprüft.

**Comment by Apollon77** [comment]
Also die iot-Daten stehen nicht in einem Datenpunkt des Adapters selbst oder einer Konfig sondern werden direkt in den Objekten gespeichert für die "iot" Aktiviert wird. Daher - wenn die Dinge verschwinden müssen Sie aus den Objekten verschwunden sein. Dies geschiet nur manuell wenn man die Konfiguration editiert oder im Adapter zB zwischen "instanzspezifischer Konfig" und nicht hin- und herschaltet oder indem die Daten aus den Objekten gelöscht werden.

Du kannst Du gern von so einem (ja jetzt wieder) aktivierten Objekt mal im Admin die Objektdefinition ansehen (Stift icon im Admin im Expertenmodus). Da stehen in common.smartName die Details.

generell würde mich mehr vom Log interessieren weil allein das "iot already running" und der Fakt das scheinbar andere Adapter zum genannten zeitpunkt neu gestartet wurden ggf auf andere Probleme mit der Installation hinweisen.

Die Herausforderung ist alsl Herauszufinden was bei dir da passiert ist. Ich glaube nicht an einen Fehler im Adapter weil der "Serverseitige Teil" die Daten nur liesst ...

**Comment by DerEmder** [comment]
> Also die iot-Daten stehen nicht in einem Datenpunkt des Adapters selbst oder einer Konfig sondern werden direkt in den Objekten gespeichert für die "iot" Aktiviert wird. 

Okay, das macht ja Sinn. Beim Abwaschlicht steht z.B.:

```
"iot.0": {
        "smartName": {
          "de": "Abwaschlicht",
          "smartType": "SWITCH"
        }
      }

```

Nur warum sollte dies aus einem selbst-angelegten Datenpunkt (Variable bzw. Switch) wie von Geisterhand gelöscht worden sein - es war ja nicht einmal jemand hier. Wenn ich dich richtig verstanden habe, hätten ja alle(!) ioT-Einträge bei den Objekten gelöscht sein müssen sein. Waren bzw. sind sie ja aber nicht.


> generell würde mich mehr vom Log interessieren weil allein das "iot already running" und der Fakt das scheinbar andere Adapter zum genannten zeitpunkt neu gestartet wurden ggf auf andere Probleme mit der Installation hinweisen.

Kein Ding, am Ende ist das komplette Log. Irgendetwas um 12:57 ist auffallend - da gab es wohl ein Problem mit der Internet-Verbindung. Aber dann würde der Adapter ja nicht die gesamten iot-Einträge löschen.
` 
> Die Herausforderung ist alsl Herauszufinden was bei dir da passiert ist. Ich glaube nicht an einen Fehler im Adapter weil der "Serverseitige Teil" die Daten nur liesst ...

Möglich, ich weiß es nicht. Aber was auch immer die Ursache war - nur der iot-Adapter war betroffen.

Hier das Log:

**Comment by Apollon77** [comment]
Kein Log dabei ... am besten als File direkt in GitHub hochladen

**Comment by DerEmder** [comment]
Sorry, hat etwas länger gedauert - ich musste alle privaten Mail-Adressen etc. entfernen.

**Comment by DerEmder** [comment]
Und heute wieder ALLE Geräte gelöscht - ich habe nur ioBroker neu gestartet. Im Log nur:

`[ALEXA] Unknown applianceId: Putzlicht_Keller`

RAW Daten aktuell - vorher standen dort die ioT Einstellungen:

```
{
  "_id": "var.0.Licht.Putzlicht_KG",
  "type": "state",
  "common": {
    "name": "Putzlicht_KG",
    "role": "",
    "type": "boolean",
    "desc": "Manuell erzeugt",
    "read": true,
    "write": true,
    "def": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1634380625022
}
```

Es nervt nur noch ... ich kann den ganzen Mist jetzt nochmal eingeben. Wann endlich wird es eine Backup/Restore-Möglichkeit geben?

**Comment by DerEmder** [comment]
Das mit dem Log kann ich vergessen - ich habe es wohl gelöscht. Das aktuelle Log ist erst wieder ab 15:44 Uhr vorhanden. Sorry. Ich habe jetzt wieder alle iot-Einträge manuell eingetragen.

**Comment by Apollon77** [comment]
Logs sind gelöscht? Warum denn sowas? Logs stehen an sich unter /opt/iobroker/logs/... ehrlich alles weg?

Also ich denke ein Log brauchen wir schon um hier weiter zu kommen

**Comment by Apollon77** [comment]
> unter welchen Umständen, wenn überhaupt, würde der Adapter die iot-Zusätze bei einem oder mehreren Objekten löschen

Unter keinen die nicht mit einer User-Interaktion zu tun haben ...

**Comment by DerEmder** [comment]
Gerade ioBroker neu starten müssen. Danach, ich könnte echt kotzen, wieder alle Geräte weg. Das hier ist ein **BUG**, ein dicker, fetter **BUG** im System oder Adapter und keine simple Frage.

![Bildschirmfoto vom 2021-10-19 17-39-06](https://user-images.githubusercontent.com/91392202/137945931-1649b334-d011-4a4e-bf7f-9ca7f901637f.png)

Diesmal habe ich ein vollständiges Log, hier angehängt. Bitte finde die Ursache.

[iot.log.zip](https://github.com/ioBroker/ioBroker.iot/files/7374812/iot.log.zip)

**Comment by DerEmder** [comment]
> Also seeehr interessant ... Fakt ist das nicht alle "custom" Daten gelöscht werden weil zB iNfluxDB problemlog erhalten ist.

problemlog? :)

Die Einträge für influxDB sind tatsächlich noch vorhanden. Lediglich die iot-Einträge sind verschwunden.

> Und es betrifft nicht nur die eigenen Datenpunkte in "var.*" wie DU oben schreibst?

Da ist korrekt. Es sind auch direkte Hardware-Datenpunkte (z.B. Brightness) von Zigbee und Z-Wave Geräten betroffen.
 
> Ist iot mit einem Pro Key genutzt? Bitte am besten mit die E-Mail mal im Forum oder so nennen.

Ja, ein Pro-Key, habe erst vor ein paar Tagen verlängert. Die Mailadresse ist iobroker(at)media-ds.de

**Comment by DerEmder** [comment]
> Man müsste jetzt mal schauen wann es genau passiert. Also ist es der restart vom gesamten iobroker? 

Ja, per ssh angemeldet und ein dezentes _sudo shutdown -h now_ bzw. _sudo reboot_ abgesetzt.

> einzige bist scheinbar wo das passiert kann ich das bei mir leider nicht nachstellen (also ich habe bissl experimentiert und kann es nicht nachstellen)

Nein, der einzige bin ich nicht - aber die die ich kenne haben jetzt openHAB oder HomeAssistant am Laufen. Und meine Frau macht mich auch wahnsinnig, weil sie nicht mehr per Alexa steuern kann. Ist schon eine wichtige Komponente geworden ;)

**Comment by DerEmder** [comment]
Eh ich es vergesse, so sah die Liste vorher aus:

![Bildschirmfoto vom 2021-09-27 13-29-44](https://user-images.githubusercontent.com/91392202/137981414-45b5e5bb-54de-4fc3-9f44-0d188e70da2f.png)

**Comment by DerEmder** [comment]
So, ich habe zum morgigen Testen drei Geräte eingetragen:

![Bildschirmfoto vom 2021-10-19 22-03-20](https://user-images.githubusercontent.com/91392202/137982767-d2142e21-d879-440d-994b-13d632cd26b0.png)

Hier die RAW-Daten der drei Objekte:

```
{
  "_id": "var.0.Multimedia.Toggle_Ambilight",
  "type": "state",
  "common": {
    "name": "Toggle_Ambilight",
    "role": "",
    "type": "boolean",
    "desc": "Manuell erzeugt",
    "read": true,
    "write": true,
    "def": false,
    "custom": {
      "iot.0": {
        "smartName": {
          "de": "Ambilight",
          "smartType": "SWITCH"
        }
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1634673772172
}


{
  "_id": "var.0.Alexa.Anlage",
  "type": "state",
  "common": {
    "name": "Anlage",
    "role": "switch",
    "type": "boolean",
    "read": true,
    "write": true,
    "desc": "Manuell erzeugt",
    "def": false,
    "custom": {
      "iot.0": {
        "smartName": {
          "de": "Anlage",
          "smartType": "SWITCH"
        }
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1634673642290
}


{
  "type": "state",
  "common": {
    "name": "Brightness",
    "type": "number",
    "unit": "",
    "read": true,
    "write": true,
    "role": "level.dimmer",
    "min": 0,
    "max": 100,
    "custom": {
      "iot.0": {
        "smartName": {
          "de": "Küchenlicht",
          "smartType": "LIGHT"
        }
      }
    }
  },
  "native": {},
  "_id": "zigbee.0.0017880106e2a81f.brightness",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1634673721200
}
```

Mal sehen, wie es morgen läuft ....

**Comment by DerEmder** [comment]
Ich dachte mir das schon - diesmal bleiben die drei Geräte drin, egal was ich mache. Ich probier es mal weiter. Ich werde wohl alle Geräte wieder eingeben und dann versuchen, den Fehler zu reproduzieren. I'll keep you posted :)
