### ISSUE TITLE
HTTP get von außerhalb des eigenen Netzwerkes

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.iot#336]
über  iot services ist es möglich,  daten von außerhalb des lokalen Netzes (z.b. vom Handy mit tasker) an den iobroker zu senden.

Kann man das auch umgekehrt einführen - also ein get State/states von außerhalb !

kam von hier: https://forum.iobroker.net/post/685306

**Comment by liv-in-sky** [comment]
yes

**Comment by Apollon77** [comment]
assistant you already have. you need remote ... bad is that assistent is included there too :-(
