### ISSUE TITLE
Alexa erkennt Homematic-Thermostat nicht richtig

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.iot#348]
**Beschreibung**  
Ich betreibe Heizungsthermostate an einer CCU3, die am ioBroker angebunden sind. Die Heizungsthermostate werden von Alexa aber irgendwie nicht richtig erkannt.

Bei dem Kommando _"Stelle Heizung Büro auf 19 Grad"_ antwortet Alexa _"Ich weiß nicht, was schief gelaufen ist."_ Die Temperatur wird aber richtig eingestellt.
Die Abfrage _"Wie ist die Temperatur bei Heizung Büro?"_ funktioniert einwandfrei.
Auf der Alexa-App am Handy wird beim Aufruf des Gerätes "Heizung Büro" auch nicht das Thermostat mit Regelungsmöglichkeit angezeigt, sondern gleich die Einstellungen des Gerätes.
![image](https://user-images.githubusercontent.com/39200469/140607509-a8b22847-e2c0-453b-bd10-fda7507b798f.png)

Konfiguration im iot.0
![image](https://user-images.githubusercontent.com/39200469/140607518-68dd769e-6148-4661-8d74-990d29e2fe6d.png)

**Versionen**  
- Cloud IoT-Verbindung: 1.8.22
- HomeMatic ReGaHSS 3.0.31
- HomeMatic RPC: 1.14.45
- JS-Controller version: 3.3.18
- Node version: v12.22.6
- Operating system: Docker / BUANET

**Ergänzungen**  
See https://forum.iobroker.net/topic/48927/alexa-erkennt-homematic-thermostat-nicht-richtig
Bin mir unsicher ob das Problem beim Homematic Adapter oder im IOT zu suchen ist, die Logs geben keine Info her.

**Comment by Apollon77** [comment]
Der Fehler ist in aktueller Version bereits gefixt

**Comment by RK62** [comment]
Danke für den Hinweis. Ab 1.8.23 aus der Beta ist die fehlerhafte Ansage behoben. 
In der ALEXA-App auf dem Handy wird immer noch kein Thermostat mit Regelungsmöglichkeit sondern direkt der Einstellungsbildschirm angezeigt. Neues Erkennen der Alexa-Geräte brachte da auch keine Abhilfe. Kann ich aber gut mit leben, weil ich eh meistens via Sprache schalte.

**Comment by Apollon77** [comment]
Das it der App hängt daran das wir den SKill auf v3 updaten müssen... das dauert noch ein bissl

**Comment by RK62** [comment]
Kein Problem, vielen Dank für eure Arbeit!
