### ISSUE TITLE
Geräte werden nicht für alle zugeordneten Räume erstellt

### ISSUE THREAD

**Issue by MikeHellracer** [ioBroker/ioBroker.iot#350]
Hi,
Wenn ich mehrere Räume zuweise wird nur ein Gerät angelegt.
Ziel ist es dem Rolladen 2 Räume (OG, SZ) zuzuordnen und dann 2 Geräte "Rolladen im SZ" und "Rolladen im OG" zu bekommen. 
Hier legt iot aber nur ein Gerät "Rolladen im Obergeschoss" an. Die vorher vorhandenen Rolladen pro Raum werden entfernt.

Wenn ich einem Gerät mehrere Funktionen zuordne werden auch mehrere Geräte in Alexa eingerichtet. z.B "Dekolicht im Bad" und "Beleuchtung im Bad" So kann ich nur Dekolicht oder die komplette Beleuchtung im Bad schalten.
Ziel ist es Dekolicht oder komplette Beleuchtung im Obergeschoss zu schalten

**Comment by Apollon77** [comment]
Wie genau kann ein Gerät in mehreren Räumen sein?

**Comment by MikeHellracer** [comment]
> Wie genau kann ein Gerät in mehreren Räumen sein?

**Comment by MikeHellracer** [comment]
Hi, habe das gerade mal versucht.
Räume (WZ, EZ) erstellt, Geräte (Rolladen) zugewiesen
Räume in Gruppe (EG) aufgenommen und 
Alexa zugeordnet
-> Alexa erkennt leider pro Raum je ein Gerät im EG
Und sie kann leider nur an und aus. Hoch/runter und ganz hoch/runter kennt sie nicht. 
Also 'Rolladen aus' gibt '2 Geräte gefunden' zurück. 
Und alles leider sehr aufwendig für ein ganzes Haus. 
Schicker wäre, wenn das er Adapter übernimmt. 
So wie er das für mehrere Funktionen auch macht. Zb. 2 Funktionen zugeordnet ergibt 2 Geräte 'Beleuchtung im WZ an' und 'Licht im WZ an' 
Wenn ich 2 "Räume" (EG & WZ) zuordne wird leider nur 1 Gerät für den 1. Raum (EG)  in der Aufzählung angelegt.

**Comment by SaberRiderStarsheriff** [comment]
Ich habe den gleichen usecase wie @MikeHellracer. Ein Rollladen soll im Wohnzimmer seperat angesteuert werden, es soll aber auch möglich sein über den fiktiven Raum "Erdgeschoss" alle Rollläden, unter anderem auch den im Wohnzimmer anzusteuern. Aktuell habe ich dies händisch über ein Gruppe gelöst, in dem jeder Rollladen mit Komma separiert den zusätzlichen Namen Rolladen Erdgeschoss bekommen hat. Gibt es eine elegantere Art dies zu lösen? Besten Dank für die Hilfe
