### ISSUE TITLE
HmIP Heizkörperthermostat & Alexa

### ISSUE THREAD

**Issue by Humpelpumpel** [ioBroker/ioBroker.iot#351]
Hallo zusammen, ich erhalte bei einem Temperaturwechsel mit Alexa eine sehr seltsame Antwort.

Gerät: HmIP Heizkörperthermostat
Datenpunkt: 1.SET_POINT_TEMPERATURE (Rolle: level.temperature)
Sage ich jetzt: "Alexa, Büro auf 22 Grad" erhalte ich als Antwort: "Automatischer Modus ist auf 22 Grad gestellt."
Erwarten würde ich eher sowas wie "Büro ist auf 22 Grad gestellt."

LG

**Comment by Apollon77** [comment]
geht leider gerade nicht anders ...
