### ISSUE TITLE
Status der Geräte in der Alexa App

### ISSUE THREAD

**Issue by IchBinSmart** [ioBroker/ioBroker.iot#352]
Hallo, 

erstmal vielen Dank für die ganze Entwicklungsarbeit, iobroker funktioniert gut und stabil. 

Schade ist, dass man über die alexa app die Geräte zwar steuern kann, der aktuelle Status (Lampe ist an / aus) aber nicht angezeigt wird. Dadurch ist man gezwungen eine VIS zu programmieren/zusammenzuklicken. Ich würde aber lieber die Alexa App nutzen, weil ich da nichts warten muss. Ich habe die remote Lizenz gebucht (nutze nichts davon, aber weil ich es fair finde iobroker zu unterstützen). Es wäre toll, wenn zumindest dieses Modell ermöglichen würde den Status der Geräte in der Alexa App darzustellen. 

Vielleicht mache ich aber auch was falsch und das geht schon lange?!

Vielen Dank, 
 Rainer

**Comment by Apollon77** [comment]
Will be possible with #29 , so duplicate
