### ISSUE TITLE
Google: iobroker is not accessible

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.iot#353]
Since 2 weeks or so I get the error message from Google Home that iobroker is not accessible ("iobroker kann nicht erreicht werden"). It worked without issues before. I do have a valid pro account for assistance.
There are no error messages from iot in the logs.

**Comment by Apollon77** [comment]
Did you tried to link it again?

**Comment by cburghardt** [comment]
What I have tried is to request new certificates but that did not change anything.
I have also tried to delete a device and create it from scratch. I have also added an additional device - that one doesn’t show up in Google at all.
In the debug log I don’t see any error messages.

**Comment by cburghardt** [comment]
I reconnected the account in Google Home, that has fixed it
