### ISSUE TITLE
beim öffnen wird nichts angezeigt

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.iot#360]
Hallo
wenn ich auf die Instance iot klicke, öffnet sich nur ein leeres Instancefenster
![image](https://user-images.githubusercontent.com/38419234/144839010-0dfe46d0-f572-4951-8953-597743990167.png)
 als fehlermeldung im Debug zeigt er folgendes an:
 `
iot.0 | 2021-12-06 12:28:55.229 | error | No cloud credentials found. Please get one on https://iobroker.pro
-- | -- | -- | --
iot.0 | 2021-12-06 12:28:55.228 | error | Please write your login only in lowercase!
iot.0 | 2021-12-06 12:28:55.201 | info | starting. Version 1.8.24 in /opt/iobroker/node_modules/iobroker.iot, node: v14.18.1, js-controller: 3.3.20
`

das ganze im Chrome, Firefox
das "Please write your login only in lowercase!" würd ich ja gerne ändern, wenn ich da ran kommen würde
BrowserCache hab ich schon geleert

der Adapter selbst ist auf dem aktuellen stand (1.8.24)

_iobroker
Plattform linux
Betriebssystem linux
Architektur x64
CPUs 4
Geschwindigkeit 2500 MHz
Modell Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
RAM 5.86 GB
System-Betriebszeit 6 T. 02:55:56
Node.js v14.18.1 (Es gibt eine neuere Version: v14.18.2)
NPM 6.14.15
Datenträgergröße 23.5 GB
freier Festplattenspeicher 15.64 GB
Anzahl der Adapter 364
Betriebszeit 6 T. 02:55:21
Aktive Instanzen 34
location /opt/iobroker/
Hostname iobroker_

**Comment by Apollon77** [comment]
Bitte mal in der JavaScript Konsole vom Browser schauen ob ein Fehler ist?

**Comment by Apollon77** [comment]
closedm no answer
