### ISSUE TITLE
Bitte Typen Thermometer und Kontakt-Sensor hinzufügen

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.iot#365]
Ich nehme mal an, dass diese o.g. Typen auch erst mit dem Skill V3 hinzugefügt werden können.
Hat sich da in den letzten drei Jahren etwas getan?  (Issue #29 stammt vom Januar 2019)

Danke für die Mühen, vG
Achim

**Comment by Apollon77** [comment]
Ja, einen plan haben wir ... rest folgt ... daher hier duplicate

**Comment by Apollon77** [comment]
(ist immer noch die Zeit)
