### ISSUE TITLE
Gerät wurde nicht hinzugefügt

### ISSUE THREAD

**Issue by Narolakk** [ioBroker/ioBroker.iot#368]
Wenn ich ein Datenpunkt hinzufügen will, kommt eine Fehlermeldung: Gerät wurde nicht hinzugefügt.
Habe schon ewig kein Alexa Gerät mehr hinzugefügt, damals ging es noch.

 - Adapter version: v1.9.16
 - JS-Controller version: 3.3.22
 - Node version: v14.18.2
 - Operating system: linux

Objektdaten:
{
  "common": {
    "name": "SchreibtischAuto_",
    "desc": "Manuell erzeugt",
    "role": "state",
    "type": "boolean",
    "read": true,
    "write": true,
    "def": false,
    "smartName": {
      "de": "SchreibtischAuto"
    }
  },
  "type": "state",
  "_id": "MeineGeräte.0.Virtuelle_Schalter.SchreibtischAuto",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1641500866078
}

**Comment by Apollon77** [comment]
Dem objekt fehlt der native teil, das ist der grund

**Comment by Narolakk** [comment]
Und was nun? Damals hat es ganz einfach funktioniert ohne die JSON zu ändern, kann das nicht automatisch passieren?

Was muss geändert werden?

**Comment by Narolakk** [comment]
Die Zeile ""native": {}," muss eingefügt werden, nicht sehr Nutzerfreundlich

**Comment by Knallochse** [comment]
Ich bin heute auch über dieses Problem gestolpert. Liegt hier ein Fehler auf Userseite vor? (falsch angelegtes Objekt?)

**Comment by Apollon77** [comment]
Ja und nein. Admin 5 hat beim manuellen Objekte anlegen einen Bug das native nicht angelegt wird ... das muss man ergänzen bis es in Admin gefixt ist

**Comment by Knallochse** [comment]
Dank für die Erklärung. Macht euch keinen Stress

**Comment by threeleg** [comment]
Ich hab das gleiche Problem. In meinen Objektdaten ist "native" aber vorhanden.
Auch "smartName" und "custom" die ja scheinbar vom iot Adapter erstellt werden sind erzeugt worden.
Trotzdem kommt immer die Fehlermeldung beim manuellem hinzufügen im iot Adapter:
"Device tradfri.0.G-131074.state was not added"

Meine Objektdaten:

{
  "_id": "tradfri.0.G-131074.state",
  "type": "state",
  "common": {
    "type": "boolean",
    "read": true,
    "write": true,
    "name": "on/off",
    "role": "switch",
    "custom": {
      "iot.0": {
        "smartName": {
          "en": "on/off"
        }
      }
    },
    "smartName": {
      "ghTraits": [
        "action.devices.traits.OnOff"
      ],
      "ghType": "action.devices.types.LIGHT"
    }
  },
  "native": {
    "path": "onOff"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1643103527970
}

Wenn ich hingegen die automatische Suche nach Geräten nutze, kann ich diese automatisch aufgelisteten Objekte nicht manuell löschen. Als wenn ich generell keine Berechtigung hätte in der Liste der Geräte überhaupt irgendwas zu editieren.

**Comment by threeleg** [comment]
Ein Update von mir:
Nachdem ich den iot Adapter gelöscht habe und aus einer andern ioBroker Installation ein backup eingespielt habe kann ich wieder Geräte hinzufügen.

Die Objektdaten sehen jetzt so aus:
{
  "_id": "tradfri.0.G-131074.state",
  "type": "state",
  "common": {
    "type": "boolean",
    "read": true,
    "write": true,
    "name": "on/off",
    "role": "switch",
    "smartName": {
      "en": "Tischlampe",
      "ghConv2GH": "",
      "ghConv2iob": "",
      "ghType": "action.devices.types.LIGHT",
      "ghTraits": [
        "action.devices.traits.OnOff"
      ],
      "ghAttributes": "{\n            \"commandOnlyOnOff\": false\n          }"
    }
  },
  "native": {
    "path": "onOff"
  },
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1643108876331
}

Falls es irgendwem hilft...
