### ISSUE TITLE
Stable version younger than latest version?

### ISSUE THREAD

**Issue by hsteinme** [ioBroker/ioBroker.iot#369]
In ioBroker the latest version is stated as 1.8.13 whereas the stable version is stated as 1.8.24. Please check.

**Comment by Apollon77** [comment]
The versions shpuld be like in the badges shown here https://github.com/ioBroker/ioBroker.iot#iobroker-iot-adapter .  ALso in my system latest ist shown as 1.8.25 ... plese update repository (the reload button on "Adapters") ... When switching repos it can happen that you need to do that manually once

**Comment by TheHaf** [comment]
If I may add to this issue thread, the proposed reload button doesn't work for me. Also the version number 1.8.25 in the badge doesn't seem to be listed in the releases section, even though it's tagged and listed in the tags section.

**Comment by Apollon77** [comment]
Releasdes section might be misleading if a automatic release fails.

relevant is https://github.com/ioBroker/ioBroker.iot#1825-2021-11-18

**Comment by TheHaf** [comment]
Ok, thank you for clarifying that, I will refer to the [Changelog](https://github.com/ioBroker/ioBroker.iot#changelog) section from now on.
