### ISSUE TITLE
[GHOME] Device Unknown

### ISSUE THREAD

**Issue by Schany79** [ioBroker/ioBroker.iot#37]
Hallo,
ich bekomme seit einigen Wochen im Log für alle Möglichen Geräte den Fehler:

iot.0 | 2019-03-06 07:13:56.243 | error | [GHOME] device sonoff.0.Sonoff_Bild_Diner.POWER is unknown to google home
iot.0 | 2019-03-06 07:12:19.662 | error | [GHOME] device sonoff.0.Sonoff_Terrasse.POWER is unknown to google home

Wie bekomme ich den weg? Ich habe im Internet leider keine Lösung dazu gefunden.

Danke.
LG,
Sascha

**Comment by GermanBluefox** [comment]
Welche IOT version hast du?

**Comment by daniel-lo** [comment]
Sorry .. hab das seit einer Weile auch :-(
iot 1.11.7
