### ISSUE TITLE
Alexa überträgt in den Datenpunkt bei 20% einen Wert von 20,8%

### ISSUE THREAD

**Issue by AlfredSch** [ioBroker/ioBroker.iot#370]
Hallo iobrokler,
brauche eure Hilfe.

Habe shelly dimmer im IOT Adapter per switch und brigthness hinterlegt.
an/aus geht leider kein dimmen, weil alexa überträgt in den Datenpunkt bei 20% einen Wert von 20,8% und dadurch dimmt er nicht.
Wenn ich manuell 20 eintrage in den Datenpunkt dimmt er wie er soll.

Wie kann ich das korrigieren?
Über ein Script vielleicht?

Eingebunden ist er über shelly adapter 5 und per mqqt.

**Comment by Apollon77** [comment]
Die Frage war doch schonmal wo ... Wie genau ist das Objekt definiert vommShelly adapter? Was sind dort Minimum und Maximum? An sich wird mit Min/Max der wert errechnet basierend auf den 100% ... heisst als ich würde erwarten das ggf im Shelly Objekt diese beiden Werte falsch sind

**Comment by Apollon77** [comment]
Closed, no answer
