### ISSUE TITLE
Geräte lassen sich nicht teilweise nicht schalten mit Alexa über IOT

### ISSUE THREAD

**Issue by Henny4184** [ioBroker/ioBroker.iot#372]
Moin, habe es gestern festgestellt das meine Alexa einige Sprachbefehle zum steuern von Shellys nicht mehr nimmt. Antwort: Gerät oder Gruppe gibt es nicht. Einige Geräte kann ich so steuernaber einige gar nicht mehr da kommt die Ansage. ODer ... unterstützt das nicht. 
Kann da einer weiter helfen? In Facebook gibt es auch noch weitere Nutzer die das Problem seit gestern haben. Neustart Adapter und Login neu alles kommt zu keiner Lösung.

node 12.22.9, NPM: 6.14.15, Admin: 5.2.3, Alexa 3.11.2, Shelly 4.0.7. Js: 3.3.22

Geräte sind im IOT angelegt. Es sind auch nicht alle meiner Shelly Geräte nur ein paar. andere gehen. Vielleicht gibt es ja eine Lösung. Ging sonst immer.  Shelly sklill nicht aktiv.

**Comment by Apollon77** [comment]
Hast du mal neu gesucht in der Alexa App?

**Comment by Henny4184** [comment]
Ja auch schon. Gelöscht auch schon.

**Comment by Apollon77** [comment]
Ok, also nach dem löschen wurden Sie neu gefunden aber gehen nicht?

**Comment by Henny4184** [comment]
Ja die Übeltäter gelöscht und wieder gesucht. Nichts

**Comment by m0rph2k** [comment]
Hi

Ich muss auch sagen das es seit gestern nicht mehr alles geht, ich habe einen Free Account und einer der Bezahlt ist, momentan macht nur der Free Account Probleme

**Comment by m0rph2k** [comment]
Hab jetzt mal das Device direkt aus IOT adapter gelöscht und neu angelegt und neu gesucht, steuerung über sprache funktioniert nicht, immer der gleiche Fehler das die Gruppe oder Gerät nicht gefunden wird, über die Alexa app selbst funktioniert alles bzw wenn ich die objekte direkt ändere im Iobroker :/

**Comment by mbausm** [comment]
Hat Jemand weiterhin die Probleme? Bei mir lassen sich auch verschiedene Geräte über den iot Adapter + iot Skill nicht mehr schalten. Über die Alexa App lassen sich die Geräte weiterhin steuern. Im ioBroker Log ist auch nichts zu sehen. Sobald ich die Geräte einer Alexa Gruppe oder Routine zuordne, lassen diese sich ebenfalls steuern. Nur eben einzeln nicht mehr. Es betrifft scheinbar nur die Geräte, welchen keinen Typ zugewiesen sind (z.B. Switch, Light).

**Comment by Apollon77** [comment]
Dann meldet das mal an Amazon. Also die Alexa App und Sprache nutzen wenn dann die exakt gleichen Interfaces zu ioBroker über iot Adapter

**Comment by mbausm** [comment]
Du sagst es. Sieht nach einem Amazon Problem aus. Ich bin gerade dabei meine Geräte aufzuräumen, dann weise ich in diesem Zuge auch die passenden Typen zu. Danach lassen sich die Geräte auch wieder über Sprachbefehl steuern.

**Comment by mbausm** [comment]
Hatte gerade Kontakt mit dem Amazon Service. Problem ist bekannt und es wird daran gearbeitet.

**Comment by m0rph2k** [comment]
> Hatte gerade Kontakt mit dem Amazon Service. Problem ist bekannt und es wird daran gearbeitet.

Danke für die Info, das mit den Typen kann ich bei mir so nicht bestätigen, bei mir funktionieren teilweise Routinen auch nicht mehr, mal abwarten,

**Comment by Henny4184** [comment]
Moin. Hatte bzw habe das Problem auch, habe nun Routinen gemacht damit läuft es erst einmal.

**Comment by m0rph2k** [comment]
Es dürfte doch funktionieren wenn man im Iobroker den Type zb auf Swtich stellt, ich musste allerdings zuerst nochmal nach Geräten suchen

**Comment by m0rph2k** [comment]
@mbausm Gibt es dazu was neues von Amazon ?

**Comment by mbausm** [comment]
Guten Abend,
nein, leider habe ich bis jetzt keine Informationen von dem Amazon Technik Support erhalten. Sobald ich eine Rückmeldung bekomme, werde ich Bescheid geben. Seitdem ich den Geräten einen passenden Typ zugewiesen (...und neu im Skill gesucht) habe, funktionieren diese wieder. Daher kann ich auch nicht sagen ob das Problem mittlerweile behoben wurde.

**Comment by Napfelsaft** [comment]
Hallo zusammen,
ich bin davon auch betroffen. Bei mir funktioniert kein Homematic Rolladenaktor mehr direkt. In der Gruppe gehen alle noch und alles kam aus dem Nichts. Keine Änderung am IObroker in den letzten 4 Wochen und Anfang letzter Woche fing das Problem an.

Das interessante:
Wenn man in der Alexa App den Rolladen von "Schlafzimmerrollo" in Schlafzimmer Rollo", "Banane" oder irgendwas umbenennt dann funktioniert er bei mir wieder. Also alles andere als der originale Name gehen bei mir. Wenn man dann zurück zum original switcht -> gleicher Fehler.

Löschen, neu anlegen + neu suchen sowie IOT Skill deaktivieren und wieder aktivieren haben bei mir auch nicht gehofen.

Kontakt zu Amazon hatte ich schon und ich wurde gebeten den Skillentwickler zu kontaktieren. Bin froh den Post gefunden zu haben, somit spiele ich den Ball gleich mal wieder zurück.

**Comment by m0rph2k** [comment]
> 

Willkommen im Club :D, hast du im IOT adapter einen Typen zugeordnet, wenn nicht probier das mal aus, danach starte die Suche und versuche es nochmal

**Comment by m0rph2k** [comment]
> Hallo zusammen, ich bin davon auch betroffen. Bei mir funktioniert kein Homematic Rolladenaktor mehr direkt. In der Gruppe gehen alle noch und alles kam aus dem Nichts. Keine Änderung am IObroker in den letzten 4 Wochen und Anfang letzter Woche fing das Problem an.
> 
> Das interessante: Wenn man in der Alexa App den Rolladen von "Schlafzimmerrollo" in Schlafzimmer Rollo", "Banane" oder irgendwas umbenennt dann funktioniert er bei mir wieder. Also alles andere als der originale Name gehen bei mir. Wenn man dann zurück zum original switcht -> gleicher Fehler.
> 
> Löschen, neu anlegen + neu suchen sowie IOT Skill deaktivieren und wieder aktivieren haben bei mir auch nicht gehofen.
> 
> Kontakt zu Amazon hatte ich schon und ich wurde gebeten den Skillentwickler zu kontaktieren. Bin froh den Post gefunden zu haben, somit spiele ich den Ball gleich mal wieder zurück.



> Hallo zusammen, ich bin davon auch betroffen. Bei mir funktioniert kein Homematic Rolladenaktor mehr direkt. In der Gruppe gehen alle noch und alles kam aus dem Nichts. Keine Änderung am IObroker in den letzten 4 Wochen und Anfang letzter Woche fing das Problem an.
> 
> Das interessante: Wenn man in der Alexa App den Rolladen von "Schlafzimmerrollo" in Schlafzimmer Rollo", "Banane" oder irgendwas umbenennt dann funktioniert er bei mir wieder. Also alles andere als der originale Name gehen bei mir. Wenn man dann zurück zum original switcht -> gleicher Fehler.
> 
> Löschen, neu anlegen + neu suchen sowie IOT Skill deaktivieren und wieder aktivieren haben bei mir auch nicht gehofen.
> 
> Kontakt zu Amazon hatte ich schon und ich wurde gebeten den Skillentwickler zu kontaktieren. Bin froh den Post gefunden zu haben, somit spiele ich den Ball gleich mal wieder zurück.

Willkommen im Club :D, hast du im IOT adapter einen Typen zugeordnet, wenn nicht probier das mal aus, danach starte die Suche und versuche es nochmal

**Comment by Napfelsaft** [comment]
> > Hallo zusammen, ich bin davon auch betroffen. Bei mir funktioniert kein Homematic Rolladenaktor mehr direkt. In der Gruppe gehen alle noch und alles kam aus dem Nichts. Keine Änderung am IObroker in den letzten 4 Wochen und Anfang letzter Woche fing das Problem an.
> > Das interessante: Wenn man in der Alexa App den Rolladen von "Schlafzimmerrollo" in Schlafzimmer Rollo", "Banane" oder irgendwas umbenennt dann funktioniert er bei mir wieder. Also alles andere als der originale Name gehen bei mir. Wenn man dann zurück zum original switcht -> gleicher Fehler.
> > Löschen, neu anlegen + neu suchen sowie IOT Skill deaktivieren und wieder aktivieren haben bei mir auch nicht gehofen.
> > Kontakt zu Amazon hatte ich schon und ich wurde gebeten den Skillentwickler zu kontaktieren. Bin froh den Post gefunden zu haben, somit spiele ich den Ball gleich mal wieder zurück.
> 
> > Hallo zusammen, ich bin davon auch betroffen. Bei mir funktioniert kein Homematic Rolladenaktor mehr direkt. In der Gruppe gehen alle noch und alles kam aus dem Nichts. Keine Änderung am IObroker in den letzten 4 Wochen und Anfang letzter Woche fing das Problem an.
> > Das interessante: Wenn man in der Alexa App den Rolladen von "Schlafzimmerrollo" in Schlafzimmer Rollo", "Banane" oder irgendwas umbenennt dann funktioniert er bei mir wieder. Also alles andere als der originale Name gehen bei mir. Wenn man dann zurück zum original switcht -> gleicher Fehler.
> > Löschen, neu anlegen + neu suchen sowie IOT Skill deaktivieren und wieder aktivieren haben bei mir auch nicht gehofen.
> > Kontakt zu Amazon hatte ich schon und ich wurde gebeten den Skillentwickler zu kontaktieren. Bin froh den Post gefunden zu haben, somit spiele ich den Ball gleich mal wieder zurück.
> 
> Willkommen im Club :D, hast du im IOT adapter einen Typen zugeordnet, wenn nicht probier das mal aus, danach starte die Suche und versuche es nochmal

Danke dir! Die waren wirklich ohne Typ. Mit Typ laufen sie auch alle wieder.

Nur erklärt es nicht warum umbennenen in der App funktioniert, außer die Alexa App macht Ähnliches in dem Moment.

**Comment by m0rph2k** [comment]
Bei mir funktionieren auch weiterhin geräte ohne Type, nur manche nicht, keine Ahnung warum.

**Comment by Henny4184** [comment]
Ja ich bin gespannt was wird . Auf alle Fälle kann es ja nicht von heute auf morgen an der Bezeichnung liegen ob da was steht wenn es vorher auch ging .

**Comment by mbausm** [comment]
Hallo Zusammen,
ich habe bisher keine Rückmeldung von Amazon erhalten. Allerdings scheint es wieder zu funktionieren. Ich hatte noch einige virtuelle Geräte ohne Typ-Zuweisung die zeitweise nicht mehr funktionierten. Diese lassen sich mittlerweile allerdings wieder mit Sprachbefehl schalten.
Viele Grüße!
