### ISSUE TITLE
Invalid URL Pro Key

### ISSUE THREAD

**Issue by duczz** [ioBroker/ioBroker.iot#373]
Hallo,

ich nutze den Adapter als Free User und bekomme immer folgenden Fehler, woran kann das liegen?

![image](https://user-images.githubusercontent.com/25475385/151651977-158065c3-33c7-4337-9d45-2eda7b2cd645.png)

**Comment by GermanBluefox** [comment]
Das sollte jetzt besser sein. Gibt es das Problem noch?

**Comment by duczz** [comment]
Hab's nach 2 Tagen dann selber gelöst. Ob's nun besser ist kann ich deswegen leider nicht sagen.
