### ISSUE TITLE
1.9.3  Error in main: TypeError: Cannot read property 'certificates' of undefined

### ISSUE THREAD

**Issue by HolgerGERMANY** [ioBroker/ioBroker.iot#383]
**Describe the bug**  
After upgrading to 1.9.3 I was not able to get GREEN ON this Adapter. iot.0.certs where not filled with data.

Log File Reporter: `Error in main: TypeError: Cannot read property 'certificates' of undefined`

Downgrading to 1.8.24 solved the problem right away. iot.0.certs where filled.

**Expected behavior**  
Loading the certificates from iobroker.pro site.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <1.9.3>
 -  <
//usr/bin/nodejs
/usr/bin/node
/usr/bin/npm
v14.19.0
v14.19.0
6.14.16
nodejs:
  Installiert:           14.19.0-deb-1nodesource1
  Installationskandidat: 14.19.0-deb-1nodesource1
  Versionstabelle:
 *** 14.19.0-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_14.x bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     12.22.5~dfsg-2~11u1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
>
 
**Additional context**  
<

Used repository: beta
--
  | hash changed or no sources cached => force download of new sources
  | update done
  | Adapter    "admin"         : 5.2.3    , installed 5.2.3
  | Adapter    "alexa2"        : 3.12.0   , installed 3.12.0
  | Adapter    "backitup"      : 2.2.4    , installed 2.2.3 [Updateable]
  | Adapter    "bydhvs"        : 1.3.0    , installed 1.3.0
  | Adapter    "cloud"         : 4.1.0    , installed 4.1.0
  | Adapter    "devices"       : 1.0.9    , installed 1.0.9
  | Adapter    "discovery"     : 2.7.5    , installed 2.7.3 [Updateable]
  | Adapter    "fb-checkpresence": 1.1.13  , installed 1.1.13
  | Adapter    "flot"          : 1.10.7   , installed 1.10.7
  | Adapter    "fritzdect"     : 2.2.3    , installed 2.2.3
  | Adapter    "habpanel"      : 0.4.3    , installed 0.4.3
  | Adapter    "ham"           : 4.0.2    , installed 4.0.2
  | Adapter    "history"       : 1.10.5   , installed 1.9.14 [Updateable]
  | Adapter    "hm-rega"       : 3.0.35   , installed 3.0.35
  | Adapter    "hm-rpc"        : 1.15.2   , installed 1.15.0 [Updateable]
  | Adapter    "hs100"         : 2.0.7    , installed 2.0.7
  | Adapter    "ical"          : 1.11.6   , installed 1.11.6
  | Adapter    "icons-mfd-png" : 1.0.2    , installed 1.0.2
  | Adapter    "influxdb"      : 2.4.0    , installed 2.4.0
  | Adapter    "iot"           : 1.9.3    , installed 1.9.3
  | Adapter    "javascript"    : 5.2.21   , installed 5.2.21
  | Controller "js-controller" : 3.3.22   , installed 3.3.22
  | Adapter    "mqtt"          : 2.4.1    , installed 2.4.0 [Updateable]
  | Adapter    "node-red"      : 2.4.1    , installed 2.4.1
  | Adapter    "parser"        : 1.0.7    , installed 1.0.7
  | Adapter    "ping"          : 1.5.2    , installed 1.5.0 [Updateable]
  | Adapter    "ring"          : 1.2.8    , installed 1.2.8
  | Adapter    "shelly"        : 5.1.2    , installed 5.1.2
  | Adapter    "simple-api"    : 2.6.2    , installed 2.6.2
  | Adapter    "socketio"      : 4.1.0    , installed 3.1.5 [Updateable]
  | Adapter    "systeminfo"    : 0.3.1    , installed 0.3.1
  | Adapter    "telegram"      : 1.11.1   , installed 1.11.1
  | Adapter    "text2command"  : 2.1.1    , installed 2.1.1
  | Adapter    "vis"           : 1.4.8    , installed 1.4.8
  | Adapter    "vis-jqui-mfd"  : 1.0.12   , installed 1.0.12
  | Adapter    "vis-weather"   : 2.5.5    , installed 2.5.5
  | Adapter    "web"           : 4.1.1    , installed 3.4.16 [Updateable]
  | Adapter    "whatsapp-cmb"  : 0.1.6    , installed 0.1.6
  | Adapter    "yeelight-2"    : 1.1.2    , installed 1.1.2
  | Adapter    "zigbee"        : 1.6.14   , installed 1.6.14

>

**Comment by Diginix** [comment]
1.9.3 with iot license works for me. But I was updating from 1.9.1 to 1.9.3.

**Comment by Pocky2507** [comment]
iot.0 | 2022-02-06 13:53:48.402 | info | (645376) Connection changed: connect
-- | -- | -- | --
iot.0 | 2022-02-06 13:53:48.012 | warn | (645376) Cannot update api-secret: undefined

**Comment by Hausmeister486** [comment]
Today... IOT Adapter not working since:
2022-02-06 17:09:55.665 | error | Error in main: TypeError: Cannot read property 'certificates' of undefined

**Comment by GermanBluefox** [comment]
Please check 1.9.4

**Comment by Hausmeister486** [comment]
> Please check 1.9.4
1.9.4 installed and working, just had to disable/enable Alexa skill.
Thanks
