### ISSUE TITLE
Update to 1.9.3 ends in a restart loop 

### ISSUE THREAD

**Issue by JF62** [ioBroker/ioBroker.iot#385]
**Describe the bug**  
Update from 1.8.25 to 1.9.3 gnerates following errors and a restart loop of iot adapter:

`<html>
<body>

host.iobroker | 2022-02-07 23:43:16.700 | warn | Do not restart adapter system.adapter.iot.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2022-02-07 23:43:16.700 | info | Restart adapter system.adapter.iot.0 because enabled
host.iobroker | 2022-02-07 23:43:16.699 | error | instance system.adapter.iot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
iot.0 | 2022-02-07 23:43:16.284 | info | Connection lost
iot.0 | 2022-02-07 23:43:16.282 | info | Connection changed: disconnect
iot.0 | 2022-02-07 23:43:15.993 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
iot.0 | 2022-02-07 23:43:15.991 | info | terminating
iot.0 | 2022-02-07 23:43:15.991 | info | terminating
iot.0 | 2022-02-07 23:43:15.437 | error | Request failed with status code 401
iot.0 | 2022-02-07 23:43:15.436 | error | Error: Request failed with status code 401 at createError (/opt/iobroker/node_modules/iobroker.iot/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/iobroker.iot/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.iot/node_modules/axios/lib/adapters/http.js:312:11) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
iot.0 | 2022-02-07 23:43:15.435 | error | unhandled promise rejection: Request failed with status code 401
iot.0 | 2022-02-07 23:43:15.434 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
iot.0 | 2022-02-07 23:43:15.311 | info | Connection changed: connect
iot.0 | 2022-02-07 23:43:14.937 | warn | Cannot update api-secret: undefined
iot.0 | 2022-02-07 23:43:14.875 | info | Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
iot.0 | 2022-02-07 23:43:14.781 | info | starting. Version 1.9.3 in /opt/iobroker/node_modules/iobroker.iot, node: v14.19.0, js-controller: 4.0.4
iot.0 | 2022-02-07 23:43:14.454 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
host.iobroker | 2022-02-07 23:43:12.050 | info | instance system.adapter.iot.0 started with pid 28325

</body>
</html>`

**To Reproduce**  
1. Just update working 1.8.25
2. See error log

**Versions:**  
 - Adapter version: 1.9.3
 - JS-Controller version: 4.0.4
 - Node version: 14.19.0
 - Operating system: raspian buster

**Additional context**  
Restore of 1.8.25 all work fine again

**Comment by GermanBluefox** [comment]
401 shows that the Problem is with invalid Username or password

**Comment by JF62** [comment]
But without change 1.8.25 works?

**Comment by JF62** [comment]
Close
Complete remove of adapter, and reinsllation fixed it
