### ISSUE TITLE
Gerät knx.0.Licht_und_Steckdosen.EG.Licht_Schalten wurde nicht hinzugefügt

### ISSUE THREAD

**Issue by vonCartman** [ioBroker/ioBroker.iot#387]
wie schon in mehreren Themen hier, habe ich es auch diesen problem.

Allerdings andere DP lassen sich einwandfrei hinzufügen und steuern, aber es gibt diese Ausnahme.
Selbst der Tip mit "native{}" hat nicht funktioniert.
hier auch mein DP:

Für euren Hilfen bedanke ich mich im Voraus.

{
  "_id": "knx.0.Licht_und_Steckdosen.EG.EG_Küche_1_Licht_Schalten",
  "type": "state",
  "common": {
    "name": "EG Küche 1 Licht Schalten",
    "type": "boolean",
    "role": "indicator",
    "read": false,
    "write": false,
    "max": true,
    "min": false,
    "smartName": {
      "de": "EG Küche 1 Licht Schalten"
    }
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "2/2/6",
    "addressRefId": "P-0442-0_GA-152",
    "statusGARefId": "",
    "actGARefId": "",
    "update": true,
    "objRef": "O-0_R-10000",
    "devName": "M-0083_A-0008-21-C628",
    "devInst": "P-0442-0_DI-61",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1645221779599
}

**Comment by Apollon77** [comment]
Das ist ein "indicator" der laut infos weder gelesen noch geschrieben werden darf ... was sollte iot damit tun?

**Comment by Apollon77** [comment]
Bitte ggf beim Adapter ein Issue anlegen das das Objekt sinnvoll wird

**Comment by vonCartman** [comment]
Ich habe mittlerweile herausgefunden. 

Das Problem lag na "role" und "write".
Role habe ich als indicator, habe ich auf Value geändert und die weite  von false auf True.

Dann funktioniert alles.
