### ISSUE TITLE
Keine keys unter "Services und IFTTT" in Beta Version 1.9.5 und 1.9.7

### ISSUE THREAD

**Issue by arkinson9** [ioBroker/ioBroker.iot#388]
In den letzten Beta Versionen konnten unter "Services und IFTTT" für die Dienste kein keys erzeugt werden.
Nach downgrade auf Stable Version 1.8.24 wurden die keys wieder erzeugt.

Screenshots und Lösungsversuche siehe hier:

[https://forum.iobroker.net/topic/52654/iot-adapter-keine-keys-unter-services-und-ifttt-gel%C3%B6st/14](url)

**Versions:**  
 - Adapter version: in folgenden Versionen getestet: 1.9.5, 1.9.7
 - JS-Controller version: 4.0.15
 - Node version: v12.22.1
 - Operating system: Linux

**Comment by arkinson9** [comment]
Kurzes update:
Habe aufgrund veralteter Ubuntu Version mein Betriebssystem neu aufgesetzt und iobroker per Restore vom alten System neu eingespielt. Node Verson ist jetzt aktuell: 14.19.0.

Den iot-Adapter habe ich anschließend von Version 1.8.24 auf 1.9.7 geupdated. Die vorhandenen keys wurden jetzt beibehalten.
Webhooks funktionieren.

**Comment by Apollon77** [comment]
Also issue solved?
