### ISSUE TITLE
V0.3.1 nicht möglich Smart Geräte anzulegen

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.iot#39]
Hallo, es ist bei mir nicht mehr möglich Smart Geräte anzulegen. Probiere es seit 2 Tagen ohne Erfolg. Woran kann das liegen?

**Comment by Stormbringer11** [comment]
Hab den Fehler auch. Probier mal nach dem hinzufügen von einem Neuen Objekt den Reiter auf "Einstellungen" kurz zu wechseln und dann wieder zurück auf "Smart Geräte", dann erscheint das Eingabefeld mit Namen. Hast du den Fehler schon auf GitHub gemeldet?

**Comment by BigDi** [comment]
Ich hatte gerade auch das gleiche Problem. Bei mir fehlte die Rolle bei einem Wert.

**Comment by zakuma666** [comment]
Bei mir funktioniert es immer so das ich eins hinzufüge es kommt dann zwar keine Bestätigung aber wenn ich den Adapter Neustarte geht es dann ist das Gerät da
