### ISSUE TITLE
Programmatically add/reconnect Alexa device to iobroker.iot

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.iot#394]
From time to time rpc.1 adapter looses all devices for any reason. All settings in sql.0 and iot.0 are lost for rpc.1 devices.
For sql there is an "enableHistory" command, that can be used to configure all HmiP devices programmatically for use with sql adapter.

My wish is to have the same option for iot, so I do not have to manually add all devices to iot for interchange with Alexa again.

Maybe this is already possible, but I haven't found related information, yet.

I love this adapter! Very well done! Thank you!!

-jayvee

**Comment by Apollon77** [comment]
Please go to the hm-rpc configuration and tick the setting to NOT delete devices wghen reported by CCU ... this seem to be an issue still in CCU firmware for HMIP mainly
