### ISSUE TITLE
IoT-Adapter Alexa Geräte Grenze/Limit nicht eindeutig

### ISSUE THREAD

**Issue by Eldarion85** [ioBroker/ioBroker.iot#397]
Hallo,
die wichtigsten Infos vorab, da der Post etwas länger werden könnte:

- Die Grenze von 300 Alexa-Geräten aus der Beschreibung von ioBroker.iot ist "falsch"
- Die JSON der Sprachbefehle die bei der Suche an Alexa übertragen wird darf nicht größer als 128kB sein
- Amazon hat auf ihrer Seite keine Grenze für Geräte

Ich hatte das Problem, dass plötzlich die Gerätesuche von Alexa nicht mehr funktioniert hat und keine neuen Geräte hinzugefügt wurden. Die Grenze bei mir liegt genau bei 247 Sprachbefehlen in der IoT-Instanz. Lege ich 248 an, geht es nicht mehr. Da ich 8 Echo Dots habe konnte ich also in Alexa genau 255 Geräte finden. Sobald es eins mehr war, ging es nicht mehr und Alexa hat nur noch die 8 Echo Dots gefunden. Wer sich etwas auskennt, dem wäre vllt. die Zahl 255 auch verdächtig vorgekommen, da es die höchste Zahl ist, die man mit einem Byte (8 Bit) darstellen kann. Außerdem war für mich die Grenze bei 247 Sprachbefehlen in der IoT-Instanz nicht wirklich logisch. Zumal in der Beschreibung steht, dass das Limit für ioBroker.iot bei 300 Alexa-Geräten liegt.

Also habe ich viele E-Mail mit der IT-Abteilung von Alexa geschrieben. Der Support war super, aber am Ende kam folgende Antwort:

> also ich habe bei den IT-Kollegen mehrfach nachgehackt und diese können keine Obergrenze an Geräten / Sprachbefehle bestätigen.
> Ich habe dies wirklich mehrfach hinterfragt und den Kollegen Ihre Aussagen aus unserem Chat weitergeleitet aber Sie bleiben bei Ihrer Antwort:
> "Von Amazon Seite her gibt es keine Begrenzung".
> Ich hoffe das die IT-Kollegen Ihnen mit dieser Antwort helfen konnten.

Also habe mich an den Support von ioBroker gewandt und dort nachgefragt. Da habe ich dann die Info bekommen, dass ich den Log auf Debug stellen und prüfen soll, was drin steht wenn ich bei Alexa die Gerätesuche starte.

Am Anfang steht immer das:
![Response](https://user-images.githubusercontent.com/90176159/158762302-75b290c3-bc82-42cd-8f24-14c2cb9f8c79.png)

Darunter kommt die JSON, die meine Sprachobjekte beschreibt. Wenn es funktioniert ist die JSON auch gleichzeitig der letzte Eintrag. In meinem Fall also immer dann, wenn ich maximal 247 Sprachbefehle anlege. Sobald es mehr sind kommt unter der JSON folgendes:
![Disconnect](https://user-images.githubusercontent.com/90176159/158762373-0990d286-ce6d-4fc2-a45c-e8e1e36a7604.png)

Lösche ich einen Sprachbefehl raus, geht es wieder. Also unterm Strich ist die Grenze eben nicht fest bei 300 sondern wird durch die JSON, die die Objekte beschreibt, begrenzt. Ob es bei 300 nochmal eine zusätzliche fixe Grenze gibt kann ich nicht sagen.

Meine Frage ist, warum ist die Grenze so niedrig und was ist die beste Möglichkeit mehr Sprachbefehle zu nutzen? Funktioniert es mit einer zweiten Instanz? Kann ich mich dort mit dem gleichen [ioBroker.pro](http://iobroker.pro/) Account anmelden? Wie definiere ich welches Objekt in welcher IoT-Instanz gelistet werden soll?

Besten Dank vorab!

**Comment by Apollon77** [comment]
@Eldarion85 my last info was that it is more a "timeout issue" aka "time needed to collect all these details nd amazon not waiting that long",but with your log ithis cloearly can not be the case :-) So, very good intel. We need to look into this

**Comment by Apollon77** [comment]
@Eldarion85 hast Du mal ein volles Log was debug zeigt wie es angefragt ist und wie danach die verbindung abbricht? Ich will das mal zeitlich schauen

**Comment by Apollon77** [comment]
hhmm ... this could it really be ... "The payload for every publish request can be no larger than 128 KB. AWS IoT Core rejects publish and connect requests larger than this size." ... https://github.com/aws/aws-iot-device-sdk-python/issues/21

So it is s limitation of the aws-iot-device-sdk which is used by the iot adapter to communicate with the AWS servcie that handles all the iot stuff ...

**Comment by Apollon77** [comment]
To support more we would need to implement a "chunking" of responses from iot adapter to the iobroekr aws services and implement an option there to put the chunks together ...

**Comment by Eldarion85** [comment]
Hallo,
erstmal vielen Dank für die schnelle Antwort.
Mir war schon aufgefallen, dass ich die Screenshots dummerweise aus zwei unterschiedlichen Logs genommen hatte und die Zeiten nicht passen.

Ich habe aktuell 283 Geräte angelegt.
![Geraete](https://user-images.githubusercontent.com/90176159/158788342-751b33dc-7a83-4b11-a8e0-25390be93e2e.png)

Dadurch ist meine JSON jetzt 143kb groß. Ich habe dann nach und nach Geräte gelöscht und bei 247 Geräten ist die Datei noch 128kb groß und es geht wieder.

Hier ein kompletter Log:
![2](https://user-images.githubusercontent.com/90176159/158788948-9bd70e7b-d9e4-4362-abc7-4c4b8768cd6e.png)
![1](https://user-images.githubusercontent.com/90176159/158788960-06984bf5-f9e3-4a0c-8ec3-ae91bce1ea3e.png)

Wenn es geht sieht das Log genauso aus, lediglich die letzten 5 Einträge (ab "offline") fehlen natürlich und die JSON wird mit 128kb angezeigt.

**Comment by Eldarion85** [comment]
Natürlich wäre es mit einer Instanz am schönsten. Aber du kannst mir sicher sagen ob es die Möglichkeit gibt das mit einer zweiten Instanz zu realisieren? Wenn ja, kann ich mich dort mit dem gleichen ioBroker.pro Account anmelden und wie definiere ich welches Objekt in welcher IoT-Instanz gelistet werden soll?
Dort füge ich nämlich aktuell lediglich folgende Eigenschaften im Objekt hinzu:
```
    "smartName": {
      "de": "Licht Feuerstelle im Garten, Licht Feuerstelle",
      "smartType": "LIGHT"
    }
  },
  "native": {},
```
So würden beide Instanzen wahrscheinlich alle Objekte anzeigen.

**Comment by Diginix** [comment]
@Eldarion85 Eine 2 Instanz funktioniert, aber ob der Alexa Skill dann die Geräte von beiden abruft, k.a. Ich nutze eine 2 Instanz mit einem zweiten Amazon Konto und somit getrennten Logins für den Skill usw.
Im JSON des Objektes sieht das dann so aus:
`"common": {
  "type": "number",
  "role": "value.temperature",
  "read": true,
  "write": false,
  "unit": "°C",
  "custom": {
     "iot.1": {
      "smartName": {
        "de": "Name",
        "smartType": "THERMOSTAT"
      }
    }
  },
  "smartName": {
    "de": "Name",
    "smartType": "THERMOSTAT"
  }
}`

**Comment by Eldarion85** [comment]
@Diginix vielen Dank für die Info. Dann weiß ich auf jeden Fall schon mal, wie ich die Objekte den unterschiedlichen Instanzen zuordnen kann.
Bevor ich jetzt aber alles anpacke, warte ich mal ab. Vielleicht gibt es ja doch die Möglichkeit das Ganze grundlegend zu verbessern und so auch größere Anfragen als 128kb zu übertragen.
Falls nicht, hat ja evtl. schon mal jemand versucht eine zweite Instanz mit dem gleichen Konto zu verknüpfen. Wenn sich in den nächsten Tagen niemand meldet, werde ich es selbst versuchen.

**Comment by Apollon77** [comment]
Ich hab auch mit Bluefixox geschrieben, eine Option wäre die daten zu compressen ... könnte vllt sogar generell bissl performanter werden. Damit würde sich auf jeden Fall mal das Limit erhöhen ... müsste man mal schauen auf welche größe es damit zusammendampft und wie damit das Limit erhöht werden würde :-)

**Comment by Apollon77** [comment]
ich glaube zwei instanzen mit dem gleichen Amazon account geht nicht weil man bei Amazon einen Skill pro Account nur einmal istallieren kann

**Comment by Eldarion85** [comment]
Das geht ja echt schnell bei euch mit der Problemverfolgung :D! Dafür erstmal vielen Dank!
Das hört sich ja schonmal sehr vielversprechend an. Mich wundert, dass das bisher noch niemand gemeldet hat. Ich bin ja wahrscheinlich nicht der erste der an diese Grenze gestoßen ist. Wenn ich fertig bin werde ich irgendwo bei 340 Geräten landen. Aber wenn ich das richtig verstanden habe war die 300 in der Anleitung nie ein festes Limit sondern nur eine grobe Einschätzung :D?! Dann könnte ich ja irgendwann, wenn ihr euch das näher angeschaut und implementiert habt, wahrscheinlich auch über diese Grenze raus gehen.

**Comment by Apollon77** [comment]
Please try 1.11.0

**Comment by Eldarion85** [comment]
Wow! Das ging schnell :D!

1. Update installiert
2. alle Geräte und Szenen bei Alexa gelöscht
3. neue Gerätesuche gestartet
4. 268 Geräte, 15 Szenen und 8 Echo Dots gefunden

Es läuft also perfekt! Wie weit sich die Grenze jetzt erhöht hat könnt ihr wahrscheinlich nicht abschätzen, oder? Ca. 60 Geräte werde ich noch einbinden, falls ich dabei nochmal auf Probleme stoße, melde ich mich wieder.
Vielen Dank für die mega schnelle Umsetzung!

**Comment by Apollon77** [comment]
> Wie weit sich die Grenze jetzt erhöht hat könnt ihr wahrscheinlich nicht abschätzen, oder?

Fürchte nicht :-) Try it

Am Ende wird der String jetzt gepackt "zip" was es um einiges verkleinern sollte ... danach base64 encoded was wieder ca 1/3 drauf schlägt. Aber wenn du magst  können wirs mal rausfinden wo wir jetzt stehen:

Installiere mal iot von GitHub neu  (hab gerade logging eingebaut). Dann Debug Logging aktivieren und ein discovery machen.

Da müsste eine Logzeile zu finden sein ala

> [REMOTE] Content was packed from ${msg.length} bytes to ${packed.length} bytes

Sag mal an :-)

**Comment by Ilovegym66** [comment]
euch beiden vielen Dank! Auf einmal werden mir auch viel mehr Geraete angezeigt.. hab ja auch 300 irgendwas drin.. ! Hatte das aber nur sekundar auf dem Schirm mit low prio. Zeit zum debuggen hab ich leider im Moment nicht.. :-(

**Comment by Eldarion85** [comment]
Puuh... jetzt ist richtig Luft nach oben!
![Size](https://user-images.githubusercontent.com/90176159/158965522-cf703fe4-aa85-4161-9ee9-8f135ce633bb.png)

Also die 128kb werde ich jetzt mit meinem Projekt jedenfalls nicht mehr erreichen :D.

**Comment by Apollon77** [comment]
WTF ist das geil :-)

Also wäre ne Schätzung so bei 300 -> 3000 devices *gg*

Na komm .... Challenge accepted? ;-))

**Comment by Eldarion85** [comment]
Also wenn die 11256 bytes schon base64 sind, sind die 3000 jetzt locker drin. Aber selbst wenn da noch 1/3 drauf kommt, landet man so bei 2500. Ich denke das ist jetzt ne Grenze, die ihren Meister so schnell nicht findet :D.

Obwohl... wenn ich jedem meiner 300 Objekte 10 Sprachbefehle (Smart Name) verpasse, würde es vllt. klappen. Wobei man schon kreativ sein muss um sich für die gleiche Lampe 10 unterschiedliche Ansagen auszudenken :).

Unter Strich, perfekte Umsetzung!!!

**Comment by Apollon77** [comment]
:-) Jupp ist schon base64 encoded ... von daher ... Danke an dich für den schubs in die richtige Richtung ... haben da schon mehrfach länger dran gesucht :-)

**Comment by Eldarion85** [comment]
Sehr gerne... und ein ganz kleines bisschen Eigeninteresse war ja auch dabei :P.

**Comment by Eldarion85** [comment]
Formsache:
Den Punkt unter Limits mit "Everything has a limits, so the Amazon Alexa too. Alexa can support only up to 300 devices." könntest du bei Gelegenheit noch ändern :).

**Comment by GermanBluefox** [comment]
Es muss jetzt gehen, größer  als 127kb Objekte zu senden

**Comment by Eldarion85** [comment]
Moin,
wir haben letztes Jahr festgestellt, dass es bei Amazon keine Grenze für die Anzahl der Geräte gibt und ihr hattet das angepasst, sodass über 3.000 Geräte möglich waren.

> * Die Grenze von 300 Alexa-Geräten aus der Beschreibung von ioBroker.iot ist "falsch"
> * Die JSON der Sprachbefehle die bei der Suche an Alexa übertragen wird darf nicht größer als 128kB sein
> * Amazon hat auf ihrer Seite keine Grenze für Geräte

Jetzt ist das plötzlich wieder begrenzt. Leider ist die Lizenz bzw. der Adapter danach für große Häuser mit vielen Geräten nicht mehr nutzbar. Ich liege bei 365 Geräte was immer funktioniert hatte. Wieso wurde das wieder verschlechtert. Ich hatte gestern nochmal mit Amazon gesprochen, die haben mir gesagt, dass es von ihrer Seite keine Einschränkung bzw. Gründe für ein Limit gibt.

**Comment by Apollon77** [comment]
Definiere verschlechtert? Durch was wurde es ausgelöst? Ist es plötzlich passiert? Gab es ein Update vom Adapter? Seit wann? Alle Details helfen

**Comment by Eldarion85** [comment]
Sorry, wenn es einfach nicht mehr funktionieren würde, hätte ich die Frage anders formuliert :).
Es kommt ein PopUp mit der Info, dass nur noch 300 Geräte möglich sind. Die Meldung gab es früher nicht und muss mit einem der letzten Updates gekommen sein. Mir ist es jetzt erst aufgefallen, da ich neue Geräte hinzufügen wollte und es nicht mehr geht.
Wegen der Meldung war ich davon ausgegangen, dass es bewusst gemacht wurde.

![300](https://github.com/ioBroker/ioBroker.iot/assets/90176159/2594d1a7-d25b-4716-a1a8-4bcf0e10dfed)

**Comment by Eldarion85** [comment]
Kann mir jemand sagen wie sich diese Grenze aktuell verhält? Welche Geräte werden denn nicht mehr an Alexa übergeben? Die zuletzt angelegten oder die am Ende der Liste? Ich habe immer noch über 360 Geräte in Alexa, da sie wahrscheinlich nicht gelöscht werden, wenn sie bereits existieren. Aktuell habe ich aber noch nicht rausfinden können, welche nicht mehr funktionieren. Ich kann lediglich keine neuen übertragen.

Gibt es dazu schon was Neues? Warum wurde diese Grenze wieder eingeführt, obwohl es laut Amazon keine Begrenzung gibt und ihr das vor einem Jahr so mega schnell durch das Komprimieren der Daten sogar verzehnfacht habt?

**Comment by Eldarion85** [comment]
> Definiere verschlechtert? Durch was wurde es ausgelöst? Ist es plötzlich passiert? Gab es ein Update vom Adapter? Seit wann? Alle Details helfen

@Apollon77 gibt es dazu schon eine Information? Warum habt ihr das erst erhöht und dann doch wieder begrenzt? Bleibt das jetzt so und was sind die Hintergründe der Begrenzung?

**Comment by Apollon77** [comment]
Irgendwo in einem Issue hatte ich es erklärt ...

Es ist so das Bluefox einen Service von AWS nutzt damit der Adapter mit dem AWS Cloud Dienst reden kann und dieser Dienst hat ein Message Size Limit was wir mal festgestellt haben als es Probleme gab das ab einer gewissen Geräteanzahl nichts mehr ging. Daher haben wir die Anzahl der Geräte so limitiert wie es grob zu der Messagesize passt. Daher das Limit.
Von daher ist es korrekt das Amazo im Discovery ggf mehr kann, aber ein anderer AWS Service limitiert uns hier gerade.

Das anzupassen heisst die generelle Kommunikation des Adapters mit dem Service anzupassen. Das muss man sich genau ansehen.
