### ISSUE TITLE
[0.3.1] Smart Devices list is missing several devices

### ISSUE THREAD

**Issue by adx-git** [ioBroker/ioBroker.iot#40]
As in the topic, I am missing several devices in the smart devices list.
I allow lights and heating to show up in the selected rooms.
But for some rooms not all lights show up and the heating does not show up in other rooms.
All devices are provided by Homematic, but I could not find a logic behind the messing devices or any other relation, so it is hard to provide further information.
Any idea how I could help to debug?

**Comment by GermanBluefox** [comment]
Homematic IP? 
If yes, HMID states are missing some important roles. And this must be fixed.

**Comment by adx-git** [comment]
It is a CCU1, 
Most, but not all, missing devices are CUxD devices.

Btw., looking into "Aufzählung", all devices can be found.
