### ISSUE TITLE
iot Adapter always opens amazon.de login page

### ISSUE THREAD

**Issue by GreatSUN** [ioBroker/ioBroker.iot#418]
**Describe the bug**  
Opening the base Settings (Options) page always results in opening an amazon.de page with login fields

**To Reproduce**  
1. Deploy a blank iot Adapter
2. Enter iobroker pro user/pw
3. Save and Close
4. Start the Instance
5. go onto settings page (all done with Google Chrome 101.0.4951.54 64bit Windows

**Expected behavior**  
No window opens

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: 1.11.4
 - JS-Controller version: 4.0.23
 - Node version: v16.14.2
 - Operating system: Debian 11.3

**Additional context**  
None.

**Comment by Apollon77** [comment]
Please provide a screenshot

**Comment by GreatSUN** [comment]
LOL... Yesterday I could have provided you with screenshots all over... always 2 pages of Amazon were opened. Tried everything (restart iot, reinstall iot, restart iob, etc.) nothing helped.
Today... no issue anymore. Looks like some browser/cache/js combination hooked up and caused that issue.

Sorry for any inconvenience this has brought to you guys.
