### ISSUE TITLE
"Alexa reagiert gerade nicht" - geht aber alles!

### ISSUE THREAD

**Issue by DanielHD80** [ioBroker/ioBroker.iot#42]
Ich habe ein komisches Phänomen festgestellt: Ich habe meine Klimasteuerung über den iot-Adapter mit Alexa verbunden. Hierzu habe ich ein Smartgerät namens Klimaanlage angelegt, welches die beiden Datenpunkte für Power und Temperatur beinhaltet. 

Wenn ich nun sage: "Alexa, stelle Klimaanlage auf 18 Grad", kommt die Ansage "Klimaanlage reagiert gerade nicht". Verstellt wird jedoch sowohl mein Datenpunkt (level.temperature) als auch die Klimaanlage an sich (gesteuert über einen Broadlink). Die Skripte stimmen also in meinen Augen alle! Beim ein- und ausschalten kommt der Fehler nicht, hier kommt einfach der "Bestätigungs-Dong" (Datenpunnkt ist switch.power). 

In den Smartgeräten haben beide Datenpunkte den Typ "Thermostat". Ich bekomme als Funktion angezeigt: an aus ° ↑ ↓ ±?

Theoretisch müsste es doch auch möglich sein, nach der aktuell eingestellten Temperatur zu fragen? Wenn ich sage "Alexa wie ist die Temperatur von Klimaanlage?" kommt "Klimaanlage unterstützt das nicht". Deute ich den Befehl "?" falsch? Der Wert müsste für den Adapter ja problemlos aus dem Datenpunkt, den er ja auch beschreibt, auszulesen sein...

**Comment by Apollon77** [comment]
Das liegt daran das der iobroker skill bei Thermostaten noch nicht alles unterstützt. Dann kommt es  zu solchen komischen Effekten. 
Abhilft bedeutet Migration der api auf die neue „v3“. Ist geplant aber noch nicht fertig.

**Comment by DanielHD80** [comment]
Dann ist ja alles gut bei mir uns ich muss nur noch ein wenig warten... :)

**Comment by Apollon77** [comment]
duplicate #27
