### ISSUE TITLE
Find new devices with Alexa does not work

### ISSUE THREAD

**Issue by buzz0r** [ioBroker/ioBroker.iot#420]
If I add a new device in the Alexa tab and start searching for new devices in the Alexa-App / on the Alexa webpage or via speech command, I always get the message "no new devices found".
The only workaround to get the new devices imported to Alexa is to deactivate the skill inside the Alexa-App and reactivating it afterwards. This involves logging in to iobroker.pro again.
Restarting the instance or the whole iobroker does net help either.

My environment:
PLATTFORM: DOCKER
RAM: 62.6 GB
NODE.JS: V14.19.3
NPM: V6.14.17
IOT Adapter: v1.11.4
iobroker.pro: license active

Is this the official and only way to get fresh / new devices into Alexa?

Sorry for the somewhat stupid question! :)
I am unsure if this is a bug or a human error.

**Comment by Apollon77** [comment]
I think you are not in the right adapter ... Alexa2 is there to control your Alexa devices and NOT to bring your iobroker devices into Alexa worls.

Please check out issues from "iot" adapter and also check forum for the Cloud/iot FAQ before you open an issue there
