### ISSUE TITLE
Commands will not be recognized correctly (reordered + missing content)

### ISSUE THREAD

**Issue by RkcCorian** [ioBroker/ioBroker.iot#442]
**Describe the bug**  

**To Reproduce**  
**Say: "Alexa sage ioBroker er soll Flur Wohnzimmer und Küche saugen"**

**Expected behavior**  
**I receive the sentence and can it analye. But in ```iot.0.smart.lastCommand``` is the result ```controlDevice wohnzimmer flur er soll```. I expect a sentence that I can parse like in ```alexa2.0.Echo-Devices.G000RA0583660F1U.Commands.textCommand```where is the result```sage i.O.broker Reinige Flur Küche und Kinderzimmer```**

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 **- Adapter version: 1.11.4**
 **- JS-Controller version: 4.0.23**
 **- Node version: v16.15.1**
 **- Operating system: docker, linux, Synology NAS**

**Additional context**  
**I wish a solution where I can pass the original (w/o sage i.o.broker) command without missing and exchanged content to text2command so that I have a chance.**
Background: I would like to have a native Alexa experience. I thought aber using the alexa2 text Command but then I have to sync two adapters and the response is not that what I would likt to have

**Comment by Apollon77** [comment]
The detection in custom skill is not that straight forward possible and thats why there will never be "a sentence like you expect". This is simply technicalla not possible (and yes I would also love to have that, but Amazon does not allow that :-(

But yes it seems that "sauge" bzw "reinige" is missing as verb :-(

**Comment by RkcCorian** [comment]
@Apollon77 : Thx for your fast response!
- I would like to use "reinige" / "reinigen" (for "saugen"+"wischen") as well as "sauge" / "saugen" and "wische" / "wischen" as different commmands. Once this will be fixed please take those in consideration :-)
- Would this fix that text is missing when "und" is used?
- What I do not understand... alexa2 adapter has the "correct" sentence. Therefore I do not understand why we cannot get this as well with iot adapter. But maybe I do not have enough details...

**Comment by Apollon77** [comment]
1.) I think we need to enhance these words in the list of words to recognize
2.) No idea what you mean?
3.) Alexa2 is getting te text from the "voice history of the Alexa mobile App/your amazon account" - the custom skill needs to define rules and such to "parse" the spoken words and proces it ... in this case it is not the same as the original text. These are two completely different stories

**Comment by RkcCorian** [comment]
According...
1.) Do you know how fast this might come?
2.) I say and would expect something with "Flur Wohnzimmer UND Küche" but I receive "wohnzimmer flur er soll", where "Küche is completely missing.
3.) Might be. But for parsing it should have also the original text that is parsed?!

**Comment by RkcCorian** [comment]
Two (bad) results / examples...
![image](https://user-images.githubusercontent.com/79741077/174487993-13bdaece-c072-44a2-91f6-c76a80d4295e.png)

**Comment by Apollon77** [comment]
1.) No idea ... I need to have time to dig into this and you are the first reporting that so far
3.) No, Skills do work completely different then you think.I would love to get a text then I would simply pass it over to the iobroker side without any other magic stuff :-)
4.) Would this work once you add the missing verbs? ... Maybe ... I need to understand the issue first ...

**Comment by RkcCorian** [comment]
@Apollon77 : Ich schau gerade nochmal. Der Text wird bei einer erkannten Anfrage korrekt wiedergegeben. Sobald er einen Befehl erkennt geht Text verloren. Im Folgenden der Vergleich, was Alexa erkannt hat und was der ioBroker Custom Skill erkannt hat...

Anfrage:
![image](https://user-images.githubusercontent.com/79741077/175559376-c660d4f0-74dc-4cb5-a560-03016adf1b80.png)


Erkannter Befehl:
![image](https://user-images.githubusercontent.com/79741077/175559299-e51208df-096c-4242-bf98-c7676d7d246b.png)

**Comment by Apollon77** [comment]
@RkcCorian participate here for the beginning :-)
https://forum.iobroker.net/topic/56304/wie-spricht-man-mit-iobroker-iobroker-custom-skill-2022
