### ISSUE TITLE
URL-Schlüssel für Dienste nicht identisch!?

### ISSUE THREAD

**Issue by JWSchumacher** [ioBroker/ioBroker.iot#452]
Hi all,
die Diagnoseseite von iobroker.pro zeigt mit den Fehler:
Dieser Schlüssel muss mit dem URL-Schlüssel identisch sein. Versuchen Sie, IoT-Anmeldeinformationen erneut zu erstellen.
Die Anmeldeinformationen habe ich neu erstellt, aber die Fehlermeldung bleibt. Screenshot anbei.
Was kann ich machen um das Problem zu beseitigen?
![Screenshot1](https://user-images.githubusercontent.com/71602076/179387175-c83676f4-3ad0-460a-8856-da9e96c462bf.png)

**Comment by Apollon77** [comment]
it dies noch relevant? Falls ja bitte E-Mail an info@iobroker.net mit den Informationen zum Account und so stellen
