### ISSUE TITLE
Status von Steckdose/Licht etc. in Alexa sichtbar

### ISSUE THREAD

**Issue by mcdhrts** [ioBroker/ioBroker.iot#46]
Hi Zusammen,

mich würde es sehr interessieren ob geplant ist, und wenn nicht eingeplant werden kann, das ich in meiner Alexa App den Status des Gerätes das ich über iobroker eingebunden habe sehen kann. Also zum Beispiel bei einer Steckdose ob diese gerade an oder ausgeschaltet ist usw. 
Funktioniert bei jedem Skill den ich bisher eingebunden habe also müsste die Technik vorhanden sein.

Grüße

**Comment by Apollon77** [comment]
Ja, sobald #29 umgesetzt ist

**Comment by mcdhrts** [comment]
thx
