### ISSUE TITLE
Klimaanlage Alexa App Steuerung

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.iot#461]
wüsste gerne ob es hierfür eine Lösung gibt. ich habe z.b ein Objekt Klimaanlage angelegt und ein objekt temperatur das alles über den IOT Adapter dann als einzelnes Gerät Klimaanlage in Alexa eingebunden. wenn ich nun auf das Gerät Klimaanlage tippe in der App zeigt es mir im Endeffekt nur den an- und Ausschalter an.der datenpunkt Temperatur hat value temperature als role. Read write ist aktiviert. was muss ich denn jetzt genau noch verändern damit die Alexa App theoretisch das Einstellen der Temperatur über die App ermöglicht ? Mir also die aktuell eingestellte Temperatur anzeigt und eventuell ein Plus und Minus

**Comment by Apollon77** [comment]
Bitte zeige mal die Konfiguration in iot ... Wenn da bei Klimaanlage auch ein temperatiricon ist dann geht das mindestens per sprache ... Alex App UI kommt erst wenn wir auf Skill v3 umgestellt haben

**Comment by vaaarg** [comment]
![_20220828_213029](https://user-images.githubusercontent.com/36050542/187091299-582d0b13-cece-4ae8-8c10-62311d01e143.JPG)

Die Sprachsteuerung funktioniert. Mir ging es nur um die manuelle einstellung via app.

**Comment by Apollon77** [comment]
Dann duplicate #29
