### ISSUE TITLE
weitere "type" und "trait" Einträge

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.iot#50]
Zur Zuordnung meiner Sonos Lautsprecher vermisse ich so etwas wie "Speaker" und/oder "Audio" in den Typen und dazu entsprechend "On/Off" und "Volume" (und ggf. "Channel"?) für trait

Ebenfalls sollte der type "Button" mit dem trait "press" als Ergänzung mit aufgenommen werden

**Comment by Apollon77** [comment]
Auf was genau beziehst Du dich?
Alexa? Google Home?

**Comment by BramTown** [comment]
Google Home - ich hatte zuvor den Begriff "trait" noch nicht gsehen ;-)

**Comment by TA2k** [comment]
Gehört hier nicht hin:
https://github.com/TA2k/ioBroker.iot/issues
Kann geschlossen werden.
