### ISSUE TITLE
IoT Adapter get no Connection and has missing URL keys

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.iot#51]
The service iobroker.in is not working with the hashed password.
Plain password returns url keys with hashed password it returns internal server error

**Comment by Kev0123** [comment]
Same here. Now with iot v1.0.5 the google device listing is broken as well. 

[GHOME] Invalid URL key. Status update is disabled: {"error":{"message":"One or more requested attributes do not exist.","code":"InvalidParameterException",

[GHOME] Cannot report device state: {"error":{"message":"One or more requested attributes do not exist.","code":"InvalidParameterException",

**Comment by Apollon77** [comment]
Please remove instance and install again. Still problematic?

**Comment by Kev0123** [comment]
Nope, but if I enable alexa then the listing will be fine. As soon as only ghome is on no listed devices.

**Comment by GermanBluefox** [comment]
listing device is another issue.
