### ISSUE TITLE
Alexa : Komische Rückmeldung bei Thermostat Regelung über IOT

### ISSUE THREAD

**Issue by haahne** [ioBroker/ioBroker.iot#517]
Ich habe die Thermostate in den IOT Adapter eingegeben und kann Sie auch Steuern . Aber:

Wenn ich sage: Alexa, Wohnzimmer 23 Grad.
kommt von ihr zurück: Automatischer Modus ist auf 23 Grad gestellt.

Sie Sollte aber sagen das Wohnzimmer auf 23 Grad gestellt ist.
Habe eben selbst einen Datenpunkt mit level.temperatur erstellt und °C als Einheit. Diesen im IOT Eingebunden , auch dort sagt sie es so.
Die Beta vom IOT habe ich auch ausprobiert.
Dort auch das selbe.

**Comment by Apollon77** [comment]
leider ist dies aktuell nicht anders möglich, da immer auch ein Modus gesetzt werden muss inn der aktuell verwendeten Skill Version. Damit kommt dann sowas als Antwort. Vielleicht ändert sich das wenn wir auf "Skill v3" gehen, aber das dauert noch etwas. Geht aktuell nicht anders.
