### ISSUE TITLE
[ghome] devices not named correct in home app

### ISSUE THREAD

**Issue by Kev0123** [ioBroker/ioBroker.iot#53]
The devices are only named "light" in the home app instead of e.g. "livingroom light", regardless of the given names in iobroker. The room names are cut away
![Screenshot_20190805-222506](https://user-images.githubusercontent.com/19821853/62492891-0109a280-b7d0-11e9-8e6d-9d57b9d919ee.png)
![Screenshot_20190805-222537](https://user-images.githubusercontent.com/19821853/62492892-0109a280-b7d0-11e9-9dc0-a8aa2e451969.png)

**Comment by TA2k** [comment]
Hi,
I'm working on an improved google device tab maybe you are interested to test it and give your feedback
https://forum.iobroker.net/topic/24061/google-home-assistant-iobroker-einrichten-nutzen/
