### ISSUE TITLE
Seit instali von iot-Adapter steht mein ioBroker, install wurde unterbrochen. Komme nur noch mit SSH auf den Raspi. Bitte um Hilfe

### ISSUE THREAD

**Issue by fricor** [ioBroker/ioBroker.iot#542]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Apollon77** [comment]
Bitte im Forum einen Thread eröfnen, Logs posten aus dem Logfile

**Comment by fricor** [comment]
Hallo, danke für die schnelle Antwort

 

Ich habe leider keine Logfiles, da wie es aussieht nur noch der Raspi läuft. Auf der Linux-Basis bin ich ein blutiger Anfänger,

ich glaube für mich das einfachste alles zusammen neu aufsetzen.

Danke nochmals     Fritz Cornella

 

Von: Ingo Fischer ***@***.***> 
Gesendet: Donnerstag, 2. Februar 2023 00:00
An: ioBroker/ioBroker.iot ***@***.***>
Cc: Fritz ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.iot] Seit instali von iot-Adapter steht mein ioBroker, install wurde unterbrochen. Komme nur noch mit SSH auf den Raspi. Bitte um Hilfe (Issue #542)

 

Bitte im Forum einen Thread eröfnen, Logs posten aus dem Logfile
