### ISSUE TITLE
Dialogmodus mit Alexa bleibt so lange offen bis Befehl Stop kommt

### ISSUE THREAD

**Issue by sansonifabio** [ioBroker/ioBroker.iot#543]
Es wäre schön wenn das so möglich wäre:

**Alexa starte ioBroker:** Sagt sie, ja was möchtest du wissen oder steuern?

Dann kommen meine Fragen die ich **hintereinander stelle** nach jeder Antwort von ihr zum Beispiel so.

Frage: Stromverbrauch =es folgt die Antwort.
Frage: Luftfeuchtigkeit = es folgt die Antwort.
Frage: Windgeschwindigkeit = es folgt die Antwort.
und wenn ich dann keine Fragen mehr habe mit Stop den Dialog beende. Das alles über den text2command Adapter.

**Weitere Infos**
Weitere Infos imForum
(https://forum.iobroker.net/topic/63407/gel%C3%B6st-alexa-und-custom-iobroker-skill-dialogmodus)

---------------------------------------------------------------------------------------------------------------------------------------
It would be nice if it were possible like this:

**Alexa start ioBroker:** She says yes what do you want to know or control?

Then come my questions, which I **put one after the other** after each answer from her, for example like this.

Question: power consumption = the answer follows.
Question: Humidity = the answer follows.
Question: wind speed = the answer follows.
and when I have no more questions, end the dialog with Stop. All this via the text2command adapter.

**Further information**
More information in the forum
(https://forum.iobroker.net/topic/63407/gel%C3%B6st-alexa-und-custom-iobroker-skill-dialogmode)

**Comment by Apollon77** [comment]
Hi, sorry I seem to have missed this request initially ... basically you can do this, but you need to code it yourself
