### ISSUE TITLE
Alexa Geräte können nicht mehr bearbeitet werden.

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.iot#547]
- OS Windows 10 x64
- Node.js v16.19.1
- NPM 8.19.3
- Adapter Version 1.14.4
 

Alexa Geräte können nicht mehr bearbeitet werden.

[intro---HP-ED800-iobroker003-.webm](https://user-images.githubusercontent.com/17329042/222041668-56f856fe-a203-4272-87d4-24cd4b6b879a.webm)

**Comment by tobi-nmx** [comment]
Ist bei mir auch so. Diese Fehler werden auf der Developer-Konsole angezeigt:

![grafik](https://user-images.githubusercontent.com/44090017/222063391-32dea5c8-de76-4513-a30c-f073db697e63.png)

**Comment by Apollon77** [comment]
hat es mit einem Update angefangen? Wenn ja mit wlechem?

**Comment by tobi-nmx** [comment]
Ich denke nicht. Die Alexa-Verbindung habe ich erst am Wochenende eingerichtet. Da habe ich die Devices gesehen, einen Tag später nicht mehr. Ich kann mich nicht erinnern, dass ich ein Update gemacht hatte. Meine Installation ist eigentlich immer auf dem neusten Stand, d.h. wenn es in den letzten 2-3 Tagen ein Update gab, dann kommt nur das in Frage.

**Comment by Diginix** [comment]
It's not fixed and happens in both of my instances with 1.14.4.
Console says:
`AlexaSmartNames.js:637 Uncaught TypeError: Cannot convert undefined or null to object`
