### ISSUE TITLE
Error by device connection: "read ECONNRESET"

### ISSUE THREAD

**Issue by klotzma** [ioBroker/ioBroker.iot#55]
Hallo,

Ich will mit diesem Issue nochmal an das jetzt schon längere Zeit bestehendes Problem zu errinern, in der Hoffnung Hilfe zu finden, da ich den Iot Service sehr eingeschränkt nutzen kann.

Ich muss teilweise befehle an mein Google Home mehrmals wiederholen, damit er ausgeführt wird, ob über IFTTT oder die direkte Anbindung an GHome, ich Zitiere "Der Service Iobroker ist zurzeit nicht erreichbar".

Der Iot adapter wird im wechsel gelb und grün, der Log ist voll mit dieser Meldung:
`2019-08-11 22:16:54.958  - [31merror[39m: iot.0 Error by device connection: "read ECONNRESET"
2019-08-11 22:16:54.958  - [32minfo[39m: iot.0 Connection changed: disconnect
2019-08-11 22:16:54.958  - [32minfo[39m: iot.0 Connection lost
2019-08-11 22:17:00.268  - [32minfo[39m: iot.0 Connection changed: connect
2019-08-11 22:22:00.541  - [31merror[39m: iot.0 Error by device connection: "read ECONNRESET"`.

[Forum Thema "Iot Fehler"](https://forum.iobroker.net/topic/18433/iot-fehler) 
[Aws Iot Issue #251](https://github.com/aws/aws-iot-device-sdk-js/issues/251)

**Comment by Apollon77** [comment]
Dann ist der aws Thread der richtige Platz. Am besten dort in englisch das Thema nochmals erinnern. Wir können nichts tun im Moment. Die aws beendet für Verbindung. Warum ist unbekannt. :-(

**Comment by GermanBluefox** [comment]
Please test the new version 1.1.4
