### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.iot#552]
version 1.14.4

open settings

![grafik](https://user-images.githubusercontent.com/6681528/222906771-c795da4b-911c-4f92-b124-f30095450418.png)

**Comment by benbensimpson** [comment]
hier das selbe problem es betrifft bei mir die alexa einstellungen 
der rest wird normal angezeigt 
![iot_alexa](https://user-images.githubusercontent.com/120809194/222960022-49e77fcf-d58c-4339-a157-6e393b071b30.png)

**Comment by Diginix** [comment]
Same here and supposedly fixed. But not for me.
https://github.com/ioBroker/ioBroker.iot/issues/547
https://github.com/ioBroker/ioBroker.iot/issues/553
https://github.com/ioBroker/ioBroker.iot/issues/554

**Comment by dirkhe** [comment]
Das problem ist, dass er versucht, auf ein property "channel" zuzugreifen, welches so nicht existiert. Müsste man ggf abfangen.

**Comment by benbensimpson** [comment]
update auf v1.14.5 gemacht problem damit bei mir behoben

**Comment by Diginix** [comment]
1.14.5 works for me as well
