### ISSUE TITLE
Version 1.14.4 View Alexa Devices disappear after loading

### ISSUE THREAD

**Issue by rookie50** [ioBroker/ioBroker.iot#555]
In IOT configuration I can't see the Alexa devices anymore. The header bar will disappear after loading the Alexa devices. Google works as expected:

**To Reproduce**  
1. Go to 'IOT settings'
2. Click on 'Alexa Devices'
3. Header Bar will disapare after some seconds

![grafik](https://user-images.githubusercontent.com/57443640/223397425-ca0810b1-be52-40b3-a8b4-3d018c82946c.png)

![grafik](https://user-images.githubusercontent.com/57443640/223397559-3f82f310-7390-4648-8977-8f7f7464096c.png)

**Versions:**  
 - Adapter version: 1.14.4
 - JS-Controller version: 4.0.24
 - Node version: 8.19.3
 - Operating system: DSM DSM 7.1.1-42962 Update 4 - Docker Version 20.10.3-1308 - Buanet ioBroker Image Version 7.2.0

**Additional context**  
I tried differenet browsers (FF, Chrome) with cleared cache.

**Comment by SilyHome** [comment]
I have the same problem.

Adapter version: 1.14.4
JS-Controller version: 4.0.24
Node version: v14.19.3

ioBroker-raspi
ARMv7 Processor rev 3 (v7l)
