### ISSUE TITLE
iot adapter crashed today the whole time

### ISSUE THREAD

**Issue by radebold** [ioBroker/ioBroker.iot#556]
> 
![image](https://user-images.githubusercontent.com/25064101/224495229-f8abf10e-f5a7-4df5-a568-b06f0fee41c6.png)

what can I do?

**Comment by Apollon77** [comment]
Do you use Redis as DB? If yes then it seems somehow that an internal datastructiure is broken:
* stop iobroker - all hosts if multihost!!
* Login via ssh to one host
* iob object deactivateSets
* iob object activateSets 
* start iobroker again
* verify

**Comment by radebold** [comment]
Thanks for support. It works again
