### ISSUE TITLE
Verbindung regelmässig verloren

### ISSUE THREAD

**Issue by zakuma666** [ioBroker/ioBroker.iot#58]
Guten Tag liebe Devs,

ich bin ja bereit für guten Service Geld auszugeben, leider ist der IoT Adapter der schlimmste Adapter den ich in IOBroker je genutzt habe.

Andauernd verliert er die Verbindung zu Alexa dann sagt mir Alexa nur das das Gerät Offline sei, dann funktioniert die Geschichte mit den Hinzufügen von Geräten immer nur mit hin und herschalten der Tabs in den Einstellungen, und bei Zigbee Geräten muss ich noch irgendwas in den RAW Daten Rumpfuschen.

Ich bastel ja gerne, aber wenn schon Grundfunktionen nicht möglich sind (wie eine Stabile Verbindung) ist es einfach traurig. 
Anscheinend gibt es für mich wohl auch keine Alternative, außer ich binde jedes Gerät aufwendig in meine Homematic CCU ein, um dann mit Cloudmatic zu arbeiten.

Bekommt ma eure Sachen gefitxt, und löscht die "alten" Cloud Adapter raus, bis ich raus hatte welcher der aktuellste ist vergingen auch eins zwei Stunden.

Um mal etwas detallierter zu werden bekomme ich diese Fehlermeldung bezüglich der verbindung:

`

iot.0 | 2019-09-08 18:26:56.703 | error | read ECONNRESET
-- | -- | -- | --
iot.0 | 2019-09-08 18:21:56.589 | warn | [GHOME] Invalid URL key. Status update is disabled: {"error":{"error":"No license found or license is no more valid"}}
iot.0 | 2019-09-08 18:21:56.587 | error | [GHOME] Cannot report device state: null
iot.0 | 2019-09-08 18:21:56.425 | info | Connection changed: connect
iot.0 | 2019-09-08 18:21:53.454 | info | Connecting with a18wym7vjdl22g.iot.eu-west-1.amazonaws.com
iot.0 | 2019-09-08 18:21:53.387 | info | starting. Version 0.4.3 in /opt/iobroker/node_modules/iobroker.iot, node: v8.16.0
host.raspberrypi | 2019-09-08 18:21:51.303 | info | instance system.adapter.iot.0 started with pid 3377
host.raspberrypi | 2019-09-08 18:21:48.873 | info | instance system.adapter.iot.0 terminated with code 0 (OK)
host.raspberrypi | 2019-09-08 18:21:48.784 | info | stopInstance system.adapter.iot.0 killing pid 2336
host.raspberrypi | 2019-09-08 18:21:48.784 | info | stopInstance system.adapter.iot.0
host.raspberrypi | 2019-09-08 18:21:48.782 | info | object change system.adapter.iot.0
iot.0 | 2019-09-08 18:21:14.942 | info | Request devices
iot.0 | 2019-09-08 18:21:14.588 | info | Request devices
iot.0 | 2019-09-08 18:21:09.638 | info | Request devices
iot.0 | 2019-09-08 18:20:59.717 | warn | [GHOME] Invalid URL key. Status update is disabled: {"error":{"error":"No license found or license is no more valid"}}
iot.0 | 2019-09-08 18:20:59.716 | error | [GHOME] Cannot report device state: null
iot.0 | 2019-09-08 18:20:59.501 | info | Connection changed: connect
`

Grüße
Zakuma

**Comment by Apollon77** [comment]
Bitte mal die aktuellste Version vom GitHub testen.

**Comment by Apollon77** [comment]
bzw PS: Ich habe gerade Stable auf die 1.0.7 gezogen. Das wäre die empfohlene Version

**Comment by zakuma666** [comment]
Ich teste mal die Version 1.0.7. Vielen dank schon mal für das Update

**Comment by zakuma666** [comment]
So das einbinden von Geräten funktioniert nun Tadellos, allerdings weiterhin alle 5 Minuten verliert er die Verbindung.

`

iot.0 | 2019-09-11 07:33:00.603 | error | Error by device connection: "read ECONNRESET"
-- | -- | -- | --
info.0 | 2019-09-11 07:32:52.750 | info | Popup-News readed...
iot.0 | 2019-09-11 07:28:00.337 | info | Connection changed: connect
iot.0 | 2019-09-11 07:27:55.012 | info | Connection lost
iot.0 | 2019-09-11 07:27:55.012 | info | Connection changed: disconnect
iot.0 | 2019-09-11 07:27:55.012 | error | Error by device connection: "read ECONNRESET"
iot.0 | 2019-09-11 07:22:54.744 | info | Connection changed: connect
iot.0 | 2019-09-11 07:22:49.440 | info | Connection lost
iot.0 | 2019-09-11 07:22:49.440 | info | Connection changed: disconnect
iot.0 | 2019-09-11 07:22:49.440 | error | Error by device connection: "read ECONNRESET"
iot.0 | 2019-09-11 07:17:49.174 | info | Connection changed: connect
iot.0 | 2019-09-11 07:17:43.881 | info | Connection lost
iot.0 | 2019-09-11 07:17:43.881 | info | Connection changed: disconnect
iot.0 | 2019-09-11 07:17:43.880 | error | Error by device connection: "read ECONNRESET"
iot.0 | 2019-09-11 07:12:43.608 | info | Connection changed: connect
iot.0 | 2019-09-11 07:12:38.267 | info | Connection lost
iot.0 | 2019-09-11 07:12:38.267 | info | Connection changed: disconnect
iot.0 | 2019-09-11 07:12:38.267 | error | Error by device connection: "read ECONNRESET"
iot.0 | 2019-09-11 07:07:38.002 | info | Connection changed: connect
iot.0 | 2019-09-11 07:07:32.630 | info | Connection lost
iot.0 | 2019-09-11 07:07:32.630 | info | Connection changed: disconnect
iot.0 | 2019-09-11 07:07:32.629 | error | Error by device connection: "read ECONNRESET"
info.0 | 2019-09-11 07:02:52.766 | info | Popup-News readed...
iot.0 | 2019-09-11 07:02:32.367 | info | Connection changed: connect
iot.0 | 2019-09-11 07:02:27.016 | info | Connection lost
iot.0 | 2019-09-11 07:02:27.016 | info | Connection changed: disconnect
iot.0 | 2019-09-11 07:02:27.016 | error | Error by device connection: "read ECONNRESET"
iot.0 | 2019-09-11 06:57:26.743 | info | Connection changed: connect
iot.0 | 2019-09-11 06:57:21.392 | info | Connection lost
iot.0 | 2019-09-11 06:57:21.391 | info | Connection changed: disconnect
iot.0 | 2019-09-11 06:57:21.391 | error | Error by device connection: "read ECONNRESET"

`

**Comment by Apollon77** [comment]
Für das ECONNRESET könnte mit https://github.com/aws/aws-iot-device-sdk-js/issues/280#issuecomment-530222159 eineLösung absehbar sein. FOlge mal bitte den Anweisungen dort ... hilft das bei dir auch? Vornehmlich: https://github.com/aws/aws-iot-device-sdk-js/issues/280#issuecomment-529990098

**Comment by GermanBluefox** [comment]
Es gibt auch eine neue Version

**Comment by Apollon77** [comment]
Anderes Prblem, bitte anderes Issue öffnen
