### ISSUE TITLE
Zweiter iobroker.pro Account mit zweiter Instanz -> Trotzdem sehe ich alle Geräte auch der ersten Instanz.

### ISSUE THREAD

**Issue by Hohenbostler** [ioBroker/ioBroker.iot#585]
**Describe the bug**  
Hallo, aus gründen teste ich gerade eine zweite iot Instanz mit einem komplett neuen iobroker.pro Benutzer. Sprich Account erstellt iot instanz hinzugeügt. Bei Alexa-Geräte sehe ich allerdings bei beiden instanzen alle Geräte. Eigentlich möchte ich natürlich pro Instanz nur die Geräte sehen die ich auch mit der Instanz verknüpfe. 

Das hat nämlich zur folge das ich auch in der Amazon Alexa App bei jederm Amazon Nutzer alle Geräte beider instanzen sehe.

Bei der Instanz 0 soll das rot eingekreiste eigentlich nicht sein.

![image](https://github.com/ioBroker/ioBroker.iot/assets/42488069/11a5707a-6a55-46e8-8861-be502c683ada)

Bei der Instanz 1 soll NUR das grün eingekreiste zu sehen sein.

![image](https://github.com/ioBroker/ioBroker.iot/assets/42488069/c6b3fa77-49c8-43c8-b8da-e6634415706b)

**Comment by Negalein** [comment]
du musst bei der 2. Instanz unter "erweiterte Einstellungen" das "Eigene Einstellungen (nur pro)" anhaken!

**Comment by Hohenbostler** [comment]
> du musst bei der 2. Instanz unter "erweiterte Einstellungen" das "Eigene Einstellungen (nur pro)" anhaken!

OK danke. Und wenn der zweite Account aber keine wirkliche pro Lizenz hat sondern nur die free Version des pro Account nutzt ?

Die erste Instanz ist ein vollwertiger pro Account

**Comment by Negalein** [comment]
hab ich noch nicht versucht, da ich mit der free nicht auskommen würde.

**Comment by Apollon77** [comment]
Die lösung ist genau die genannte. Mit dem "haken" werden die settings instanzspezifisch genutzt, sonst ohne. kannst auch den Haken nur bei einer instanz setzen
