### ISSUE TITLE
V1.1.0 - GHOME Can't recognize any devices

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.iot#59]
After completely fresh install of v1.1.0 GHOME can't add any devices. 
In the log I see that some devices are automatically added with type dimmer and light, but when I try to add IoBroker to Gogole Home App, nothing is added and in the log I get message that I have no devices:
![image](https://user-images.githubusercontent.com/40002726/64508783-e783db00-d2e6-11e9-9972-5ae9f35c4851.png)

Also, it is not possible to see anything on the GOOGLE DEVICES tab of the adapter. It just shows constantly spinning circle with repeating requests to GH devices in the log:
![image](https://user-images.githubusercontent.com/40002726/64508903-3f224680-d2e7-11e9-8270-74ee94eb50e5.png)

.... and to add. 
After enabling Alexa on adapter restart it throws the following
![image](https://user-images.githubusercontent.com/40002726/64510506-02584e80-d2eb-11e9-83e8-8d810760a338.png)

**Comment by Apollon77** [comment]
Please check GitHub version.

**Comment by algar42** [comment]
hmm, if you noticed I'm talking about latest github version 1.1.0. And it was completely fresh install, i.e. old instance and adapter were deleted before installation.

**Comment by TA2k** [comment]
Can you please install via git source https://github.com/TA2k/ioBroker.iot/
and share your log or some export of your devices in the forum?
https://forum.iobroker.net/topic/24061/google-home-assistant-iobroker-einrichten-nutzen

**Comment by algar42** [comment]
Thanks, Thomas. Version from 1.0.8 from your repo works more or less fine. At least I can see devices list in adapter settings. 
Version 1.1.0 from this repo still does not work for me...

**Comment by TA2k** [comment]
can you please double check for errors in my 1.0.8 version.

**Comment by algar42** [comment]
Playing with it... :) Will post any finding in your repo

**Comment by TA2k** [comment]
I see it is a issue with a new feature introduce with 1.1.0 can you please upload some linkeddevice in the forum?

**Comment by algar42** [comment]
Uploaded. Plus yet another problem with thermostat.

**Comment by algar42** [comment]
Now it does recognize more devices automatically from LinkedDevices, good.. But it does not recognize Room for all of the added devices:
![image](https://user-images.githubusercontent.com/40002726/64590401-1dd95d00-d3b0-11e9-929f-1a812ac07f5f.png)

...Tried both versions 1.1.1 and 1.1.2 - the same thing.

**Comment by TA2k** [comment]
I added this functionality in my git it will soon added to the official iot adapter

**Comment by TA2k** [comment]
fix with pr #61
