### ISSUE TITLE
Issue to update @1.14.2 to @1.14.6

### ISSUE THREAD

**Issue by peterimnetz** [ioBroker/ioBroker.iot#590]
**Describe the bug**  
I tried to update @1.14.2 to @1.14.6

**To Reproduce**  
iobroker upgrade iot@1.14.6 --debug

**Expected behavior**  
Should update to 1.14.6

**Screenshots & Logfiles**  
Would you like to upgrade iot from @1.14.2 to @1.14.6 now? [(y)es, (n)o]: y
Update iot from @1.14.2 to @1.14.6
NPM version: 8.15.0
Installing iobroker.iot@1.14.6... (System call)
**npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.iot@1.14.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.**

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/iobroker/.npm/_logs/2023-06-19T16_46_20_506Z-debug-0.log
upload [132] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/actions.js actions.js application/javascript
upload [100] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Cold Water.937aad5fa21b0c20a856.svg static/media/Cold Water.937aad5fa21b0c20a856.svg image/svg+xml
upload [90] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Doorstep.10630b759b4867a10776.svg static/media/Doorstep.10630b759b4867a10776.svg image/svg+xml
upload [80] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Garage Doors.0c2a1cfca7ad1ea59625.svg static/media/Garage Doors.0c2a1cfca7ad1ea59625.svg image/svg+xml
upload [70] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Handle.3de1d1320fc3ce2f9712.svg static/media/Handle.3de1d1320fc3ce2f9712.svg image/svg+xml
upload [60] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Laundry Room.58da550dff0173676e02.svg static/media/Laundry Room.58da550dff0173676e02.svg image/svg+xml
upload [50] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Music.67bc6063cb601642fd74.svg static/media/Music.67bc6063cb601642fd74.svg image/svg+xml
upload [40] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Pump.a6035507cddbe7db5f6a.svg static/media/Pump.a6035507cddbe7db5f6a.svg image/svg+xml
upload [30] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/SmokeDetector.8222f77cb07030a409ee.svg static/media/SmokeDetector.8222f77cb07030a409ee.svg image/svg+xml
upload [20] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Temperature Sensors.75d805988a6b77b231d8.svg static/media/Temperature Sensors.75d805988a6b77b231d8.svg image/svg+xml
upload [19] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Terrace.d71d07d9290674f2ca20.svg static/media/Terrace.d71d07d9290674f2ca20.svg image/svg+xml
upload [18] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Toilet.83604dd2daafb67067dd.svg static/media/Toilet.83604dd2daafb67067dd.svg image/svg+xml
upload [17] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Tv.4e9745a548e57bfac0c7.svg static/media/Tv.4e9745a548e57bfac0c7.svg image/svg+xml
upload [16] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Upstairs.441813e54e0daca0882d.svg static/media/Upstairs.441813e54e0daca0882d.svg image/svg+xml
upload [15] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Vacuum Cleaner.9c8d50e436e6cea06dfa.svg static/media/Vacuum Cleaner.9c8d50e436e6cea06dfa.svg image/svg+xml
upload [14] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Ventilation.c31761d86d67e245ac92.svg static/media/Ventilation.c31761d86d67e245ac92.svg image/svg+xml
upload [13] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Wardrobe.e8019970a2b51412cfdc.svg static/media/Wardrobe.e8019970a2b51412cfdc.svg image/svg+xml
upload [12] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Washing Machines.577f3acdb3cef002b523.svg static/media/Washing Machines.577f3acdb3cef002b523.svg image/svg+xml
upload [11] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Washroom.bfb54196f381f36de9d6.svg static/media/Washroom.bfb54196f381f36de9d6.svg image/svg+xml
upload [10] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Water Consumption.68891649591cc2434c5b.svg static/media/Water Consumption.68891649591cc2434c5b.svg image/svg+xml
upload [9] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Water Heater.7e4bb4d99a5213f24d08.svg static/media/Water Heater.7e4bb4d99a5213f24d08.svg image/svg+xml
upload [8] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Water.f50411984c5c24fa574d.svg static/media/Water.f50411984c5c24fa574d.svg image/svg+xml
upload [7] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Wc.83604dd2daafb67067dd.svg static/media/Wc.83604dd2daafb67067dd.svg image/svg+xml
upload [6] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Weather.e91dae647698d48365e3.svg static/media/Weather.e91dae647698d48365e3.svg image/svg+xml
upload [5] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Window.421664f57c35e5109aa2.svg static/media/Window.421664f57c35e5109aa2.svg image/svg+xml
upload [4] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Windscreen.6058448bf63f72dd5036.svg static/media/Windscreen.6058448bf63f72dd5036.svg image/svg+xml
upload [3] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Workshop.7856e59fe4f164c90609.svg static/media/Workshop.7856e59fe4f164c90609.svg image/svg+xml
upload [2] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/Workspace.97d73e419d966bfb6428.svg static/media/Workspace.97d73e419d966bfb6428.svg image/svg+xml
upload [1] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/names.3a7dae0bd6b8b03b280f.txt static/media/names.3a7dae0bd6b8b03b280f.txt text/plain
upload [0] iot.admin /opt/iobroker/node_modules/iobroker.iot/admin/static/media/names.e7efb5283d98000c74ac.txt static/media/names.e7efb5283d98000c74ac.txt text/plain

**Versions:**  
 - Adapter version: 1.14.6
 - JS-Controller version: 4.0.24
 - Node version: 16.17.0
 - Operating system: buanet/iobroker 6.3.5

**Comment by andre-bu** [comment]
Hello,
same Problem but no unusual in the LOG.
`iobroker exit 0`
After the update, the adapter is still on version 1.14.2

-  Node.js 14.19.1
-  NPM 6.14.16
-  Admin 6.3.5
-  js.controller 4.0.24

**Comment by Apollon77** [comment]
My fault, I will correct the repo! 1.14.5 is the one that needs to be there

**Comment by Apollon77** [comment]
Is fixed over night
