### ISSUE TITLE
IFTTT Applet skipped "Unable to make web request. Your server returned a 501"

### ISSUE THREAD

**Issue by Plasmachef** [ioBroker/ioBroker.iot#6]
IFTTT meldet, dass das Applet geskipped wurde ... aber es kommt trotzdem an.

Meldung vom Applet: Unable to make web request. Your server returned a 501

**Comment by elzershark** [comment]
ifttt funktioniert nicht mit der iot Cloud. Es sieht so aus als wenn die Befehle direkt "immer" zur "alten" cloud gesendet/empfangen werden. Auch ist im Blockly bei "sendto" der ifttt block nur über der "alten" Cloud einstellbar. Auch dann wenn man iot auswählt. wenn ich die "alte" cloud lösche, dann habe ich kein Zugriff mehr im Blockly auf das "sendto". Dort werden alle Blöcke übereinander gestapelt und sind dann nicht mehr anwählbar.

**Comment by Apollon77** [comment]
Aber es ist die neue IFTTT URL aus dem iot Adapter eingestellt?!

**Comment by elzershark** [comment]
ja. hab das jetzt mal mit einem frisch aufgesetzten iobroker gemacht.  Wenn ich nur die Adapter  admin, web, iot, javascript installiert habe... es kommt nichts in der  iot Cloud an wenn ifttt per web-hooks was senden soll. fehler 501 Auch ist unter blockly alle "sentto" Blöcke nicht anwählbar

**Comment by elzershark** [comment]
so, also ich krieg es nicht zum laufen. 3 verschiedene Accounts, 2 verschieden iobroker. Frisch installiert, und "meinen". Immer Fehler 501.

**Comment by schmupu** [comment]
Echt merkwürdig @elzershark . Bei mir funktionierte es auf Anhieb. So bin ich vorgegangen : [Foum](https://forum.iobroker.net/viewtopic.php?f=8&t=19853&start=60#p208177). Hast Du mal die alte cloud deaktiviert und es dann versucht?

**Comment by elzershark** [comment]
sagen wir mal so. ich bin durch mit testen. hab alles getestet,was mir überhaut einfällt.. iot clouds downgrade. verschidenen npm, node versionen. mit alte cloud. ohne cloud. nur iot. dann mit iot.. erst iot, dann alte cloud. neuen iobroker installiert. verschiedene Accounts getestet. mit was kaufen. ohne kaufen. test version (7tage). nur die nötigsten adapter. mit fast allen adaptern. nx zu machen.

**Comment by elzershark** [comment]
irgend etwas muss bei dir anders sein, was andere nicht haben..

**Comment by elzershark** [comment]
wurde gefixt. thx bluefox

**Comment by Apollon77** [comment]
Was war es denn? Wenn ich mal ganz Dumm fragen darf?

**Comment by Apollon77** [comment]
@elzershark Bitte auch im Forum Thread mitteilen mit ggf Infos das es anderen Usern auch hilft! Danke
