### ISSUE TITLE
Keine Verbindung mit Gerät oder Dienst

### ISSUE THREAD

**Issue by Myair85** [ioBroker/ioBroker.iot#604]
Hallo zusammen,
ich möchte den iot Adapter nutzen um apager Pro einzubinden. Das scheint generell mit dem iot Adapter zu funktionieren (siehe https://youtu.be/AnQYOJZrh6A )
Aber bei mir sagt die Iot Instanz immer, dass keine Verbindung zum Gerät oder Dienst besteht. 
hat jemand eine Idee, woran das liegen kann?
Die iobroker pro Lizenz habe ich. 

Danke im Voraus!

**Comment by Apollon77** [comment]
Bitte genaue Log ausgaben posten.

**Comment by Myair85** [comment]
Danke für die Hilfe,
habe in den Logs gesehen, dass der login in großen Buchstaben geschrieben war.

Liebe Grüße

Stefan

0170/8229423
Am 11. Juli 2023, 09:32 +0200 schrieb Ingo Fischer ***@***.***>:
