### ISSUE TITLE
own settings pro effect

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.iot#64]
Guys, please make visible somehow that if you check the box "own settings" you lose all smart devices connected to the cloud adapter .. this has kept me busy for a while :-(

**Comment by t6a** [comment]
had the same problem. I don't even know what this "personal settings (only pro)" is for

**Comment by Apollon77** [comment]
If you set this the smart device information are stored not globally but „per iot instance“. That’s why you need to newly set them up after enabling this. Disabling will directly use the „global“ infos instead again.
