### ISSUE TITLE
Cannot add object to alexa devices

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.iot#65]
Hi, I have a problem adding the up object (button) from my shelly marqee actor:

![2019-09-14_082903shelly](https://user-images.githubusercontent.com/4311558/64904390-d9103780-d6c9-11e9-93ae-4d79e7f10664.png)

**Comment by Apollon77** [comment]
Please post the object definition

**Comment by daniel-lo** [comment]
sure .. please advise how to do that

**Comment by daniel-lo** [comment]
Is that the object definition you had asked for?

**Comment by daniel-lo** [comment]
Hi .. is there any news related to this problem? There are also other objects from other adapters that I cannot add. AFAIK others have the same problem.  Cheers

**Comment by daniel-lo** [comment]
OK .. change role from button to switch and all is good. Workaround that I can easily live with.
