### ISSUE TITLE
Service URL Username kodieren

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.iot#654]
Ich habe das Problem, dass ich eine App nutze (Ekey bionyx) um http requests an ioBroker zu schicken. Leider lässt die App kein % Zeichen beim request zu.

Ein Link sieht ja so aus:

https://service.iobroker.in/v1/iotService?service=custom_service&key=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&user=meine.email%40gmail.com

Es wäre cool, wenn man auch ein hex-codierten Usernamen schicken könnte z.B.:

https://service.iobroker.in/v1/iotService?service=custom_service&key=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&userhex=6D65696E652E656D61696C40676D61696C2E636F6D

**Comment by GermanBluefox** [comment]
You can use `https://service.iobroker.in/v1/iotService?service=custom_service&key=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&user=6D65696E652E656D61696C40676D61696C2E636F6D`
