### ISSUE TITLE
Frage: Wie kriege ich es hin in Alexa zu sagen: "Alexa, [SmartName]" (ohne an, aus, ein,... als Suffix)

### ISSUE THREAD

**Issue by uwe72** [ioBroker/ioBroker.iot#656]
Lampen über Alexa zu steuern funktioniert sehr gut. Ich würde den Adapter gerne auch nutzen um über Alexa "Befehle" abzusetzen, z.B. (fiktiv) "versende Smarthome-Status über Email". SmartDevice-Name wäre "Versende Status". 

Welche Eigenschaften muss der zugrundeliegende Datenpunkt haben und wie ist die Konfiguration in der Instanz? 

Ziel ist es eben, dass in Alexa nur gesagt werden muss: "Alexa, versende Status" (und nicht: "Alexa, versende Status ein")

Gibt es eine **vertiefte Dokumentation** zum Adapter, beispielsweise würde mich interessieren wie man einen Activity_Trigger oder Scene_Trigger anwendet?

**Comment by Apollon77** [comment]
Das ist eine Limitierung der Smart Home Skills von Alexa und geht nicht so einfach. Vllt können wir mit dem geplanten kommenden v3 Skill etwas tun. Eine alternative ist der Custom Skill der mit "Alexa, sage ioBroker freier Text hier" arbeiten kann und zb dann via Text2Command
