### ISSUE TITLE
Google Home issues - saving manual changes not possible

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.iot#66]
Whenever I start the adapter I get the message:

[GHOME] Invalid URL key. Status update is disabled you can set states but not receive state updates: {"error":"Email not found or URL key not found"}

When I try to change some values in the Google Devices Tab I get stuck in the tab. (wait screen - turning circle) and the message appears in the log again.

I am currently evaluating and intend to buy a licence and hope this is not the origin of the error as it basically works with Google Home and cloud is registered, password changed.

The downside of this issue - configuration gets painful as for every change i need the reopen the instance again.

Maybe I did something wrong but it looks like an issue to me. 

Are there any work arounds? Getting rid of GHOME message and not getting stuck while configuring?

Thanks a lot

Cheers

Wolfgang
PS: Danke für den Adapter! ;)

**Comment by realwax** [comment]
![image](https://user-images.githubusercontent.com/14924590/65141736-7e504600-da11-11e9-92bd-c8ecf373e5ea.png)

![image](https://user-images.githubusercontent.com/14924590/65141744-83ad9080-da11-11e9-9a5e-e5bec7e6d060.png)

**Comment by realwax** [comment]
Update:
After reading some user bought a license which I intended to do and got rid of the error I did the same. Error message gone. BUT - the turning circle - loading/wait screen in the Google Devices does not go away and lead to no storing/saving any changes.

**Comment by TA2k** [comment]
What is the log when you press in Chrome:
Command+Option+J (Mac) or Control+Shift+J (Windows)
Did you try to restart the instance?

**Comment by realwax** [comment]
I noticed that names get stored and can be changed when exiting interface and reopening without restart. But Types and Traits cant. The log shows nothing - except the messages that appear when reopening. A restart changed nothing. 
![image](https://user-images.githubusercontent.com/14924590/65144171-fbca8500-da16-11e9-8e0f-833763da4748.png)

**Comment by realwax** [comment]
In addition I can report the following. I still can't save any changes to types and traits but it seems like I get another error. I tried to change an xiaomi door sensor (reports true when opened and false when closed) from TYPE sensor to door as Google reports it wrong. (It reports closed when true and vise versa) when trying to save that. I get an unknown error.... I really hope being able to use the adapter - currently I can change only names which does not enable me doing a proper config. Thank you! I happy to contribute any logs, test required.... Kind regards Wolfgang 
![image](https://user-images.githubusercontent.com/14924590/65146597-83ff5900-da1c-11e9-817e-c9a1fa67b353.png)

**Comment by TA2k** [comment]
Please join the forum and install the adapter via github link
https://forum.iobroker.net/topic/24061/google-home-assistant-iobroker-einrichten-nutzen

**Comment by realwax** [comment]
I will join the forum but I installed via Github link - I am on 1.1.18 
![image](https://user-images.githubusercontent.com/14924590/65147563-b5792400-da1e-11e9-8063-c4805ba8bedd.png) What about the error?

**Comment by TA2k** [comment]
Please us this github link 
https://github.com/TA2k/ioBroker.iot

**Comment by realwax** [comment]
Check! reinstalling.... and reporting back afterwards!

**Comment by realwax** [comment]
Danke Thomas - vermutlich können wir auch auf Deutsch schreiben.
Ich habe deine Version nun installiert. Folgende Änderung... das drehende Kreissymbol geht nun weg, wenn ich z.B einen Sensor als Door ändere. Beim Speichern wird es aber nicht geändert und bekommt wieder den alten Wert. Selbiges passiert z.b. wenn ich einen Switch auf Scene ändere und den Trait dazu auch. Speichern wird beendet - alte Werte stehen wieder da. Änderung ging nicht. 
![image](https://user-images.githubusercontent.com/14924590/65148542-b3b06000-da20-11e9-9c6f-588708dee2fe.png)

**Comment by realwax** [comment]
Ab und zu meldet es auch einen unknown error mit popup fenster. 
![image](https://user-images.githubusercontent.com/14924590/65148923-6aacdb80-da21-11e9-9f9a-91b148550449.png)

**Comment by realwax** [comment]
So jetzt meldet es dauerhaft wenn ich type, oder trait ändern möchte diesen unknown error. auf grund des chrome debugs "translater" habe ich mal die Sprache auf System gestellt, hat aber nichts verändert. 
![image](https://user-images.githubusercontent.com/14924590/65150487-8960a180-da24-11e9-96eb-2524810c10b5.png)

**Comment by GermanBluefox** [comment]
Auf dem letzen Bild sind keine Fehler, sondern debug Meldungen.

**Comment by realwax** [comment]
Ja, ich wurde gebeten den Debug mitzusenden. Der Fehler kommt mit unknown.... ich kann gerne iobroker log senden, hätte aber nichts auffälliges gesehen. Fakt ist, Types und Traits können nicht geändert werden. Generell kann nur der Name geändert werden. Ein anderer user hat den Fehler im issue 67 auch gemeldet. Vielen Dank!

**Comment by realwax** [comment]
![image](https://user-images.githubusercontent.com/14924590/65322838-2566e600-dba8-11e9-8524-24dfbdfb977b.png)

**Comment by TA2k** [comment]
duplicate  #67
