### ISSUE TITLE
Geräte werden Falsch erkannt, keine manuellen Korrekturen an Automatischen Einträgen möglich

### ISSUE THREAD

**Issue by Peter1980FFM** [ioBroker/ioBroker.iot#67]
Hallo Zusammen,
ich versuche den IOT Adapter zum Laufen zu Bekommen,
jedoch gibt es noch Massive Probleme...
In Google Devices Stimmen die Namen bei den HMIP Geräten nicht...
Schalter werden als Temperatur erkannt...
Steckdosen werden als Temperatur erkannt...
Automatische Einträge können nicht Korrigiert werden....
Bei den Automatischen Thermostaten wird die Luftfeuchtigkeit nicht mitgenommen.... Wenn ich das Thermostat einzeln Hinzufügen will lässt er mich nur die Einzeln Staten Hinzufügen, jedoch nicht das Komplette Thermostat.... Obwohl der Name das Device gleich ist werden die EInzelen Staten nicht zusammen gefügt....
Ich habe folgende Geräte die ich Steuern will:
HM-LC-Sw1-Ba-PCB --> Test OK
HM-LC-Sw1-FM --> Erkannt als Outlet... Setze es jedoch einmal als Licht und einmal als Steckdose ein in der Automatik nicht umzustellen
HM-LC-Sw2PBU-FM --> Kanal 1 als Licht erkannt, Kanal 2 als Outlet...
HmIP-BSM --> Werden als Thermostate Erkannt....
HmIP-FSM --> Werden als Thermostate Erkannt....
HMIP-PSM --> Werden als Thermostate Erkannt...
HmIP-BWTH --> Werden als Thermostate erkannt, jedoch kein Manuelles Hinzufügen möglich, Luftfeuchtigkeit wird nicht übergeben

![Fehler_iot](https://user-images.githubusercontent.com/45266139/65157964-d7c86d00-da31-11e9-9e71-63045e248634.png)

Die Lichtschalter und Steckdosen kann ich manuell Hinzufügen.... Jedoch die Heizungssteuerung nicht, das die Status nicht Zusammen gefasst werden können und in der Automatik die Namen nicht passen....

**Comment by realwax** [comment]
Den Fehler habe ich auch. Die Auto Einträge können nur beim Namen geändert werden, jedoch nicht TYPE or TRAIT. Nach Speichern geht es auf den vorherigen Wert zurück. Ich habe dies initial auch hier beschrieben. Anfangs war noch ein Fehler mehr dabei, jener konnte durch Lizenzerwerb vermieden werden. [Issue 66](https://github.com/ioBroker/ioBroker.iot/issues/66)

**Comment by TA2k** [comment]
Kannst du bitte die Geräte die falsch erkannt werden exportieren und hier hochladen:
https://forum.iobroker.net/topic/24061/google-home-assistant-iobroker-einrichten-nutzen/

**Comment by realwax** [comment]
![image](https://user-images.githubusercontent.com/14924590/65322792-0a947180-dba8-11e9-865b-b37f8566f0b2.png)

**Comment by TA2k** [comment]
Zur Zeit werden Channels und Devices automatisch erkannt. Manuell können im Moment nur einzelne States hinzugefügt und bearbeitet werden.
Das Bearbeiten von Channels und Devices wird in naher Zukunft hinzugefügt.
Man kann im Moment nur die automatischen erkannten Löschen und die einzelnen States mit selben Smartname hinzufügen.

**Comment by realwax** [comment]
Ok danke für die Info. Ich freu mich darauf, denn erst dann kann ich es vernünftig konfigurieren.

FYI: deconz.0.Groups.11.Scene_1.recall ist ein state eines devices. Ich habe diesem State einen Raum und ein Funktion gegeben, wird automatisch hinzugefügt, kann aber auch nicht verändert werden. 

Ich möchte mich dafür bedanken, dass ihr diesen Adapter geschaffen habt und freue mich auf seine Erweiterung! 
LG
Wolfgang

**Comment by olli0815** [comment]
> Zur Zeit werden Chanel und Devices automatisch erkannt. Manuell können im Moment nur einzelne States hinzugefügt und bearbeitet werden

Moin,

wie denn?
wenn ich auf das "+" klicke und einen Datenpunkt / state hinzufügen will bekommen ich:
![grafik](https://user-images.githubusercontent.com/17963080/65900708-e2cab800-e3b6-11e9-91e8-b855b90a287a.png)
