### ISSUE TITLE
Keine "intelligente Aufzählung" möglich wenn Gerät als Smart Device angelegt ist

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.iot#69]
Wenn ein Gerät als Smart Gerät angelegt ist, lässt es sich bei mir nicht mehr über die "intelligenten Aufzählungen" hinzufügen. Das ist auch nicht möglich, wenn ich das Gerät bei den Smart Devices rausnehme.

**Comment by TA2k** [comment]
Kannst du vielleicht noch im Detail erklären was du mit Smart Gerät meinst. Vielleicht könntest du ein Bild hinzufügen

**Comment by LJSven** [comment]
Sorry, heute heißen die "Alexa-Geräte" - früher hatten die eine andere Bezeichnung. Wenn ich die da anlege, funktioniert alles. Ich dachte man kann Dinge einfacher über die "intelligente Aufzählung" lösen.

![Bildschirmfoto 2019-10-01 um 09 14 46](https://user-images.githubusercontent.com/8560588/65941729-00863480-e42c-11e9-8f89-e2e4acbdbc2b.png)

**Comment by TA2k** [comment]
Das ginge auch dafür müssen die Channels, states oder devices ein Raum und Funktion zugeordnet sein.

**Comment by LJSven** [comment]
Und genau darum geht - wenn ich ein Device unter "Alexa-Geräte" angelegt habe, funktioniert es nicht mit dem "Intelligenten Aufzählungen"

**Comment by TA2k** [comment]
Dann das Gerät unter Objekte löschen und durch den jeweiligen Adapter neuerstellen lassen oder bearbeiten und unter raw den Punkt smartname löschen.

**Comment by LJSven** [comment]
Du meinst, wenn es z.B. ein Shelly ist, diesen unter den Shelly Objekten löschen?

**Comment by TA2k** [comment]
Wenn die einfach erneut erzeugt werden ohne Probleme dann Ja. Oder die raw Beschreibung bearbeiten

**Comment by LJSven** [comment]
Okay! Hat es einen Grund, daß nicht beides gleichzeitig geht?

**Comment by TA2k** [comment]
Wenn du die Geräte unter Alexa device löscht werden sie auf ignorieren gesetzt. Damit werden sie nicht mehr automatisch erkannt
