### ISSUE TITLE
Support for Alexa questions / customskill

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.iot#7]
support for Alexa questions, like discussed here:
https://forum.iobroker.net/viewtopic.php?t=18884&p=197172#p197172

**Comment by Apollon77** [comment]
Bitte mal 0.4.0 vom Github testen. Es gibt jetzt einerseits mehr Details (userId, SessionId, DeviceId) und eine Response kann definieren ob die Session offen bleibt. Man kann sich also im eigenen JavaScript per sessionIds den "State" merken und somit eine Interaktion abbilden.

Siehe https://github.com/ioBroker/ioBroker.iot#custom-skill

Bin gespannt.
