### ISSUE TITLE
Alexa-Geräte // ID Manuell hinzufügen schlägt fehl !

### ISSUE THREAD

**Issue by Knallix** [ioBroker/ioBroker.iot#70]
Hallo,

kann leider keine ID mehr hinzufügen.
Update 1.1.8 iot mit Pro-Account (Alles läuft einwandfrei)// 
Es öffnet sich ganz kurz das Auswahlfenster und schließt sich sofort wieder.
Browser: chrome und Firefox 
Bitte um schnellste Hilfe. DANKE

**Comment by TA2k** [comment]
Welches Betriebssystem und welche Chrome version?
Chrome Cache gelöscht?
Schon ein upload des iot adapters durchgeführt?
iobroker u iot

**Comment by Knallix** [comment]
Was meinst du mit upload ?
Ja Cache hatte ich schon gelöscht gehabt :-(
Windows 10 // Version chrom  77.0.3865.90 (Offizieller Build) (64-Bit)

**Comment by TA2k** [comment]
Unter Adapter rechts neben dem IoT Adapter den Pfeil nach oben drücken

**Comment by Knallix** [comment]
Leide kein Erfolg 👎 .

**Comment by Knallix** [comment]
Schau dir mal das video an

[instances - ioBroker - Google Chrome 2019-10-02 19-24-25.zip](https://github.com/ioBroker/ioBroker.iot/files/3682449/instances.-.ioBroker.-.Google.Chrome.2019-10-02.19-24-25.zip)

**Comment by TA2k** [comment]
Wenn du vorher F12 drückst werden dann irgendwelche Fehler ausgegeben

**Comment by Knallix** [comment]
anbei der LOG
Kannst du hier was sehen ?
Kommen wohl Fehler

[192.168.178.53-1570038267838.log](https://github.com/ioBroker/ioBroker.iot/files/3682517/192.168.178.53-1570038267838.log)

**Comment by Knallix** [comment]
![Beispiel](https://user-images.githubusercontent.com/42406048/66068173-65857b80-e54d-11e9-9fce-82275995f4e5.png)

**Comment by TA2k** [comment]
Die Eignene Einstellung unter Erweitere Einstellungen hast du nicht aktiv oder?

**Comment by Knallix** [comment]
Nein sind nicht Aktiv

**Comment by TA2k** [comment]
@GermanBluefox 
Ich denke es ist eine verrückte ID die richtig gehandelt werden kann in:
https://github.com/ioBroker/adapter-react/blob/master/src/Components/Utils.js#L88

**Comment by Knallix** [comment]
Gibt es hier noch keine Lösung :-(
