### ISSUE TITLE
fehlerhafte Warnmeldung bei Geräte mit Farbe

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.iot#709]
Wenn man bspw. sagt: "Alexa, licht an", dann erscheint für ein Gerät mit zusätzlicher Farbe im ioT Adapter folgender log:

`[ALEXA] Cannot controlOnOff Error: Won't control alias.0.Talstrasse1A.Logik.stateSpotSideboard as we have a switch available`

Die Konfiguration im ioT Adapter bei Alexa sieht so aus:
![image](https://github.com/ioBroker/ioBroker.iot/assets/92173565/5e367f49-3d86-41b2-ba1c-bdca140230ec)

Diese Meldung kommt nur bei Geräten bei denen zusätzlich zum Switch noch die Farbe hinzugefügt ist.

**Comment by Voodoo2man** [comment]
Das gleiche Problem habe ich auch schon länger. Hate jemand eine Lösung dafür?

**Comment by vaaarg** [comment]
Schliesse mich an. Hätte auch gerne mal eine Lösung für die Warnmeldungen im Log

**Comment by ahnungsbefreit** [comment]
Das Issue gibt es schon: https://github.com/ioBroker/ioBroker.iot/issues/651
