### ISSUE TITLE
Warnung beim schalten der States

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.iot#730]
wenn ein state farben UND einen onOff state hat, erscheint beim Befehl:
Alexa, licht aus:

das hier:

`

iot.0 | 2024-03-17 14:53:00.079 | warn | [ALEXA] Cannot controlOnOff: Error: Won't control alias.0.Talstrasse1A.Logik.stateSpotSideboard as we have a switch available -- | -- | -- | -- `

**Comment by foxriver76** [comment]
Das sollte eigentlich nur ein debug log sein, wurde wohl irgendwann mal zu einem warn aus versehen.
