### ISSUE TITLE
Unable to send messages to app in correct format

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.iot#743]
**Describe the bug**  

I'm not able to send a notification via ioBroker.

Setting `iot.0.app.message` to `Test` leads to

```
Cannot send message to app: TypeError: Cannot create property 'ttlSeconds' on string 'test'
```

https://github.com/ioBroker/ioBroker.iot/blob/c19528da12a2c8981593944455a272365200a3c7/main.js#L376-L386

EDIT: The problem is, that `json` will contain the given string (since parsing is skipped).

-----

Setting `iot.0.app.message` as suggested in object description (also tested double quotes)

```
{message: 'test', title: 'title', expire: 60, priority: 1}
```

leads to

![IMG_6218](https://github.com/ioBroker/ioBroker.iot/assets/1959049/c208abab-d5e1-4a77-8ac3-c4eba31fe41b)

**Versions:**  

- App-Version: 1.1.0
- Adapter version: 3.2.0
- JS-Controller version: 5.0.19
- Node version: 20.11.1
- Operating system: Debian 12

CC @foxriver76

**Comment by klein0r** [comment]
Just checked the code.
The description of the object is not correct. Valid JSON is required.

https://github.com/ioBroker/ioBroker.iot/blob/c19528da12a2c8981593944455a272365200a3c7/io-package.json#L510

e.g. `{"message": "Test"}`

or `{"message": "test", "title": "title", "expire": 60, "priority": 1}`

**Comment by foxriver76** [comment]
From a short look it should just be something like this.. need to do some other stuff first unfortunately. 

```
if (json.startsWith('{') && json.endsWith('}')) { 
     try { 
         json = JSON.parse(json); 
     } catch (e) { 
         adapter.log.warn(`Cannot parse message: ${json}`); 
         json = null; 
     } 
 } 
// new stuff here
else {
    json = null;
}
```
