### ISSUE TITLE
Verwendung von 2 IOT-Adaptern

### ISSUE THREAD

**Issue by joesilver8** [ioBroker/ioBroker.iot#76]
Genau wie bei der Cloud, ist es anscheinend nicht möglich zwei IOT-Adapter zu verwenden.
Diese haben natürlich getrennte Pro-Accounts. Wird allerdings bei der einen Instanz ein Gerät gelöscht, ist bei der anderen Instanz auch weg.

**Comment by joesilver8** [comment]
Wer lesen kann ist klar im Vorteil. Hat sich erledigt. Danke!

**Comment by lkn94** [comment]
Das Issue ist zwar schon älter, es wäre aber wünschenswert eine Quelle anzugeben. Wo kann man das nachlesen bzw. wo findet man mehr Informationen dazu?

**Comment by Apollon77** [comment]
Was meinst du? Vr allem ... Auf ein seit 2 Jahren geschlosssenes Issue zu kommentieren ist maximal unsichtbar

**Comment by lkn94** [comment]
Hat sich in der Zwischenzeit erledigt. Mir war nicht bewusst, dass man zwei IoT-Adapter jeweils getrennt betreiben kann. Hier haben sich die Geräte miteinander vermischt. Man muss tatsächlich in den Einstellungen ein Häkchen setzen, dann funktioniert das.

Da ich zu diesem Zeitpunkt die Info nicht hatte, war die einzige Chance auf dieses alte Issue zu antworten ;)

**Comment by erkilic** [comment]
Hallo Ikn, 
wo genau finde ich die Einstellung mit der ich zwei IOT Adpter parallel betreiben kann?

**Comment by Apollon77** [comment]
![Bildschirmfoto 2022-02-05 um 21 59 33](https://user-images.githubusercontent.com/11976694/152658869-2dba69da-c3d8-414f-9c97-6fca7846f64c.png)


... unter "Erweitere Einstellungen". Aber Achtung. Damit gehen erst einmal alle aktuellen Geräte  "verloren" und müssen neu eingestellt werden
