### ISSUE TITLE
Keine Funktion bei der Option "eigene Einstellungen (nur Pro)"

### ISSUE THREAD

**Issue by joesilver8** [ioBroker/ioBroker.iot#77]
Der gleiche Punkt ist zwar schon mal als closed markiert, aber irgendwie besteht das Problem noch immer.
Adapterversion ist 1.1.8
Sobal die Einstellung "Eigene Einstellungen (nur pro)" angehakt ist (wird benötigt, da zwei Instanzen mit unterschiedlichen Pro- und Amazon-Accounts laufen), werden Räume und Funktionen importiert und lassen sich nicht deaktivieren. Versucht man unter Geräte einzelne Geräte zu löschen, wird das Gerät zunächst rot markiert und nach einigen Sekunden wieder grün. Gelöscht ist nix.
Neue Geräte lassen sich anlegen. Allerdings z.B. nur der State und nie das komplette Gerät.
Das so angelägte Gerät lässt sich auch wieder löschen. Alles andere nicht.
Mehrfaches löschen der Instanzen und Adapter mit anschließender Neuinstallation hat nicht gebracht.

**Comment by Ilovegym66** [comment]
kann ich bestaetigen, verwende auch 2 Cloud accounts ( ob jetzt cloud oder iot, denke das Handling ist bei beiden gleich.. daher sind auch die Fehler gleich).

ich verstehe das so, dass bei "eigenen Einstellungen" alle Smarthome Devices die jetzt vorhanden sind, nur fuer diese Instanz verwendet werden.  Genau das funktioniert aber nicht, es sind alle Geráete in allen Instanzen da oder sie sind in allen geloescht, wenn ich es loesche...

**Comment by joesilver8** [comment]
Problem ist ja schon, dass sich weder Gruppen noch Funktionen abwählen lassen. Es wird einfach immer alles importiert, sobald der Haken "eigene Einstellungen gesetzt ist" Und dann lässt sich auch nix löschen, da ja sofort wieder neu importiert wird, anscheinend. Dadurch habe ich immer wieder das Problem, dass Alexa sagt: es gibt mehrere Geräte mit........
Habe ja versucht über die zwei Accounts, zwei getrennte Wohnungen einzubinden.
Nun zahl ich schon ewig für zwei getrennte Pro-Accounts, kann es aber nicht sinvoll  nutzen. Schade!
Das soll aber auch kein Vorwurf sein. Ich weiß die freiwillige Arbeit der Adapterentwickler wirklich sehr zu schätzen.

**Comment by Apollon77** [comment]
Welche Version iot? Also bei mir tut das alles ... ich kann getrennte Konfig s je instanz nutzen, Ich habe alles manuell angelegt und hole nichts von Functions und so ...

**Comment by joesilver8** [comment]
Version ist 1.1.8
Aber sobald ich den Haken für getrennte Config setze, sind unter "intelligente Aufzählung" alle Schieber gesetzt und lassen sich auch nicht deaktivieren. Somit ist unter "Alexa Geräte" natürlich auch schon alles vorhanden und lässt sich auch nicht löschen. Nur wenn ich händisch noch Datenpunkte hinzufüge, kann ich diese auch wieder löschen. Aber nix was automatisch importiert wurde.

**Comment by joesilver8** [comment]
![grafik](https://user-images.githubusercontent.com/56589070/68205494-c2e86e80-ffca-11e9-88bb-7409564e6ab1.png)

**Comment by joesilver8** [comment]
![grafik](https://user-images.githubusercontent.com/56589070/68205563-eca19580-ffca-11e9-9b9f-d1857f3e0f00.png)

**Comment by joesilver8** [comment]
@Apollon77 
Genauso wollte ich es auch machen. Also alles manuell anlegen, aber das klappt leider nur wenn ich keine getrennte Configuration anhake. Dann kann ich alle Gruppen und Funktionen auch problemlos abhaken.

**Comment by Apollon77** [comment]
entferne einfach alle häkchen bei den Function/Room listen. Dann verschwinden an sich alle devices die dadurch gekommen sind

**Comment by joesilver8** [comment]
Genau das ist ja das Problem. Die Häkchen lassen sich nicht entfernen.

**Comment by joesilver8** [comment]
Hab jetzt mal ein bisschen rumgespielt. Habe alle Homematic-Adapter gelöscht und auch die dazugehörigen Objekte. Auch IOT-Adapter und Objekte wurden gelöscht, sogar der Adapter selbst.
Dann hab ich den IOT-Adapter neuinstalliert. Er hat sofort alle in der CCU angelegten Räume und Funktionen. Woher??? Keine HM-Instanzen vorhanden und auch alle Objekte gelöscht.
Die IOT-Instanz "0" ist durch die Bastelei nun völlig zerschossen. Alle Funktionen und Räume angehkt, importiert aber trotzdem nix. Wird teilweise auch nicht grün.
Neue Instanz "3" angelegt, wird sofort grün und verhält sich wie schon die ganzen Tage.
Ohne Haken "eigene Einstellungen" geht alles. Bei gesetztem Haken sofort wieder alle Räume und Funktionen angewählt und nicht abwählbar.
Irgendwie sieht es so aus, als wenn der Adapter (trotz Löschen) irgendwoher Altdaten bezieht.

**Comment by Apollon77** [comment]
Die Räume und Funktionen bleiben im System wenn einmal angelegt (ggf automaisiert). Z finden im Admin unter "Enums"

**Comment by joesilver8** [comment]
Ui, da wäre ich nie drauf gekommen. Kannte den Punkt Aufzählungen garnicht, war bei mir immer ausgeblendet im admin.
Hab da jetzt mal alle Einträge gelöscht und nun sind sie im IOT-Adapter endlich weg. Nun kann ich Objekte wie gewünscht anlegen. Weiß zwar nicht was passieren würde, wenn ich die Aufzählungen wieder im Rega-Adapter anhaken würde, aber das versuche ich jetzt auch gar nicht.
Ich bedanke mich erstmal herzlich für die Unterstützung und versuche jetzt erstmal weiter voran zu kommen. Danke
