### ISSUE TITLE
temperatur schreiben lesen Alexa iot Version 3.3.0

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.iot#784]
Wenn ich einen Temperatur IST und Sollwert in dem ioT Adapter als Gerät einfüge dann,
dann geht das Sollwertsetzen des Temperaturwerts über Alexa nicht. (Bspw. wird aus 28° ein 28% Wert, welcher dann irgendeine Temperatur ergibt).
Die Integration sieht so aus:

iot: V3.3.0
Alexa2.0: V3.26.5

![image](https://github.com/user-attachments/assets/5f5b0d99-6891-4464-bbd7-82b4cb5c6a79)

Verwendet wird diese Einstellung:

![image](https://github.com/user-attachments/assets/1c754c32-6882-4866-af68-9690c00e350e)

States:
![image](https://github.com/user-attachments/assets/69090cc0-a55f-4b1b-9580-f10f532c973e)

Hier meine Logs: 

`2024-07-19 08:43:31.348 - debug: iot.0 (19508) Request command/bsahrdt_gmail_com/alexa -- 2024-07-19 08:43:31.349 - debug: iot.0 (19508) Data: "{\"header\":{\"messageId\":\"bb1567a9-41b4-4bee-bf35-066da2f4ae5e\",\"namespace\":\"Alexa.ConnectedHome.Control\",\"name\":\"SetPercentageRequest\",\"payloadVersion\":\"2\"},\"payload\":{\"accessToken\":\"eyJraWQiOiJRYWgyT01jdHY1ZlJuZ0xWR0plQzNUN1lGcThIZHFKSnZmU2R1MEtOWEFvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxZGJmOGQyMC0xNzkwLTRkODEtYTU1ZC0wODM3YTY5ODkxYjIiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6InByb2ZpbGUiLCJhdXRoX3RpbWUiOjE3MjEzNzEwNzYsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0xX2haZG1KMlAwWiIsImV4cCI6MTcyMTM3NDY3NiwiaWF0IjoxNzIxMzcxMDc2LCJ2ZXJzaW9uIjoyLCJqdGkiOiJhNjcwZDc2Ny0xNDAxLTRhNmUtYTgxMC00ZWNhNDk1NTBjODIiLCJjbGllbnRfaWQiOiI3dmwyYW83NWpvOGpmN24zODZraXAwYm04cyIsInVzZXJuYW1lIjoiMWRiZjhkMjAtMTc5MC00ZDgxLWE1NWQtMDgzN2E2OTg5MWIyIn0.DJw3YhDVXnU4SFkLh05UsqwSYw7sL2Kz8gKh-G96kwNc9-2k5S9lVUkU7xusMNcgFPEEFHoq0NxKAbaIAxqnUBV2M8JfwB8Tib-ecB3wT1PdvsC5HTaRPYYI3TClc1UKnu08aFidf8u6K2AyiVWW9LPSa_acRtNBJZa1OttymoEErTHzey-nIKpH-u11cVZdsLudsKo5tW-__pKHvupjAoVWy5nmWMzSnppWXf9qExOqZUNCEuMrzaN0pbVbrvElPADrtrY8kMo8CkRDYNRJ7yRH_9BdibJBUeT0f80mqlrFxOKD5ZKF2yxJrgvO7hSz99FmSGomvQ8wHUpSpcAk9Q\",\"appliance\":{\"applianceId\":\"W_rmepumpe\",\"additionalApplianceDetails\":{\"group\":\"true\"}},\"percentageState\":{\"value\":28}}}" 2024-07-19 08:43:31.349 - debug: iot.0 (19508) 1721371411349 ALEXA: {"header":{"messageId":"bb1567a9-41b4-4bee-bf35-066da2f4ae5e","namespace":"Alexa.ConnectedHome.Control","name":"SetPercentageRequest","payloadVersion":"2"},"payload":{"accessToken":"eyJraWQiOiJRYWgyT01jdHY1ZlJuZ0xWR0plQzNUN1lGcThIZHFKSnZmU2R1MEtOWEFvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxZGJmOGQyMC0xNzkwLTRkODEtYTU1ZC0wODM3YTY5ODkxYjIiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6InByb2ZpbGUiLCJhdXRoX3RpbWUiOjE3MjEzNzEwNzYsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0xX2haZG1KMlAwWiIsImV4cCI6MTcyMTM3NDY3NiwiaWF0IjoxNzIxMzcxMDc2LCJ2ZXJzaW9uIjoyLCJqdGkiOiJhNjcwZDc2Ny0xNDAxLTRhNmUtYTgxMC00ZWNhNDk1NTBjODIiLCJjbGllbnRfaWQiOiI3dmwyYW83NWpvOGpmN24zODZraXAwYm04cyIsInVzZXJuYW1lIjoiMWRiZjhkMjAtMTc5MC00ZDgxLWE1NWQtMDgzN2E2OTg5MWIyIn0.DJw3YhDVXnU4SFkLh05UsqwSYw7sL2Kz8gKh-G96kwNc9-2k5S9lVUkU7xusMNcgFPEEFHoq0NxKAbaIAxqnUBV2M8JfwB8Tib-ecB3wT1PdvsC5HTaRPYYI3TClc1UKnu08aFidf8u6K2AyiVWW9LPSa_acRtNBJZa1OttymoEErTHzey-nIKpH-u11cVZdsLudsKo5tW-__pKHvupjAoVWy5nmWMzSnppWXf9qExOqZUNCEuMrzaN0pbVbrvElPADrtrY8kMo8CkRDYNRJ7yRH_9BdibJBUeT0f80mqlrFxOKD5ZKF2yxJrgvO7hSz99FmSGomvQ8wHUpSpcAk9Q","appliance":{"applianceId":"W_rmepumpe","additionalApplianceDetails":{"group":"true"}},"percentageState":{"value":28}}} 2024-07-19 08:43:31.351 - debug: iot.0 (19508) [ALEXA] Found following devices to control: {"group":true,"channels":{"alias.0.Pool.Wärmepumpe":[{"id":"alias.0.Pool.Wärmepumpe.isttemperatur","role":"value.temperature","actions":["getTemperatureReading"]},{"id":"alias.0.Pool.Wärmepumpe.solltemperatur","role":"value.temperature","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff"]}]},"smartTypes":{"alias.0.Pool.Wärmepumpe.isttemperatur":"THERMOSTAT","alias.0.Pool.Wärmepumpe.solltemperatur":"THERMOSTAT"},"names":{"alias.0.Pool.Wärmepumpe.isttemperatur":"temp_current","alias.0.Pool.Wärmepumpe.solltemperatur":"temp_set"},"byONs":{"alias.0.Pool.Wärmepumpe.isttemperatur":false,"alias.0.Pool.Wärmepumpe.solltemperatur":"100"},"room":null,"func":null} 2024-07-19 08:43:31.351 - debug: iot.0 (19508) [ALEXA] New Request: SetPercentageRequest 2024-07-19 08:43:31.351 - debug: iot.0 (19508) [ALEXA] ALEXA Percent: W_rmepumpe 28% 2024-07-19 08:43:31.351 - debug: iot.0 (19508) [ALEXA] DATA: [{"id":"alias.0.Pool.Wärmepumpe.isttemperatur","role":"value.temperature","actions":["getTemperatureReading"]},{"id":"alias.0.Pool.Wärmepumpe.solltemperatur","role":"value.temperature","actions":["setPercentage","incrementPercentage","decrementPercentage","turnOn","turnOff"]}] 2024-07-19 08:43:31.351 - debug: iot.0 (19508) null 2024-07-19 08:43:31.351 - debug: iot.0 (19508) [ALEXA] Controlling percentage: alias.0.Pool.Wärmepumpe.isttemperatur 2024-07-19 08:43:31.355 - debug: iot.0 (19508) [ALEXA] alias.0.Pool.Wärmepumpe.isttemperatur is no valid datapoint to set the percentage. 2024-07-19 08:43:31.355 - debug: iot.0 (19508) [ALEXA] Controlling percentage: alias.0.Pool.Wärmepumpe.solltemperatur 2024-07-19 08:43:31.357 - debug: iot.0 (19508) [ALEXA] Controlling alias.0.Pool.Wärmepumpe.solltemperatur . 2024-07-19 08:43:31.405 - debug: iot.0 (19508) Response: {"header":{"messageId":"bb1567a9-41b4-4bee-bf35-066da2f4ae5e","namespace":"Alexa.ConnectedHome.Control","name":"SetPercentageConfirmation","payloadVersion":"2"},"payload":{}} 2024-07-19 08:43:31.406 - debug: iot.0 (19508) [REMOTE] Send response to 'response/bsahrdt_gmail_com/alexa: {"header":{"messageId":"bb1567a9-41b4-4bee-bf35-066da2f4ae5e","namespace":"Alexa.ConnectedHome.Control","name":"SetPercentageConfirmation","payloadVersion":"2"},"payload":{}}`

**Comment by BenAhrdt** [comment]
Früheres Issue, in dem ich leider keine Lösung gefunden habe: [Issue](https://github.com/ioBroker/ioBroker.iot/issues/187)

**Comment by Gaspode69** [comment]
Ich bin zwar nicht Ingo und das Issue ist schon älter, aber bei mir funktioniert das mit der Rolle level.temperature. Du verwendest - wenn ich das richtig sehe - die Rolle value.temperature.
Vielleicht hilft es.

**Comment by BenAhrdt** [comment]
> Ich bin zwar nicht Ingo und das Issue ist schon älter, aber bei mir funktioniert das mit der Rolle level.temperature. Du verwendest - wenn ich das richtig sehe - die Rolle value.temperature. Vielleicht hilft es.

Hi. Danke für dein Input.
es ging auch mit Level nicht.
Erst, als ich ein Gerät mit dem device adapter erstellt habe, ging es. also auch nur in Verbindung mit dem Namen des STates.

**Comment by mcm1957** [comment]
value.xxx sind READONLY roles. States mit role VALUE.xxx müssen write:false haben.

Wenn ein Stste beschrieben werden soll,d.h. eine Eknstellung an ein Gerät gesendet werden soll,dann muss dir role LEVEL.xxx sein.

Wenn ein Adapter einem writeable state eine  value.xxx role assigned sann ist das ein Bug ind es sollte ein issue beim Gerätedapter erstellt werden.

**Comment by mcm1957** [comment]
dann müsstest du schaun 2as an den state nun anders definiert ist.

**Comment by Gaspode69** [comment]
Du hast das Issue zwar schon geschlossen, dennoch der Hinweis, falls mal jemand drüber stolpert:
Ein State nach folgender Definition verhält sich exakt wie gewollt und schickt die gesagte Temperatur 1:1 an diesen State, wenn man für ihn ein Alexa Device mit Rolle "THERMOSTAT" anlegt.

```
createState("0_userdata.0.Thermo", 0, {
  read: true, 
  write: true, 
  unit: "°C",
  type: "number", 
  role: "level.temperature", 
  def: 0
});
```

**Comment by BenAhrdt** [comment]
> Du hast das Issue zwar schon geschlossen, dennoch der Hinweis, falls mal jemand drüber stolpert: Ein State nach folgender Definition verhält sich exakt wie gewollt und schickt die gesagte Temperatur 1:1 an diesen State, wenn man für ihn ein Alexa Device mit Rolle "THERMOSTAT" anlegt.
> 
> ```
> createState("0_userdata.0.Thermo", 0, {
>   read: true, 
>   write: true, 
>   unit: "°C",
>   type: "number", 
>   role: "level.temperature", 
>   def: 0
> });
> ```

und genau das war eben NICHT der Fall.
Hatte es genau so, aber es ging nicht. erst, wenn der State mit dem device adapter erzeugt wurde.
Aber ja jetzt auch nicht mehr relevant drüber zu diskutieren.

**Comment by Gaspode69** [comment]
Ich diskutiere hier gar nichts, ich teile meine Beobachtungen mit. Was du draus machst ist deine Sache.

**Comment by BenAhrdt** [comment]
> Ich diskutiere hier gar nichts, ich teile meine Beobachtungen mit. Was du draus machst ist deine Sache.

Sorry, dass sollte nicht so rüberkommen, wie es offenbar bei Dir angekommen ist.

Ich wollte nur mitteilen, dass ich einen DP hatte, der genau so in den Eigenschaften aufgebaut war, es aber nicht funktionierte.
Wahrscheinlich habe ich sonst noch etwas übersehen, aber hate es über Wochen versucht und keinen Unterschied zum state, der vom geräte adapter erzeugt wurde, gefunden.

**Comment by Apollon77** [comment]
Ok, die rolle hatte ich übersehen ... grmpff .., ABer ja wenn der Devices das so anlegt wäre der Fehler dort zu suchen (und zu reporten)
