### ISSUE TITLE
Alias-Geräte können nicht hinzugefügt werden

### ISSUE THREAD

**Issue by derseber** [ioBroker/ioBroker.iot#79]
JS-Controller-Verion: 2.0.35
iot-Version: 1.1.8

Die neuen Alias-Geräte können nicht als Smart-Device hinzugefügt werden.
Beim manuellen Hinzufügen kommt die Meldung im Log:
_"alias.0.XXX" not exists or no native part._
Native{} ist im Alias-Datenpunkt vorhanden.

**Comment by Garfonso** [comment]
Verrückt.. ich habe mal geguckt und debug eingebaut... an der Stelle, wo der Fehler geworfen wird ( https://github.com/ioBroker/ioBroker.iot/blob/12a33dbe7397eb4078acb49f9e0cbd65392d40b6/lib/alexaSmartHomeV2.js#L203 ) gibt es tatsächlich keinen native part. In der Objects Liste sehe ich aber {} als native. Wie kommt das? *grübel*

**Comment by Garfonso** [comment]
Habe jetzt mal in der object.json geguckt. Für den State, den ich gespeichert habe gibt es "native":{}. Für die anderen taucht native:{} tatsächlich nicht auf. Im Objects-Tab gibt es den aber. Warum lügt der einen an? *grübel*

Objects.json:

> "alias.0.lamps.Esszimmer.state":  {
>     "type":"state",
>     "common": {
>         "type":"boolean",
>         "read":true,
>         "write":true,
>         "role":"switch",
>         "min":false,
>         "max":true,
>         "name":"Licht Esszimmer",
>         "alias": {
>             "id":"knx.0.Beleuchtung.Ein_Aus.Licht_EG_Esszimmer_Ein_Aus"
>         },
>         "smartName": {
>             "de":"Licht Esszimmer","smartType":"LIGHT"
>         },
>         "custom": {
>             "history.0": {
>                 "enabled":true,
>                 "changesOnly":false,
>                 "debounce":"",
>                 "maxLenght":1000,
>                 "retention":0
>             },
>             "iogo.0": {
>                 "enabled":true
>             },
>             "iqontrol.0": {
>                 "enabled":true
>             },
>             "lovelace.0": {
>                 "enabled":true,
>                 "entity":"auto"
>             }
>         }
>     },
>     "from": "system.adapter.javascript.0",
>     "user": "system.user.admin",
>     "ts": 1575301080381,
>     "_id": "alias.0.lamps.Esszimmer.state",
>     "acl": {
>         "object":1636,
>         "state":1636,
>         "owner":"system.user.admin",
>         "ownerGroup":"system.group.administrator"
>     }
> },

Raw im Objects-Tab:

> {
>   "type": "state",
>   "common": {
>     "type": "boolean",
>     "read": true,
>     "write": true,
>     "role": "switch",
>     "min": false,
>     "max": true,
>     "name": "Licht Esszimmer",
>     "alias": {
>       "id": "knx.0.Beleuchtung.Ein_Aus.Licht_EG_Esszimmer_Ein_Aus"
>     },
>     "smartName": {
>       "de": "Licht Esszimmer",
>       "smartType": "LIGHT"
>     },
>     "custom": {
>       "history.0": {
>         "enabled": true,
>         "changesOnly": false,
>         "debounce": "",
>         "maxLenght": 1000,
>         "retention": 0
>       },
>       "iogo.0": {
>         "enabled": true
>       },
>       "iqontrol.0": {
>         "enabled": true
>       },
>       "lovelace.0": {
>         "enabled": true,
>         "entity": "auto"
>       }
>     }
>   },
>   "from": "system.adapter.javascript.0",
>   "user": "system.user.admin",
>   "ts": 1575301080381,
>   "_id": "alias.0.lamps.Esszimmer.state",
>   "acl": {
>     "object": 1636,
>     "state": 1636,
>     "owner": "system.user.admin",
>     "ownerGroup": "system.group.administrator"
>   },
>   "native": {}
> }

Wie man sieht, identisch bis auf das "native": {} im Objects-Tab und nicht in objects.json.... :-(
