### ISSUE TITLE
Custom Service request returs code 500, but works

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.iot#8]
I tried to switch my custom service requests to the iot adapter (and service). The state is correctly set in ioBroker but the client receives a 500 status code indicating an error (but body is `{result: ok}`).

It would be nice to get a 200 status code, if the request worked fine. I currently have two widgets on my android home screen using the app "HTTPRequestWidget" and they stop working and require reconfiguration, if they receive an error status code. 

This might be related to #6 .

**Comment by Apollon77** [comment]
still relevant or fixed?

**Comment by Garfonso** [comment]
Is fixed, now I get a 200 result as expected.
