### ISSUE TITLE
Direktes schalten von Geräten in der Alexa app

### ISSUE THREAD

**Issue by udochrist** [ioBroker/ioBroker.iot#80]
Ich nutze neben dem iobroker.iot skill auch den Ikea Smart Home skill.
Bei Ikea ist es so dass die Geräte einen direkten an/aus Knopf zeigen. Bei iobroker aber nicht.
Ist das ein Problem mit meiner Konfiguration, oder fehlt dieses Feature noch im skill?

Anbei ein Beispiel als Screenshot. Der Küchenschrank hat Ikea LEDs eingebaut.

![ADC0EABC-AE96-404D-846F-494DAB0535F0](https://user-images.githubusercontent.com/869637/67741571-e3885580-fa19-11e9-9197-ef5c6a85b312.jpeg)

**Comment by Apollon77** [comment]
Vermutung ist das es am skill liegt

**Comment by udochrist** [comment]
Danke für die schnelle Antwort.
Sollte ich bei der Analyse der Unterschiede behilflich sein können, dann gerne. gleiches natürlich auch im Test.

**Comment by GermanBluefox** [comment]
Ich denke es ist nur mit v3 Protokoll möglich ist.

**Comment by Apollon77** [comment]
Sehe ich auch so

**Comment by ronnytom** [comment]
Hallo!
Gibt es schon Neuigkeiten hierzu? Wäre schön wenn man den aktuellen Status in der Alexa App sehen könnte :)

**Comment by Apollon77** [comment]
Nope, no time till now, sorry

**Comment by ronnytom** [comment]
Kein Problem, wird ja hoffentlich irgendwann einmal :)

**Comment by Conslinger** [comment]
Kann man grob sagen ob dies in den nächsten Monaten oder Quartalen gelöst wird? Wäre eine große Verbesserung für unseren Haushalt. Danke und schöne Weihnachten!

**Comment by ronnytom** [comment]
Möglich ist diese bereits jetzt mit dem NodeRed Adapter (ohne IOT) im IOBroker. Allerdings nicht ganz so einfach zu programmieren  :)

**Comment by Apollon77** [comment]
Ja ist geplant ...

**Comment by Apollon77** [comment]
Weiterhin geplant

**Comment by Apollon77** [comment]
@udochrist Why you close the issue if it is still reevant and planned? Please leave it open,. Thank you

**Comment by udochrist** [comment]
1) as the creator of this issue I have no longer any interest in it being implemented but keep getting mails and updates since I am linked to it. 
sorry say but i have  long ago removed all of iobroker and moved to a different solution 
2) it has been created more than 3 years ago without any progress made and not an issue per-se as the skill lacks v3 support. Implementing this should be a feature. 
can you please take ownership of the issue and keep me out of this if you want to keep it open.
