### ISSUE TITLE
V3.4.0 - adden von Alexa Devices - Dialog kommt nicht

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.iot#803]
Buanet Docker V10.0, JS-Controller. 6.0.11, Admin 7.0.25 wie auch Admin V7.1.0.

Adde ich mit dem + ein Datenpunkt (egal ob Switch oder was auch immer), kann ich diesen auswaehlen, aber nachdem die Objektauswahl geschlossen ist, dreht sich der Spinner.. und das Fenster vom iot bleibt leer...  
Ich muss erst im Admin auf ein anderes Tab gehen, dann zurueck in die Instanzen, Iot-Adapter Config, Alexa-Devices, dann ist das neue ausgewaehlte Device zwar da, aber ich konnte weder den Namen aendern noch festlegen, ob Switch, Licht etc.. 

Zurueck auf Version 3.3.0 und alles ist bestens, sowohl mit Admin 7.1.0 als auch mit Admin 7.0.25.

**Comment by sokrates-sith** [comment]
ich habe das gleiche problem. auch das bearbeiten von vorhandenen devices ist nicht mehr möglich. mit v3.3.0 funktioniert es wieder.

**Comment by Ilovegym66** [comment]
auch mit 3.4.2 ist das Problem noch da. Liegt wohl am Refreshen der Seite, die bleibt dann leer, refreshe ich das Browser Tab, ist das Device angelegt. Allerdings falsch mit irgendeiner default einstellung.
Getestet mit Google-Chrome, Firefox, Safari, auch im Privat-Mode und cache geloescht.

**Comment by bimbolongo** [comment]
Ich kann dieses Problem auch bestätigen. Mit 3.3.0 funktioniert alles fehlerfrei.

**Comment by danieldriessen** [comment]
Kann ich bestätigen. Mit v3.4.0 kommt der Dialog nicht. v3.3.0 funktioniert dahingehend.

**Comment by Knoddel** [comment]
Bei mir das selbe Problem, vorhandene Geräte lassen sich nicht editieren. Der Dialog wenn man auf den Stift klickt wird nicht angezeigt mit der Version 3.4.2 mit der Version 3.3.0 funktionier noch alles.

**Comment by NinjaTurtle85** [comment]
Ich habe das selbe problem bei 3.4.2.

3.3.0 läuft alles super!
Admin adapter 7.2.6
Js-Controller 7.0.0

**Comment by haselchen** [comment]
Auch hier das gleiche Problem.
3.42 und 3.40 kommt kein Dialog Bildschirm
Mit 3.30 geht alles.

Wundert mich, dass hier nicht noch mehr schreiben.
Normal müssten ja alle betroffen sein, die die neuen Version mindestens mal installiert haben.

**Comment by Negalein** [comment]
auch bei mir mit 3.4.2

**Comment by Ilovegym66** [comment]
Es wurde irgendwo mal von @mcm1957 erklaert ( war irgendeine depency die erst mit js-c7 drin sein wird, glaube ich), wo es zur Zeit haengt, und es deshalb hier kein Bugfix so schnell gibt.
Bedenkt auch, dass zur Zeit alle Ressourcen wegen dem Event am 9.11. vergeben sind, und man sich auf das wichtigste konzentieren muss. 
Von daher.. wer unbedingt neue Geraete anlegen muss, zurueck auf V3.3.0, die Funktioniert ja einwandfrei. 
Die 3.4.2 stuerzt ja nicht ab, bis auf das anlegen neuer Geraete funktioniert ja alles. Waere fuer mich jetzt kein Grund, die Version wieder zurueck zu ziehen. Also bitte etwas Geduld, Leute.

**Comment by haselchen** [comment]
> Es wurde irgendwo mal von @mcm1957 erklaert ( war irgendeine depency die erst mit js-c7 drin sein wird, glaube ich), wo es zur Zeit haengt, und es deshalb hier kein Bugfix so schnell gibt. Bedenkt auch, dass zur Zeit alle Ressourcen wegen dem Event am 9.11. vergeben sind, und man sich auf das wichtigste konzentieren muss. Von daher.. wer unbedingt neue Geraete anlegen muss, zurueck auf V3.3.0, die Funktioniert ja einwandfrei. Die 3.4.2 stuerzt ja nicht ab, bis auf das anlegen neuer Geraete funktioniert ja alles. Waere fuer mich jetzt kein Grund, die Version wieder zurueck zu ziehen. Also bitte etwas Geduld, Leute.

Hey....
solange mit der 3.30 alles geht, ist ja auch alles okay.
Aber Hauptschwerpunkt beim IOT ist das Hinzufügen von Geräten. Ohne diese Gegebenheit ist der Adapter nutzlos.
Und ja, da das mit den 2 Versionen über 3.3.0 nicht funktioniert, muss man diese fixen oder zurückziehen. Da gibt es keine 2 Meinungen.

**Comment by mcm1957** [comment]
Kann mich  zwar nicht erinnern wann / wo ich doetwas gesagt bzw geschrieben habe aber zur folgender Aussage möchte ich doch noch was loswerden:

> Und ja, da das mit den 2 Versionen über 3.3.0 nicht funktioniert, muss man diese fixen oder zurückziehen. Da gibt es keine 2 Meinungen.

**Die Version 3.4.2 ist BETA / LATEST.** Bei BETA Versionen können Fehler enthalten sein. Beta Versionen können durchaus auch schwere Fehler enthalten. Da BETA Versionen auch nur auf Testsystem eingesetzt werden sollen, sollte es für einen Tester auch kein Problem sein mit dem Fehler umzugehen und ggF lokal downzugraden. Wer produktive BETA Versionen (d.h. das LATEST Repository) benutzt sollte wissen was er tut. Fehlerhafte Beta Versionen werden nur in Ausnahmefällen aktiv zurückgezogen Abgesehen vom Hinzufügen neuer Devices sind zumindest mir keine (neuen) Problem bekannt.

**Comment by mcm1957** [comment]
> Hey.... solange mit der 3.30 alles geht, ist ja auch alles okay. Aber Hauptschwerpunkt beim IOT ist das Hinzufügen von Geräten. Ohne diese Gegebenheit ist der Adapter nutzlos. Und ja, da das mit den 2 Versionen über 3.3.0 nicht funktioniert, muss man diese fixen oder zurückziehen. Da gibt es keine 2 Meinungen.

**Deswegen ist 3.3.0 auch die STABLE Version.**

3.4.2 ist eine BETA LATEST Version. BETA/LATEST Versionen sind nur zum Testen auf Testsystemen vorgesehen. Wer BATE/LATEST auf einem produktiven System einsetzt sollte wissen was er tut und von Fehlern nicht allzu überrascht sein.  BETA Versionen werden nur in Ausnahmefällen zurückgezogen - außerdem scheinen die 3.4.x Versionen ja abgesehen von der sicher fehlenden Möglichkeit neue Geräte hinzuzufügen ja zu funktionieren.

**Comment by haselchen** [comment]
> > Hey.... solange mit der 3.30 alles geht, ist ja auch alles okay. Aber Hauptschwerpunkt beim IOT ist das Hinzufügen von Geräten. Ohne diese Gegebenheit ist der Adapter nutzlos. Und ja, da das mit den 2 Versionen über 3.3.0 nicht funktioniert, muss man diese fixen oder zurückziehen. Da gibt es keine 2 Meinungen.
> 
> **Deswegen ist 3.3.0 auch die STABLE Version.**
> 
> 3.4.2 ist eine BETA LATEST Version. BETA/LATEST Versionen sind nur zum Testen auf Testsystemen vorgesehen. Wer BETA/LATEST auf einem produktiven System einsetzt sollte wissen was er tut und von Fehlern nicht allzu überrascht sein. BETA Versionen werden nur in Ausnahmefällen zurückgezogen - außerdem scheinen die 3.4.x Versionen ja abgesehen von der sicher fehlenden Möglichkeit neue Geräte hinzuzufügen ja zu funktionieren.

Also bitte...ist das Deine Argumentationskette?
Ein Auto funktioniert auch nur mit Rädern. Für volle Funktionalität fehlt das Benzin.
Wir reden hier von 2 Monaten und 2 Versionen, die nicht funktionieren. BETA hin oder her. Kein Fix und keine Antwort aufs Issue.
Um dem Ganzen noch die Krone zu verleihen.
Diese Funktion wird vom User bezahlt durch die Assistentenlizenz. Nur nebenbei....
Da ist dieser Satz "**abgesehen von der sicher fehlenden Möglichkeit neue Geräte hinzuzufügen.......**" mehr als Fehl am Platz.
Mir geht es nur ums Prinzip. Funktionieren tut er 100% mit der 3.30. Alles gut.
Aber ich mag Deine Argumentation nicht.

**Comment by Ilovegym66** [comment]
tja ob du das magst oder nicht.. Beta versionen koennen Fehler enthalten und diese hat welche, alles gut. Es ist eine Funktion, die nicht geht, welche aber in der stable ohne Probleme geht. 
Also hier bitte keine Panikmache - ansonsten kann jeder natuerlich sich an der Entwicklung beteiligen und ein PR erstellen.

**Comment by haselchen** [comment]
> tja ob du das magst oder nicht.. Beta versionen koennen Fehler enthalten und diese hat welche, alles gut. Es ist eine Funktion, die nicht geht, welche aber in der stable ohne Probleme geht. Also hier bitte keine Panikmache - ansonsten kann jeder natuerlich sich an der Entwicklung beteiligen und ein PR erstellen. Edit: Achso, du bezahlst fuer jede neue Version wieder die volle Lizenz, oder wie verstehe ich das? Oder mit welchem Recht nimmst du dir raus, fuer die paar Dollar im Jahr, was die iot Lizenz kostet, dauernd neue Versionen zu verlangen..? Mal abgesehen davon, dass es absolut KEINEN Grund gibt, eine Beta zu installieren. Die 3.3.0 funktioniert 100%ig. :)

Nicht anderes habe ich geschrieben.
Von Panikmache bin ich noch weit entfernt ;)
Ich weiß, dass ihr jedes Wort auf die Goldwaage legt...
Ich nehme mir gar nichts raus. Und ich verlange auch nichts. Ihr müsst mal an eurer Zündschnur arbeiten.
Die ist hier und im Forum extrem kurz.
Lies den Kontext mal genau.
Es ging um die Aussage, dass ja sonst alles funktioniert , nur die Hauptfunktionalität nicht. (BETA mal völlig ausgeblendet)
Außerdem, wir beide sind seit 7 bzw. 6 Jahren dabei, meinst Du, dass Deine Zeilen an mich dementsprechend angemessen sind?
Du hast das Issue mit der 3.4.0 eröffnet und trotzdem ist die nächste BETA knapp nen Monat später veröffentlich worden.
Ist nur ne Prinzipssache.

**Comment by Ilovegym66** [comment]
Ei.. ja.. ich versteh dich ja.. und ja, ich hab mich auch geaergert, dass die naechste Beta den gleichen Fehler hat wie die davor..  Wir trinken in Solingen n Bier und lass uns von Bluefox mal ausfuehrlich erklaeren, warum das jetzt hier so ist, ok?

**Comment by haselchen** [comment]
> Ei.. ja.. ich versteh dich ja.. und ja, ich hab mich auch geaergert, dass die naechste Beta den gleichen Fehler hat wie die davor.. Wir trinken in Solingen n Bier und lass uns von Bluefox mal ausfuehrlich erklaeren, warum das jetzt hier so ist, ok?


**DEAL** 
![image](https://github.com/user-attachments/assets/82057434-5404-43fb-b822-e4c88bccbd8b)

**Comment by Ilovegym66** [comment]
Fixed with 3.4.3, well done!
