### ISSUE TITLE
Nachricht an die Viso App

### ISSUE THREAD

**Issue by chris0one** [ioBroker/ioBroker.iot#808]
Massage to App funktioniert seit einigen Wochen nicht mehr. Folgender Fehler steht immer im Log:

'Cannot send message to app: AxiosError: Request failed with status code 500'

Egal ob Version 3.3.0 oder 3.4.0

MfG
chris0one

![Screenshot_20240915_204237_Chrome](https://github.com/user-attachments/assets/318f5a53-5488-4b35-abe1-55417c726917)

**Comment by GermanBluefox** [comment]
Fixed. Please retry

**Comment by chris0one** [comment]
Funktioniert wieder. Danke.
It's working, thx.

**Comment by chris0one** [comment]
Funktioniert wieder. Danke.
It's working, thx.
