### ISSUE TITLE
iot datenpunkt für Alexa hinzufügen: "<Datenpunkt> wurde nicht hinzugefügt

### ISSUE THREAD

**Issue by udochrist** [ioBroker/ioBroker.iot#81]
Ich versuche meine Wandthermostate (hmip-bwth) unter Alex zum sprechen zu bringen.
Ich brauche dazu nach meinem Verständnis mindestens datenpunkte SET_TEMPERATURE (rolle: level.temperature) und ACTUAL_TEMPERATURE (rolle: value.temperature)

Bug 1) Obwohl die Rollen korrekt gesetzt sind und das Gewerk korrekt gestetzt ist wird das Gerät für Alexa nicht korrekt gebaut. Dort wird nur der "level.temperature" berücksichtigt. Das macht das Fragen nach der Temperatur unmöglich

Bug 2) für HM-IP lässt sich der Datenpunkt value temperature auch manuell nicht hinzufügen.
Hier der Punkt in der Auswahl

![Bildschirmfoto 2019-11-05 um 13 27 32](https://user-images.githubusercontent.com/869637/68208376-50c75800-ffd1-11e9-92c6-f672ffccf87b.png)

und hier die meldung nach "ok"
![Bildschirmfoto 2019-11-05 um 13 27 48](https://user-images.githubusercontent.com/869637/68208496-8e2be580-ffd1-11e9-8df3-d3f2e5a53530.png)

sowie im Log:
![Bildschirmfoto 2019-11-05 um 13 29 11](https://user-images.githubusercontent.com/869637/68208514-971cb700-ffd1-11e9-83d6-5d32bf837c16.png)

Ich vermute mal das 1) und 2) die identische ursache hat? Der DP kann nicht geschrieben werden. Das wäre auch logisch. Es ist ja der Wert der Temp..

Für ein non-HMIP Wandthermostat funktioniert das.

**Comment by udochrist** [comment]
wenn ich den code in actions.js richtig verstehe wird eine Einheitsangabe (C,F,K) am ende des Temperaturwertes erwartet...
Bei dem HMIP-BWTH steht im Wert aber nur der Wert, keine Einheit. Ich vermute mal dass der Datenpunkt daher nicht als "getTemperature" erkannt wird und damit beschreibbar sein muss?

**Comment by Apollon77** [comment]
wenn nicht am End edes wertes, maximal als Unit, aber in dem Fall ist die Meldung eindeutig das es nicht beschreibbar ist

**Comment by udochrist** [comment]
die antwort verstehe ich gerade nicht wirklich (type ist eine number und eine unit gibts nicht)

```
{
  "type": "state",
  "common": {
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -3276.8,
    "max": 3276.7,
    "role": "value.temperature",
    "name": "Office.Thermostat.Climate.ACTUAL_TEMPERATURE"
  },
  "native": {
    "MIN": -3276.8,
    "OPERATIONS": 5,
    "MAX": 3276.7,
    "FLAGS": 1,
    "ID": "ACTUAL_TEMPERATURE",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "HEATING_CONTROL_HMIP.TEMPERATURE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1565523873196,
  "_id": "hm-rpc.1.ZZZZZZZZZZZZZZZ.1.ACTUAL_TEMPERATURE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

wo wäre dann der unterschied zwischen hm und hm-ip. die hm zeigen den wert nämlich als °C (mit einheit) und funktionieren problemlos im gegensatz zu den hmip. die berechtigungen im iobroker sind jedenfalls rw für user/group und r für other bei beiden für den datenpunkt
