### ISSUE TITLE
Alexa Devices are not editable

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.iot#810]
**Describe the bug**  
If you would like to rename a device for alexa by clicking on the pen symbol a blank screen appears.
So I'm unable to rename a device.

iot version 3.4.2

See Screenshot. 

**To Reproduce**  
1. Go to iot adapter
2. Click on Alexa Device --> Edit pen symbol of any device

**Expected behavior**  

**Screenshots & Logfiles**  

Click on pen right screen
![image](https://github.com/user-attachments/assets/639d01b6-6803-4d0d-8400-e5416732f2c1)

![image](https://github.com/user-attachments/assets/cb2a0091-aad1-4bb2-9cf4-ff8970390654)

**Versions:**  

ioBroker
Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
4
Geschwindigkeit
3626 MHz
Modell
Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
RAM
15.48 GB
System-Betriebszeit
26 T. 01:19:15
Node.js
v20.17.0 (Empfohlene Version v18.20.4)
time
1726654746469
timeOffset
-120
NPM
10.8.2
Anzahl der Adapter
629
Datenträgergröße
58.76 GB
freier Festplattenspeicher
13.2 GB
Aktive Instanzen
59
Pfad
/opt/iobroker/
Betriebszeit
21 T. 17:27:01
Hostname
ioBroker

**Comment by Apollon77** [comment]
duplicate to #803
