### ISSUE TITLE
settings > smart enums view broken if rooms/functions >1

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.iot#821]
**Describe the bug**  

**To Reproduce**  
create more then 1 room/function, then go to  iot adapter -> settings -> smart enums

**Screenshots & Logfiles**  
<img width="998" alt="image" src="https://github.com/user-attachments/assets/4b445925-c224-4828-8a83-74bcc4c7885c">

**Versions:**  
 - Adapter version: 3.4.2
 - JS-Controller version: 6.0.11
 - Node version: v20.17.0
 - Operating system: Ubuntu 24.04.

**Additional context**  
tested on a fresh installation with stable repo.

**Comment by Feuer-sturm** [comment]
@darkiop please check if this issue is fixed and can be closed

**Comment by darkiop** [comment]
i can't reproduce it with admin v7.1.5 and 7.4.10. issue closed.
