### ISSUE TITLE
Alexa Skill v2-to-v3 Migration

### ISSUE THREAD

**Issue by Marsx79** [ioBroker/ioBroker.iot#84]
Is it planned to migrate the skill from v2 to v3?

https://developer.amazon.com/de/docs/smarthome/smart-home-skill-migration-guide.html

**Comment by Apollon77** [comment]
duplicate  to #29 Yes it is planned ... no ETA

**Comment by Apollon77** [comment]
If you have time to rewrite the logic and provide basic stuff we would also accept a PR
