### ISSUE TITLE
Alexa Datenpunkte Netatmo

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.iot#86]
Hallo,

ich versuche im IOT-Adapter Alexa-Datenpunkte aus dem Netatmo-Adapter hinzuzufügen.

Leider klappt da gar nicht so recht.

Bei den reinen Temperatur-Werten habe ich immer das Problem, dass der iot-Adapter folgendes bemängelt:

``<Object> not exists or no native part``

Wenn ich das Objekt dann manuell editiere und im RAW-Bereich folgendes hinzufüge, dann klappts:

``  "native": {},``

Die Werte für Luftfeuchtigkeit und CO2 bekommen ich gar nicht hinzugefügt.

Wenn ichs richtig verstehe wird in der actions.js folgendes geprüft:

`if (obj.common.write === false) {
        if (obj.common.unit === 'C' || obj.common.unit === 'C°' || obj.common.unit === '°C' ||
            obj.common.unit === 'F' || obj.common.unit === 'F°' || obj.common.unit === '°F' ||
            obj.common.unit === 'K' || obj.common.unit === 'K°' || obj.common.unit === '°K') {
            actions = ['getTemperatureReading'];
            type = '';
        } else {
            return null;
        }`

Da der CO2-Wert und die Luftfeuchtigkeit "read-only" sind, aber keine Temperatur-Werte darstellen klappt es vermutlich mal mindestens beim Hinzufügen nicht.

Wäre es möglich auch die Luftfeuchtigkeit in % sowie den CO2-Wert (ppm) zu integrieren ?

Vielen Dank und Gruss
Ralf

**Comment by Apollon77** [comment]
Luftfeuchte ist aber keine Temperatur. Infamsten unterstützt im skill v2 was wir nutzen keine weiteren abfragemöglichkeiten. 

Wenn native fehlt bitte issues beim Adapter Erstellen.

**Comment by gaudes** [comment]
Hi Apollon77,

verstehe, danke.
