### ISSUE TITLE
Alexa Sprachbefehl schaltet nicht korrekt: Won't control zigbee.0.group_1.state as we have a switch available

### ISSUE THREAD

**Issue by wolfganghuse** [ioBroker/ioBroker.iot#89]
Hallo,
ich habe eine Hue-Lampe mittels Zigbee-Adapter eingebunden.
Nachdem ich Write-Rechte auf "state" und "brightness" gesetzt habe kann ich das Gerät als Smart Device hinzufügen.
Versuche ich nun das Device über Alexa auszuschalten wird nur "brightness" auf 0 bzw gesetzt, der "state" mit der Rolle "switch" bleibt aber auf TRUE.
Damit kann ich die Lampe zwar ausschalten aber ein Kommando um die Lampe wieder einzuschalten setzt nur "brightness" wieder auf 40 (zb). Dadurch das aber der state nicht wieder gesetzt ist bleibt die Lampe aus.
Ich muss im Zigbee-Object state manuell nochmal mit TRUE belegen damit die Lampe angeht.
Im Protokoll erscheint:
Won't control zigbee.0.group_1.state as we have a switch available

Wie komme ich den Adapter dazu den state explizit zu setzen ?

Gruß,
Wolfgang

**Comment by wolfganghuse** [comment]
Ok.. Nachtrag (bzw) Lösung: Das ganze geschieht nur bei Gruppen die innerhalb des Zigbee-Adapters angelegt werden, einzelne Devices lassen sich korrekt steuern.
Gibt es eine Best Practice wenn ich zwei Lampen über einen Sprachbefehl steuern möchte ? 
Gruppe in Zigbee ist ja anscheinend fehlerhaft... Szene oder Scripte ?

**Comment by Apollon77** [comment]
Fehler-Issue beim zigbee adapter das es dort gefixt wird? :-)
