### ISSUE TITLE
Google Devices mit mehrere STATES

### ISSUE THREAD

**Issue by dominikoyen** [ioBroker/ioBroker.iot#90]
Hallo zusammen,
zunächst wünsche ich allen Frohe Weihnachten. Der IOT-Adapter ist wirklich toll und es macht Spaß damit zu arbeiten.

Zur Einrichtung meines Google Nest Hub konnte ich bereits einige STATES den Geräten zuweisen. Allerdings immer nur 1 STATE zu 1 Gerät. Ich möchte aber beispielsweise für mein Thermostat nicht nur die Solltemperatur zuweisen, sondern auch die aktuelle Temperatur und den notwendigen Modus. 
Ich kann zwar die Ist-Temperatur einem zweiten Gerät zuweisen. Allerdings muss das doch auch in einem Gerät funktionieren oder ? 
Schließlich sieht Google das in den vorgegebenen Geräten auch so vor.

Für die Einbindung ist zusätzlich ein Mapping notwendig, damit ich die Modi des Thermostat auch richtig übernehmen kann. 
Kann das Mapping auch schon irgendwie durchgeführt werden?

Danke und viele Grüße

Dominik

**Comment by Apollon77** [comment]
An sich sollte das gegen wenn du einfach den gleich Smart Name für alle drei States vergibst - zumindestens ist das so bei Alexa :-)

@tombox

**Comment by dominikoyen** [comment]
Oh man peinlich, das hat funktioniert! Vielen Dank.

Hat denn noch jemand eine Idee, wie das mit dem Mapping funktioniert?
Das ist bei Alexa wirklich sehr elegant!

Danke

**Comment by TA2k** [comment]
Was möchtest du genau wissen.

**Comment by dominikoyen** [comment]
Es fehlt die Möglichkeit ein Mapping durchzuführen. Den Status kriege ich zur Zeit überhaupt nicht gesetzt.

Max! Heizthermostate
0(auto)
1(manual)
2(vacation)
3(boost)

Google Home
Kühlen
Heizen
Aus

Wie kann ich die Stati der Thermostate mit den vorgegebenen Stati von Google Home verknüpfen?
Bei Alexa mache ich das mittels mapping.

Danke und Grüße

Dominik

**Comment by 6RomN6** [comment]
Das kannst du machen mit Kühlen==1 etc. meine ich

Mein Problem ist sobald ich ein SetTemp setzte kommen immer die Attribute mit was meiner Meinung nach nicht so sein muss da ich dafür ja dann ein Mode mache oder nicht?

**Comment by dominikoyen** [comment]
Das ist ja im Prinzip gleich, wie das Mapping. Allerdings weiß ich nicht wo ich das eintragen soll. Hat das schon mal jemand erfolgreich gemacht?

Danke und Grüße

Dominik
