### ISSUE TITLE
Alexa Aufmachen/Zumachen (Open/Close) utterances

### ISSUE THREAD

**Issue by zaunermax** [ioBroker/ioBroker.iot#92]
Erst mal großes Lob an die maintainer und die community dieses projekts!

Dann auch gleich zu meiner Frage: Ich hab gesehen, dass die smart-home payloads noch eine alte version (2) verwenden? Ich habe nämlich versucht, meine Rollos mit dem Befehl "Mach die Rollos im Schlafzimmer auf", was natürlich nicht unterstützt ist, da der Iot skill nur power und percentage controllers unterstützt.

Ich hab grad selbst einen smart home skill programmiert bevor ich von ioBroker erfahren habe und hab da gesehen, dass mam per Toggle controller so ein feature easy adden kann. Meine ikea Rollos kann ich damit steuern (Ikea selbst scheint die Sprachsteuerung ja nicht hinzubekommen...) 

Nachlesen kann man das [hier](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-togglecontroller.html#discover-semantics). Man müsste also nur semantics in die discovery bzw die response einbauen. 

Kann aber auch sein, dass es das schon gibt und ich habs auch nur übersehen. Ich würde mich sonst auch anbieten, mal einen PR zu machen für das Feature. Jedoch bin ich mir nicht sicher, ob ich das kann, da ja die Payload version noch V2 zu sein scheint und mir aber nur V3 gerade geläufig ist.

PS: hab gerade das migration issue gefunden, denke dieses issue wird bis zur migration erst mal im backlog landen

**Comment by zaunermax** [comment]
I think adding the `Alexa.Actions.Open` and `Alexa.Actions.Close` action mapping semantics can only be done once #29 is completed.

**Comment by Apollon77** [comment]
You are right. :-( v3 skill is a huge project to allow the usage of all controllers and map States and such.
