### ISSUE TITLE
Adapter-Konfiguration keine Funktion Logo dreht sich im Kreis.

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.iot#94]
Iot Adapter ist Grün, beim Aufrufen der Konfiguration  via Schraubenschlüssel dreht sich das Logo ständig im Kreis. 
Nach Update auf V 1.1.10-12

![Screenshot (1164)](https://user-images.githubusercontent.com/41079106/71771052-70c5ba00-2f35-11ea-8c46-cec9599dc32a.png)

`window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. ace.js:1
Subscribe: system.adapter.* admin.js:1305
Subscribe: system.host.* admin.js:1305
Subscribe: *.info.connection admin.js:1305
426 adminInstances.js:1065
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:8081/socket.io/?ws=true&EIO=3&transport=polling&t=MzoCQAF. (Grund: CORS-Anschlag schlug fehl).
Connect error: Error: xhr poll error Connection.js:96:12
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:8081/socket.io/?ws=true&EIO=3&transport=polling&t=MzoCRw7. (Grund: CORS-Anschlag schlug fehl).
Connect error: Error: xhr poll error Connection.js:96:12
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://localhost:8081/socket.io/?ws=true&EIO=3&transport=polling&t=MzoCTns. (Grund: CORS-Anschlag schlug fehl).`

**Comment by fastback2000** [comment]
Auch ich hatte das gleiche Problem - nach 2 Installationsversuchen und auch Neustarts von iobroker.
Ich binzunächst zurück auf 1.1.9 gegangen. Interessant ist aber, dass Alexa.Kommandos ohne Probleme abgearbeitet wurden.

**Comment by TA2k** [comment]
Ich denke der xhr poll error hat damit direkt nichts zu tun. Könnte ihr nochmal schauen wann welche Fehler auftauchen wenn ihr die iot optionen aufruft?

**Comment by TA2k** [comment]
oder meine version probieren ob da der fehler auch auftaucht
https://github.com/TA2k/ioBroker.iot

**Comment by sigi2345** [comment]
> oder meine version probieren ob da der fehler auch auftaucht
> https://github.com/TA2k/ioBroker.iot

Selber Fehler.

**Comment by sigi2345** [comment]
**Zurück auf 1.1.9!**
Geht wieder.

**Comment by Apollon77** [comment]
Ist irgendwo ssl im Spiel bei dir?

**Comment by sigi2345** [comment]
> Ist irgendwo ssl im Spiel bei dir?

Nein

**Comment by TA2k** [comment]
sind denn im log für den iot adapter irgendwelche fehler. Gerade wenn du ihn stoppst.

**Comment by GermanBluefox** [comment]
> > Ist irgendwo ssl im Spiel bei dir?
> 
> Nein

Ist dein admin nicht auf dem Port 8081?

**Comment by GermanBluefox** [comment]
Sollte mit 1.2.0 gefixt sein

**Comment by sigi2345** [comment]
> Sollte mit 1.2.0 gefixt sein

Funktioniert!
