### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by StinkyHeXoR** [ioBroker/ioBroker.iot#95]
Don't need to tell you whats actually wrong with it.
Your time is priceless, but doing such a great job and not doing a proper documentation should not be your level of professional work.

Thanks!

**Comment by Apollon77** [comment]
Please tell us what’s wrong with it. Or even better support us and tell what’s missing. The more details the better. 

And even much better: write it and provide as PR for the Readme.md ... with this you can drive the documentation from a user perspective and support Allerheiligen other users.

**Comment by StinkyHeXoR** [comment]
- Your docu has one image in it... and thats from the old cloud adapter
- Smart Enums (or i guess its the same like "intelligente Aufzählungen" are not mentioned or explained
- Explanation of: Alexa Device Typ Thermostat / Activitiy_Trigger / Scene_Trigger / Smartplug / Smartlock / Camera missing
- (Thermostat Device Typ has an "On" in % definition btw)
- cant find anything to "advanced settings / Erweiterte Einstellungen"  ( What is "verbinde Raum und Funktion mit..." and "Ersetze in Namen" for?)

Appreciate your work. Thanks!
