### ISSUE TITLE
No devices for Alice

### ISSUE THREAD

**Issue by VictorSvetogor** [ioBroker/ioBroker.iot#98]
Can't see any devices for Alisa in "Alisa devices" tab. At the same time,  there are a lot of devices in "Alexa devices" tab.
"Room" and "Function" are properly defines for states, but the adapter just doesn't see it. There are not  errors in log according to Alisa part of functionality (in debug mode).

**Comment by itProfi** [comment]
Absolutly same problem!

**Comment by XAKEPEHOK** [comment]
+1
